### ISSUE TITLE
the issue list in justin's email that block release

### ISSUE THREAD

**Issue by tanzhongyibidu** [apache/incubator-brpc#1013]
I’m -1 (binding) for three reasons:
- the artefact names must include "incubating “ but this can be easily fixed and the voting doesn’t need to restarted (if this was the only issue)
- but it also contains category B code [2] under the CDDL license.
- and it also contains category X code [9] under the GPL license.

you may want to consider using the work in progress disclaimer while you sort these issues out. [11]

I checked:
- incubating not in name
- DISCLAIMER exists
- LICENSE is missing appendix
- NOTICE year needs to be updated
- Source release contains category B code which is not allowed [2]
- Source release contains Category X software which is not allowed. [9]
- All ASF source files have ASF headers
- No unexpected binary files

I did a spot check on licenses in LICENSE and it look like it missing a few things:
- SVGPan library 1.2 Copyright 2009-2010 Andrea Leofredd contain within [3]
- This file written by Colin Plumb 
- Supporting functions within this file by Dean Edwards of unknown license.
- Code Copyright (c) 2006-2013 Alexander Chemeris in these files [6][7]
- MPEG2 transport stream  Copyright (c) 2003 Fabrice Bellard in his file. [8] This is category X and can’t be included in a source release.
- This file [10] is list as copyright Tencent when it actually Copyright (c) 2013, The TOFT Authors.

Thanks,
Justin

1. src/brpc/builtin/flamegraph_perl.cpp
2. https://www.apache.org/legal/resolved.html#weak-copyleft-licenses
3. ./src/brpc/builtin/pprof_perl.cpp
4. ./src/butil/md5.cc
5. ./src/brpc/builtin/sorttable_js.cpp
6. ./src/butil/third_party/rapidjson/msinttypes/inttypes.h
7. ./src/butil/third_party/rapidjson/msinttypes/stdint.h
8. ./src/brpc/ts.cpp
9. https://www.apache.org/legal/resolved.html#category-x
10. src/butil/memory/scoped_array.h
11. https://incubator.apache.org/policy/incubation.html#disclaimers

**Comment by jamesge** [comment]
fixed 4 in [86ca8af3](https://github.com/apache/incubator-brpc/commit/86ca8af34b6f9329394e8d44c93c98a00501c7e6), 10 in [bb29ab6a](https://github.com/apache/incubator-brpc/commit/bb29ab6a74cd949e4588ff408b530a8262dac56b)

**Comment by zyearn** [comment]
fixed [6][7] in https://github.com/apache/incubator-brpc/pull/1014

**Comment by zyearn** [comment]
fixed [3] in https://github.com/apache/incubator-brpc/pull/1015

**Comment by zyearn** [comment]
fix [8] in https://github.com/apache/incubator-brpc/pull/1016/commits. The new crc code is adopted from another apache project nifi-minifi-cpp

**Comment by zyearn** [comment]
[1] is a remained problem, for now just add a DISCLAIMER-WIP(https://github.com/apache/incubator-brpc/pull/1024) to workaround.

**Comment by zyearn** [comment]
check remaining issues in https://github.com/apache/incubator-brpc/issues/1045
