### ISSUE TITLE
Are there any heartbeat APIs based on brpc ?

### ISSUE THREAD

**Issue by wuchangping** [apache/incubator-brpc#1021]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

About heartheat based on brpc.

**Describe the solution you'd like (描述你期望的解决方法)**
The heartbeat features include the cases:
1, network long latency handling
2, kill -9 process handling
3, power down handling 

**Describe alternatives you've considered (描述你想到的折衷方案)**

or examples, thanks.

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
The situations are already handled by retries and backup requests, https://github.com/apache/incubator-brpc/blob/master/docs/en/client.md#retry

**Comment by wuchangping** [comment]
> The situations are already handled by retries and backup requests, https://github.com/apache/incubator-brpc/blob/master/docs/en/client.md#retry

Thank you very much!
