### ISSUE TITLE
src/butil/containers/case_ignored_flat_map.h 中CaseIgnoredFlatSet 定义错误，编译无法通过，不能使用

### ISSUE THREAD

**Issue by SOSDAN** [apache/incubator-brpc#1022]
**Describe the bug (描述bug)**
使用该结构的代码无法编译通过
class CaseIgnoredFlatSet : public butil::**FlatMap**<
    std::string, CaseIgnoredHasher, CaseIgnoredEqual> {};

**To Reproduce (复现方法)**
使用该类insert

**Expected behavior (期望行为)**
代码写错了，应该改为：
class CaseIgnoredFlatSet : public butil::**FlatSet**<
    std::string, CaseIgnoredHasher, CaseIgnoredEqual> {};

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
Thanks for reporting, fixed in https://github.com/apache/incubator-brpc/commit/d81ba3f1bc6a7f4bd09439798678733d24e6a729
