### ISSUE TITLE
对于client来说ERPCTIMEDOUT的具体含义

### ISSUE THREAD

**Issue by walterzhaoJR** [apache/incubator-brpc#1040]
在使用brpc过程中遇到了errormsg:[E1008]Reached timeout=100ms 这个异常，查看文档后得知：

ChannelOptions.timeout_ms是对应Channel上所有RPC的总超时，Controller.set_timeout_ms()可修改某次RPC的值。单位毫秒，默认值1秒，最大值2^31（约24天），-1表示一直等到回复或错误。

ChannelOptions.connect_timeout_ms是对应Channel上所有RPC的连接超时，单位毫秒，默认值1秒。-1表示等到连接建立或出错，此值被限制为不能超过timeout_ms。注意此超时独立于TCP的连接超时，一般来说前者小于后者，反之则可能在connect_timeout_ms未达到前由于TCP连接超时而出错。

注意1：brpc中的超时是deadline，超过就意味着RPC结束，超时后没有重试。其他实现可能既有单次访问的超时，也有代表deadline的超时。迁移到brpc时请仔细区分。

注意2：RPC超时的错误码为ERPCTIMEDOUT (1008)，ETIMEDOUT的意思是连接超时，且可重试。

那么这个ERPCTIMEDOUT 是指从client发起这次request到接收response整个过程超时了吗？

**Comment by jamesge** [comment]
对，就是遇到了rpc的deadline，故超时后不会重试，对用户更可控。若需要等待一段时间后无返回便重试，对应的是backup request功能，可以搜索下文档。字面上类似的ETIMEDOUT是系统的错误码，代表连接超时。

**Comment by walterzhaoJR** [comment]
ok THX
