### ISSUE TITLE
编译出错:make: *** [protoc-gen-mcpack] 错误 1` with gcc8.2.0

### ISSUE THREAD

**Issue by fastjrun** [apache/incubator-brpc#1044]
**Describe the bug (描述bug)**
`Linking protoc-gen-mcpack
src/mcpack2pb/generator.o：在函数‘mcpack2pb::get_idl_name[abi:cxx11](google::protobuf::FieldDescriptor const*)’中：
generator.cpp:(.text+0x332)：对‘google::protobuf::internal::ExtensionSet::GetString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
src/mcpack2pb/generator.o：在函数‘mcpack2pb::generate_declarations(std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, google::protobuf::io::Printer&)’中：
generator.cpp:(.text+0x832)：对‘google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
generator.cpp:(.text+0x872)：对‘google::protobuf::io::Printer::Print(char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
……
idl_options.pb.cc:(.text+0x1b9)：对‘google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
collect2: 错误：ld 返回 1
make: *** [protoc-gen-mcpack] 错误 1`

**To Reproduce (复现方法)**
`git clone https://github.com/brpc/brpc.git
cd brpc
git log -p -1
commit fd5058c76e32270a20fb82f1ba986a90a2862f68
Merge: 074e031 91cf5cb
Author: Ge Jun <jge666@gmail.com>
Date:   Tue Jan 21 18:29:10 2020 +0800

    Merge pull request #1003 from TousakaRin/auto_cl
    
    limit minimum value of max_concurrency for auto_cl
sh config_brpc.sh --headers="/usr/include /usr/local/gflags/build/include/gflags /usr/local/protobuf/include /usr/local/leveldb/include" --libs=" /usr/local/gflags/build/lib /usr/local/protobuf/lib /usr/local/leveldb" --nodebugsymbols --cxx=/opt/complied/gcc8.2/bin/g++ --cc=/opt/complied/gcc8.2/bin/gcc
make`

**Expected behavior (期望行为)**
make success

**Versions (各种版本)**
OS: centos7.7
Compiler: gcc8.2.0
brpc: git log:fd5058c76e32270a20fb82f1ba986a90a2862f68
protobuf: libprotoc 2.6.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by buptUnixGuys** [comment]
I face the same problem. U may check protobuf version. Arena in pb 3.x is not supported yet.

**Comment by guodongxiaren** [comment]
这个是因为你编译的protobuf没有开启C++11的编译参数。所以protobuf的string不会套上cxx11的命名空间！
