### ISSUE TITLE
arm64环境，使用example/multi_threaded_echo_c++下echo_server和echo_client测试消息收发，echo_client会卡住

### ISSUE THREAD

**Issue by chenlei5662** [apache/incubator-brpc#1054]
**Describe the bug (描述bug)**
如题，arm64环境，使用example/multi_threaded_echo_c++下echo_server和echo_client测试消息收发，echo_client会卡死

**To Reproduce (复现方法)**
两台arm64服务器，
一台起server服务：./echo_server
一台起client发送消息：./echo_client -server 192.168.1.123:8002 -timeout_ms=6000 -thread_num=100

运行几分钟左右，
client 的qps为0，请求卡住；
服务端有连接超时的提示；

**Expected behavior (期望行为)**
如在x86上，运行一直平稳，没有qps为0的情况；

**Versions (各种版本)**
OS:  CentOS Linux release 7.6.1810 (AltArch)
Compiler: gcc version 4.8.5 20150623
brpc: master
protobuf: protobuf-2.5.0-8.el7.aarch64

**Additional context/screenshots (更多上下文/截图)**
server端日志如下：
[server ~]$ ./echo_server 
I0305 08:28:15.456613 61113 /mnt/incubator-brpc-master/src/brpc/server.cpp:1045] Server[example::EchoServiceImpl] is serving on port=8002.
I0305 08:28:15.456997 61113 /mnt/incubator-brpc-master/src/brpc/server.cpp:1048] Check out http://server:8002 in web browser.
W0305 08:29:07.853208 61223 /mnt/incubator-brpc-master/src/brpc/input_messenger.cpp:214] Fail to read from Socket{id=128 fd=7 addr=192.168.1.129:9932:8002} (0x51b2000): Connection timed out
W0305 08:29:27.053205 61191 /mnt/incubator-brpc-master/src/brpc/input_messenger.cpp:214] Fail to read from Socket{id=257 fd=7 addr=192.168.1.129:10102:8002} (0x7096200): Connection timed out

client端日志如下：
[client /mnt/incubator-brpc-master/example/multi_threaded_echo_c++]$ ./echo_client -server 192.168.1.123:8002 -timeout_ms=6000 -thread_num=100
I0305 08:28:46.132966 60972 client.cpp:145] Sending EchoRequest at qps=150778 latency=480
I0305 08:28:47.133238 60972 client.cpp:145] Sending EchoRequest at qps=202766 latency=488
I0305 08:28:48.133376 60972 client.cpp:145] Sending EchoRequest at qps=203046 latency=487
I0305 08:28:49.133520 60972 client.cpp:145] Sending EchoRequest at qps=204117 latency=485
I0305 08:28:50.133657 60972 client.cpp:145] Sending EchoRequest at qps=203837 latency=486
I0305 08:28:51.133794 60972 client.cpp:145] Sending EchoRequest at qps=201979 latency=490
I0305 08:28:52.133950 60972 client.cpp:145] Sending EchoRequest at qps=201911 latency=490
I0305 08:28:53.134083 60972 client.cpp:145] Sending EchoRequest at qps=201957 latency=490
I0305 08:28:54.134218 60972 client.cpp:145] Sending EchoRequest at qps=200951 latency=493
I0305 08:28:55.134363 60972 client.cpp:145] Sending EchoRequest at qps=164764 latency=492
I0305 08:28:56.134517 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:28:57.134665 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:28:58.134811 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:28:59.134958 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:00.135108 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:01.135249 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:02.135396 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:03.135547 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:04.135698 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:05.135842 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:06.135985 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:07.136130 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:08.136274 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:09.136424 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:10.136572 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:11.136723 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:12.136867 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
W0305 08:29:13.088414 60980 /mnt/incubator-brpc-master/src/brpc/socket.cpp:1615] Fail to keep-write into Socket{id=0 fd=3 addr=192.168.1.123:8002:9932} (0x207e000): Connection reset by peer
I0305 08:29:13.136994 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:13.188530 60985 /mnt/incubator-brpc-master/src/brpc/socket.cpp:2201] Checking Socket{id=0 addr=192.168.1.123:8002} (0x207e000)
I0305 08:29:13.188721 60985 /mnt/incubator-brpc-master/src/brpc/socket.cpp:2261] Revived Socket{id=0 addr=192.168.1.123:8002} (0x207e000) (Connectable)
I0305 08:29:14.137118 60972 client.cpp:145] Sending EchoRequest at qps=114095 latency=482
I0305 08:29:15.137271 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0
I0305 08:29:16.137421 60972 client.cpp:145] Sending EchoRequest at qps=0 latency=0

**Comment by chenlei5662** [comment]
网卡问题

**Comment by machh** [comment]
你好，你arm64环境编译过程是怎样的呢？我一直没编译成功， 能留个联系方式交流下吗，我邮箱 machh@qq.com
