### ISSUE TITLE
宕机后重启server节点，一段时间内client无法连接server

### ISSUE THREAD

**Issue by wu-hanqing** [apache/incubator-brpc#1057]
**Describe the bug (描述bug)**

在我们的一个测试场景下，宕机server节点，然后重启。server服务起来后，client的rpc请求还是失败，报not connected to错误，持续2分钟左右恢复。
期间bthread_worker_usage为1，其中有一个峰值800多。宕机前后，usage大概在20-30之间。

![image](https://user-images.githubusercontent.com/10327590/76071617-80af5800-5fd1-11ea-8846-01cee5b72f8c.png)
图中红框阶段bthread_worker_usage持续为1。

请教一下，产生这个问题的原因？或者说从哪些方面进行分析？

**Versions (各种版本)**
OS: debian9
Compiler: gcc-6.0
brpc:  cmmit id 1b9e0064
protobuf: 3.5.0

**Comment by zyearn** [comment]
看看这个相关issue https://github.com/apache/incubator-brpc/issues/943

**Comment by wu-hanqing** [comment]
> 看看这个相关issue #943

我们是没有开启健康检查的，提问的时候忘记说明了。而且从日志中也没有搜到相关的checking/revivid日志。
