### ISSUE TITLE
如何修改brpc.server 的并发数

### ISSUE THREAD

**Issue by lucky-you** [apache/incubator-brpc#1060]
设置访问并发个数为100个，启动server 之后，运行程序，结果成功了68个，返回了32个异常信息。我想修改server 的并发连接数量，请问在哪里修改配置？

下图是我捕获到的异常信息。
![图片](https://user-images.githubusercontent.com/22268878/76483406-ec6e4680-6451-11ea-9467-a2c8fe506bfd.png)

**Comment by jamesge** [comment]
请问打开-usercode_in_pthread的原因是？

**Comment by lucky-you** [comment]
> 请问打开-usercode_in_pthread的原因是？

项目里面默认是打开的，这个我没有改动过，可以关闭吗？

**Comment by jamesge** [comment]
-usercode_in_pthread只有在需要在整个检索流程中通过pthread local共享数据时才需要。如果无法关闭，可以调大ServerOptions.num_threads增加工作线程的数量，同时尽量避免阻塞，因为这种情况下阻塞就会阻塞整个工作线程。另外，你截图中的错误只是临时拒绝，压力下来了应该就ok了。

**Comment by lucky-you** [comment]
我也想通过调节server 的数量来增加工作线程数量，可我不是很清楚应该在哪里修改 ServerOptions.num_threads 的数量，请问一下如何修改ServerOptions.num_threads 的数量呢？

**Comment by serverglen** [comment]
> erverOptions.num_thread

在初始化 Server的时候设置ServerOptions.num_threads
