### ISSUE TITLE
brpc支持mysql的连编

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1061]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
mysql里面想用brpc的功能，编译的时候发现出现LOG_NONE冲突。
LOG_NONE是logging中的一个枚举，但是在mysql中是一个宏定义。

**Describe the solution you'd like (描述你期望的解决方法)**
LOG_NONE在brpc的代码里面并没有用到，通过将LOG_NONE改为LOG_TO_NONE即可

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
Thanks for pointing out the issue, fixed in master
