### ISSUE TITLE
How to output the function name into log by setting up logging

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1063]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
I want to output the function name into the log. How can I do?

**Describe the solution you'd like (描述你期望的解决方法)**
None

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
Sorry, no such options.

**Comment by GOGOYAO** [comment]
Will you add __FUNCTION__ into the log function?
