### ISSUE TITLE
计数溢出导致程序退出

### ISSUE THREAD

**Issue by ryankeke** [apache/incubator-brpc#1067]
**Describe the bug (描述bug)**
线上一个服务在跑4~5天左右，就会出现程序退出现象，最后的日志如下：
F0316 12:30:30.953776 393651 percentile.h:98] Check failed: _num_samples == _num_added (254 vs. 4294967280) _nu    m_added=4294967280 rhs._num_added30 _num_samples=254 rhs._num_samples=30 SAMPLE_SIZE=254 size2=30
从日志看应该是计数溢出引起的

**Comment by jamesge** [comment]
这是在fork产生的进程中么？

**Comment by ryankeke** [comment]
> 这是在fork产生的进程中么？

不是的

**Comment by jamesge** [comment]
> > 这是在fork产生的进程中么？
> 
> 不是的

这个可能是采样的线程没起来，和fork关系比较密切。一个方法是你们把brpc版本替换为master最新版，看看能否复现问题

**Comment by ryankeke** [comment]
能说下为什么采用线程没起来可能会引起这个问题？

**Comment by jamesge** [comment]
percentile需要被定期reset，这个reset是在采样线程里做的

**Comment by ryankeke** [comment]
谢谢！我试下。
