### ISSUE TITLE
cntl->latency_us() 返回负值

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1068]
**Describe the bug (描述bug)**
在使用brpc和braft的过程中，出现了
W0320 21:44:51.506333 15335 /tmp/incubator-brpc/src/bvar/detail/percentile.cpp:121] Input=-277 to 'raft_send_entries' is negative, drop
W0320 21:44:51.506701 15335 /usr/local/include/bvar/recorder.h:254] Input=2147483647 to 'raft_send_entries_normalized' overflows
`raft_send_entries` 对应的代码是 ` g_send_entries_latency << cntl->latency_us();`  也就是说`cntl->latency_us()`出现了负值。

**To Reproduce (复现方法)**
暂无

**Expected behavior (期望行为)**
返回正数

**Versions (各种版本)**
OS: cenos 7.7
Compiler: gcc8
brpc: 最新master
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
如果偶尔的话是可能的，测量latency的是wall-time，可能回退

**Comment by GOGOYAO** [comment]
> 如果偶尔的话是可能的，测量latency的是wall-time，可能回退

那这里为什么不考虑使用std::chrono::steady_clock这种来避免呢？

**Comment by PFZheng** [comment]
monotonic time 会比 wall-time 慢，统计类的数据偶尔出现时钟回退影响不大，通常优先考虑效率

**Comment by GOGOYAO** [comment]
> monotonic time 会比 wall-time 慢，统计类的数据偶尔出现时钟回退影响不大，通常优先考虑效率

有道理。不过这种latency的数据出现这种情况，也会干扰对server是否正常的判断吧

**Comment by PFZheng** [comment]
> > monotonic time 会比 wall-time 慢，统计类的数据偶尔出现时钟回退影响不大，通常优先考虑效率
> 
> 有道理。不过这种latency的数据出现这种情况，也会干扰对server是否正常的判断吧

正常情况下不会。这类指标都是统计意义上的，偶尔的异常会被平均下去

**Comment by GOGOYAO** [comment]
> > > monotonic time 会比 wall-time 慢，统计类的数据偶尔出现时钟回退影响不大，通常优先考虑效率
> > 
> > 
> > 有道理。不过这种latency的数据出现这种情况，也会干扰对server是否正常的判断吧
> 
> 正常情况下不会。这类指标都是统计意义上的，偶尔的异常会被平均下去

但是会有异常日志吧

**Comment by yc90s** [comment]
我在centos7上也出现了这个问题，运行example/parallel_echo_c++这个例子，用默认参数运行，会必现

**Comment by yc90s** [comment]
W1119 20:13:06.020002 39796 src/bvar/detail/percentile.cpp:121] Input=-27746 to `client' is negative, drop
W1119 20:13:06.020441 39762 src/bvar/detail/percentile.cpp:121] Input=-27858 to `client' is negative, drop
W1119 20:13:06.020510 39762 src/bvar/detail/percentile.cpp:121] Input=-28094 to `client_sub_0' is negative, drop
W1119 20:13:06.020464 39775 src/bvar/detail/percentile.cpp:121] Input=-27330 to `client' is negative, drop
W1119 20:13:06.020919 39762 src/bvar/detail/percentile.cpp:121] Input=-28006 to `client_sub_1' is negative, drop
W1119 20:13:06.020977 39762 src/bvar/detail/percentile.cpp:121] Input=-27989 to `client_sub_2' is negative, drop
W1119 20:13:06.021572 39788 src/bvar/detail/percentile.cpp:121] Input=-26742 to `client' is negative, drop
W1119 20:13:06.021632 39788 src/bvar/detail/percentile.cpp:121] Input=-26929 to `client_sub_0' is negative, drop
W1119 20:13:06.021649 39788 src/bvar/detail/percentile.cpp:121] Input=-26819 to `client_sub_1' is negative, drop
W1119 20:13:06.021701 39788 src/bvar/detail/percentile.cpp:121] Input=-26840 to `client_sub_2' is negative, drop
