### ISSUE TITLE
arm 编译brpc-0.9 出现如下错误:

### ISSUE THREAD

**Issue by machh** [apache/incubator-brpc#1072]
arm  平台，  
centos7.6 
gcc-4.85 
 编译brpc-0.9 出现如下错误:

Compiling src/butil/files/file_enumerator_posix.o
In file included from ./src/butil/basictypes.h:18:0,
                 from ./src/butil/files/file.h:20,
                 from src/butil/files/file_posix.cc:5:
src/butil/files/file_posix.cc: In member function ‘int64_t butil::File::Seek(butil::File::Whence, int64_t)’:

./src/butil/macros.h:173:34: **error:**    static assertion failed: off_t_64_bit
 #define BAIDU_CASSERT(expr, msg) static_assert(expr, #msg)
                                  ^
./src/butil/macros.h:218:36: note: in expansion of macro ‘BAIDU_CASSERT’
 #define COMPILE_ASSERT(expr, msg)  BAIDU_CASSERT(expr, msg)
                                    ^
src/butil/files/file_posix.cc:286:3: note: in expansion of macro ‘COMPILE_ASSERT’
   COMPILE_ASSERT(sizeof(int64_t) == sizeof(off_t), off_t_64_bit);
   ^
make: *** [src/butil/files/file_posix.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by jamesge** [comment]
用一下0.9.7或master，加入了对arm64的支持

**Comment by machh** [comment]
> 
> 
> 用一下0.9.7或master，加入了对arm64的支持

arm64没问题 ， 我这是32位arm，.armv7hl 

Linux localhost 4.19.72-300.el7.armv7hl

**Comment by leo07046219** [comment]
32bit arm的，能用么？

**Comment by wwbmmm** [comment]
32位arm不支持
