### ISSUE TITLE
brpc自带的log支持日志切割和删除老日志么？

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1074]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
brpc自带的log支持日志切割和删除老日志么？

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
不支持，此类功能都需要对接用户的LogSink自行完成。
