### ISSUE TITLE
brpc 做 http server，在传输稍微大一点的数据时存在奇怪的高延迟

### ISSUE THREAD

**Issue by billtenor** [apache/incubator-brpc#1075]
**Describe the bug (描述bug)**
1. 基于 brpc 的 http server，例如 example/http_c++_server
2. client 发 POST 请求给 server，body 的数据使用 json 格式，并稍微有些大（目前8KByte复现），部分 client 从发起请求到返回会出现超长延迟的情况（1s以上，有时2s以上）。目前发现 curl, laravel 作为 http client 会有这种情况，而 python2 python3 的 urllib 库没有这种情况。
3. 用同样的 client 给 django 的 http server 发请求，不会出现异常延迟的情况

**To Reproduce (复现方法)**
最简单的复现方法：
使用 0.9.7-rc03 编译 example/http_c++_server 并启动服务
使用 time curl $host:$port/HttpService/Echo -X POST -d @large.json --header "Content-Type: application/json" 发送POST请求，其中 large.json 文件为 8KByte 以上的 json 数据文件
测得 client 的运行时间为 1s 以上

**Expected behavior (期望行为)**
使用内建服务 rpcz 查到的延迟都在 us 级
21:39:53.172773    .    58 Processing the request in a new bthread
21:39:53.172842    .    69 Enter example.HttpService.Echo
21:39:53.172864    .    22 Leave example.HttpService.Echo
21:39:53.172902    .    38 Responded(8447)
但 client 看来延迟在 1s 以上，期望 client 延迟最多在 ms 级 

**Versions (各种版本)**
OS: centos 7.6 64bit
Compiler: gcc version 4.8.5
brpc: 0.9.7-rc03
protobuf: 3.7.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenzhangyi** [comment]
curl传输的时候，会设置 Expect: 100-continue, 这个协议brpc本身没有实现, 所以curl对等待一个超时。
加上 `-H 'Expect:'`  可以解决这个问题

**Comment by billtenor** [comment]
加上 -H 'Expect:'，问题解决了，非常感谢！
我记得我仔细看过文档，这个信息好像没在文档里，可以更新一下
