### ISSUE TITLE
Channel在server已kill的时候，init成功了

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1077]
**Describe the bug (描述bug)**
channel 第一次init的时候，server正常运转。然后把server kil掉，在此init  channel，init操作依然成功。
这个现象是符合预期的么？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
server kill之后，channel init失败

**Versions (各种版本)**
OS: centos 7.7
Compiler: gcc 8
brpc: master最新代码
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
符合预期，socket建连是发生在第一次发送数据的时候。

**Comment by GOGOYAO** [comment]
> 符合预期，socket建连是发生在第一次发送数据的时候。

哦。init channel的时候，只是检查了ip port的格式对不对？

**Comment by zyearn** [comment]
> > 符合预期，socket建连是发生在第一次发送数据的时候。
> 
> 哦。init channel的时候，只是检查了ip port的格式对不对？

嗯，另外如果访问集群的话，会去访问naming service得到集群列表

**Comment by GOGOYAO** [comment]
感谢
