### ISSUE TITLE
brpc stream模式，stream和connection的关系

### ISSUE THREAD

**Issue by hello-jianghongke** [apache/incubator-brpc#1080]
现在的实现，brpc stream模式下，stream和connection是一对一的吧，就是一个connection上只有一个stream，因为我看StreamClose直接就关连接了

**Comment by chenzhangyi** [comment]
如果connection指的是tcp connection的话， 是一对多的. 一个connection上可以有多个stream.

**Comment by jenrryyou** [comment]
一对多的关系。`stream::close`关闭的是`_fake_socket_weak_ref`引用的`fake_socket`，不是真正的网络socket。`fake_socket`用来复用socket对象的写出逻辑（真正写出的时候调用的是`_host_socket`）。

> 现在的实现，brpc stream模式下，stream和connection是一对一的吧，就是一个connection上只有一个stream，因为我看StreamClose直接就关连接了
