### ISSUE TITLE
FlatMap::erase在特定情况下，可能会出现Bug。

### ISSUE THREAD

**Issue by nnnjkk** [apache/incubator-brpc#1084]
**Describe the bug (描述bug)**
如果，Value的结构体存储了类似文件描述符这样的系统资源，且在析构时释放系统资源。
当删除一个bucket的第一个node，且第二个node非空的时候，会出现Bug。
因为operator=方法，一般只会把系统资源的ID赋值，而并不会主动释放系统资源；所以第一个node的系统资源不能得到释放。
又因为调用了第二个node的析构，所以会释放掉第二个node的资源，让以后使用这个node的时候出异常。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
将“用第二个node赋值第一个node；析构第二个node；”
改成“析构第一个node；用第二个node拷贝构造第一个node；”

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
可以直接上示例代码看看吗？

**Comment by jamesge** [comment]
> 改成“析构第一个node；用第二个node拷贝构造第一个node；”
之后不还是要析构“第二个node”么？如果拷贝构造也仅是拷贝下id，第二个node析构后，留在第一个node里的id仍然是野的。

这里的问题是放在FlatMap中的对象没有正确地实现operator=（以及拷贝构造函数）。
