### ISSUE TITLE
使用cmake依赖brpc编译成功，运行报undefined symbol: pthread_mutex_lock

### ISSUE THREAD

**Issue by bai-charisu** [apache/incubator-brpc#1086]
使用cmake动态依赖brpc，编译显示正常，但是运行的时候报错：
![image](https://user-images.githubusercontent.com/29573385/79290344-718bc600-7efe-11ea-9948-909a47874238.png)

nm查看libbrpc.so是有这个符号的
![image](https://user-images.githubusercontent.com/29573385/79290386-8ff1c180-7efe-11ea-9365-75ac04a5ad17.png)

ldd查看，可执行程序也确实链接了brpc和pthread，所以不知道问题出在哪里：
![image](https://user-images.githubusercontent.com/29573385/79290466-c2032380-7efe-11ea-87e6-28ff24e5f0c2.png)

**Comment by lils1102** [comment]
遇到了同样的问题

**Comment by kungf** [comment]
+1

**Comment by kungf** [comment]
@bai-charisu have you solve this problem？

**Comment by bai-charisu** [comment]
解决了，怀疑是加载顺序的问题，在编译的时候把-lbrpc放在最前面之后ok了

**Comment by kungf** [comment]
> 解决了，怀疑是加载顺序的问题，在编译的时候把-lbrpc放在最前面之后ok了

ok，thanks  very much.

**Comment by starrysky9959** [comment]
```bash
./mongodb/build/install/bin/mongod: symbol lookup error: /usr/lib/libbrpc.so: undefined symbol: pthread_mutex_lock
```
用静态链接一切正常，用动态链接能通过编译链接，但一运行就出现上述报错。

**Comment by starrysky9959** [comment]
感觉本质是因为brpc通过`dlsym(RTLD_NEXT, "pthread_mutex_lock");`hook了`libpthread`中的`pthread_mutex_lock`方法导致的. `RTLD_NEXT`意味着在load dynamic libraries时, `libpthread`必须在`libbrpc`之后被load, 且两者中间不能有其他含有symbol为`pthread_mutex_lock`的library(虽然一般不会再有了). 以下几篇文章介绍了相关概念和实践.
[https://optumsoft.com/dangers-of-using-dlsym-with-rtld_next/](https://optumsoft.com/dangers-of-using-dlsym-with-rtld_next/)

[https://csstormq.github.io/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E7%AF%87%E4%B9%8B%E9%93%BE%E6%8E%A5%EF%BC%8816%EF%BC%89%EF%BC%9A%E7%9C%9F%E6%AD%A3%E7%90%86%E8%A7%A3%20RTLD_NEXT%20%E7%9A%84%E4%BD%9C%E7%94%A8](https://csstormq.github.io/blog/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB%E7%BB%9F%E7%AF%87%E4%B9%8B%E9%93%BE%E6%8E%A5%EF%BC%8816%EF%BC%89%EF%BC%9A%E7%9C%9F%E6%AD%A3%E7%90%86%E8%A7%A3%20RTLD_NEXT%20%E7%9A%84%E4%BD%9C%E7%94%A8)

[https://zhuanlan.zhihu.com/p/44132805](https://zhuanlan.zhihu.com/p/44132805)


我的项目中不方便修改pthread的链接位置，可以利用`LD_PRELOAD`来提前加载`libbrpc`以满足这一要求.
```bash
export LD_PRELOAD=/lib/libbrpc.so
```
