### ISSUE TITLE
请问大佬们，brpc里如何进行线程hang检测

### ISSUE THREAD

**Issue by tinnfu** [apache/incubator-brpc#1088]
RT，

使用过程中发现有些运行比较慢的task会导致后续请求排队时间变长。brpc有没有提供什么方法可以动态的检测线程hang

例如，我提供一个时间阈值：T(ms)，期望能检测出来某线程超过T时间一直在处理同一个任务，并且能把处理该任务的堆栈打出来

**Comment by jamesge** [comment]
[tracing](https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpcz.md)有类似的作用
