### ISSUE TITLE
brpc支持链接保活吗？怎么设置？

### ISSUE THREAD

**Issue by nju2012zcl** [apache/incubator-brpc#1089]
项目里使用brpc调用server请求，tcp连接可能长时间静默(没有调用)，这个时候server会释放该链接，client再次调用时会出现问题。

所以，想知道brpc怎么设置keepalive，能够间隔固定时间ping一下server。

**Comment by jamesge** [comment]
server端关闭连接大概率会导致client端关闭连接，下次rpc时会按需创建连接，对用户是透明的。即使一些原因下（fin包丢失）client端没关闭连接，下次写时也会发现，重试会解决这个问题。

**Comment by nju2012zcl** [comment]
client使用brpc的方式访问clb，clb再访问real server，现在的问题是clb会释放长时间静默的链接，client再次调用clb时clb也不返回rst(什么都不返回)，导致client一直收到timeout。tcp重试十几分钟后，才会重建链接，恢复正常。

所以希望brpc能够设置间隔一定时间ping一下clb；或者client能够主动断开连接，下次调用时再重连。

**Comment by gydong** [comment]
听起来是CLB的工作方式不太符合预期？释放连接后，当有新的数据包需要传输时，应该和real server重新建立可用连接才对。不管CLB工作在4层还是7层，都应该有相应的处理机制。
