### ISSUE TITLE
h2grpc core

### ISSUE THREAD

**Issue by guocanwen** [apache/incubator-brpc#1093]
server端是brpc
client 采用h2:grpc
今天在异常情况下，好几台client直接FATAL掉：
[http2_rpc_protocol.cpp:1765] Check failed: h2_req 
看代码
    H2UnsentRequest* h2_req = dynamic_cast<H2UnsentRequest*>(accessor.get_stream_user_data());
    CHECK(h2_req);
要么accessor.get_stream_user_data() = nullptr，要么类型不匹配
都是什么情况下才能出现呢？

**Comment by zyearn** [comment]
可以复现吗？日志上有什么异常吗？

**Comment by guocanwen** [comment]
不能复现，当时很多请求都超时（120ms）
需要补充的是：部分server是grpc，部分server是brpc

**Comment by guocanwen** [comment]
![image](https://user-images.githubusercontent.com/11960192/80078972-37679780-8582-11ea-8350-7c5571b6d841.png)

**Comment by guocanwen** [comment]
很多这样的异常

**Comment by guocanwen** [comment]
一台机器重启之后触发其他机器也core掉

**Comment by guocanwen** [comment]
研究下代码，发现是必现的。
条件是：

**Comment by guocanwen** [comment]
![image](https://user-images.githubusercontent.com/11960192/81824686-572e2200-9568-11ea-84e6-07e7554e3d22.png)
满足这几个条件，+h2:grpc + 有重试， 必然会core
原因在于cntl->HandleSendFailed()会issuseRpc，但是_serialize_request并没有执行

**Comment by yann-yy** [comment]
#1114 相同的问题

**Comment by zyearn** [comment]
Fix in https://github.com/apache/incubator-brpc/pull/1161, Thanks all.
