### ISSUE TITLE
brpc版本: 0.9.7 和 0.9.7-rc3重叠

### ISSUE THREAD

**Issue by darmac** [apache/incubator-brpc#1103]
**Describe the bug (描述bug)**
请问 brpc `0.9.7` 和 `0.9.7-rc3` 是一个版本吗?
正式版本和rc版本混在一起的话,有些用户可能比较难以抉择到底用不用.
是否需要修改一下tag呢?

**Comment by zyearn** [comment]
是一个版本，已经更新0.9.7的下载链接了，可以再试一下。

**Comment by darmac** [comment]
好的,谢谢.
