### ISSUE TITLE
rpc_press 是否支持动态 request

### ISSUE THREAD

**Issue by m3ngyang** [apache/incubator-brpc#1104]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
rpc_press 是否支持动态 request，每次发送的请求不一样？

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
rpc-press的输入可以是一个json文件，从中随机选取
