### ISSUE TITLE
在aarch64处理器上编译brpc-0.9.5出错

### ISSUE THREAD

**Issue by codeofdave** [apache/incubator-brpc#1109]
**Describe the bug (描述bug)**
在aarch64处理器上编译brpc出错。

**To Reproduce (复现方法)**
doris依赖brpc，通过doris的build-thirdparty.sh会自动编译brpc，当编译brpc时，就会报错。

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:CentOS Linux release 7.6.1810
Compiler:gcc version 7.3.0
brpc:brpc-0.9.5
protobuf:3.5.1

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/5085284/81381608-92cb8500-913f-11ea-94e5-20fd4ca00d07.png)

/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h: In function ‘void bthread::jump_stack(bthread::ContextualStack*, bthread::ContextualStack*)’:
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:75: error: expression list treated as compound expression in functional cast [-fpermissive]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);

**Comment by codeofdave** [comment]
详细报错：
`===== begin build incubator-brpc-0.9.5
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found gflags: /root/incubator-doris-master/thirdparty/installed/lib/libgflags.a
fatal: Not a git repository (or any of the parent directories): .git
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Protobuf: /root/incubator-doris-master/thirdparty/installed/lib/libprotobuf.a;-lpthread (found version "3.5.1") 
-- Found OpenSSL: /root/incubator-doris-master/thirdparty/installed/lib/libcrypto.a (found version "1.0.2k") 
-- Found Protobuf: /root/incubator-doris-master/thirdparty/installed/lib/libprotobuf.a;-lpthread;-lpthread (found version "3.5.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/build
Scanning dependencies of target PROTO_LIB
[  0%] Building CXX object CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o
Scanning dependencies of target OBJ_LIB
[  1%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/rtmp.pb.cc.o
[  1%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/collector.cpp.o
[  1%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/rpc_dump.pb.cc.o
[  1%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/get_favicon.pb.cc.o
[  1%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/default_variables.cpp.o
[  1%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/span.pb.cc.o
[  2%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/percentile.cpp.o
[  3%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/builtin_service.pb.cc.o
[  3%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/detail/sampler.cpp.o
[  3%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/gflag.cpp.o
[  4%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/latency_recorder.cpp.o
[  4%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/get_js.pb.cc.o
[  4%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bvar/variable.cpp.o
[  4%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/errno.pb.cc.o
[  5%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/nshead_meta.pb.cc.o
[  5%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/bthread.cpp.o
In file included from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack.h:25:0,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_meta.h:26,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_control.h:28,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_group.h:23,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/bthread.cpp:22:
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/context.h:69:1: error: expected initializer before ‘bthread_jump_fcontext’
 bthread_jump_fcontext(bthread_fcontext_t * ofc, bthread_fcontext_t nfc,
 ^~~~~~~~~~~~~~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/context.h:72:1: error: expected initializer before ‘bthread_make_fcontext’
 bthread_make_fcontext(void* sp, size_t size, void (* fn)( intptr_t));
 ^~~~~~~~~~~~~~~~~~~~~
In file included from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack.h:78:0,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_meta.h:26,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_control.h:28,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/task_group.h:23,
                 from /root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/bthread.cpp:22:
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h: In function ‘void bthread::jump_stack(bthread::ContextualStack*, bthread::ContextualStack*)’:
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:75: error: expression list treated as compound expression in functional cast [-fpermissive]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);
                                                                           ^
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:24: warning: left operand of comma operator has no effect [-Wunused-value]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);
                        ^~~~~~~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:44: warning: right operand of comma operator has no effect [-Wunused-value]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);
                                        ~~~~^~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:75: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);
                                                                           ^
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:129:5: warning: statement has no effect [-Wunused-value]
     bthread_fcontext_t(&from->context, to->context, 0/*not skip remained*/);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[  5%] Building CXX object CMakeFiles/PROTO_LIB.dir/brpc/options.pb.cc.o
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h: In instantiation of ‘bthread::StackFactory<StackClass>::Wrapper::Wrapper(void (*)(intptr_t)) [with
 StackClass = bthread::SmallStackClass; intptr_t = long int]’:/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:188:13:   required from ‘T* butil::ObjectPool<T>::LocalPool::get(const A1&) [with A1 = void (*)
(long int); T = bthread::StackFactory<bthread::SmallStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:235:32:   required from ‘T* butil::ObjectPool<T>::get_object(const A1&) [with A1 = void (*)(lon
g int); T = bthread::StackFactory<bthread::SmallStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool.h:78:55:   required from ‘T* butil::get_object(const A1&) [with T = bthread::StackFactory<bthread::Sm
allStackClass>::Wrapper; A1 = void (*)(long int)]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:68:42:   required from ‘static bthread::ContextualStack* bthread::StackFactory<StackClass>::get_sta
ck(void (*)(intptr_t)) [with StackClass = bthread::SmallStackClass; intptr_t = long int]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:98:47:   required from here
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:23: error: expression list treated as compound expression in functional cast [-fpermissive]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:50: warning: left operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                          ~~~~~~~~^~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:66: warning: right operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                                          ~~~~~~~~^~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h: In instantiation of ‘bthread::StackFactory<StackClass>::Wrapper::Wrapper(void (*)(intptr_t)) [with
 StackClass = bthread::NormalStackClass; intptr_t = long int]’:/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:188:13:   required from ‘T* butil::ObjectPool<T>::LocalPool::get(const A1&) [with A1 = void (*)
(long int); T = bthread::StackFactory<bthread::NormalStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:235:32:   required from ‘T* butil::ObjectPool<T>::get_object(const A1&) [with A1 = void (*)(lon
g int); T = bthread::StackFactory<bthread::NormalStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool.h:78:55:   required from ‘T* butil::get_object(const A1&) [with T = bthread::StackFactory<bthread::No
rmalStackClass>::Wrapper; A1 = void (*)(long int)]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:68:42:   required from ‘static bthread::ContextualStack* bthread::StackFactory<StackClass>::get_sta
ck(void (*)(intptr_t)) [with StackClass = bthread::NormalStackClass; intptr_t = long int]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:100:48:   required from here
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:23: error: expression list treated as compound expression in functional cast [-fpermissive]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:50: warning: left operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                          ~~~~~~~~^~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:66: warning: right operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                                          ~~~~~~~~^~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h: In instantiation of ‘bthread::StackFactory<StackClass>::Wrapper::Wrapper(void (*)(intptr_t)) [with
 StackClass = bthread::LargeStackClass; intptr_t = long int]’:/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:188:13:   required from ‘T* butil::ObjectPool<T>::LocalPool::get(const A1&) [with A1 = void (*)
(long int); T = bthread::StackFactory<bthread::LargeStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool_inl.h:235:32:   required from ‘T* butil::ObjectPool<T>::get_object(const A1&) [with A1 = void (*)(lon
g int); T = bthread::StackFactory<bthread::LargeStackClass>::Wrapper]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/butil/object_pool.h:78:55:   required from ‘T* butil::get_object(const A1&) [with T = bthread::StackFactory<bthread::La
rgeStackClass>::Wrapper; A1 = void (*)(long int)]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:68:42:   required from ‘static bthread::ContextualStack* bthread::StackFactory<StackClass>::get_sta
ck(void (*)(intptr_t)) [with StackClass = bthread::LargeStackClass; intptr_t = long int]’/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:102:47:   required from here
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:23: error: expression list treated as compound expression in functional cast [-fpermissive]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:50: warning: left operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                          ~~~~~~~~^~~~~~
/root/incubator-doris-master/thirdparty/src/incubator-brpc-0.9.5/src/bthread/stack_inl.h:55:66: warning: right operand of comma operator has no effect [-Wunused-value]
             context = bthread_fcontext_t(storage.bottom, storage.stacksize, entry);
                                                          ~~~~~~~~^~~~~~~~~
`

**Comment by machh** [comment]
试下 0.90

**Comment by wwbmmm** [comment]
最新master已支持aarch64
