### ISSUE TITLE
Wrong FlvWriter header when audo/video only

### ISSUE THREAD

**Issue by zyearn** [apache/incubator-brpc#1110]
**Describe the bug (描述bug)**

FlvWriter直接在header中的媒体标识位中写入[0x05](https://github.com/apache/incubator-brpc/blob/master/src/brpc/rtmp.cpp#L66)(0x04是音频，0x01是视频），忽略了用户可能只需要音频/视频，导致flv的音频/视频流在某些播放器中无法播放。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

根据用户输入来写入header。

**Comment by luluyouyue** [comment]
老大，这个问题解决了吗

**Comment by zyearn** [comment]
还没有，有兴趣的话可以给我们提pr。

**Comment by luluyouyue** [comment]
> 还没有，有兴趣的话可以给我们提pr。

我试试^_^

**Comment by luluyouyue** [comment]
我看了下代码，不是很懂这个问题的解决思路，什么叫根据用户输入来写入header？

**Comment by zyearn** [comment]
比如可以给flvWriter的构造函数加一个struct FlvWriterOption类似的参数，里面用来控制用户的预期行为。

**Comment by v1siuol** [comment]
I can pick up this one, if still available :)
