### ISSUE TITLE
32 arm编译brpc错误

### ISSUE THREAD

**Issue by machh** [apache/incubator-brpc#1111]
**Describe the bug (描述bug)**

arm  32位 centos    (armv7hl)  编译brpc-0.9.0 错误:

Compiling src/butil/hash.o
In file included from ./src/butil/basictypes.h:18:0,
                 from ./src/butil/files/file.h:20,
                 from src/butil/files/file_posix.cc:5:
src/butil/files/file_posix.cc: In member function ‘int64_t butil::File::Seek(butil::File::Whence, int64_t)’:
./src/butil/macros.h:173:34: error: static assertion failed: off_t_64_bit
 #define BAIDU_CASSERT(expr, msg) static_assert(expr, #msg)
                                  ^
./src/butil/macros.h:218:36: note: in expansion of macro ‘BAIDU_CASSERT’
 #define COMPILE_ASSERT(expr, msg)  BAIDU_CASSERT(expr, msg)
                                    ^
src/butil/files/file_posix.cc:286:3: note: in expansion of macro ‘COMPILE_ASSERT’
   COMPILE_ASSERT(sizeof(int64_t) == sizeof(off_t), off_t_64_bit);
   ^
make: *** [src/butil/files/file_posix.o] Error 1
make: *** Waiting for unfinished jobs....

**To Reproduce (复现方法)**

编译命令
sh config_brpc.sh  --headers="/usr/include  /home/machh/out/gflags/include/gflags \
/usr/local/openssl/include/openssl \
/home/machh/out/protobuf-2.6/include \
/home/machh/out/leveldb-1.2/include" \
--libs="/home/machh/out/gflags/lib  /usr/local/openssl/lib /home/machh/out/protobuf-2.6/lib /home/machh/out/leveldb-1.2/lib" --nodebugsymbols 

**Expected behavior (期望行为)**

使用同样版本brpc，同样环境，在华为arm64服务器编译OK，arm32机器上报上述错误

**Versions (各种版本)**
OS:  CentOS Linux release 7.7.1908 (AltArch)

Linux localhost 4.19.72-300.el7.armv7hl

Compiler:  gcc version 4.8.5
brpc:  brpc-0.9.0
protobuf:  protobuf-2.6/

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
brpc不支持32位系统

**Comment by leo07046219** [comment]
> brpc不支持32位系统
1.有支持计划么？
2.如果自己去支持，是否具备可行性，成本多高？

**Comment by wwbmmm** [comment]
> > brpc不支持32位系统
> > 1.有支持计划么？
> > 2.如果自己去支持，是否具备可行性，成本多高？

没有支持计划
