### ISSUE TITLE
check failed when retry after a ELIMIT failure

### ISSUE THREAD

**Issue by yann-yy** [apache/incubator-brpc#1114]
**Describe the bug (描述bug)**
thread mode: pthread
max retry: 3
request mode: synchronous request
protocol: h2:grpc

call method fail because of pthread exhaust
```cpp
if (FLAGS_usercode_in_pthread &&
    done != NULL &&
    TooManyUserCode()) {
    cntl->SetFailed(ELIMIT, "Too many user code to run when "
                    "-usercode_in_pthread is on");
    return cntl->HandleSendFailed();
}
```
code path: `HandleSendFailed`->`OnVersionedRPCReturned`->`IssueRPC`->`PackH2Request`
and CHECK `h2_req` failed.

```cpp
H2UnsentRequest* h2_req = dynamic_cast<H2UnsentRequest*>(accessor.get_stream_user_data());
CHECK(h2_req);
```
root cause: `PackH2Request` before `SerializeHttpRequest` which will set a stream creator and create stream user data later

**To Reproduce (复现方法)**
use pthread mode, and set pthread num = 1, will easily reproduce this case in stress test

**Expected behavior (期望行为)**
retry properly or do not retry in this case would be nicer than check fail.

**Versions (各种版本)**
OS: centos 7
Compiler: gcc8.3
brpc: 0.9.5
protobuf: 3.5.1

**Additional context/screenshots (更多上下文/截图)**
![stack](https://user-images.githubusercontent.com/32092715/81826118-04556a00-956a-11ea-95e3-fa3c71a79b87.png)

**Comment by zyearn** [comment]
Thanks for reporting and we will check it and fix this later.
