### ISSUE TITLE
RedisCommandHandler在多连接场景下，做不了batch？

### ISSUE THREAD

**Issue by liumh8** [apache/incubator-brpc#1119]
如果在某个连接上，[flush_batched](https://github.com/apache/incubator-brpc/blob/a3b22660096c4f00cfdffc7571063603ccb5a428/src/brpc/redis.h#L264)为false的情况下，缓存了几条命令，这时候RedisCommandHandler处理另一条连接的请求，且flush_batched为true，将已缓存的命令都处理完返回，但是其中一些命令是来自其他连接的。请问是否有这样的问题？

**Comment by liumh8** [comment]
@zyearn 请问是否有这样的问题？

**Comment by zyearn** [comment]
是的，目前有这个问题，正在计划修复，先用非batch版本吧。

**Comment by liumh8** [comment]
> 是的，目前有这个问题，正在计划修复，先用非batch版本吧。

请问这个大概什么时候能修复好？此外，有另一个问题，对于一个命令'set key value'，RedisCommandHandler的Run函数提供了[const std::vector<const char*>& args](https://github.com/apache/incubator-brpc/blob/a3b22660096c4f00cfdffc7571063603ccb5a428/src/brpc/redis.h#L262)这个参数，但是如果value里面包含字符 '\0'，该怎么处理？

**Comment by zyearn** [comment]
> > 是的，目前有这个问题，正在计划修复，先用非batch版本吧。
> 
> @zyearn 请问这个大概什么时候能修复好？此外，有另一个问题，对于一个命令'set key value'，RedisCommandHandler的Run函数提供了[const std::vector<const char*>& args](https://github.com/apache/incubator-brpc/blob/a3b22660096c4f00cfdffc7571063603ccb5a428/src/brpc/redis.h#L262)这个参数，但是如果value里面包含字符 '\0'，该怎么处理？

batch的问题会尽快修复，可能1~2周。目前的实现value不是二进制安全的，可以先做个base64来绕过这个问题。
