### ISSUE TITLE
当event_dispatcher_num 大于 num_threads 时，ctrl c失效

### ISSUE THREAD

**Issue by baiwfg2** [apache/incubator-brpc#1120]
**Describe the bug (描述bug)**
我发现
1. 当event_dispatcher_num 大于 num_threads ， http server的一个简单测试中，qps大于 event_dispatcher_num =num_threads 时的qps。`我原本以为 event_dispatcher_num 不应该大于 num_threads `？？
2. 当event_dispatcher_num 大于 num_threads时，用ctrl c 停止不了服务，ctrl \ 可以。但当 event_dispatcher_num 小于 num_threads时，ctrl c是可以的。这行为不一致

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/5157680/82431537-58f46a00-9ac1-11ea-95c0-bbf5bf0448c4.png)

**Comment by gydong** [comment]
event_dispatcher_num 保持默认值即可

**Comment by baiwfg2** [comment]
@gydong 实际压测发现不是如此哦，我的server 24cores,一种情况是num_threads=event_dispatcher_num=24， 一种是num_threads=24,event_dispatcher_num默认，结果随着连接数增加，吞吐前者明显要好 ，延时也要好！

![image](https://user-images.githubusercontent.com/5157680/82745457-23989680-9db7-11ea-9fb0-2ba21a2a5ed2.png)

![image](https://user-images.githubusercontent.com/5157680/82745499-b9ccbc80-9db7-11ea-9738-cfc575b53012.png)

**Comment by zyearn** [comment]
目前event_dispatcher跑在worker里，epoll_wait会无限阻塞worker，如果event_dispatcher_num大于worker数量的话，那么所有worker都被阻塞了。这时候发一个SIGINT，并没有可用worker来做一些清理工作，所以一直卡住了。把event_dispatcher_num设置小于worker数量（至少有一个可用worker）可以暂时规避这个问题。

**Comment by onmore** [comment]
unsubscribe







在 2020-05-22 14:35:55，"gydong" <notifications@github.com> 写道：

event_dispatcher_num 保持默认值即可

**Comment by NageNalock** [comment]
我这里还有其他问题.

当设置 event_dispatcher_num 等于 num_threads 时, 在代码中使用 channel 去请求后台 http_server, 会发不出去请求

brpc 接口代码
```c++
    void Echo(google::protobuf::RpcController* cntl_base,
              const HttpRequest*,
              HttpResponse*,
              google::protobuf::Closure* done) {
        // This object helps you to call done->Run() in RAII style. If you need
        // to process the request asynchronously, pass done_guard.release().
        brpc::ClosureGuard done_guard(done);
        
        brpc::Controller* cntl =
            static_cast<brpc::Controller*>(cntl_base);

        butil::IOBufBuilder os;
        // Fill response.
        cntl->http_response().set_content_type("text/plain");

        brpc::Controller c_cntl;
        c_cntl.http_request().uri() = url;
        c_cntl.http_request().set_method(brpc::HTTP_METHOD_POST);

        c_cntl.request_attachment().append(cntl->request_attachment());
        channel.CallMethod(NULL, &c_cntl, NULL, NULL, NULL);
        if (c_cntl.Failed()) {
            std::cerr << c_cntl.ErrorText() << std::endl;
            os << c_cntl.ErrorText() << '\n';
            cntl->SetFailed(c_cntl.ErrorText());
        } else {
            // os << "queries:";
            for (brpc::URI::QueryIterator it = cntl->http_request().uri().QueryBegin();
                    it != cntl->http_request().uri().QueryEnd(); ++it) {
                os << ' ' << it->first << '=' << it->second;
            }
            os << c_cntl.response_attachment() << '\n';
        }

        os.move_to(cntl->response_attachment());
    }
```

brpc启动命令(第一个参数是后台 server 接口)
```shell
./router_server xxx.xxx.xxx.xx:20002/echo  -num_threads=24 -event_dispatcher_num=12
```
使用 curl 测试. 请求被阻塞住了, 经过抓包, brpc 没有发出 http 请求
![image](https://user-images.githubusercontent.com/33447197/94511602-60383b00-024c-11eb-8195-1ecb8806a227.png)

当设置 num_threads 数量大于 event_dispatcher_num 时, 无该现象, 可正常收发请求
```shell
./router_server xxx.xxx.xxx.xx:20002/echo  -num_threads=24 -event_dispatcher_num=12
```

**Comment by gydong** [comment]
你这个场景在实际生产环境下存在吗？还是纯粹为了研究，event_dispatcher_num 一般保持默认，即便要增加也远比worker个数少

**Comment by NageNalock** [comment]
> 你这个场景在实际生产环境下存在吗？还是纯粹为了研究，event_dispatcher_num 一般保持默认，即便要增加也远比worker个数少

在进行项目技术调研, 场景里可能会有大量的短连接, 所以想把 event_dispatcher_num 调大. 但是我发现似乎Brpc所有的链接都是由一个线程来完成的? 短连接场景的 CPU 负载很不均匀, 负载最高的 CPU 函数栈里可以看到是在抢 fd 的锁
![image](https://user-images.githubusercontent.com/33447197/94541557-4dd4f600-027a-11eb-9642-edac8d163ec3.png)

![image](https://user-images.githubusercontent.com/33447197/94541521-43b2f780-027a-11eb-9a2b-a1ad80862103.png)

**Comment by gydong** [comment]
上图对应的配置是什么样的？几个worker，几个event_dispatcher_num

**Comment by gydong** [comment]
微信号可以发我邮箱中，我加你到开发者群中

**Comment by NageNalock** [comment]
> 上图对应的配置是什么样的？几个worker，几个event_dispatcher_num

24核机器, 24个线程, event_dispatcher_num=24

使用 wrk 压测的 http 协议

**Comment by NageNalock** [comment]
> 微信号可以发我邮箱中，我加你到开发者群中

已发邮件, 感谢
