### ISSUE TITLE
undefined reference to `google::protobuf::io::Printer::Print

### ISSUE THREAD

**Issue by darionyaphet** [apache/incubator-brpc#1124]
**Describe the bug (描述bug)**

make 的时候：

```undefined reference to `google::protobuf::io::Printer::Print```

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: CentOS 7
Compiler: 8.2.0
brpc:  incubator-brpc-0.9.7
protobuf: libprotoc 2.5.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by sebastianliu** [comment]
May I know how you solved it issue later? Seems I have the same error like above

**Comment by darionyaphet** [comment]
The new version does not have this problem. Maybe you can have a try.

**Comment by trikker** [comment]
If you are using Ubuntu or Debian, maybe this will help:
```
sudo apt-get install libprotobuf-dev protobuf-compiler
```
