### ISSUE TITLE
make -j8 71%

### ISSUE THREAD

**Issue by breaveSun** [apache/incubator-brpc#1126]
**Describe the bug (描述bug)**
Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/builtin/bthreads_service.cpp.o
In file included from /Users/yuemeihui/kit/unit-uskit/third_party/brpc/src/butil/file_util_posix.cc:26:
/Users/yuemeihui/kit/unit-uskit/third_party/brpc/src/butil/mac/foundation_util.h:54:35: error: 
      typedef redefinition with different types ('struct OpaqueSecTrustRef *' vs
      'struct __SecACL *')
typedef struct OpaqueSecTrustRef* SecACLRef;
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:216:46: note: 
      previous definition is here
typedef struct CF_BRIDGED_TYPE(id) __SecACL *SecACLRef API_UNAVAILABLE(i...
                                             ^
In file included from /Users/yuemeihui/kit/unit-uskit/third_party/brpc/src/butil/file_util_posix.cc:26:
/Users/yuemeihui/kit/unit-uskit/third_party/brpc/src/butil/mac/foundation_util.h:55:48: error: 
      typedef redefinition with different types ('struct
      OpaqueSecTrustedApplicationRef *' vs 'struct __SecTrustedApplication *')
typedef struct OpaqueSecTrustedApplicationRef* SecTrustedApplicationRef;
                                               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:200:61: note: 
      previous definition is here
typedef struct CF_BRIDGED_TYPE(id) __SecTrustedApplication *SecTrustedAp...

……
[ 71%] Built target OBJ_LIB
make: *** [all] Error 2

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
如何才能通过编译成功

**Versions (各种版本)**
OS:10.15.4 (19E287)
Compiler:Apple clang version 11.0.3 (clang-1103.0.32.59)
brpc:2ae7f04ce513c6aee27545df49d5439a98ae3a3f
protobuf: libprotoc 3.6.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
这个是老版本吧，新版本（master或者0.9.7）已经修复了。
