### ISSUE TITLE
ParseRedisMessage 非法内存引用？

### ISSUE THREAD

**Issue by liumh8** [apache/incubator-brpc#1131]
如果这里[parser](https://github.com/apache/incubator-brpc/blob/4e519089a4f009c6892409a1a70d76fdb07eb5d5/src/brpc/policy/redis_protocol.cpp#L172)返回`PARSE_ERROR_NOT_ENOUGH_DATA`，说明只解析了一部分，但是[arena](https://github.com/apache/incubator-brpc/blob/4e519089a4f009c6892409a1a70d76fdb07eb5d5/src/brpc/policy/redis_protocol.cpp#L192)会把之前已解析参数申请的内存释放掉，那么等这个命令完全解析后，使用时就引用了非法内存地址。

**Comment by liumh8** [comment]
如果parser返回PARSE_OK，才arena.clear()

**Comment by liumh8** [comment]
@zyearn 你好，请确认一下是否如上所述？

**Comment by zyearn** [comment]
是的，我看到你在新的commit修复了，我看一下。另外pr还剩两个review意见也修改提交一下吧。

**Comment by luluyouyue** [comment]
请问这个问题已经修复了吗

**Comment by gydong** [comment]
已经修复了，见：https://github.com/apache/incubator-brpc/pull/1156

**Comment by liumh8** [comment]
> 已经修复了，见：#1156
没有修复吧，1156是修复的另一个[bug](https://github.com/apache/incubator-brpc/issues/1155)吧
