### ISSUE TITLE
怎么开启brpc框架的log？

### ISSUE THREAD

**Issue by DieYoungWsn** [apache/incubator-brpc#1133]
在文档中找不到

**Comment by zyearn** [comment]
可以找一个example/下的任一例子看下

**Comment by DieYoungWsn** [comment]
我的意思是开启brpc本身框架的log，不用用户自己打的那种

**Comment by zyearn** [comment]
可以用./program --help看一下，搜一下'Flags from src/butil/logging.cc'。

另一个可能有用的log是-http_verbose，可以把http req/res打印出来。

**Comment by DieYoungWsn** [comment]
好的，非常感谢～

**Comment by tuhbo** [comment]
![image](https://github.com/apache/brpc/assets/75490989/02583c63-f5eb-4026-8b3f-24b761c006ae)
这个http_verbose怎么打开呢

**Comment by chenBright** [comment]
`./program -http_verbose=true`
这个是gflag，可以看看[gflag的文档](https://gflags.github.io/gflags/#commandline)。 @tuhbo
