### ISSUE TITLE
brpc熔断和限流

### ISSUE THREAD

**Issue by masnail** [apache/incubator-brpc#1135]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
一个下游节点的熔断和限流同时开启，在限流发生的时候，被认为是故障节点，后面的请求不再发往该节点，默认时间30s后重新探测，在洪峰到来的时候，该节点可能处于长时间不在请求的情况。请问下，这种情况是否符合预期？

**Comment by gydong** [comment]
是说当限流发生的时候，会触发 callee 被caller熔断的问题吗？ 限流的error code 是 ELIMIT 这个code是不被熔断机制所惩罚的

**Comment by serverglen** [comment]
可以看看 https://github.com/apache/incubator-brpc/blob/master/docs/cn/auto_concurrency_limiter.md
