### ISSUE TITLE
请教 ParallelChannel现在支持http了吗？

### ISSUE THREAD

**Issue by better0001** [apache/incubator-brpc#1141]
看文档未说 ParallelChannel不支持http，请问ParallelChannel现在支持http了吗？看示例代码没有ParallelChannel的http相关的。如果已支持，如何使用？谢谢

17年回答是“http在当前实现下用不了parallel channel”：
https://github.com/apache/incubator-brpc/issues/94

https://github.com/apache/incubator-brpc/blob/master/docs/cn/combo_channel.md#parallelchannel

**Comment by wwbmmm** [comment]
不支持
