### ISSUE TITLE
Bazel 编译潜在问题（zlib 版本冲突）

### ISSUE THREAD

**Issue by hcoona** [apache/incubator-brpc#1145]
**Describe the bug (描述bug)**
我发现 BUILD 文件中依赖于系统中的 zlib 库（动态链接），但是实际上 protobuf 也依赖于一个 zlib 库（静态链接），这两个 zlib 版本不一致的时候有潜在风险。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: 0.9.7
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by hcoona** [comment]
我发现实际上我们并没有用到 ZLIB，那为什么要有个 `-DHAVE_ZLIB`？

**Comment by zyctree** [comment]
add
```
new_local_repository(
    name = "zlib",
    build_file = "bazel/zlib.BUILD",
    path = "bazel/zlib_empty"
)
```
with content like
```
cc_library(
    name = "zlib",
    linkopts = [
        "-lz",
    ],
)
```
in workspace

**Comment by wwbmmm** [comment]
master have rework bazel support
if still have this issue, please reopen
