### ISSUE TITLE
StartCancel会取消服务端还未处理的请求吗

### ISSUE THREAD

**Issue by baiwfg2** [apache/incubator-brpc#1147]
我理解cancel请求应该要具备这样的功能，发两个请求出去，互打tag（也就是互传callId给done)，哪个响应先到，就取消另外一个请求，特别在服务端还未处理它时应该是有用的。

但我看cancel_c++例子中并未体现这一点，也不确定StartCancel到底有没有发信号给server叫它丢弃某个CallId的请求。

所以请教一下这一点，且是否有必要改写一下cancel_c++的逻辑以使得更加符合`cancel`的语义？ （改写工作我可考虑来做）

**Comment by chenzhangyi** [comment]
不会
