### ISSUE TITLE
OnNewMessages中last_msg处理机制，是否会影响请求延时？

### ISSUE THREAD

**Issue by dangding** [apache/incubator-brpc#1149]
在OnNewMessage中，针对last_msg的处理，会延后到下一轮DoRead中，进行处理。
请问，当单个socket中，qps较大，且每次DoRead到消息量较多时，是否会增加last_msg的响应时间？

**Comment by heyuyi0906** [comment]
说下我对这个问题的理解哈，这里说的延时应该是指从CutInputMessage得到一个新的msg，到建立的bthread flush之间的延时。
延时来源于两方面：
1) 一次DoRead得到的所有msg会通过一次bthread_flush被调度执行。
2) last_msg的处理时机会被延后。当次DoRead的last_msg会在下一次DoRead后被QueueMessage，伴随下一次DoRead产生的msg被flush；若当次DoRead后读不到新的数据，last_msg会在析构时在当前bthread执行ProcessInputMessage。
理论上来说last_msg的延时和一次DoRead的第一个msg是相当的，因此，OnNewMessages中延时主要是上述1)带来的。为什么要这么做，OnNewMessages下面的注释也给出了解释——“To minimize the overhead, scheduling is batched”。

**Comment by dangding** [comment]
> 说下我对这个问题的理解哈，这里说的延时应该是指从CutInputMessage得到一个新的msg，到建立的bthread flush之间的延时。
> 延时来源于两方面：
> 
> 1. 一次DoRead得到的所有msg会通过一次bthread_flush被调度执行。
> 2. last_msg的处理时机会被延后。当次DoRead的last_msg会在下一次DoRead后被QueueMessage，伴随下一次DoRead产生的msg被flush；若当次DoRead后读不到新的数据，last_msg会在析构时在当前bthread执行ProcessInputMessage。
> 
> 理论上来说last_msg的延时和一次DoRead的第一个msg是相当的，因此，OnNewMessages中延时主要是上述1)带来的。为什么要这么做，OnNewMessages下面的注释也给出了解释——“To minimize the overhead, scheduling is batched”。

如果单个socket上qps很高，一次DoRead的数据量比较大呢？延时会不会明显？

PS：用echo_server起了一个服务，在另一台机器上通过rpc_press发请求，当qps较大时，通过brpc的监控页面，可以看到，运行时间越长，延时会越来越大。

**Comment by wwbmmm** [comment]
> PS：用echo_server起了一个服务，在另一台机器上通过rpc_press发请求，当qps较大时，通过brpc的监控页面，可以看到，运行时间越长，延时会越来越大。

这是rpc_press的问题，已经修复：https://github.com/apache/incubator-brpc/pull/1763
