### ISSUE TITLE
brpc单深度时延

### ISSUE THREAD

**Issue by hyswtj** [apache/incubator-brpc#1153]
请问有brpc单深度时延的数据吗？
最近在使用brpc时发现，在单机上的150字节的数据包，rtt用了100us左右，其中socket->write用了14-18us。 
看到benchmark上的测试代码路径：<https://svn.baidu.com/com-test/trunk/public/rpc-perf/>，我也想在我们的环境上测试一下，以对比我们的使用方法是否有问题，但该路径打不开了。
能否提供该测试程序呢？
谢谢！

**Comment by wwbmmm** [comment]
可以用rpc_press工具测试：https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpc_press.md
