### ISSUE TITLE
grpc客户端访问brpc 服务的一些疑问

### ISSUE THREAD

**Issue by walterzhaoJR** [apache/incubator-brpc#1158]
我期望访问到brpc或者braft中这种服务
![image](https://user-images.githubusercontent.com/22393698/87024450-b7a9aa80-c20b-11ea-85c6-dce086c26de8.png)
我看到brpc的客户端可以这样访问：
![image](https://user-images.githubusercontent.com/22393698/87024516-cdb76b00-c20b-11ea-8bbc-d84fc729893f.png)
想请问下go版本的grpc 客户端要如何访问呢？
或者有没有什么办法获取到response_attachment
THX

**Comment by zyearn** [comment]
这种是http service，不需要用grpc访问，直接用语言自带的http client访问就可以了

**Comment by walterzhaoJR** [comment]
@zyearn 是的，不过就是解析字符串复杂一些……

**Comment by historyliao** [comment]
如果是非http协议的怎么取response_attachment?
