### ISSUE TITLE
centos7编译报错

### ISSUE THREAD

**Issue by breaveSun** [apache/incubator-brpc#1170]
**Describe the bug (描述bug)**
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found gflags: /usr/lib64/libgflags.so
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PROTOBUF: /usr/local/lib/libprotobuf.so  
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2k") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/unit-dmkit/brpc/_build
[  0%] Generating brpc/proto_base.pb.h, brpc/proto_base.pb.cc
[  0%] Generating idl_options.pb.h, idl_options.pb.cc
[  0%] Generating brpc/rtmp.pb.h, brpc/rtmp.pb.cc
[  1%] Generating brpc/rpc_dump.pb.h, brpc/rpc_dump.pb.cc
[  1%] Generating brpc/get_favicon.pb.h, brpc/get_favicon.pb.cc
[  1%] Generating brpc/span.pb.h, brpc/span.pb.cc
[  2%] Generating brpc/builtin_service.pb.h, brpc/builtin_service.pb.cc
[  2%] Generating brpc/get_js.pb.h, brpc/get_js.pb.cc
[  2%] Generating brpc/errno.pb.h, brpc/errno.pb.cc
[  3%] Generating brpc/nshead_meta.pb.h, brpc/nshead_meta.pb.cc
[  3%] Generating brpc/options.pb.h, brpc/options.pb.cc
[  3%] Generating brpc/policy/baidu_rpc_meta.pb.h, brpc/policy/baidu_rpc_meta.pb.cc
[  3%] Generating brpc/policy/hulu_pbrpc_meta.pb.h, brpc/policy/hulu_pbrpc_meta.pb.cc
[  4%] Generating brpc/policy/public_pbrpc_meta.pb.h, brpc/policy/public_pbrpc_meta.pb.cc
[  4%] Generating brpc/policy/sofa_pbrpc_meta.pb.h, brpc/policy/sofa_pbrpc_meta.pb.cc
[  4%] Generating brpc/policy/mongo.pb.h, brpc/policy/mongo.pb.cc
[  5%] Generating brpc/trackme.pb.h, brpc/trackme.pb.cc
[  5%] Generating brpc/streaming_rpc_meta.pb.h, brpc/streaming_rpc_meta.pb.cc
Scanning dependencies of target PROTO_LIB
[  6%] Building CXX object CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o
In file included from /root/unit-dmkit/brpc/_build/idl_options.pb.cc:5:0:
/root/unit-dmkit/brpc/_build/idl_options.pb.h:12:2: 错误：#error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
/root/unit-dmkit/brpc/_build/idl_options.pb.h:13:2: 错误：#error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
/root/unit-dmkit/brpc/_build/idl_options.pb.h:14:2: 错误：#error your headers.
 #error your headers.
  ^
In file included from /usr/local/include/google/protobuf/descriptor.pb.h:25:0,
                 from /root/unit-dmkit/brpc/_build/idl_options.pb.h:26,
                 from /root/unit-dmkit/brpc/_build/idl_options.pb.cc:5:
/usr/local/include/google/protobuf/generated_message_reflection.h:406:6: 错误：template<class EnumType> bool google::protobuf::internal::ParseNamedEnum(const google::protobuf::EnumDescriptor*, const string&, EnumType*)’ 重定义
 bool ParseNamedEnum(const EnumDescriptor* descriptor,
      ^
In file included from /root/unit-dmkit/brpc/_build/idl_options.pb.h:25:0,
                 from /root/unit-dmkit/brpc/_build/idl_options.pb.cc:5:
/usr/include/google/protobuf/generated_enum_reflection.h:67:6: 错误：‘template<class EnumType> bool google::protobuf::internal::ParseNamedEnum(const google::protobuf::EnumDescriptor*, const string&, EnumType*)’ previously declared here
 bool ParseNamedEnum(const EnumDescriptor* descriptor,
      ^
make[2]: *** [CMakeFiles/PROTO_LIB.dir/idl_options.pb.cc.o] 错误 1
make[1]: *** [CMakeFiles/PROTO_LIB.dir/all] 错误 2
make: *** [all] 错误 2

**To Reproduce (复现方法)**
rm -rf _build && mkdir -p _build && cd _build && cmake .. && make -j10

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:centos 7
Compiler:gcc 版本 4.8.5
brpc:master
protobuf:libprotoc 2.5.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by wasphin** [comment]
> /root/unit-dmkit/brpc/_build/idl_options.pb.h:12:2: 错误：#error This file was generated by a newer version of protoc which is
#error This file was generated by a newer version of protoc which is

``protoc`` 和 ``libprotobuf`` 版本不一致

> -- Found PROTOBUF: /usr/local/lib/libprotobuf.so

可以确认下 ``protoc`` 的路径及版本.

**Comment by breaveSun** [comment]
> > /root/unit-dmkit/brpc/_build/idl_options.pb.h:12:2: 错误：#error This file was generated by a newer version of protoc which is
> > #error This file was generated by a newer version of protoc which is
> 
> `protoc` 和 `libprotobuf` 版本不一致
> 
> > -- Found PROTOBUF: /usr/local/lib/libprotobuf.so
> 
> 可以确认下 `protoc` 的路径及版本.

[root@robot-release-1 _build]# protoc --version
libprotoc 2.5.0
[root@robot-release-1 _build]# which protoc
/usr/bin/protoc

请问这样有什么问题么

**Comment by wasphin** [comment]
> > `protoc` 和 `libprotobuf` 版本不一致
> > > -- Found PROTOBUF: /usr/local/lib/libprotobuf.so

cmake 找到的是你自己编辑的 ``protobuf``(在 /usr/local 下)

> [root@robot-release-1 _build]# protoc --version
> libprotoc 2.5.0
> [root@robot-release-1 _build]# which protoc
> /usr/bin/protoc

而 ``protoc`` 是系统自带的, 两个版本不一致.

保持 ``protoc`` 和 ``libprotobuf.so`` 版本一致就可以, 要么都使用系统提供的, 要么都使用自己编译的.

``/usr/local/bin`` 下应该也有自己编译的 ``protoc``, 可以考虑卸载掉系统自带的 ``protobuf`` 相关包:
```
yum remove -y  protobuf-compiler
```
或者修改 ``PATH`` 变量把 ``/usr/local/bin`` 放到前面, 如:
```
export PATH=/usr/local/bin:$PPATH
```
然后再进行编译, 编译前可以把 ``CMakeCache.txt`` 删掉, 重新执行编译步骤.
