### ISSUE TITLE
能否访问brpc的内置服务

### ISSUE THREAD

**Issue by walterzhaoJR** [apache/incubator-brpc#1171]
![image](https://user-images.githubusercontent.com/22393698/87642254-d95ee080-c77b-11ea-8c66-e5fafb602b35.png)
有没有什么方法可以访问到brpc的内置服务，目前看来可以用个http请求，那除了http的请求之外，还有什么办法能访问到内部的这些服务吗？
THX

**Comment by gydong** [comment]
通过HTTP请求可以
或者描述一下您的原始的需求是啥
