### ISSUE TITLE
epoll_wait协程about_to_quit=true导致时延上升

### ISSUE THREAD

**Issue by ustccy** [apache/incubator-brpc#1177]
**Describe the bug (描述bug)**
一次网络抖动让epoll_wait协程的about_to_quit被置为true，导致epoll_wait协程切出时不唤醒其他worker。进而导致多数worker进入永久的休眠状态。
正常的切换流程:
1.epoll_wait有新事件被唤醒。所在线程A开始处理EPOLL事件。
2.线程A处理EPOLLIN事件，调用StartInputEvent->bthread_start_urgent->start_foreground->set_remained保留epoll_wait当前调用栈，然后在sched_to中jump_stack到task_runner函数。
3.线程A在task_runner中首先调用remain函数(ready_to_run_in_worker),将epoll_wait协程入rq并唤醒一个线程。
4.线程A进入ProcessEvent->OnNewMessages开始处理第一个EPOLLIN事件，线程B被唤醒后steal到epoll_wait协程继续执行后续的EPOLLIN事件。如此循环。

当epoll_wait的about_to_quit被置true时，上述步骤3会调用ready_to_run_in_worker_ignoresignal函数处理remain，该函数只是将epoll_wait协程入队并不唤醒。没有唤醒机制下，只有about_to_quit置true时还在work的协程会在调完当前协程后继续steal epoll_wait工作，当时在wait_task的协程将无法再被唤醒。后续EPOLL事件只能被这些少量的worker处理，整体处理时延上升。

通过内置服务获取epoll_wait协程的状态，about_to_quit被置true了
![image](https://user-images.githubusercontent.com/16217871/88007169-f0b51980-cb3f-11ea-8367-ab63085a8c5b.png)

通过分析发现
epoll_wait在处理EPOLLOUT|EPOLLERR|EPOLLHUP时没有起协程，所以由epoll_wait协程处理这些事件，当连接失败时触发EPOLLOUT事件,依次调用HandleEpollOut->HandleEpollOutRequest->KeepWriteIfConnected->CheckConnectedAndKeepWrite->AfterAppConnected->ReturnFailedWriteRequest->bthread_id_error2->controller::HandleSocketFailed->OnVersionedRPCReturned->IssueRPC

如果epoll_wait协程在最后一次重试调用IssueRPC里，出现HandleSendFailed()，并且本次RPC是同步调用(_done==NULL)，就会导致代码走到OnVersionedRPCReturned(new_bthread=false)->EndRPC()->bthread_about_to_quit()。将epoll_wait协程的about_to_quit错误的置为true，进而导致后续的唤醒机制失效

**To Reproduce (复现方法)**
服务的接口实现里创建一个不存在的下游channel，并rpc该下游，调用该接口即可将epoll_wait的about_to_quit置为true。
以example/echo_c++/server.cpp为例测试:在Echo函数中添加如下代码，再分别启动echo_server echo_client即可复现。
注:可以在event_dispatcher.cpp中打印epoll_wait的协程id，再通过内置服务接口验证about_to_quit是否置1
`        
 
        brpc::Channel ch;
        brpc::ChannelOptions options;
        options.protocol = "http";
        //8888 not listened
        if (ch.Init("127.0.0.1:8888", &options) != 0) {
            LOG(ERROR) << "Fail to initialize channel";
            return;
        } else {
            LOG(INFO)<<"init channel success";
        }
        brpc::Controller cntl1;
        cntl1.http_request().uri() = "http://abc.com";
        ch.CallMethod(NULL,&cntl1,NULL, NULL, NULL);
        if(cntl1.Failed()){
           LOG(ERROR)<<"call failed err is "<<cntl1.ErrorText();
        }

`

**Expected behavior (期望行为)**
epoll_wait的about_to_quit always be false

**Versions (各种版本)**
应该和版本无关
OS:ubuntu16.04
Compiler:gcc 5.4.0
brpc:all
protobuf:~

**Additional context/screenshots (更多上下文/截图)**

**Comment by ustccy** [comment]
疑问1：about_to_quit大部分在一次rpc调用协程结束时设置，完成后该协程不是会立即退出么？那设置这个标记位的意义还有多少
疑问2：EPOLLERR事件由epoll_wait协程同步处理，会执行到controller::IssueRPC，该函数的处理耗时直接影响了epoll_wait的整体处理时延，如果较慢就会导致后续事件耗时变大，上游感知的调用时延上升，另起协程处理EPOLLERR是否更合理。这样改有没有坑

**Comment by hyng8** [comment]
怎么获取bthread id的
