### ISSUE TITLE
example的http_c++的例子中，http_server 段错误

### ISSUE THREAD

**Issue by deardeng** [apache/incubator-brpc#1180]
**Describe the bug (描述bug)**
编译运行http_server，用./http_client localhost:8010/FileService/largefile测试，会出现core dump

**To Reproduce (复现方法)**

![image](https://user-images.githubusercontent.com/3887565/88258513-e7b87980-ccf2-11ea-97d5-f0effd9b678c.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:centos7
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
[已修复](https://github.com/apache/incubator-brpc/commit/2071a22c7f8ca4dfd47b1f0b607737082b66c865), 原因是返回的ProgressiveAttachment没有在rpc结束前用intrusive_ptr接住，而在rpc结束时直接被删除了。目前改为创建时就直接返回intrusive_ptr<ProgressiveAttachment>
