### ISSUE TITLE
GLOG连接失败

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1181]
**Describe the bug (描述bug)**
编译echo的例子时，glog链接报错的部分日志如下：
```
[ 12%] Linking CXX executable echo_server
CMakeFiles/echo_server.dir/server.cpp.o: In function `example::EchoServiceImpl::Echo(google::protobuf::RpcController*, example::EchoRequest const*, example::EchoResponse*, google::protobuf::Closure*)':
server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x32): undefined reference to `google::LogMessage::LogMessage(char const*, int)'
server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x3a): undefined reference to `google::LogMessage::stream()'
server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x1f9): undefined reference to `google::LogMessage::~LogMessage()'
server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x282): undefined reference to `google::LogMessage::~LogMessage()'
CMakeFiles/echo_server.dir/server.cpp.o: In function `main.cold.24':
server.cpp:(.text.unlikely+0xb): undefined reference to `google::LogMessage::~LogMessage()'
server.cpp:(.text.unlikely+0x48): undefined reference to `google::LogMessage::~LogMessage()'
CMakeFiles/echo_server.dir/server.cpp.o: In function `main':
server.cpp:(.text.startup+0x123): undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
server.cpp:(.text.startup+0x12b): undefined reference to `google::LogMessage::stream()'
server.cpp:(.text.startup+0x146): undefined reference to `google::LogMessage::~LogMessage()'
server.cpp:(.text.startup+0x164): undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
server.cpp:(.text.startup+0x16c): undefined reference to `google::LogMessage::stream()'
server.cpp:(.text.startup+0x187): undefined reference to `google::LogMessage::~LogMessage()'
/home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_listen(butil::EndPoint)':
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::stream()'
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::~LogMessage()'
/home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_connect(butil::EndPoint, int*)':
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessage::stream()'
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
/home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_listen(butil::EndPoint)':
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::~LogMessage()'
/home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_connect(butil::EndPoint, int*)':
/home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
/home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(iobuf.cpp.o): In function `butil::IOBufAsZeroCopyInputStream::BackUp(int)':
/home/work/workspace/incubator-brpc/src/butil/iobuf.cpp:1870: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
/home/work/workspace/incubator-brpc/src/butil/iobuf.cpp:1870: undefined reference to `google::LogMessage::stream()'
```

**To Reproduce (复现方法)**
1. cmake编译brpc并安装：mkdir bld && cd bld && cmake -DCMAKE_INCLUDE_PATH="/usr/local/include" -DCMAKE_LIBRARY_PATH="/usr/local/lib" -DWITH_GLOG=ON .. && sudo make install
2. 进入到echo例子的目录：mkdir bld && cd bld && cmake .. && make -j 8。 因为glog连接问题，编译失败

**Expected behavior (期望行为)**
编译成功

**Versions (各种版本)**
OS: centos 7.3
Compiler: gcc 8
brpc: master 最新代码 (Wed Jul 22 00:19:49 2020)
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by GOGOYAO** [comment]
找到原因了。是echo例子里面没有引用指定glog的连接项

**Comment by liuhongshuocl** [comment]
您好，请问引用指定glog的连接项是指什么？是使用SetLogDestination函数吗

**Comment by liuhongshuocl** [comment]
> **Describe the bug (描述bug)** 编译echo的例子时，glog链接报错的部分日志如下：
> 
> ```
> [ 12%] Linking CXX executable echo_server
> CMakeFiles/echo_server.dir/server.cpp.o: In function `example::EchoServiceImpl::Echo(google::protobuf::RpcController*, example::EchoRequest const*, example::EchoResponse*, google::protobuf::Closure*)':
> server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x32): undefined reference to `google::LogMessage::LogMessage(char const*, int)'
> server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x3a): undefined reference to `google::LogMessage::stream()'
> server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x1f9): undefined reference to `google::LogMessage::~LogMessage()'
> server.cpp:(.text._ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE[_ZN7example15EchoServiceImpl4EchoEPN6google8protobuf13RpcControllerEPKNS_11EchoRequestEPNS_12EchoResponseEPNS2_7ClosureE]+0x282): undefined reference to `google::LogMessage::~LogMessage()'
> CMakeFiles/echo_server.dir/server.cpp.o: In function `main.cold.24':
> server.cpp:(.text.unlikely+0xb): undefined reference to `google::LogMessage::~LogMessage()'
> server.cpp:(.text.unlikely+0x48): undefined reference to `google::LogMessage::~LogMessage()'
> CMakeFiles/echo_server.dir/server.cpp.o: In function `main':
> server.cpp:(.text.startup+0x123): undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
> server.cpp:(.text.startup+0x12b): undefined reference to `google::LogMessage::stream()'
> server.cpp:(.text.startup+0x146): undefined reference to `google::LogMessage::~LogMessage()'
> server.cpp:(.text.startup+0x164): undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
> server.cpp:(.text.startup+0x16c): undefined reference to `google::LogMessage::stream()'
> server.cpp:(.text.startup+0x187): undefined reference to `google::LogMessage::~LogMessage()'
> /home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_listen(butil::EndPoint)':
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::LogMessage(char const*, int, int)'
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::stream()'
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::~LogMessage()'
> /home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_connect(butil::EndPoint, int*)':
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessage::stream()'
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
> /home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_listen(butil::EndPoint)':
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:337: undefined reference to `google::LogMessage::~LogMessage()'
> /home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(endpoint.cpp.o): In function `butil::tcp_connect(butil::EndPoint, int*)':
> /home/work/workspace/incubator-brpc/src/butil/endpoint.cpp:307: undefined reference to `google::LogMessageFatal::~LogMessageFatal()'
> /home/work/workspace/incubator-brpc/bld/output/lib/libbrpc.a(iobuf.cpp.o): In function `butil::IOBufAsZeroCopyInputStream::BackUp(int)':
> /home/work/workspace/incubator-brpc/src/butil/iobuf.cpp:1870: undefined reference to `google::LogMessageFatal::LogMessageFatal(char const*, int)'
> /home/work/workspace/incubator-brpc/src/butil/iobuf.cpp:1870: undefined reference to `google::LogMessage::stream()'
> ```
> 
> **To Reproduce (复现方法)**
> 
> 1. cmake编译brpc并安装：mkdir bld && cd bld && cmake -DCMAKE_INCLUDE_PATH="/usr/local/include" -DCMAKE_LIBRARY_PATH="/usr/local/lib" -DWITH_GLOG=ON .. && sudo make install
> 2. 进入到echo例子的目录：mkdir bld && cd bld && cmake .. && make -j 8。 因为glog连接问题，编译失败
> 
> **Expected behavior (期望行为)** 编译成功
> 
> **Versions (各种版本)** OS: centos 7.3 Compiler: gcc 8 brpc: master 最新代码 (Wed Jul 22 00:19:49 2020) protobuf: 3.11
> 
> **Additional context/screenshots (更多上下文/截图)**



> 

您好，请问引用指定glog的连接项是指什么？是使用SetLogDestination函数吗
