### ISSUE TITLE
rpc dump不支持http么？

### ISSUE THREAD

**Issue by gxkevin** [apache/incubator-brpc#1191]
**Describe the bug (描述bug)**
rpc dump不支持http么？

**Comment by gydong** [comment]
不支持HTTP，目前只支持baidu_std协议

**Comment by serverglen** [comment]
> **Describe the bug (描述bug)** rpc dump不支持http么？

现已支持

**Comment by hejingzhilian** [comment]
怎么支持的 我用example/http_c++ 尝试rpc_dump 发现卡在method->input_type()->field_count()>0 这行了

**Comment by wwbmmm** [comment]
目前只支持 http 协议接收 rpc方式的请求 (请求body能转为protobuf message）的rpc dump。如果是example/http_c++里那种纯http的请求还不支持
