### ISSUE TITLE
remaining license problem

### ISSUE THREAD

**Issue by zyearn** [apache/incubator-brpc#1194]
# 问题和目标

目前brpc用到的源码依赖中，还存在license冲突的是flamegraph_perl（category b），需要在下一次正式release前解决这个依赖问题。

# 解决方法

让用户自己安装flamegragh，并文档里写清楚如果要用这个功能，需要设置环境变量以指明脚本路径。

**Comment by zyearn** [comment]
测试结果：

* 正确设置FLAMEGRAPH_PL_PATH后，火焰图效果：
![image](https://user-images.githubusercontent.com/4475779/108899037-3a0aa180-7618-11eb-8544-d88287a5b032.png)

* 没有设置FLAMEGRAPH_PL_PATH效果：
![image](https://user-images.githubusercontent.com/4475779/108899245-80f89700-7618-11eb-9f9d-34377aa8fe04.png)

* 设置错误的FLAMEGRAPH_PL_PATH效果：
![image](https://user-images.githubusercontent.com/4475779/108899395-a685a080-7618-11eb-9d22-a7852c731c60.png)

**Comment by baiwfg2** [comment]
@zyearn 你好。这功能很棒，但我发现鼠标点上去，不能像常规查看svg文件那样缩放？

**Comment by shili1992** [comment]
@baiwfg2 @zyearn  这个地方确实 不能点进去， 请问后面如何解决的
