### ISSUE TITLE
支持pb2.5以上编译太费尽了，很多问题

### ISSUE THREAD

**Issue by songlong** [apache/incubator-brpc#1216]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by songlong** [comment]
In file included from src/mcpack2pb/generator.cpp:30:0:
./src/idl_options.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
./src/idl_options.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
./src/idl_options.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
make: *** [src/mcpack2pb/generator.o] Error 1

**Comment by zyearn** [comment]
这是因为环境的protoc和protobuf runtime的版本对应不上导致的，一般是由于装了多个版本的protobuf

**Comment by songlong** [comment]
手动处理了一下config.sh，己安装成功

**Comment by cavalier23** [comment]
> 手动处理了一下config.sh，己安装成功

怎么处理的？
