### ISSUE TITLE
能否在server中增加SetMinLogLevel的接口以及禁用日志的宏开关

### ISSUE THREAD

**Issue by qicosmos** [apache/incubator-brpc#1223]
现在logging里面有一个SetMinLogLevel接口，能否在server里面增加一个代理接口，让用户可以通过server去设置日志级别。
另外能否增加一个宏开关用来控制是否输出日志？因为测试的时候发现日志刷得很频繁，有时候不希望输出日志。

**Comment by gydong** [comment]
-minloglevel 这个gflag无法满足需求吗？

**Comment by qicosmos** [comment]
我们的工程中也用到了glog，只想禁用brpc部分的输出，而且brpc已经在logging中提供了这个接口了。

**Comment by gydong** [comment]
编译brpc时，如果开启了 BRPC_WITH_GLOG ， 则SetMinLogLevel 这个函数没有被定义。
目前只能设置-minloglevel 这个gflag。
是哪些日志刷得频繁？

**Comment by qicosmos** [comment]
我开启了这宏。
default_variables.cpp中的fail to sscanf, faile to read, fail to xxx之类的日志。

**Comment by gydong** [comment]
出现这些error本身是不符合预期的吧？我们使用过程中，很少见到brpc框架本身输出的日志，输出的日志都比较重要，能帮助排查问题

**Comment by qicosmos** [comment]
说得也是，也许还得继续查找为什么频繁刷这个日志的原因。
