### ISSUE TITLE
rpc_dump不支持HTTP协议吗

### ISSUE THREAD

**Issue by guodongxiaren** [apache/incubator-brpc#1226]
**Describe the bug (描述bug)**
服务是支持HTTP+JSON的形式请求的。
但是这种HTTP的请求。好像rpc_dump并不能dump请求到日志中。是不是不支持HTTP

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
#https://github.com/apache/incubator-brpc/issues/1191
