### ISSUE TITLE
brpc端口占用的时候停止core

### ISSUE THREAD

**Issue by guodongxiaren** [apache/incubator-brpc#1228]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
brpc启动如果端口占用，会产生core dump。进程大概2分钟后才消失。能不能不出core dump直接终止进程。
经常误以为进程启动了。其实是在产出core，进程停留了2分钟。

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
代码中有对Start()函数有加判断吗？类似这样子

![image](https://user-images.githubusercontent.com/3294444/92422786-2aee7f00-f1b1-11ea-919f-7f07a1b4a997.png)

**Comment by guodongxiaren** [comment]
> 代码中有对Start()函数有加判断吗？类似这样子
> 
> ![image](https://user-images.githubusercontent.com/3294444/92422786-2aee7f00-f1b1-11ea-919f-7f07a1b4a997.png)

有的。
return -1之前，也尝试添加了server.Stop(0); server.Join(); 结果还是一样。先出core，等几分钟再结束进程。
return -1之前的LOG还能打印出来。不知道你们遇到过没。

**Comment by gydong** [comment]
我遇到过几次端口被占用的情况，可以顺利退出，不会core

**Comment by guodongxiaren** [comment]
找到问题了。不是brpc引起的。是return的时候。会触发另外一个第三方库的对象析构。这时候core掉的。
