### ISSUE TITLE
bthread_worker_usage超出bthread_worker_count

### ISSUE THREAD

**Issue by Evangelione** [apache/incubator-brpc#1231]
**Describe the bug (描述bug)**
应用场景是dmkit当发起一个调用unit的请求时，bthread_worker_usage有时会超出bthread_worker_count很多，
当bthread_worker_count设置为9的时候，bthread_worker_usage最大会跳到100多，
当bthread_worker_count设置为48的时候，bthread_worker_usage最大会跳到1200多，
然后就会一直timeout，无论请求多少次。
此时如果过一会不管他，再次请求就好了。。。

**To Reproduce (复现方法)**
偶尔的访问调用会触发 bthread_worker_usage 的爆炸式增长，正常情况下是不会增长太多的，bthread_worker_usage也就长个1左右

**Expected behavior (期望行为)**
bthread_worker_usage波动正常，不会出现跳跃

**Versions (各种版本)**
OS: centos 7
Compiler: 
brpc: commit 2ae7f04c
protobuf: 2.5.0

**Additional context/screenshots (更多上下文/截图)**
![1599556575113](https://user-images.githubusercontent.com/24892968/92457644-0ae1ae80-f1f7-11ea-9951-86027a01d7f6.jpg)
<img width="1368" alt="WeChatbfc8219ad99a001851121a190aacd2ff" src="https://user-images.githubusercontent.com/24892968/92471435-8731bd00-f20a-11ea-8dbd-943f189fb2ae.png">

**Comment by Evangelione** [comment]
是不是和我的服务器实例有关呢，我是突发性实例1cpu 2g的，但是我看我的cpu内存占用也不高啊。

**Comment by cxbyr** [comment]
这个问题原因是啥啊

**Comment by HQF2017** [comment]
请问下有具体原因和解决方法吗...碰到了一样的问题
