### ISSUE TITLE
使用std::locale相关接口导致cpu消耗剧增，不知道是否和brpc有关

### ISSUE THREAD

**Issue by yc1258** [apache/incubator-brpc#1240]
在server main函数开始调用了std::locale的global函数设置全局编码，会导致cpu消耗剧增，连接大量超时和拥堵。从流量进入时开始记录gperf，看热点集中在locale函数的锁的开销上。这个locale的global设置在老的ub框架下也在用，没有出现这种情况。想问下是否和brpc有关？或者有什么排查方向吗？非常感谢！
[ranker.pdf](https://github.com/apache/incubator-brpc/files/5200669/ranker.pdf)

**Comment by gydong** [comment]
看你描述，不会和brpc有关系，main函数开始的时候，brpc框架本身还没有初始化完成，不会形成竞争。

记录下 std::locale 函数运行了多少us看看？ 
是用的brpc自带的cpu profile功能吗，流量开始进入的时候，这时候global函数不都运行完了么？

**Comment by jamesge** [comment]
@yc1258 上面的图是contention还是cpu？

**Comment by yc1258** [comment]
> 看你描述，不会和brpc有关系，main函数开始的时候，brpc框架本身还没有初始化完成，不会形成竞争。
> 
> 记录下 std::locale 函数运行了多少us看看？
> 是用的brpc自带的cpu profile功能吗，流量开始进入的时候，这时候global函数不都运行完了么？

是gperftools的cpu工具，brpc自带的有个尴尬的问题，就是用了这个locale global后，brpc的调试网页返回会是invalid http response。。最后那个问题我也很奇怪，只有开头调用了一次，但是从采样图上看确实一直在这个内部竞争

**Comment by yc1258** [comment]
> @yc1258 上面的图是contention还是cpu？

是cpu的热点采样

**Comment by jamesge** [comment]
可能locale设置影响到很多和string相关的函数了？至少从profile看来就是它的问题。

**Comment by yc1258** [comment]
> 可能locale设置影响到很多和string相关的函数了？至少从profile看来就是它的问题。

应该是，业务中有大量宽窄字符转换的接口会调用 wcstombs mbstowcs，有说这两个函数会和locale有交互。不过ub框架下的代码也用了这个，但是没有出现这种情况
