### ISSUE TITLE
有社区交流群吗

### ISSUE THREAD

**Issue by yu199195** [apache/incubator-brpc#1241]
我的分布式事务框架，准备支持一波brpc

**Comment by gydong** [comment]
有的，留一下你的微信号，我拉你

**Comment by yu199195** [comment]
13786298670------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;gydong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月14日(星期一) 上午9:38
收件人:&nbsp;&quot;apache/incubator-brpc&quot;<incubator-brpc@noreply.github.com&gt;;
抄送:&nbsp;&quot;xiaoyu&quot;<549477611@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/incubator-brpc] 有社区交流群吗 (#1241)

**Comment by kungf** [comment]
@gydong 麻烦拉我一下，微信号发您gmail了

**Comment by weinberggithub** [comment]
> 有的，留一下你的微信号，我拉你

想要进社区交流群，_zihuatanejo_   ，谢谢

**Comment by gydong** [comment]
已拉

**Comment by yockie** [comment]
@gydong 想要进社区交流群，yockie，谢谢

**Comment by xiaopeifeng** [comment]
@gydong 求拉社区交流群，fengxiaopei0324, 谢谢

**Comment by lkkey80** [comment]
@gydong 求拉社区交流群, saga_weixin_80

**Comment by guodongxiaren** [comment]
微信 guodongxiaren求拉

**Comment by uuuuu-diwu** [comment]
@gydong Stockholm-robber 求拉

**Comment by limindlmu** [comment]
@gydong vx：cflimi ，求拉社区交流群

**Comment by chongg039** [comment]
@gydong vx：uestc_gch，求拉谢谢

**Comment by panlei-coder** [comment]
> 有的，留一下你的微信号，我拉你

vx:PL17396120156，求拉谢谢

**Comment by xiaohei-info** [comment]
vx: xiaohei-info，求拉谢谢

**Comment by GreateCode** [comment]
vx：chao10001，求拉谢谢

**Comment by zhangdongqiu** [comment]
vx:xishanzhidian帮我拉到群里

**Comment by GreateCode** [comment]
> vx：chao10001，求拉谢谢

@gydong 求

**Comment by egolearner** [comment]
vx:tjuking @gydong 麻烦拉下微信群，谢谢
