### ISSUE TITLE
brpc能基于protobuf 3.x 版本构建service吗？

### ISSUE THREAD

**Issue by yyhclimacool** [apache/incubator-brpc#1242]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

我们工程使用的tensorflow需要protobuf 3.8.0版本，brpc能基于这个版本构建service吗？

**Comment by gydong** [comment]
protobuf-3.10.0我们已经用过了，没有问题

**Comment by yyhclimacool** [comment]
> protobuf-3.10.0我们已经用过了，没有问题

具体怎么构建呢？有没有文档？
官方的demo如`incubator-brpc/example/echo_c++/echo.proto`是`syntax="proto2"`，2.x的protobuf是会生成service基类的，但是3.x的protobuf不会根据pb文件生成service了，我该怎么实现我的rpc的method呢？

**Comment by gydong** [comment]
protobuf-3.x 的库，.proto文件中依然保持使用 syntax="proto2"

**Comment by yyhclimacool** [comment]
> protobuf-3.x 的库，.proto文件中依然保持使用 syntax="proto2"

了解了，谢谢。

**Comment by yanglimingcn** [comment]
用proto 3的语法会有什么问题吗？文档说Arena不支持是啥意思

**Comment by marsmiao** [comment]
> > protobuf-3.10.0我们已经用过了，没有问题
> 
> 具体怎么构建呢？有没有文档？
> 官方的demo如`incubator-brpc/example/echo_c++/echo.proto`是`syntax="proto2"`，2.x的protobuf是会生成service基类的，但是3.x的protobuf不会根据pb文件生成service了，我该怎么实现我的rpc的method呢？

为啥我编译demo的时候改成3.x版本依然可以运行😂
