### ISSUE TITLE
Is there a brpc version which can match protobuf-3.8.x for using with TF2.0?

### ISSUE THREAD

**Issue by rikuki** [apache/incubator-brpc#1248]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
No

**Describe the solution you'd like (描述你期望的解决方法)**
I hope developers can upgrade the brpc with protobuf 3.8.x.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
https://github.com/apache/incubator-brpc/issues/1242

**Comment by rikuki** [comment]
> #1242

Thanks!
