### ISSUE TITLE
关于is_current_pthread_task 这个函数的疑问

### ISSUE THREAD

**Issue by brokensword2018** [apache/incubator-brpc#1249]
Dear all.   
```cpp 
// True iff current task is the one running run_main_task()
    bool is_current_main_task() const { return current_tid() == _main_tid; }
    // True iff current task is in pthread-mode.
    bool is_current_pthread_task() const
    { return _cur_meta->stack == _main_stack; }
```
每个worker线程应该都是执行，run_main_task. current_tid() == _main_tid 不是和 _cur_meta->stack == _main_stack等效的吗？ True iff current task is in pthread-mode这句话不是很理解。

**Comment by gydong** [comment]
两个条件不等价， _cur_meta->stack == _main_stack 成立的时候，current_tid() == _main_tid 不一定成立。有些情况下bthread会复用main task 的堆栈，可以读一下ending_sched这个函数的源码理解一下

**Comment by brokensword2018** [comment]
> 两个条件不等价， _cur_meta->stack == _main_stack 成立的时候，current_tid() == _main_tid 不一定成立。有些情况下bthread会复用main task 的堆栈，可以读一下ending_sched这个函数的源码理解一下

非常感谢

**Comment by brokensword2018** [comment]
> 两个条件不等价， _cur_meta->stack == _main_stack 成立的时候，current_tid() == _main_tid 不一定成立。有些情况下bthread会复用main task 的堆栈，可以读一下ending_sched这个函数的源码理解一下

非常感谢
