### ISSUE TITLE
关于process_cpu_usage明显大于bthread_worker_usage的情况

### ISSUE THREAD

**Issue by GOGOYAO** [apache/incubator-brpc#1250]
**Describe the bug (描述bug)**
在《高效率排查server卡顿》中，可以有以下方法进行排查
> 如果process_cpu_usage和bthread_worker_usage接近，说明是cpu-bound，工作线程大部分时间在做计算。

> 如果process_cpu_usage明显小于bthread_worker_usage，说明是io-bound，工作线程大部分时间在阻塞。

但是如果出现如下 process_cpu_usage明显大于bthread_worker_usage的情况，这个应该怎么分析呢。
![image](https://user-images.githubusercontent.com/18675094/93729747-67ca6500-fbf8-11ea-903d-97a33e30198d.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos7
Compiler: gcc 8
brpc: 11da9c8
protobuf: 3.11

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
说明你的进程大部分计算不是运行在brpc框架内，可能有其他的线程计算比较密集，比如rdkafka和faiss这种库都是有自己的线程池的，他们不占用brpc的worker线程但却是占用CPU

**Comment by GOGOYAO** [comment]
明白。感谢
