### ISSUE TITLE
用cmake编译example出错

### ISSUE THREAD

**Issue by anancds** [apache/incubator-brpc#1253]
**Describe the bug (描述bug)**
cmake编译example报错，但是直接用make是可以的

**To Reproduce (复现方法)**
cd example/echo_c++
mkdir bld && cd bld && cmake .. && make

**Expected behavior (期望行为)**
成功

**Versions (各种版本)**
OS:5.4.0-47-generic #51-Ubuntu SMP
Compiler:g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
brpc: 0.9.7
protobuf:3.13.0

**Additional context/screenshots (更多上下文/截图)**
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:46: undefined reference to `google::protobuf::io::GzipOutputStream::Options::Options()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:48: undefined reference to `google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:53: undefined reference to `google::protobuf::io::GzipOutputStream::Close()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:48: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::ZlibCompress(google::protobuf::Message const&, butil::IOBuf*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:146: undefined reference to `google::protobuf::io::GzipOutputStream::Options::Options()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:148: undefined reference to `google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:149: undefined reference to `google::protobuf::io::GzipOutputStream::Close()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:148: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipDecompress(butil::IOBuf const&, google::protobuf::Message*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:59: undefined reference to `google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:59: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::ZlibDecompress(butil::IOBuf const&, google::protobuf::Message*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:155: undefined reference to `google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:155: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:70: undefined reference to `google::protobuf::io::GzipOutputStream::Options::Options()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:74: undefined reference to `google::protobuf::io::GzipOutputStream::GzipOutputStream(google::protobuf::io::ZeroCopyOutputStream*, google::protobuf::io::GzipOutputStream::Options const&)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:81: undefined reference to `google::protobuf::io::GzipOutputStream::Next(void**, int*)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:102: undefined reference to `google::protobuf::io::GzipOutputStream::Close()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:74: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:100: undefined reference to `google::protobuf::io::GzipOutputStream::BackUp(int)'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipCompress(google::protobuf::Message const&, butil::IOBuf*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:48: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::ZlibCompress(google::protobuf::Message const&, butil::IOBuf*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:148: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipDecompress(butil::IOBuf const&, google::protobuf::Message*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:59: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::ZlibDecompress(butil::IOBuf const&, google::protobuf::Message*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:155: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipCompress(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipOutputStream::Options const*)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:74: undefined reference to `google::protobuf::io::GzipOutputStream::~GzipOutputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/build/output/lib/libbrpc.a(gzip_compress.cpp.o): in function `brpc::policy::GzipDecompressBase(butil::IOBuf const&, butil::IOBuf*, google::protobuf::io::GzipInputStream::Format)':
/home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:109: undefined reference to `google::protobuf::io::GzipInputStream::GzipInputStream(google::protobuf::io::ZeroCopyInputStream*, google::protobuf::io::GzipInputStream::Format, int)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:131: undefined reference to `google::protobuf::io::GzipInputStream::Next(void const**, int*)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:119: undefined reference to `google::protobuf::io::GzipInputStream::Next(void const**, int*)'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:109: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
/usr/bin/ld: /home/cds/code/incubator-brpc/src/brpc/policy/gzip_compress.cpp:109: undefined reference to `google::protobuf::io::GzipInputStream::~GzipInputStream()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/echo_server.dir/build.make:118: echo_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/echo_server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by zyearn** [comment]
编译protobuf的时候需要把zlib选项打开
