### ISSUE TITLE
支持Weighted Random负载均衡策略

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1254]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
支持Weighted Random负载均衡策略

**Describe the solution you'd like (描述你期望的解决方法)**
random在下游处理能力（cpu、内存等资源）大致相等的情况下能很好的工作，但是当下游处理能力相差较大的时候，如果还是按照完全随机的方法将流量转发给下游实例，就会导致下游某些实例负载高、某些实例负载低的情况；而Weighted Random就可以根基机器的资源配置来调整其被选择的权重。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
能具体描述一下你的应用场景吗？或者要解决什么问题

**Comment by hohodu** [comment]
wrr_lb  基于权重的负载均衡策略

**Comment by serverglen** [comment]
> wrr_lb 基于权重的负载均衡策略

这个我看到了，wr其实也是需要的

**Comment by yc1037642433** [comment]
“Weighted Random就可以根基机器的资源配置来调整其被选择的权重”，请问这个Weighted Random根据资源配置来调整权重的原理是什么呢
