### ISSUE TITLE
虚拟ip 被删除后，部分建立在该虚拟ip 的brpc::channel 发送rpc请求超时

### ISSUE THREAD

**Issue by tojoyccnu** [apache/incubator-brpc#1257]
**Describe the bug (描述bug)**
由于集群采用虚拟vip 方式对外提供服务， 一旦当前master 发生vip 切换，存在一些channel  发送rpc 总是超时。经查，这些channel 是自动绑定本地地址，分配在了虚拟ip  上的。

如何才能触发这些问题channel 重置？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: 0.9.8
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by tojoyccnu** [comment]
如何在不销毁brpc::channel 前提下，触发底层重新连接

**Comment by tojoyccnu** [comment]
如何在不销毁brpc::channel 前提下，触发底层重新连接

**Comment by gydong** [comment]
没有这样的接口函数，不过你可以通过开启enable_circuit_breaker来实现相同的效果。建议的做法还是重新new一个Channel实例
