### ISSUE TITLE
在客户端判断stream 结束

### ISSUE THREAD

**Issue by cstarc** [apache/incubator-brpc#1259]
**Describe the bug (描述bug)**

是否能在发送端streamwrite 结束并close 后，  在发送端通过调用一个函数方便的判断 stream 有没有结束？
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cstarc** [comment]
是否可以通过判断内部的_produced == _remote_consumed，若相等即表名server端处理结束？

**Comment by gydong** [comment]
如果要在客户端判断服务端是否真正处理完成，则一定要服务端的主动反馈机制，客户端不可能单方面判断服务端是否处理完成
