### ISSUE TITLE
关于bthread_start_urgent 的一些疑问

### ISSUE THREAD

**Issue by zhongleihe** [apache/incubator-brpc#1263]
bthread_start_urgent 与bthread_start_background 是分别执行紧急与不紧急的任务，有一下两点疑问：
（1）在主线程情况下即bthread::TaskGroup* g = bthread::tls_task_group; g为nullptr时，bthread_start_urgent和bthread_start_background的实现方式是一样的，都是把协程任务插在了队列尾部，并没有体现bthread_start_urgent的紧迫性？
（2）bthread_start_urgent在g不为nullptr时，是立刻创建了个协程任务，并且立刻jump_stack。相当于在协程中又创建一个协程任务。这样和不创建协程任务，而是把这个不代码放在当前协程中执行的区别是什么？

**Comment by cdjingit** [comment]
1. bthread_start_urgent只有在worker中才会立即切换到新创建的bthread执行。非worker中只能放到remote queue中。用brpc框架代码应该大多数时候都是运行在worker线程中。除了一些特别需要开启另外pthread执行的计算。
2. 比如 考虑新的bthread可能需要阻塞的情况。并且当前的bthread也可能被别的worker偷走和新的bthread并行执行。你所说的情况，不应该bthread_start_urgent一个新的bthread，直接本地计算好了。

**Comment by zhongleihe** [comment]
2明白了，忘记了你们可以worker_steal，感谢解答
