### ISSUE TITLE
baidu_std协议。request都是const的，如果我想修改。只能CopyFrom一次request再修改吗？

### ISSUE THREAD

**Issue by guodongxiaren** [apache/incubator-brpc#1265]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
我有一个比较大的request。CopyFrom的开销比较大。
request里面有一个大的队列。现在我想给队列里的元素都做一次预处理。我想对后面处理逻辑透明。只能自己CopyFrom一个新的request。然后让后续的逻辑都解析新request吗？

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
可以const_cast之后再处理

**Comment by whutbd** [comment]
嗯，可以强转获得非const指针
