### ISSUE TITLE
https url，rr load balance的channel，在使用的时候会报错E1016

### ISSUE THREAD

**Issue by yyweii** [apache/incubator-brpc#1266]
**Describe the bug (描述bug)**

https url，rr load balance的channel，在使用的时候会报错E1016，如下：
[E1016]Fail to connect Socket{id=7694 addr=49.7.48.27:80} (0x0x7efb49575e30): SSL related operation failed
看domain_naming_service.cpp的代码好像是因为指定了默认80端口引起的

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: ubuntu
Compiler: g++ 7.4.0
brpc: 0.9.7
protobuf: 2.6.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by TousakaRin** [comment]
https://github.com/apache/incubator-brpc/pull/1139 这里已经修复

显示指定下端口就可以，比如https://dummy.domain:443, rr
