### ISSUE TITLE
Timer Keeping的精度问题

### ISSUE THREAD

**Issue by xuqing-er** [apache/incubator-brpc#1267]
https://github.com/apache/incubator-brpc/blob/master/docs/cn/timer_keeping.md
![image](https://user-images.githubusercontent.com/47977252/96278769-7b56c900-1008-11eb-879e-651bf21f20b9.png)
由于Linux是分时操作系统，那么到达最早的定时器超时时间后，TimerThread被唤醒之后可能不会立刻运行，这需要至少等待几ms，因此精度就已经超出了ms，按之前的说法brpc提供的定时机制精度也较差？

**Comment by gydong** [comment]
『唤醒之后等待即ms』 这个数据是从哪里获取到的？只要CPU没有被占用完，不会这么慢，调度时间一般在微秒级吧

**Comment by xuqing-er** [comment]
如果唤醒之后Linux调度了另一个线程A运行，那么TimerThread就要等待线程A的时间片耗尽（假设A没有阻塞操作），根据《Linux内核设计与实现》中CFS算法说明，而每个线程默认最少的时间片为1ms

**Comment by gydong** [comment]
如果发生你说这种情况，那就是CPU耗尽了。简单理解一下，如果CPU闲着，OS却让任务在等待是显然不合理的设计。

**Comment by xuqing-er** [comment]
那就是说在CPU耗尽的情况下就不能提供较好的精度？但是在系统中很可能有较多的线程，唤醒之后不会立即获得CPU资源这种情况应该是比较常见的吧。

**Comment by gydong** [comment]
不常见。如果真出现这种情况，问题就不仅仅是精度不准了，会有很多其他并发症

**Comment by xuqing-er** [comment]
![Uploading image.png…]()

**Comment by xuqing-er** [comment]
![image](https://user-images.githubusercontent.com/47977252/96544729-b2afc900-12d9-11eb-9a5f-870eb37394d4.png)

**Comment by xuqing-er** [comment]
这是我理解的调度过程，如果有错误希望指正。
按照这个过程，TimerThread应该会等待CPU，要想使得TimerThread立即运行应该需要修改其优先级。

**Comment by gydong** [comment]
能描述一下你遇到的具体问题吗？ 最好有相关数据，避免在纯理论层面推演导致的大家理解无法达成一致

**Comment by xuqing-er** [comment]
我是在调研RPC和Linux定时器的实现，还没有具体的使用，看到brpc的这个文档有点没有理解，所以提出了这个问题。

**Comment by xuqing-er** [comment]
后面我对这个测试的时候看看会不会出现我说的这个问题
