### ISSUE TITLE
brpc客户端如何设置自动重连？

### ISSUE THREAD

**Issue by qicosmos** [apache/incubator-brpc#1269]
当服务器关闭时，客户端如何一直尝试自动重连，直到服务器重启连上为止？
文档中没有找到相关的说明。

**Comment by cdjingit** [comment]
连接建立是延迟执行的，发送rpc时，发现连接没有建立都会尝试建立连接。连接本身也有健康检查机制。
https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5

**Comment by qicosmos** [comment]
@cdjingit 和我问的问题没有关系吧。
我想知道的是：client是不是需要自己主动去连接服务器，client不提供自动重连功能。

**Comment by gydong** [comment]
可以描述一下你的业务场景和遇到的具体问题吗？ 单纯连上服务端和需要发送请求再去连接，从效果上来讲似乎没啥区别，所以你的场景是什么样子的呢？

**Comment by qicosmos** [comment]
场景很简单：
1. client连上了服务器并可以正常发rpc请求；
2.服务器重启；
3.client连接断开，自动尝试重连，用户无感知；
4.服务器重启成功。
5.回到步骤1

主要是用户使用便利性方面的问题，用户client是不是需要自己去处理这种重连的问题？

谢谢你及时回复。

**Comment by cdjingit** [comment]
不需要，连接的建立由框架管理。业务代码不需要关心。

**Comment by qicosmos** [comment]
> 不需要，连接的建立由框架管理。业务代码不需要关心。

那么请问client实现这个自动重连的功能具体要怎么做，什么都不管就会自动重连吗？

**Comment by gydong** [comment]
什么都不用管，因为框架中都没有暴露建立连接的接口函数，就更没有重连的接口了。建议亲自把你关心的场景实测一下

**Comment by cdjingit** [comment]
> > 不需要，连接的建立由框架管理。业务代码不需要关心。
> 
> 那么请问client实现这个自动重连的功能具体要怎么做，什么都不管就会自动重连吗？
不需要做什么。按照ChannelOptions做你需要的配置就可以。

**Comment by qicosmos** [comment]
> > > 不需要，连接的建立由框架管理。业务代码不需要关心。
> > 
> > 
> > 那么请问client实现这个自动重连的功能具体要怎么做，什么都不管就会自动重连吗？
> > 不需要做什么。按照ChannelOptions做你需要的配置就可以。

我看了channel option，并没有关于自动重连的选项。

**Comment by qicosmos** [comment]
> 什么都不用管，因为框架中都没有暴露建立连接的接口函数，就更没有重连的接口了。建议亲自把你关心的场景实测一下
跑了例子，服务器断开 channel不会自动重连，需要用户去主动发起重连操作。

**Comment by cdjingit** [comment]
> > 什么都不用管，因为框架中都没有暴露建立连接的接口函数，就更没有重连的接口了。建议亲自把你关心的场景实测一下
> 
> 跑了例子，服务器断开， channel不会自动重连，需要用户去主动发起重连操作。

用户主动发起重连操作是指什么操作？

**Comment by qicosmos** [comment]
哎，这不是很常见的吗，channel发请求失败了，是因为对端挂了，然后这时候不得重试吗，现在发请求和连接都走一个接口，需要重试。

没有连接的接口会导致封装请求之后再发消息才知道是不是连接失败了，接口设计不太友好。
另外，为什么都是iqiyi group的人来回复问题，这个项目现在是谁在维护？

**Comment by gydong** [comment]
> 场景很简单：
> 
> 1. client连上了服务器并可以正常发rpc请求；
>    2.服务器重启；
>    3.client连接断开，自动尝试重连，用户无感知；
>    4.服务器重启成功。
>    5.回到步骤1
> 
> 主要是用户使用便利性方面的问题，用户client是不是需要自己去处理这种重连的问题？
> 
> 谢谢你及时回复。

你上面描述的场景，还是没有让我明白『需要发送请求时再连接』和『预先建立连接以备发送请求』对你的业务场景来说有什么区别？brpc框架的设计依据是，在用户发送请求的时候有连接可用即可，没必要把建立连接这一步操作暴露给用户。

**Comment by qicosmos** [comment]
好吧，我期望的是单连接能自动恢复，没有用连接池。也许brpc不期望这样用？

另外我觉得暴露连接接口没问题，为什么不暴露给用户，暴露给用户还会更好，也许是brpc的channel机制导致不方便把连接接口暴露出来。

**Comment by gydong** [comment]
brpc的设计理念中很重要的一点就是『简单』，不该用户关心的事情尽量封装起来

**Comment by qicosmos** [comment]
问题也清楚了，谢谢回复。

**Comment by yz-cyz** [comment]
@cdjingit 请教下， channel的两端网络突然中断后，大概多久健康检查会发现并且会断开。

我们遇到的问题是网络中断后， 健康检查好像并没有生效，比如A -> B ,  断网后很长一段时间内， A发给B的请求，还是会写入到socket的发送缓冲区（最少持续写入了10s以上）， 导致断网恢复时B突然收到大量请求。 

看log， 10分钟后， 所有的请求还是会报E1008 超时错误， 而不是 E112 (Not connected to xxx)，

配置：health_check_interval = 3,   health_check_timeout_ms = 500。
