### ISSUE TITLE
Mac 可以编译 BRPC吗?

### ISSUE THREAD

**Issue by darionyaphet** [apache/incubator-brpc#1286]

**Comment by serverglen** [comment]
可以的，参考：https://github.com/apache/incubator-brpc/blob/master/docs/cn/getting_started.md#macos

**Comment by darionyaphet** [comment]
编译的时候 发现 `gnu-getopt must be installed and used` 但是gnu-getopt 已经装了 ...

**Comment by serverglen** [comment]
> 编译的时候 发现 `gnu-getopt must be installed and used` 但是gnu-getopt 已经装了 ...

卸载，重新执行试试

**Comment by darionyaphet** [comment]
试了 还是不好使啊 算了我还是在Linux上部署吧

**Comment by leosunli** [comment]
我这边也是编译的时候 报 gnu-getopt must be installed and used ，实际上已经安装了

请问有brpc的用户交流群嘛

**Comment by serverglen** [comment]
> 我这边也是编译的时候 报 gnu-getopt must be installed and used ，实际上已经安装了

加我微信（serverglen），拉你进群。

**Comment by fcycq** [comment]
https://blog.csdn.net/xiang_shao344/article/details/116017228
是getopt的问题，在Mac上的用法和linux不一样

**Comment by fcycq** [comment]
> https://blog.csdn.net/xiang_shao344/article/details/116017228
> 是getopt的问题，在Mac上的用法和linux不一样

export PATH="/usr/local/opt/gnu-getopt/bin:$PATH"
替换一下就好了

**Comment by Huixxi** [comment]
> > https://blog.csdn.net/xiang_shao344/article/details/116017228
> > 是getopt的问题，在Mac上的用法和linux不一样
> 
> export PATH="/usr/local/opt/gnu-getopt/bin:$PATH" 替换一下就好了

为啥我export之后没用啊，还是提示。。

**Comment by Huixxi** [comment]
> 编译的时候 发现 `gnu-getopt must be installed and used` 但是gnu-getopt 已经装了 ...

重启电脑可以解决getopt获取不到版本的问题

**Comment by zorchp** [comment]
brew 安装的 gnu-getopt 默认是 key-only 的, 所以需要配置环境变量, 然后在终端下source 一下 zshrc 就能用了

**Comment by Accelerator-liy** [comment]
> > > https://blog.csdn.net/xiang_shao344/article/details/116017228
> > > 是getopt的问题，在Mac上的用法和linux不一样
> > 
> > 
> > export PATH="/usr/local/opt/gnu-getopt/bin:$PATH" 替换一下就好了
> 
> 为啥我export之后没用啊，还是提示。。

可能你export的不对，MAC用brew安装的gnu-getopt的话可以用brew info gnu-getopt查看安装位置，会提示：
If you need to have gnu-getopt first in your PATH, run:
  echo 'export PATH="/opt/homebrew/opt/gnu-getopt/bin:$PATH"' >> ~/.zshrc
改一下PATH路径再source ～/.zshrc就好了

**Comment by wasphin** [comment]
也可以使用 cmake 的编译方式，对环境的适应性会好一些。

**Comment by ChunelFeng** [comment]
mac m1上编译 brpc，执行了，也source过好几次了，也在 zshrc文件里，确认的确写入了

但编译还是报没有 gnu-getopt 

<img width="714" alt="image" src="https://github.com/apache/brpc/assets/37905059/3757c072-0023-4d07-bf9a-b671683b345b">

请问，还有没什么可以排查的方案？

**Comment by Huixxi** [comment]
> mac m1上编译 brpc，执行了，也source过好几次了，也在 zshrc文件里，确认的确写入了
> 
> 但编译还是报没有 gnu-getopt
> 
> <img alt="image" width="714" src="https://private-user-images.githubusercontent.com/37905059/300503192-3757c072-0023-4d07-bf9a-b671683b345b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODI4ODcsIm5iZiI6MTcwNjU4MjU4NywicGF0aCI6Ii8zNzkwNTA1OS8zMDA1MDMxOTItMzc1N2MwNzItMDAyMy00ZDA3LWJmOWEtYjY3MTY4M2IzNDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAyNDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1MjE2NzBiNTk0OTBlYzU4YWRiY2ZlZTdkYTE0MzA1ZDliZjEyN2YwZTNlMjUzYWExNGY0ZjZlYzI0ZDQxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y1X14UiUW_GLmTDfbLbtebcS2DFTDAuRWeBrEDqXOms">
> 请问，还有没什么可以排查的方案？

爬楼看下吧，重启你的iTerm或者重启电脑
