### ISSUE TITLE
Build break with Bazel

### ISSUE THREAD

**Issue by pcman-zhang** [apache/incubator-brpc#1287]
**Describe the bug (描述bug)**
Try to build brpc with bazel, but build break

**To Reproduce (复现方法)**
at the directory of brpc, run:
$ bazel build brpc

This error occupied:

ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_freeman/b850d964ac91cfb4966c867783252dee/external/com_google_protobuf/protobuf.bzl", line 130, column 29, in <toplevel>
		"protoc": attr.label(
Error in label: label() got unexpected keyword argument 'single_file'
ERROR: Skipping 'brpc': error loading package '': in /Users/freeman/Dev/incubator-brpc/bazel/brpc.bzl: Extension file 'protobuf.bzl' has errors
WARNING: Target pattern parsing failed.
ERROR: error loading package '': in /Users/freeman/Dev/incubator-brpc/bazel/brpc.bzl: Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 0.048s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

**Expected behavior (期望行为)**
build success

**Versions (各种版本)**
OS: macOS catalina 10.15.7
Compiler: Apple clang version 12.0.0 (clang-1200.0.32.2) / bazel version: Build label: 3.6.0-homebrew 
brpc: current master branch 
protobuf: libprotoc 3.13.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenzhangyi** [comment]
bazel是什么版本？

**Comment by pcman-zhang** [comment]
bazel: version 3.60

**Comment by yuqZY** [comment]
一样的问题

**Comment by wwbmmm** [comment]
master has support latest version of bazel
