### ISSUE TITLE
brpc rdma异常

### ISSUE THREAD

**Issue by Pating** [apache/incubator-brpc#1296]
**Describe the bug (描述bug)**

客户端向服务端发送rdma请求，有时会出现如下问题。
E1127 17:51:28.570752 210341 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:28.819981 210349 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:29.223821 210342 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:30.028343 210349 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:37.485410 210342 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:37.590259 210344 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:37.793829 210341 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:38.240385 210345 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument
E1127 17:51:39.044575 210342 /root/byw/changlox/software/brpc/src/brpc/rdma/rdma_completion_queue.cpp:123] Fail to intialize RdmaCompletionQueue: Invalid argument

上述问题出现，客户端不能向服务端发送数据

I1127 09:51:20.775034 941982 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=9 addr=192.168.3.5:8001} (0x18cf530)
I1127 09:51:20.775188 941981 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=6 addr=192.168.3.5:8002} (0x18cef30)
I1127 09:51:20.775263 941959 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=4 addr=192.168.3.5:8000} (0x18ceb30)
I1127 09:51:20.775347 941977 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=9 addr=192.168.3.5:8001} (0x18cf530) (Connectable)
I1127 09:51:20.775396 941974 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=8 addr=192.168.3.6:8002} (0x18cf330)
I1127 09:51:20.775412 941955 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=7 addr=192.168.3.6:8000} (0x18cf130)
I1127 09:51:20.775495 941968 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=6 addr=192.168.3.5:8002} (0x18cef30) (Connectable)
I1127 09:51:20.775557 941974 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=4 addr=192.168.3.5:8000} (0x18ceb30) (Connectable)
I1127 09:51:20.775696 941973 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2377] Checking Socket{id=5 addr=192.168.3.6:8001} (0x18ced30)
I1127 09:51:20.775832 941967 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=7 addr=192.168.3.6:8000} (0x18cf130) (Connectable)
I1127 09:51:20.775841 941975 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=8 addr=192.168.3.6:8002} (0x18cf330) (Connectable)
I1127 09:51:20.775944 941984 /root/byw/changlox/software/brpc/src/brpc/socket.cpp:2437] Revived Socket{id=5 addr=192.168.3.6:8001} (0x18ced30) (Connectable)
I1127 09:51:20.995304 941950 /home/changlox/blockmaster/essd/src/blockfs/blockmaster/test/test-perf.cc:317] Sending EchoRequest at qps=0 latency=0
I1127 09:51:21.995442 941950 /home/changlox/blockmaster/essd/src/blockfs/blockmaster/test/test-perf.cc:317] Sending EchoRequest at qps=0 latency=0
I1127 09:51:22.995585 941950 /home/changlox/blockmaster/essd/src/blockfs/blockmaster/test/test-perf.cc:317] Sending EchoRequest at qps=0 latency=0

**To Reproduce (复现方法)**
rdma大压力测试

**Expected behavior (期望行为)**
出现异常后可以继续通信

**Versions (各种版本)**
OS: rhel7.6 3.10.0-957.el7.x86_64
Compiler: g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
brpc: rdma分支 commit 9028c39a0c54
protobuf: 

[root@node78 ~]# rpm -qa |grep protobuf
protobuf-java-2.5.0-8.el7.x86_64
protobuf-emacs-2.5.0-8.el7.x86_64
protobuf-c-1.0.2-3.el7.x86_64
protobuf-2.5.0-8.el7.x86_64
protobuf-static-2.5.0-8.el7.x86_64
protobuf-c-compiler-1.0.2-3.el7.x86_64
protobuf-lite-devel-2.5.0-8.el7.x86_64
protobuf-compiler-2.5.0-8.el7.x86_64
protobuf-lite-2.5.0-8.el7.x86_64
protobuf-javadoc-2.5.0-8.el7.x86_64
protobuf-vim-2.5.0-8.el7.x86_64
protobuf-lite-static-2.5.0-8.el7.x86_64
protobuf-emacs-el-2.5.0-8.el7.x86_64
protobuf-c-devel-1.0.2-3.el7.x86_64
protobuf-devel-2.5.0-8.el7.x86_64
protobuf-python-2.5.0-8.el7.x86_64

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/3406829/100406382-9fdea000-30a0-11eb-9de7-342b3d342165.png)

**Comment by Tuvie** [comment]
This should be a bug when initialize rdma CQ with incorrect queue index ID.
I will commit a patch for that soon and you can retry.

Thanks for the feedback.

**Comment by Pating** [comment]
> This should be a bug when initialize rdma CQ with incorrect queue index ID.
> I will commit a patch for that soon and you can retry.
> 
> Thanks for the feedback.

**Comment by Pating** [comment]
> This should be a bug when initialize rdma CQ with incorrect queue index ID.
> I will commit a patch for that soon and you can retry.
> 
> Thanks for the feedback.

Thansk, look forward to your patch.

**Comment by Tuvie** [comment]
@Pating The patch is merged into rdma branch. You can try again and give me a feedback.

**Comment by Pating** [comment]
> @Pating The patch is merged into rdma branch. You can try again and give me a feedback.

Hi Tuvie
   我试了你提供最新的rdma分支， commit id是 62240fea92。在这个最新分支上还会有rdma的问题，虽然出现频率比老版本低，但也不是很难复现。我这边持续大压力读写，1个小时内就会复现。
   如下是当前版本brpc的报错日志：
  
![image](https://user-images.githubusercontent.com/3406829/104279841-eddf2400-54e5-11eb-82b2-7f21e21a23d1.png)
![image](https://user-images.githubusercontent.com/3406829/104279916-0bac8900-54e6-11eb-9258-ed0c9cec323d.png)
![image](https://user-images.githubusercontent.com/3406829/104279980-25e66700-54e6-11eb-9642-a604fc321c9e.png)

  如果需要更多信息请随时@我，多谢。

**Comment by Tuvie** [comment]
从日志上看，反馈的error status 是12，这个在rdma里代表IBV_WC_RETRY_EXC_ERR，也就是重试次数超限。RDMA和TCP不一样，TCP丢包可以近乎无限的重传，RDMA丢包后，超时重传有次数上限。超出上限后，整个QP会报上面的错，连接中断。
看上去你测试底层使用的物理网络环境没有做特殊配置。建议在有PFC和ECN网络配置的物理网络环境中使用RoCE。否则确实会出现大量丢包导致连接中断的情况。
