### ISSUE TITLE
Controller的_session_local_data在归还至pool之前可否先reset

### ISSUE THREAD

**Issue by yockie** [apache/incubator-brpc#1300]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
据我周知，一次rpc结束（SendRpcResponse）会delete Controller（默认），在Controller的析构函数中，会将_session_local_data归还至server的_session_local_data_pool：
_server->_session_local_data_pool->Return(_session_local_data);

我现在遇到的问题是，我们的程序中_session_local_data每次使用会直接或间接的申请较大空间。根据打点显示，每次新的rpc进入service函数时对_session_local_data的reset的时间花费较大，影响整体平响。

**Describe the solution you'd like (描述你期望的解决方法)**
如何在rpc结束后，_session_local_data归还至pool前，先做reset操作，避免reset时间占用新的rpc时间。
为什么非要在“rpc结束后，_session_local_data归还至pool前”做呢：因为既不想占用当前rpc的时间，又不想占用新的rpc的时间。

**Describe alternatives you've considered (描述你想到的折衷方案)**
如果brpc框架不想做，能否提供自定义的接口让用户可以在rpc结束后做类似的清理工作，例如我想到的一个方法是：
（1）在DataFactory中增加一个ResetData的函数，用户自定义
（2）在SimpleDataPool::Return函数中归还给pool之前，即下面这行之前调用一下_factory->ResetData(data)：
_pool[_size++] = data;

大佬们看下是否可行，多谢！

**Comment by cdjingit** [comment]
对reset操作做优化，比如尽量重用session_data申请的内存。

**Comment by jamesge** [comment]
@yockie 加好了 https://github.com/apache/incubator-brpc/commit/fb93753bc54666fb815ed2fe099b0a98a01ea61e#diff-161b7c02b8d6d08dfefa05ed880fbdc9df1cad1239c36fbc64cddf9e02deaebf

**Comment by yockie** [comment]
赞！
