### ISSUE TITLE
set max_body_size using API

### ISSUE THREAD

**Issue by Hacky-DH** [apache/incubator-brpc#1303]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
没有

**Describe the solution you'd like (描述你期望的解决方法)**
可以通过API的方式修改max_body_size，不是通过gflags

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
什么样的业务场景？

**Comment by Hacky-DH** [comment]
我们通过python调用了brpc的so  api，有什么设置的办法？

**Comment by gydong** [comment]
可以试着调用gflags库的这个函数，把你需要的参数设置上：
![image](https://user-images.githubusercontent.com/3294444/102293850-dfebc100-3f82-11eb-805f-5598dd21b453.png)

**Comment by Hacky-DH** [comment]
@gydong 好的 多谢 我试试，我们暂时通过设置gflags导出的全局变量设置了，也能实现
