### ISSUE TITLE
grpc 客户端访问brpc服务， 服务拒绝请求

### ISSUE THREAD

**Issue by x-x-p** [apache/incubator-brpc#1306]
https://github.com/apache/incubator-brpc/blob/6502e0c5b6a8c444bb32097da955d5e7a4efcbd9/src/brpc/policy/http_rpc_protocol.cpp#L1019-L1040

为啥设置了restful之后要拒绝原生service/method 方法访问， 在grpc中访问服务时， grpc中就是使用service/method访问的， 现在grpc客户端被拒绝了

**Comment by wasphin** [comment]
添加服务的时候是允许设置是否启用原生 service/method 方法访问的 #1214

**Comment by x-x-p** [comment]
谢谢， 这个还只是在master分支里面， 我下载分支没有看到。
