### ISSUE TITLE
Please leave your company information (company name + website) in the comments below, thank you !

### ISSUE THREAD

**Issue by GuangmingLuo** [apache/incubator-brpc#1307]
Please leave your company information (company name + website) in the comments below if bRPC is used in your company, thank you!
如果您的公司使用了 bRPC，请在下面的评论里面留下公司信息和使用场景（如果方便写明的话），谢谢！

例如：
* Baidu，<场景>
* 爱奇艺

**Comment by JasonWpy** [comment]
Cloudsdnet + www.capitalonline.net.cn

**Comment by NIGHTFIGHTING** [comment]
didi+https://www.didiglobal.com/

**Comment by tanzhongyi003** [comment]
open another issue to track this。

https://github.com/apache/incubator-brpc/issues/1640

so close this
