### ISSUE TITLE
使用brpc::Channel 时，重复init导致无法连接到server

### ISSUE THREAD

**Issue by walterzhaoJR** [apache/incubator-brpc#1309]
使用brpc::Channel 时，重复init导致无法连接到server。
我的使用场景是，每当server 的发生主备切换后，我需要重新和server 的新leader 建立连接，这个时候会重复init 同一个brpc::Channel，最近偶现连接server失败，错误信息是error:112。目前通过在每次重连的时候使用新的brpc::Channel来连接server可以杜绝这个问题。
这里想请问下：重复init 同一个brpc::Channel 是否是不合理的使用方式。

**Comment by cdjingit** [comment]
是不合理的方式，看看是否可以选用合适的名字服务。

**Comment by walterzhaoJR** [comment]
好的，那我们就每次切主之后，重新连接的时候，使用一个新的brpc::Channel。感谢。
