### ISSUE TITLE
link brpc in static and dynamic simultaneously

### ISSUE THREAD

**Issue by weixinwei** [apache/incubator-brpc#1312]
如果在一个进程中同时link brpc.so和brpc.a，有什么影响吗？

**Comment by gydong** [comment]
你是怎么做到同时链接的？

**Comment by weixinwei** [comment]
> 你是怎么做到同时链接的？

cmake，一个进程下分为几个模块，有的模块直接target_link_libraries(brpc)，有的模块检查了LINK_SO，就链到了libbrpc.a。
看cmake的link.txt也能看到-lbrpc ../../lib/libheap_profiler.a ../../lib/libcpu_profiler.a ../../lib/liblua.a -lm /usr/lib64/libdl.so /usr/lib64/libbrpc.a /usr/lib64/libgflags.so /usr/lib64/libleveldb.so -lssl -ldl

**Comment by wwbmmm** [comment]
不建议同时链接brpc.so和brpc.a，可能会引起符号冲突
