### ISSUE TITLE
基于baidu_std 协议时，server端需要知道这个rpc的超时时间

### ISSUE THREAD

**Issue by feng-y** [apache/incubator-brpc#1316]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
server 端会根据rpc 的剩余时间做快速退出或者一些降级的策略，比如mean 耗时是100ms，如果业务受到剩余不到50ms时时可以直接终止的

**Describe the solution you'd like (描述你期望的解决方法)**
获取到 rpc的过期时间，或者剩余时间

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
『过期时间』方案会依赖于机器间的时间同步，『剩余时间』则忽略了网络延迟和处理延迟的影响。过去我实践过『过期时间』方案，因为机器时间同步问题，没有得到最终应用。你的场景更倾向于哪种方案？

**Comment by feng-y** [comment]
剩余时间

**Comment by gydong** [comment]
我们评估下

**Comment by wwbmmm** [comment]
已支持，开启gflag baidu_std_protocol_deliver_timeout_ms之后，即可在server端通过timeout_ms()获取client端设置的值
