### ISSUE TITLE
Fail to define brpc::ENOSERVICE(1001) which is already defined as `未知的错误 1001', abort

### ISSUE THREAD

**Issue by huangmiumang** [apache/incubator-brpc#1321]
1 bazel编译libbrpc.so，只依赖@brpc//:brpc;
2 使用java jni System.load(libbrpc.so)会出现以下报错;
3 报错: 出现了Fail to define brpc::ENOSERVICE(1001) which is already defined as `未知的错误 1001', abort。

**Comment by zhukaijun1992** [comment]
我也遇到这个问题。。

**Comment by juntao-hu** [comment]
> 1 bazel编译libbrpc.so，只依赖@brpc//:brpc; 2 使用java jni System.load(libbrpc.so)会出现以下报错; 3 报错: 出现了Fail to define brpc::ENOSERVICE(1001) which is already defined as `未知的错误 1001', abort。

请问这个问题解决了吗

**Comment by wwbmmm** [comment]
Fixed by #1142
