### ISSUE TITLE
bvar支持多维度统计

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1322]
### 设计目标
* 支持多维度统计，接口简单容易使用
* 高性能，不给程序增加性能开销
* 兼容bvar目前的单维度方案
* 做好准守开源的Prometheus(OpenMetrics)规范

### 实现方案
![image](https://user-images.githubusercontent.com/38067377/141484582-eea3aa68-6316-483f-b523-39d369f1ec31.png)

* bvar：底层bvar计数器，复用目前bvar中的单维度计数器
* Labels：监控项维度KV对，包含维度名和维度值，例如：idc为bj，method为get，status为200
* Metric：监控项，需要在创建的时候指定labels的key，并且需要管理监控项下所有的instance
* MetricManager：管理全局所有的监控项，manager全局唯一
* MetricCollector：监控数据收集者，支持将数据dump到本地磁盘文件

### 技术选型
Metric如何高效的管理bvar，显而易见，Metric管理bvar是一个读多写少的操作，程序刚开始启动的时候可能写比较多(一个labels只会写一次)，但是一段时间后基本就不会存在写操作了，因此这里共有两种选型：

#### 读写锁
临界区不是特别大的时候（毫秒级），读写锁并不比mutex快。
可以用如下几种结构来存储labels和bvar的对应关系：
* map
* unordered_map
* Flatmap
* skiplist

#### 双缓冲DBD(DoublyBufferedData)
brpc中的loadbalance就是采用这种数据结构。
可以用如下3中数据结构来存储labels和bvar的对应关系：
* map
* unordered_map
* Flatmap

最终选型：DBD + Flatmap

### 数据导出
dumper支持三种导出格式，业务方可以根据自己的实际需求进行灵活配置：
* 冒号分割的KV文本格式，也就是目前bvar的dump格式，Key：Value形式
* 开源Prometheus文本格式，兼容开源方案，方便业务往云原生方向迁移

#### 冒号分割的KV格式
文本格式，Key和Value用冒号分割，比如：
```
http_request_count{idc="bj",method="post",status="200"} : 1000
http_request_qps{idc="bj",method="post",status="200"} : 30
http_request_latency{idc="bj",method="post",status="200"} : 50
```

#### Prometheus格式
文本格式，Key和Value用空格分开，比如：
```
# MetricName{lable1_key="lable1_value",lable2_key="lable2_value",lable3_key="lable3_value"} value
# Example for Adder、Maxer、Miner and IntRecorder
http_request_count{idc="bj,method="post",status="200"} 20
http_request_count{idc="bj",method="get",status="200"} 50
```

**Comment by chenzhangyi** [comment]
是有方案了还是一个feature request？

**Comment by serverglen** [comment]
> 是有方案了还是一个feature request？

内部已经实现了，最近准备提个PR

**Comment by lorinlee** [comment]
@serverglen 预计什么时候开源呀

**Comment by serverglen** [comment]
> @serverglen 预计什么时候开源呀

预计6月份之前

**Comment by cfreebuf** [comment]
进度如何呢？

**Comment by serverglen** [comment]
> 进度如何呢？

有点推迟，我尽量早点吧

**Comment by serverglen** [comment]
> 进度如何呢？

12月份之前提交

**Comment by serverglen** [comment]
> @serverglen 预计什么时候开源呀

已提交PR #1608

**Comment by serverglen** [comment]
> 进度如何呢？

已提交PR #1608

**Comment by serverglen** [comment]
> 是有方案了还是一个feature request？

已提交PR #1608

**Comment by serverglen** [comment]
当时这么设计也是考虑到以下几点：
1. 框架帮用户拼接key，避免用户自己实现五花八门 拼接key的逻辑
2. 保留用户单维度bvar的使用习惯
3. 多维度bvar支持导出prometheus格式数据，如果用户自己拼接key，他自己也需要实现导出prometheus格式的逻辑

当前实现方式复杂度其实也还好，核心代码并没有太多，还有一部分list、count、describe等不常用接口。

**Comment by FailedNamed** [comment]
你好，我想请问下，为啥到现在这份代码还没被merge，是有其他问题或者其他考虑嘛，都9个月了诶

**Comment by serverglen** [comment]
实在不好意思，这部分代码在社区有点分歧，我们尽快同步意见，合入之后通知你。

**Comment by FailedNamed** [comment]
> 实在不好意思，这部分代码在社区有点分歧，我们尽快同步意见，合入之后通知你。
感谢大佬回复，因为目前最近我们正好想用这个功能做一些业务指标上报，但是prometheus貌似没有cpp sdk之类的（在他们官网和git都没找着），假如我们自己把这部分代码拉下来merge到我们代码里，应该也是可行的吧[思考]

**Comment by serverglen** [comment]
> FailedNamed

问一下，您这边应该使用brpc了吧？如果使用的话，辛苦您能更新下[brpc在贵公司的落地场景](https://github.com/apache/incubator-brpc/issues/1640)吗？
另外：建议您订阅dev@brpc.apache.org邮件组，我们会通过邮件沟通和讨论一些技术问题和计划，订阅之后您也能及时了解并参与brpc社区技术讨论。
订阅方式：发一封邮件给[dev-subscribe@brpc.apache.org](mailto:dev-subscribe@brpc.apache.org)，然后按照回复邮件点击对应的链接即可订阅。

--

**Comment by FailedNamed** [comment]
> > FailedNamed
> 
> 问一下，您这边应该使用brpc了吧？如果使用的话，辛苦您能更新下[brpc在贵公司的落地场景](https://github.com/apache/incubator-brpc/issues/1640)吗？ 另外：建议您订阅[dev@brpc.apache.org](mailto:dev@brpc.apache.org)邮件组，我们会通过邮件沟通和讨论一些技术问题和计划，订阅之后您也能及时了解并参与brpc社区技术讨论。 订阅方式：发一封邮件给[dev-subscribe@brpc.apache.org](mailto:dev-subscribe@brpc.apache.org)，然后按照回复邮件点击对应的链接即可订阅。
> 
> --

ok

**Comment by serverglen** [comment]
> > > FailedNamed
> > 
> > 
> > 问一下，您这边应该使用brpc了吧？如果使用的话，辛苦您能更新下[brpc在贵公司的落地场景](https://github.com/apache/incubator-brpc/issues/1640)吗？ 另外：建议您订阅[dev@brpc.apache.org](mailto:dev@brpc.apache.org)邮件组，我们会通过邮件沟通和讨论一些技术问题和计划，订阅之后您也能及时了解并参与brpc社区技术讨论。 订阅方式：发一封邮件给[dev-subscribe@brpc.apache.org](mailto:dev-subscribe@brpc.apache.org)，然后按照回复邮件点击对应的链接即可订阅。
> > --
> 
> ok

已合入。

**Comment by serverglen** [comment]
多维度bvar功能已合入，PR：#1608
