### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by zkh2016** [apache/incubator-brpc#1323]
**Describe the bug (描述bug)**
最近用rpc_replay压测一个server发现这样一个现象：
1. 当压到比如4000qps的时候就出现超时了，但是这时候的CPU，内存，网络带宽等资源都还足够继续往上压。
2. 在一台机器上开启两个server进程（不同端口），开多个rpc_replay(与server不同机器）压这两个server的时候可以压到大于4000qps，直到各种资源不足以继续往上压为止。
3. 另一种情况，开一个server进程，开两个rpc_replay可以比一个rpc_replay压的高。

附件是用perf工具生成的火焰图，可以把后缀'.txt'去掉打开查看。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

[out.svg.txt](https://github.com/apache/incubator-brpc/files/5780401/out.svg.txt)

期望server端单进程也能压到最大值。

**Versions (各种版本)**
OS: CentOS Linux release 7.4.1708 (Core)
Compiler: gcc 4.8.5
brpc: 0.9.7
protobuf: libprotobuf.so.18

**Additional context/screenshots (更多上下文/截图)**

[out.svg.txt](https://github.com/apache/incubator-brpc/files/5780403/out.svg.txt)

**Comment by zc08291161** [comment]
请问最终找到解决方案了么？
