### ISSUE TITLE
多进程架构与单线程请求处理

### ISSUE THREAD

**Issue by cfreebuf** [apache/incubator-brpc#1331]
咨询了解一下，因业务需求，需要做请求的串行处理(避免业务自己代码中对全局变量或类的数据成员并发读写造成的不一致)，是否可通过启动多个brpc process，并且设置每个进程的bthread_concurrency=1和num_threads=1来满足需求？
这种架构设计肯定会影响性能、qps，目前只是为了用户不用担心请求的并发执行造成的不易察觉的数据不一致或其它多线程编程问题。

**Comment by jamesge** [comment]
不能，brpc server不允许线程数小于4。你这种情况要用[execution queue](https://github.com/apache/incubator-brpc/blob/master/docs/cn/execution_queue.md)

**Comment by cfreebuf** [comment]
收到，我了解一下ExecutionQueue，Thanks!
