### ISSUE TITLE
Request upper limit concurrency Feature.

### ISSUE THREAD

**Issue by xiangpdu** [apache/incubator-brpc#1334]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
We are facing trouble that the concurrency may exceed the capability of the machine while auto concurrency is enabled. The time-consuming for a request is short and the timeout is longer than the time-consuming, so the number of requests in the service increasing rapidly causes an OOM.

**Describe the solution you'd like (描述你期望的解决方法)**
We desire an upper limit for concurrency even auto concurrency is enabled.

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
Is server level max_concurrency can solve your problem? may be you can set ServerOptions.max_concurrency

**Comment by cdjingit** [comment]
Auto concurrency can not work well in our services too. 
We deveplop a new auto concurrency policy which is based on bthread congestion control in run queue. 
It works well in our system. We will commit a pr recently.

**Comment by xiangpdu** [comment]
@cdjingit Great! Can you paste your merge request?

**Comment by serverglen** [comment]
please see https://github.com/apache/incubator-brpc/blob/master/docs/cn/auto_concurrency_limiter.md
