### ISSUE TITLE
macos 编译报错

### ISSUE THREAD

**Issue by wangrufeng** [apache/incubator-brpc#1336]
**Describe the bug (描述bug)**
$ make
> Linking protoc-gen-mcpack
clang++ -o protoc-gen-mcpack -I./src -I/usr/local/include/ -I/usr/local/opt/openssl/include -L/usr/local/lib -L/usr/local/opt/openssl/lib -std=c++0x src/idl_options.pb.cc src/mcpack2pb/generator.o libbrpc.a /usr/local/lib/libprotobuf.a /usr/local/lib/libleveldb.a /usr/local/lib/libsnappy.a /usr/local/lib/libprotoc.a -lpthread -lssl -lcrypto -ldl -lz -framework CoreFoundation -framework CoreGraphics -framework CoreData -framework CoreText -framework Security -framework Foundation -Wl,-U,_MallocExtension_ReleaseFreeMemory -Wl,-U,_ProfilerStart -Wl,-U,_ProfilerStop -Wl,-U,_RegisterThriftProtocol -lgflags
Undefined symbols for architecture x86_64:
  "_BIO_fd_non_fatal_error", referenced from:
      butil::IOBuf::cut_multiple_into_SSL_channel(ssl_st*, butil::IOBuf* const*, unsigned long, int*) in libbrpc.a(iobuf.o)
      butil::IOPortal::append_from_SSL_channel(ssl_st*, int*, unsigned long) in libbrpc.a(iobuf.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [protoc-gen-mcpack] Error 1

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by serverglen** [comment]
closed, reopen if you have further ideas.
Thank you for your contributions!
