### ISSUE TITLE
nhead server core 析构ConcurrencyRemover 

### ISSUE THREAD

**Issue by yqynju** [apache/incubator-brpc#1337]
**Describe the bug (描述bug)**
nshead coredump， 多线程情况下：

#0  brpc::ConcurrencyRemover::~ConcurrencyRemover (this=0x7fc2ffffff72, __in_chrg=<optimized out>) at brpc/src/brpc/details/method_status.cpp:154
#1  0x000055d41b2ada3c in brpc::NsheadClosure::Run (this=0x7fc79c0b99f0) at brpc/src/brpc/policy/nshead_protocol.cpp:95
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: 
Compiler: gcc2 4.8
brpc: 0.9.6
protobuf: 

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
好复现不，可以挂ASAN跑一下试试

**Comment by serverglen** [comment]
closed, reopen if you have further ideas.
Thank you for your contributions!
