### ISSUE TITLE
flat_map支持struct作key吗?

### ISSUE THREAD

**Issue by muween** [apache/incubator-brpc#1340]
同样的struct，使用std::map通过，而使用butil::FlatMap出现错误，大致为
`struct xxx is used but never defined [-fpermissive]`

**Comment by serverglen** [comment]
应该是支持的，需要自己实现一个hash函数

**Comment by serverglen** [comment]
struct xxx {
};

需要实现：
1. 重载==运算符
bool operator==(const struct xxx& obj) const {
    // TODO
}

2. 实现自定义的hash函数
template <>
struct butil::DefaultHasher<struct xxx> {
     // TODO
};

**Comment by lorinlee** [comment]
@muween 可以贴个代码片段吗，以及编译器报的错误

**Comment by serverglen** [comment]
closed, reopen if you have further ideas.
Thank you for your contributions!
