### ISSUE TITLE
BRPC grpc  协议支持的版本是什么

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-brpc#1344]
我使用brpc 版本是0.95，server是C++的，protoc 版本3.5.1 grpc-java 版本是1.18.0， 使用java client 去访问brpc server 时会报 如下错误 
![image](https://user-images.githubusercontent.com/9098473/108316849-68dbde80-71f8-11eb-90b7-50074c904749.png)
这个是访问 request 和response 的定义
![image](https://user-images.githubusercontent.com/9098473/108316905-7f823580-71f8-11eb-8f09-ef6aa7bf81a3.png)

**Comment by lorinlee** [comment]
可以发个最小可复现的程序吗

**Comment by yangzhg** [comment]
后来发现如果Server端有设置attachment  用grpc 访问就会出错

**Comment by wkl7123** [comment]
所以brpc只要用了request_attachment就不能兼容grpc了吗

**Comment by wwbmmm** [comment]
> 

是的
