### ISSUE TITLE
使用brpc http client访问url，返回错误信息 “400 Bad Request”

### ISSUE THREAD

**Issue by Silocean** [apache/incubator-brpc#1347]
**Describe the bug (描述bug)**

使用brpc http client GET 方式请求url，返回错误信息 “400 Bad Request”。
具体信息如下：
```plain
 Fail to send Request, [E1010]HTTP/1.1 400 Bad Request: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

初步判定是url长度超过限制导致的，因为尝试去掉某些参数降低url长度后错误消失。
请问brpc http client中是否确实有该长度限制？如果有是否可自定义？在哪里自定义？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Centos 7.2.1511
Compiler:  gcc-4.8.5
brpc: 0.9.0
protobuf: 3.6.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by guodongxiaren** [comment]
可以把完整url贴出来看下

**Comment by wwbmmm** [comment]
brpc client没有长度限制，这是server端的限制
