### ISSUE TITLE
BRPC 支持RPM安装吗？

### ISSUE THREAD

**Issue by darionyaphet** [apache/incubator-brpc#1355]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
各种依赖太复杂 

**Describe the solution you'd like (描述你期望的解决方法)**
期待BRPC支持RPM安装

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wasphin** [comment]
package/rpm 下有 rpm 打包的 spec, 目前测试可以在 rhel/centos 6/7/8 上打包安装使用, 可以从 release 界面下载 tar 包或自己使用命令打一个:
```
export TOPDIR=`pwd`/package
mkdir ${TOPDIR}/SOURCES
git archive --format=tar.gz --prefix=incubator-brpc-0.9.7/ --output ${TOPDIR}/SOURCES/incubator-brpc-0.9.7.tar.gz HEAD
```
安装依赖:
```
sudo yum-builddeps -y package/rpm/brpc.spec
```
编译:
```
rpmbuild -bb package/rpm/brpc.spec ---define "%_topdir $TOPDIR"
```

**Comment by darionyaphet** [comment]
额 大佬 仓库里面没有  必须要自己动手吗？

**Comment by wasphin** [comment]
可以考虑用[这个源](https://copr.fedorainfracloud.org/coprs/wasphin/brpc/), 刚基于 master 分支编译的, 而不是 0.9.7, 目前只编译了 epel7 和 epel8, 另外, 工具像 ``rpc_view`` 之类的也并未打包.

**Comment by darionyaphet** [comment]
谢谢大佬
