### ISSUE TITLE
将bvar::Adder和bvar::Window用在一起时，获取的数据代表什么意思

### ISSUE THREAD

**Issue by DannyLuoDan** [apache/incubator-brpc#1365]
static bvar::Adder<uint32_t> a_skip;
static bvar::Window<bvar::Adder<uint32_t>> _f_win("skip", "qps", &a_skip, 1);

类似这样的一个结构，a_skip 记录代码逻辑跳过的累积次数
那么这个时候skip_qps 这个数据代表的是什么意思？
 是去读取Adder 1s内 a_skip的当前值，还是1s中a_skip 增加了多少值？

能作为qps指标(就是每秒skip了多少个)吗？

多谢帮助

**Comment by cdjingit** [comment]
参考文档：https://github.com/apache/incubator-brpc/blob/master/docs/cn/bvar_c++.md#quick-introduction

**Comment by DannyLuoDan** [comment]
> 参考文档：https://github.com/apache/incubator-brpc/blob/master/docs/cn/bvar_c++.md#quick-introduction

谢谢。不过就是这边有些不明白的地方：
// bvar::Adder<T>用于累加，下面定义了一个统计read error总数的Adder。
bvar::Adder<int> g_read_error;
// 把bvar::Window套在其他bvar上就可以获得时间窗口内的值。
bvar::Window<bvar::Adder<int> > g_read_error_minute("foo_bar", "read_error", &g_read_error, 60);
//                                                     ^          ^                         ^
//                                                    前缀       监控项名称                  60秒,忽略则为10秒

这边时间窗口内的值是什么值？假设时间窗口为1秒，g_read_error 当前已经累加到了15，后续有时候1s增加2，有时候1s增加3等， 那么foo_bar_read_error的值是 累加后的值 17 还是 2 或者3呀？

**Comment by hotaery** [comment]
> > 参考文档：https://github.com/apache/incubator-brpc/blob/master/docs/cn/bvar_c++.md#quick-introduction
> 
> 谢谢。不过就是这边有些不明白的地方：
> // bvar::Adder用于累加，下面定义了一个统计read error总数的Adder。
> bvar::Adder g_read_error;
> // 把bvar::Window套在其他bvar上就可以获得时间窗口内的值。
> bvar::Window<bvar::Adder > g_read_error_minute("foo_bar", "read_error", &g_read_error, 60);
> // ^ ^ ^
> // 前缀 监控项名称 60秒,忽略则为10秒
> 
> 这边时间窗口内的值是什么值？假设时间窗口为1秒，g_read_error 当前已经累加到了15，后续有时候1s增加2，有时候1s增加3等， 那么foo_bar_read_error的值是 累加后的值 17 还是 2 或者3呀？

后者

**Comment by DannyLuoDan** [comment]
明白了，谢谢两位大佬
