### ISSUE TITLE
请问使用bthread_start_background执行任务，这个任务函数的一次执行有可能会运行到多个pthread上吗。

### ISSUE THREAD

**Issue by cuisonghui** [apache/incubator-brpc#1373]
如题所示，我们现在使用bthread_start_background遇到了一个问题，内部有个非线程安全的类，但是是在执行函数内部私有的局部变量，但是还是会出现莫名的core，所以想确认下是否一次任务的执行会跑到多个pthread上。

**Comment by cuisonghui** [comment]
@gydong @serverglen @jamesge

**Comment by hotaery** [comment]
有可能，如果执行函数内部有bthread提供的同步原语，比如bthread_mutex，如果没有获取到会被挂起，后面条件达到时会加入队列等待调度，此时有可能其他空闲工作线程会来窃取bthread执行，最终执行函数会在多个工作线程(pthread)执行

**Comment by cuisonghui** [comment]
> 有可能，如果执行函数内部有bthread提供的同步原语，比如bthread_mutex，如果没有获取到会被挂起，后面条件达到时会加入队列等待调度，此时有可能其他空闲工作线程会来窃取bthread执行，最终执行函数会在多个工作线程(pthread)执行

多谢，明白了。
