### ISSUE TITLE
What is `external:ssl` in BUILD.bazel

### ISSUE THREAD

**Issue by fuhailin** [apache/incubator-brpc#1375]
**Describe the bug (描述bug)**
```
com_github_brpc/BUILD.bazel:324:11: no such target '//external:ssl': target 'ssl' not declared in package 'external' defined by
```

**To Reproduce (复现方法)**
bazel build brpc

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Ubuntu 20.04.2 LTS
Compiler: bazel 3.7.0
brpc: commit b3a948c9dca29632b3367529488e070852e31f11
protobuf: v3.15.6

**Additional context/screenshots (更多上下文/截图)**

**Comment by 372046933** [comment]
`butil` depends on "//conditions:default": ["//external:ssl"],
