### ISSUE TITLE
DoublyBufferedData支持多写多读吗

### ISSUE THREAD

**Issue by cfreebuf** [apache/incubator-brpc#1376]
在业务代码中使用了DBD，从文档中看支持一个线程写，实际业务中有可能会有多写的情况，比如处理多个request时会修改request中用DBD封装的context，不确定DBD是否支持这种场景。

**Comment by hotaery** [comment]
多写多读都是支持的，但是多写最终会串行执行的，写使用了mutex来保护的，具体可以参考https://github.com/apache/incubator-brpc/blob/master/src/butil/containers/doubly_buffered_data.h#L351

**Comment by cfreebuf** [comment]
明白，多谢~
