### ISSUE TITLE
How to run code in incubator-brpc/example/rdma_performance?

### ISSUE THREAD

**Issue by XinShuoWang** [apache/incubator-brpc#1387]
Branch: rdma
Question: I am a newbie to BRPC, I have not used BRPC before, I am more interested in his RDMA communication part, so I tried it. After I compiled the code, I couldn’t run the sample code in directory ` incubator-brpc/example/rdma_performance` , and I couldn’t find a hint on how to modify client.cpp or server.cpp to make them run successfully. The running error message is like this: `incubator-brpc/src/brpc /rdma/rdma_helper.cpp:512] Now local connection only uses TCP. Try to set rdma_disable_local_connection to false to allow RDMA local connection`

**Comment by tbago** [comment]
If you use local network connection you should set rdma_disable_local_connection=false. Otherwise you can just ignore this warning.

**Comment by wwbmmm** [comment]
Hello, the original rdma branch is no longer maintained. We plan to merge rdma feature into master：https://github.com/apache/incubator-brpc/pull/1836
You can try the new rdma implementation. If still have problem, you can create a new issue.
Close this first.
