### ISSUE TITLE
关于DoublyBufferedData，切换前后台后再改一次新后台的目的是？

### ISSUE THREAD

**Issue by shiludeng** [apache/incubator-brpc#1388]
https://github.com/apache/incubator-brpc/blob/master/docs/cn/lalb.md#doublybuffereddata
![image](https://user-images.githubusercontent.com/1152246/115902723-4df64680-a495-11eb-88ad-79758b889464.png)

**Comment by zyearn** [comment]
为了保证前后台数据一致。

**Comment by shiludeng** [comment]
好的 感谢 我本来以为修改都是全量修改的，对于增量修改的场景确实需要前后台都改一次
