### ISSUE TITLE
brpc rdma multithread polling mode in pthread 

### ISSUE THREAD

**Issue by tbago** [apache/incubator-brpc#1395]
In the brpc rdma branch. when we use polling mode, we select several thread workers to do the polling all the time. These thread workers will not handle other tasks any more.  The brpc use [bthread](https://github.com/apache/incubator-brpc/blob/rdma/src/brpc/rdma/rdma_completion_queue.cpp#L197) to polling the rdma cq. But when we set multi cq num like **rdma_cq_num = 9** and bind them in separate cpu core. The bthread is not working well, and event cannot quit the process.
<img width="827" alt="WechatIMG23" src="https://user-images.githubusercontent.com/12290248/117637924-e2121e80-b1b4-11eb-926b-c5664a9054d3.png">

In the rdma polling mode, the bthread is works as pthread. And cannot processing any other task. So why not just use pthread  to process the cq event. And use bthread to do other works, and make bthread more efficient.

**Comment by wwbmmm** [comment]
Hello, the original rdma branch is no longer maintained. We plan to merge rdma feature into master：https://github.com/apache/incubator-brpc/pull/1836
You can try the new rdma implementation. If still have problem, you can create a new issue.
Close this first.
