### ISSUE TITLE
does brpc have heartbeat message when a tcp connection established?

### ISSUE THREAD

**Issue by huanyingtianhe** [apache/incubator-brpc#1397]
does brpc have heartbeat message when a tcp connection established? or we need to implement it as grpc, https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by wwbmmm** [comment]
no

**Comment by zyearn** [comment]
这个之前一直想支持的，因为server可以设置fd无活动时自动关闭，而client端没有，最简单的方案是加tcp层面的心跳
