### ISSUE TITLE
Multi rdma device not working in rdma brpc branch

### ISSUE THREAD

**Issue by tbago** [apache/incubator-brpc#1401]
We have multi rdma NIC in server. If we use the first rdma device by use **--rdma_device=mlx5_0**. The brpc client and server works well. But if we use other rdma device like **--rdma_device=mlx5_1**, the client cannot communicate to the server. It will show the following error:
<img width="827" alt="WechatIMG24" src="https://user-images.githubusercontent.com/12290248/117993016-efc0d300-b371-11eb-95f3-f8a3d18d4c20.png">

The [rdma_create_qp](https://github.com/apache/incubator-brpc/blob/rdma/src/brpc/rdma/rdma_communication_manager.cpp#L311)  will failed with errno=22 (invalid param). The root cause is that the GetRdmaProtectionDomain() is use the global context, I mean that the global context may support support well or have some bugs? I have write my custom client and use rdma_cm_id->verbs as context. Then I can connect the brpc server with other rdma device.
  But in the [rdma_helper.cpp](https://github.com/apache/incubator-brpc/blob/rdma/src/brpc/rdma/rdma_helper.cpp) the pd is init before the rdma_cm_id. 
    So my question is does someone have the same issue will me.  And how to fixed the bug, do we need the create the pd after the rdma_cm_id is created.

**Comment by tbago** [comment]
I found the rdma_cm_id is not matched when use the second device. I have add the bind function in client side. And it can fixed the client connection isuse.
<img width="829" alt="WechatIMG27" src="https://user-images.githubusercontent.com/12290248/118115593-bd6bb000-b41b-11eb-90c1-b161939d237c.png">

**Comment by tbago** [comment]
But in the brpc server side. The rdma device options still not working.

**Comment by changchengx** [comment]
@ziruiliu @tbago 
Does brpc support RoCE LAG device (two RDMA NICs are bond into one logic port)?

**Comment by wwbmmm** [comment]
brpc has no plan to support multi rdma device.

**Comment by changchengx** [comment]
@wwbmmm 
I tested the RoCE LAG device with below command and it could work
```
[307 /brpc/example/rdma_performance/]$ ./perf_server --rdma_device mlx5_bond_1
[306 /brpc/example/rdma_performance/]$ ./perf_client --rdma_device mlx5_bond_1 --servers=192.168.30.7:8002 --attachment_size=1024 --thread_num=10
```
According to the experiment's result, brpc doesn't support multi rdma devices, so it need to specify which device should be used with the option ```--rdma_device```.

**brpc supports RoCE LAG device, right?**

**Comment by Tuvie** [comment]
@changchengx 
Yes, brpc can support RoCE LAG device. But brpc does not support multi rdma devices without LAG.

**Comment by changchengx** [comment]
@Tuvie 
Got it. Thanks
