### ISSUE TITLE
Does brpc support IPv6? （请问 brpc 支持 IPv6 吗？）

### ISSUE THREAD

**Issue by MaoJianwei** [apache/incubator-brpc#1403]
Hi friends,

We want to use brpc for communication between containers.

Does brpc support IPv6? (for IPv6-only or Dual-stack environment?)
（请问brpc支持IPv6吗？支持双栈还是IPv6单栈？）

And, which version of brpc supports IPv6?
（哪个版本支持IPv6？）

Thanks!
Mao

**Comment by SHASHENp** [comment]
好像不支持，我在Channel看到存储地址的EndPoint类型是IPv4的

**Comment by MaoJianwei** [comment]
> 好像不支持，我在Channel看到存储地址的EndPoint类型是IPv4的

这样啊，多谢哈

**Comment by wwbmmm** [comment]
master已支持
