### ISSUE TITLE
Is it safe enough to retry ETIMEDOUT error by default?

### ISSUE THREAD

**Issue by joway** [apache/incubator-brpc#1406]
**Describe the bug (描述bug)**

Hi, thanks for creating such an amazing RPC framework!

I'm learning this project recently but found brpc will retry to send request when meeting `ETIMEDOUT` error. In my understanding, ETIMEDOUT means:

> A connect(2) or send(2) request failed
   because the connected party did not properly respond after a
   period of time.  (The timeout period is dependent on the communi-
   cation protocol.) 

If the server-side has processed the request, but not send back ACK to the client successfully(and still failed when the client retransmits), the client will get the `ETIMEDOUT` error finally, and retry to send the RPC call, which will cause unexpected behavior for the non-idempotent API.

```
+----------+                                +----------+                       
|  Client  |                                |  Server  |                       
+----------+                                +----------+                       
     |                                           |                             
     |                                           |                             
     |                  PSHs ==>                 |                             
     |-------------------------------------------|                             
     |                                           |                             
     |                                           |                             
     |                <== ACKs                   |                             
     |     Lost ---------------------------------|                             
     |                                           |                             
     |                                           |Process                      
     |                                           ---------                     
     |                                           |                             
     |                                           | Crash                       
     |                                           ---------                     
     |                                           |                             
     |                                           |                             
     |                                           |                             
     |                                           |                             
     |                                           |                             
     |                                           |                                          
```

Let me know if I miss anything, thanks!

**Expected behavior (期望行为)**

ETIMEDOUT should not be included in default retriable error codes.

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
Hi, the retry behavior can be controlled by yourself, you can disable retry by setting `ChannelOptions::max_retry`, or you can implement your own RetryPolicy and set it into `ChannelOptions::retry_policy`

**Comment by joway** [comment]
@lorinlee Hi, thanks for the answer. I know there are some options that could controller this behavior. But just curious about the security of the default retry policy since most developers are using it.

**Comment by zyearn** [comment]
ETIMEOUT is a connection timed our error per https://man7.org/linux/man-pages/man3/errno.3.html. If this error happens, RPC can't be sent to remote sides.

**Comment by cdjingit** [comment]
1. ETIMEOUT means that rpc reached the deadline. ETIMEOUT should not trigger to retry RPC. 
2. The default retry poliy refer the link: https://github.com/apache/incubator-brpc/blob/master/src/brpc/retry_policy.cpp#L33
3. Framework can not guarantee idempotent。The idempotent is an application level function.

**Comment by joway** [comment]
@cdjingit @zyearn thanks very much, and I found a [doc](https://github.com/apache/incubator-brpc/blob/60159fc3f3e13490fb9806ea0a0cb0dcdbda7f7d/docs/en/client.md#q-how-to-make-requests-be-processed-once-and-only-once) has answered my question.

In summary, when using brpc users should make sure their services are idempotent otherwise they need to disable the default retry policy.

**Comment by lorinlee** [comment]
Hi @joway, another thing I have missed is the meaning of error code. You can see this [doc](https://github.com/apache/incubator-brpc/blob/master/docs/en/client.md), the `Settings` section. `ETIMEDOUT` is connection timeout but not rpc timeout, so it can be retried. `ERPCTIMEDOUT` means rpc timeout, which cannot be retried for the reason you said, and the DefaultRetryPolicy also not retry, so users needn't care about the default behavior.

**Comment by lorinlee** [comment]
and all error code meanings can be found in here [error code](https://github.com/apache/incubator-brpc/blob/master/docs/en/error_code.md)
