### ISSUE TITLE
任务分发机制的请教

### ISSUE THREAD

**Issue by eedalong** [apache/incubator-brpc#1412]
按照我的理解，目前全局使用一个TaskController， TaskController底下管K个TaskGroup，TaskGroup之间通过TaskController实现work stealing。想请教一下一个task的创建以及向task_group的分发是在哪里实现的呢？以及请问下有没有什么微信交流群之类的呢？谢谢！

**Comment by lorinlee** [comment]
Task的创建和向TaskGroup分发可以参考`bthread_start_background`和`bthread_start_urgent`的实现。微信交流群可以加我微信`lorinll`，我拉你到群里
