### ISSUE TITLE
串行执行

### ISSUE THREAD

**Issue by namelij** [apache/incubator-brpc#1416]
现在的业务是基于sofa来实现的，想对整个业务使用brpc进行升级
有个关键点，我们现在系统中有几个微服务A B C D E
流量来了之后，先进入E这个微服务，在E微服务中，对A B C D这四个微服务进行串行调用(严格串行)，比如通过调用A来获取用户画像，然后用A返回的结果，进行协议适配后，再去以rpc方式请求B，同理 C 和 D

现在使用sofa操作，A B C D这个四部操作都是使用异步方式

看了ExecutionQueue这个，但是例子中，貌似是对ExecutionQueue中的iter串行操作

我想请教下，使用ExecutionQueue是否能做到对A B C D的异步执行行为

**Comment by cdjingit** [comment]
不需要这么麻烦，E收到请求后依次请求各个服务即可A RPC -> B RPC -> C RPC -> D RPC。brpc优点之一就是可以用同步的方式写异步执行的代码，bthread在框架层面提供这样的调度。建议先看下[文档](https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%8F%91%E8%B5%B7%E8%AE%BF%E9%97%AE)

**Comment by namelij** [comment]
> 不需要这么麻烦，E收到请求后依次请求各个服务即可A RPC -> B RPC -> C RPC -> D RPC。brpc优点之一就是可以用同步的方式写异步执行的代码，bthread在框架层面提供这样的调度。建议先看下[文档](https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%8F%91%E8%B5%B7%E8%AE%BF%E9%97%AE)

现在就是这么实现的，原本想通过ExecutionQueue来提升下性能，看来还是按照现在的方式来做

感谢回复
