### ISSUE TITLE
Is it safe to using a bthread::Mutex under pthread?

### ISSUE THREAD

**Issue by mapleFU** [apache/incubator-brpc#1423]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

为了使用一些 blocking 的接口，我们把部分 IO 任务放在了 `pthread` 的线程池中。这里试图使用 `bthread::Mutex` 来做一些并发控制。文档里提过 bthread 中使用 pthread 的 blocking 接口可能会造成死锁。那么在 pthread 调用 bthread mutex 有问题吗？
请问在 pthread 下使用 bthread 的 lock 是安全的吗？如果有的话，文档在哪里提到过这个问题吗？

**Comment by mapleFU** [comment]
oops, 似乎我搞错了, bthread 调 pthread blocking 接口应该不会有问题( 除非依赖 thread_local) ?

**Comment by hnwyllmm** [comment]
使用mutex这些会有问题吧，加锁的线程要和解锁线程为同一个，否则会有问题。这是手册中说的

**Comment by lorinlee** [comment]
pthread调用bthread::Mutex，和bthread调用blocking 接口都是安全的，不过不太建议在bthread中调用blocking接口
