### ISSUE TITLE
如何用brpc 发送2M左右的消息

### ISSUE THREAD

**Issue by guocanwen** [apache/incubator-brpc#1424]
我们业务场景是一个server端，多个client。每个请求约2-5MB，这些请求的数据类似flatbuffer的数据，可以直接使用。
现在的问题是server端机器的内存带宽已经被打爆了，需要减少rpc内部的数据copy。
但是使用protobuf 里面的message {bytes data}；或者attachment都需要有内存copy（server 端iobuf会拆成多个地址不连续的block，需要调用iobuf.fetch才能使用）。
在brpc中有什么方法能够避免这次内存copy吗？我试着调大DEFAULT_BLOCK_SIZE，但是有时候还是会出现多个block的现象

**Comment by lorinlee** [comment]
server端网卡带宽多高呢，以及内存带宽目前多高？

**Comment by guocanwen** [comment]
我自己写了个rpc，现在已经把网卡打满了

**Comment by hustqy** [comment]
@guocanwen 有不copy 的方法么
