### ISSUE TITLE
使用jemalloc而不是tcmalloc也能正常开启并使用cpu profiler吗

### ISSUE THREAD

**Issue by pengpengge** [apache/incubator-brpc#1436]
**Describe the bug (描述bug)**

我们的项目中集成了brpc，而且项目本身只支持jemalloc，但是brpc的cpu profiler功能依旧可以使用
**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

没有tcmalloc的话，cpu profiler功能应该不可使用吧
**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/33371640/122168791-45c3f180-ceaf-11eb-8a3c-2be0e221118f.png)
![image](https://user-images.githubusercontent.com/33371640/122168889-5f653900-ceaf-11eb-8285-7c7443c9ff29.png)

**Comment by pengpengge** [comment]
选择new profile时会提示不可使用，但是其实能够生成分析的文件和相应图形界面。是否说明jemalloc也能够在brpc中无缝替代tcmalloc？

**Comment by zyearn** [comment]
CPU profiler需要链接gperftools里ProfilerStart，你应该链接了这个lib才能启动profiler

**Comment by lorinlee** [comment]
cpu profilter和tcmalloc是gperftools里的两个库，可以单独链接cpu profiler，可能要改下链接参数之类的。heap profiler是不支持jemalloc的，需要用jemalloc自带的工具

**Comment by 17336** [comment]
> cpu profilter和tcmalloc是gperftools里的两个库，可以单独链接cpu profiler，可能要改下链接参数之类的。heap profiler是不支持jemalloc的，需要用jemalloc自带的工具

想问下目前还是这样是吧
