### ISSUE TITLE
运行一段时间，就会core在brpc内部

### ISSUE THREAD

**Issue by yqynju** [apache/incubator-brpc#1437]
**Describe the bug (描述bug)**
(gdb) bt
#0  0x00007f635e6fb597 in raise () from /lib64/libc.so.6
#1  0x00007f635e6fcdc8 in abort () from /lib64/libc.so.6
#2  0x00007f635f0029d5 in __gnu_cxx::__verbose_terminate_handler() () from /lib64/libstdc++.so.6
#3  0x00007f635f000946 in ?? () from /lib64/libstdc++.so.6
#4  0x00007f635efff909 in ?? () from /lib64/libstdc++.so.6
#5  0x00007f635f000574 in __gxx_personality_v0 () from /lib64/libstdc++.so.6
#6  0x00007f635ea99903 in ?? () from /lib64/libgcc_s.so.1
#7  0x00007f635ea99e37 in _Unwind_Resume () from /lib64/libgcc_s.so.1
#8  0x000056490472bc40 in operator() (this=<optimized out>, obj=<optimized out>) at incubator-brpc-0.9.7/src/brpc/destroyable.h:35
#9  ~unique_ptr (this=<synthetic pointer>, __in_chrg=<optimized out>) at /usr/include/c++/4.8.2/bits/unique_ptr.h:184
#10 ~DestroyingPtr (this=<synthetic pointer>, __in_chrg=<optimized out>) at incubator-brpc-0.9.7/src/brpc/destroyable.h:41
#11 brpc::policy::ProcessNsheadRequest (msg_base=<optimized out>) at incubator-brpc-0.9.7/src/brpc/policy/nshead_protocol.cpp:325
#12 0x00005649046e7eda in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x5649087f8840) at incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:135
#13 0x00005649046e8bf3 in operator() (this=<optimized out>, last_msg=0x5649087f8840) at incubator-brpc-0.9.7/src/brpc/input_messenger.cpp:141
#14 brpc::InputMessenger::OnNewMessages (m=0x7f5fa8f07040) at /usr/include/c++/4.8.2/bits/unique_ptr.h:184
#15 0x000056490479339d in brpc::Socket::ProcessEvent (arg=0x7f5fa8f07040) at incubator-brpc-0.9.7/src/brpc/socket.cpp:1017
#16 0x00005649046bcaca in bthread::TaskGroup::task_runner (skip_remained=skip_remained@entry=1) at incubator-brpc-0.9.7/src/bthread/task_group.cpp:296
#17 0x00005649046bcdcb in bthread::TaskGroup::run_main_task (this=this@entry=0x5649085aa4e0) at incubator-brpc-0.9.7/src/bthread/task_group.cpp:157
#18 0x00005649046b720e in bthread::TaskControl::worker_thread (arg=0x564907f066e0) at incubator-brpc-0.9.7/src/bthread/task_control.cpp:76
#19 0x00007f635f2b2dc5 in start_thread () from /lib64/libpthread.so.0
#20 0x00007f635e7c04dd in clone () from /lib64/libc.so.6
(gdb) 

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc: 0.9.7
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
这个看着可能是业务代码处理请求中间抛出了exception，没有捕获，最后调用abort终止了进程。可以在server method加个try cacth看下。

**Comment by guodongxiaren** [comment]
养成好习惯，给自己的代码函数接口加上noexcept声明。避免core进brpc框架内部。
