### ISSUE TITLE
基于brpc的server长期压测时内存不断上长涨，疑似内存未及时释放

### ISSUE THREAD

**Issue by panyfx** [apache/incubator-brpc#1438]
**Describe the bug (描述bug)**
长期压测时内存不断上长涨，疑似内存未及时释放。

heap对比信息如下,主要是bthread_setspecific 带来的。查看源码，只有在申请keyTab和subKeyTab时有内存申请操作。

[20210617.141836.heap - 20210617.122951.heap]
Using local file 
Using local file ./rpc_data/profiling/c97ffa948718e4ef69f519900a705d04/20210617.141836.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Total: 521.8 MB
   317.2  60.8%  60.8%    317.2  60.8% bthread_setspecific (inline)
   155.5  29.8%  90.6%    472.7  90.6% bthread_setspecific
    13.9   2.7%  93.3%     19.5   3.7% butil::ResourcePool::get_resource (inline)
    12.6   2.4%  95.7%     12.6   2.4% __libc_calloc
     9.3   1.8%  97.4%      9.3   1.8% ::do_malloc_pages
     6.6   1.3%  98.7%      6.6   1.3% bthread::butex_create (inline)
     6.0   1.1%  99.8%      6.0   1.1% __libc_malloc
     5.0   1.0% 100.8%      5.0   1.0% std::__cxx11::basic_string::_M_assign
     2.0   0.4% 101.2%      2.0   0.4% bvar::Reducer::operator<< (inline)
     2.0   0.4% 101.6%      2.0   0.4% google::protobuf::internal::RepeatedPtrFieldBase::MergeFromInnerLoop
     1.0   0.2% 101.8%      1.0   0.2% std::_Rb_tree::_M_insert_unique (inline)
     0.5   0.1% 101.9%      1.0   0.2% brpc::Socket::Create (inline)
     0.5   0.1% 102.0%      0.5   0.1% brpc::Socket::Write (inline)

**To Reproduce (复现方法)**

bthread_start_background（&tid, BthreadFunc，data)
static bthread_key_t g_logId ;
 bthread_key_create(&g_logId, nullptr);
void* BthreadFunc(void *data){
  auto bdata = static_cast<BthreadData<RetType> *>(data);
    if (bdata == nullptr) {
        return nullptr;
    }
 bthread_setspecific(g_logId, bdata->ndc);

workerFun(bdata );
bthread_setspecific(g_logId, nullptr);

}
通过bthread_setspecific实现在workerFunc的执行线程中传递线程参数。

**Expected behavior (期望行为)**
内存稳定，不上涨。

**Versions (各种版本)**
OS:
Compiler: g++ 9.3
brpc: 0.97
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
目前实现一些对象池里的对象不会回收，所以内存使用量会和最大并发时的情况相关

**Comment by panyfx** [comment]
这里最大并发是怎么影响内存的？内存增长有上限吗？有控制增长的方式没有？

**Comment by panyfx** [comment]
[20210617.194732.heap - 20210617.141836.heap]
Using local file 
Using local file ./rpc_data/profiling/c97ffa948718e4ef69f519900a705d04/20210617.194732.heap.
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Adjusting heap profiles for 1-in-524288 sampling rate
Heap version 2
Total: 1336.6 MB
   791.4  59.2%  59.2%    791.4  59.2% bthread_setspecific (inline)
   393.1  29.4%  88.6%   1184.5  88.6% bthread_setspecific


稳定的20并发压测5个多小时，内存上涨了1G多，这个正常吗？

**Comment by lorinlee** [comment]
Hi, 可以尝试在第一次调用bthread_setspecific之前，先调用一次bthread_getspecific

**Comment by lorinlee** [comment]
已经有对应的issue描述具体问题了，可以参考 #1449 ，这个issue先关掉了，如果有问题可以再打开哈
