### ISSUE TITLE
ExecutionQueue 提供缓存的任务数量接口么？

### ISSUE THREAD

**Issue by xdlove** [apache/incubator-brpc#1439]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
No

**Describe the solution you'd like (描述你期望的解决方法)**
ExecutionQueue 提供缓存的任务数量接口

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
vars页面搜索bthread_execq*

**Comment by xdlove** [comment]
了解，如果想在代码里引用 ExecutionQueueVars 呢？目前这个函数好像没有暴露接口出来~

**Comment by cdjingit** [comment]
> 了解，如果想在代码里引用 ExecutionQueueVars 呢？目前这个函数 get_execq_vars 好像没有暴露接口出来~
> Ping @cdjingit ^~^

这个函数可以获取相关vars的对象：[ExecutionQueueVars* get_execq_vars()](https://github.com/apache/incubator-brpc/blob/master/src/bthread/execution_queue.cpp#L64)。不过没有暴露出来，需要你自己把inline去掉。

**Comment by xdlove** [comment]
> > 了解，如果想在代码里引用 ExecutionQueueVars 呢？目前这个函数 get_execq_vars 好像没有暴露接口出来~
> > Ping @cdjingit ^~^
> 
> 这个函数可以获取相关vars的对象：[ExecutionQueueVars* get_execq_vars()](https://github.com/apache/incubator-brpc/blob/master/src/bthread/execution_queue.cpp#L64)。不过没有暴露出来，需要你自己把inline去掉。

**Comment by xdlove** [comment]
明白 ~ 我去打个 patch

**Comment by xdlove** [comment]
hi 有个小问题想问一下 ~ 
为啥不统计每个 queue 的 vars 呀？目前是一个总的 vars 统计，业务上如果想知道不同 queue 的统计，好像没法知道？
Ping @cdjingit

**Comment by cdjingit** [comment]
> hi 有个小问题想问一下 ~
> 为啥不统计每个 queue 的 vars 呀？目前是一个总的 vars 统计，业务上如果想知道不同 queue 的统计，好像没法知道？
> Ping @cdjingit
框架不会统计这么详细，这个可以由业务层面统计的。
