### ISSUE TITLE
使用bthread_setspecific实现thread_local内存一直增长

### ISSUE THREAD

**Issue by corznoc** [apache/incubator-brpc#1441]
**Describe the bug (描述bug)**
通过bthread_setspecific实现bthread local功能，压测的时候，发现内存一直增长，通过页面上brpc提供的heap工具查看，大多是bthread_setspecific使用的。请问有规避的方法吗?

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
期望压测时，内存稳定

**Versions (各种版本)**
OS:centos7
Compiler:g++-9.3.0
brpc:0.9.7
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by corznoc** [comment]
#1438 和这个有点像

**Comment by lorinlee** [comment]
Hi, you can try to call `bthread_getspecific` before `bthread_setspecific`

**Comment by lorinlee** [comment]
已经有对应的issue描述具体问题了，可以参考 #1449 ，这个issue先关掉了，如果有问题可以再打开哈
