### ISSUE TITLE
关于bthread创建和调度的开销？

### ISSUE THREAD

**Issue by rpbear88** [apache/incubator-brpc#1447]
各位好，

我们在一个低负载的原型系统中进行性能测试，发现bthread从被创建到被执行所花的时间基本在10us(CPU主频2.6GHz)。[这个文档](https://github.com/apache/incubator-brpc/blob/master/docs/cn/memory_management.md)提到bthread的创建耗时大约在200ns，所以是否可以认为出现10us的场景并不是创建耗时导致的，而是调度延迟导致的。

我理解可能有两种产生调度延迟的场景：
- 新建的bthread会在本地worker执行，而worker需要先执行在`_rq`中的其他任务，如果这些任务的整体处理延时为10us，就会导致我们新建的bthread产生10us的调度延迟。目前这个实验结果是在使用braft的场景下，在raft逻辑中产生的，具体还待分析可能是哪个函数执行耗时大。但原型系统的压力非常低，仅仅是响应一个4KB的单队列写请求，所以不存在`_rq`被打满的情况
- 新建的bthread被其他worker偷过去执行，可能会产生cache miss/cacheline 同步等性能开销，一般这个work stealing性能开销是多少呢？

**Comment by rpbear88** [comment]
另外，我们很想让所有bthread的调用修改为urgent的原地执行方式，但是braft中部分逻辑对锁的使用导致在这个场景下会死锁。

**Comment by lorinlee** [comment]
Hi @rpbear88 , 如文档所述，bthread创建是比较快的，主要耗时确实是在调度延迟。任务创建后直至被运行也有几个步骤，首先会在当前worker的rq中排队，若其他worker空闲，则会进行work stealing；其他worker可能之前处于挂起睡眠状态，work stealing之前还需要执行唤醒。而work stealing中可能会对多个TaskGroup进行尝试，极端负载下如果尝试多次也会造成很大的overhead，每次work stealing会先偷取某线程的rq，会有原子操作开销，之后会尝试remote_rq会有锁的开销，stealing之后由于cache locality不佳，也会有性能的损失。整体链路延迟可能会有几微秒到几十微秒不等

**Comment by lorinlee** [comment]
另外关于braft的使用方式，可以咨询braft的同学哈

**Comment by jiangdongzi** [comment]
> Hi @rpbear88 , 如文档所述，bthread创建是比较快的，主要耗时确实是在调度延迟。任务创建后直至被运行也有几个步骤，首先会在当前worker的rq中排队，若其他worker空闲，则会进行work stealing；其他worker可能之前处于挂起睡眠状态，work stealing之前还需要执行唤醒。而work stealing中可能会对多个TaskGroup进行尝试，极端负载下如果尝试多次也会造成很大的overhead，每次work stealing会先偷取某线程的rq，会有原子操作开销，之后会尝试remote_rq会有锁的开销，stealing之后由于cache locality不佳，也会有性能的损失。整体链路延迟可能会有几微秒到几十微秒不等

hi, pthread调度开销也时几微秒, 为什么不直接使用pthread线程池呢
