### ISSUE TITLE
这两个全局变量是不是用反了？

### ISSUE THREAD

**Issue by jameseatorange** [apache/incubator-brpc#1450]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/76277223/123644010-921c1380-d857-11eb-8d07-5863972af55b.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
是的，可以提PR修一下哈

**Comment by jameseatorange** [comment]
> 是的，可以提 PR 修一下哈

好，我周末有空提个 PR

**Comment by cdjingit** [comment]
#1477
