### ISSUE TITLE
when will apollo configuration be supported?

### ISSUE THREAD

**Issue by h-zh-cn** [apache/incubator-brpc#1452]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
no

**Describe the solution you'd like (描述你期望的解决方法)**
I need apollo configuration

**Describe alternatives you've considered (描述你想到的折衷方案)**
no

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
Hi, thanks for your issue, but can you provide some detailed information about the apollo configuration?

**Comment by h-zh-cn** [comment]
> Hi, thanks for your issue, but can you provide some detailed information about the apollo configuration?

https://github.com/ctripcorp/apollo

Apollo is a reliable configuration management system. It can centrally manage the configurations of different applications and different clusters. It is suitable for microservice configuration management scenarios.

The server side is developed based on Spring Boot and Spring Cloud, which can simply run without the need to install additional application containers such as Tomcat.

**But there isn't cpp SDK**

**Comment by cdjingit** [comment]
I think we will not support apollo in brpc framwork recently. It is not an essential function for brpc.
