### ISSUE TITLE
rdma 有开源计划吗？

### ISSUE THREAD

**Issue by bystorm** [apache/incubator-brpc#1453]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by bystorm** [comment]
有计划把rdma何如到主干吗？

**Comment by TousakaRin** [comment]
@bystorm 暂时还没有合入计划，rdma的改动有点多容易引入问题，后续可能会考虑增加一个unstable的分支来合入这类patch

**Comment by wwbmmm** [comment]
你好，原来的rdma分支不再维护了，计划将rdma功能合入master：https://github.com/apache/incubator-brpc/pull/1836
