### ISSUE TITLE
Socket::WaitAndReset内存泄露

### ISSUE THREAD

**Issue by wwbmmm** [apache/incubator-brpc#1455]
**Describe the bug (描述bug)**
heap profiling结果：
![image](https://user-images.githubusercontent.com/3894631/124116125-2d53f980-daa1-11eb-8a05-dcb8e541cf81.png)

**To Reproduce (复现方法)**
当Server端连接不稳定的情况下，会频繁触发client端的Socket的CheckHealth->Revive，会多次调用WaitAndReset，引发内存泄露

**Expected behavior (期望行为)**
修复内存泄露

**Versions (各种版本)**
OS:linux
Compiler:gcc8.2
brpc:百度内部版本，看代码，开源版本应该也有类似问题
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
merged, thanks!
