### ISSUE TITLE
Feature rpc_view support setting timeout

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1458]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**
通过gflags设置超时时间

**Describe alternatives you've considered (描述你想到的折衷方案)**
通过gflags设置超时时间

**Additional context/screenshots (更多上下文/截图)**
OS:linux
Compiler:gcc8.2
protobuf:

**Comment by lorinlee** [comment]
merged, thanks!
