### ISSUE TITLE
Feature brpc server Start(PortRange range, const ServerOptions *opt)

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1460]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
实现Start(PortRange range, const ServerOptions *opt);

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
请问这个是用在什么场景的？

**Comment by serverglen** [comment]
> 请问这个是用在什么场景的？�

为了解决端口号被占用的问题，这样的话，不需要用户按个尝试哪个端口可用。

**Comment by wasphin** [comment]
PR 与这个不是一回事吧?  看 PR 中只是添加了一个默认 `IP_ANY` 的接口, 而上面提到的功能本身就是支持的.

**Comment by serverglen** [comment]
> PR 与这个不是一回事吧? 看 PR 中只是添加了一个默认 `IP_ANY` 的接口, 而上面提到的功能本身就是支持的.

#1461 

目前 brpc server 的4个Start函数：

- int Server::Start(const butil::EndPoint& endpoint, const ServerOptions* opt);
- int Server::Start(const char* ip_port_str, const ServerOptions* opt);
- int Server::Start(int port, const ServerOptions* opt);
- int Server::Start(const char* ip_str, PortRange port_range, const ServerOptions *opt);

最后一个支持PortRange，但是需要用户手工传一个 const char* ip_str参数

这个PR 新增了如下函数：
int Server::Start(PortRange port_range, const ServerOptions* opt);
不需要传const char* ip_str参数，这种方式更加方便。
@wasphin @lorinlee
