### ISSUE TITLE
如何让client发送的IO，在同一线程收割

### ISSUE THREAD

**Issue by Pating** [apache/incubator-brpc#1464]
场景描述：
   我们目前以brpc为基础rpc框架开发了一套分布式存储，io流程基本如下：
   KVM虚机 ->  spdk-vring -> **存储驱动（spdk bdev层）** -> 后端分布式存储
      
问题描述：
  spdk本身的IO模型是在同一个reactor线程中进行IO收发的。目前我们的实现是在**存储驱动**中发出异步IO(即在reactor线程中发出IO)，并希望能在reactor线程中直接收割IO。
  但观测发现IO发出后brpc client是在其专有的pthread/bthread里自行IO收割（在约6个线程中触发异步IO的回调函数）。
 
  ![image](https://user-images.githubusercontent.com/3406829/124691907-36185580-df0f-11eb-8067-3f0ef0555b54.png)
 

  这会导致一些问题，如：为了保证存储的稳定性，在高IOPS场景下，我们需要在计算侧额外规划6个cpu绑定收割线程， 浪费cpu资源

问题如下：
  1. brpc是否有方法在非其专有pthread/bthread中进行IO收割（即做到client发送的IO，在同一线程收割）
  2. 是否可以改变IO收割线程的数量，这样至少可以减少需要绑定cpu数量

**Comment by TousakaRin** [comment]
1.  应该是做不到的
2. 可以通过flag `bthread_concurrency' 来调整。

**Comment by Pating** [comment]
> 1. 应该是做不到的
> 2. 可以通过flag `bthread_concurrency' 来调整。

好的，多谢
