### ISSUE TITLE
unstable unittest: test_bvar may failed in linking

### ISSUE THREAD

**Issue by lorinlee** [apache/incubator-brpc#1465]
**Describe the bug (描述bug)**
see https://app.travis-ci.com/github/apache/incubator-brpc/jobs/508012385

**To Reproduce (复现方法)**
can not be reproduced stably

**Expected behavior (期望行为)**
not fail

**Versions (各种版本)**
see CI above

**Additional context/screenshots (更多上下文/截图)**

**Comment by serverglen** [comment]
These unittests really unstable, hope can be fixed early

**Comment by wwbmmm** [comment]
Fixed by #1711
