### ISSUE TITLE
WSL2-Ubuntu20.04 下编译 bRPC 不成功

### ISSUE THREAD

**Issue by jvfan** [apache/incubator-brpc#1469]
**Describe the bug (描述bug)**
WSL2-Ubuntu20.04 下编译 bRPC 不成功，总是提示找不到 BIO_fd_non_fatal_error 函数；

![image](https://user-images.githubusercontent.com/31410192/124874989-f75fc980-dffa-11eb-84dc-39fdfbde3503.png)

**To Reproduce (复现方法)**
1. 安装 openssl、snappy、google-perftools、gtest
    默认会安装 libxxx 到 /usr/local/lib 目录；
    ```
    sudo apt-get install -y libssl-dev
    sudo apt-get install -y libsnappy-dev
    sudo apt-get install -y libgoogle-perftools-dev
    sudo apt-get install -y libgtest-dev
    ```
2. 手动源码编译一些库 gflags、protobuf、leveldb
    默认会安装 libxxx 到 /usr/local/lib 目录，已经验证 protobuf 完全正常；
3. 添加 /usr/local/bin 到环境变量，并确保了以下条件
    –/usr/include 目录中至少存在：
    * openssl/ssl.h
    * gflags/gflags.h

    –/usr/local/lib 目录至少存在：
    * gflags
    * protobuf
    * leveldb
4. 执行 brpc 编译脚本如下：
    ```
    sh config_brpc.sh --headers=/usr/include --libs=/usr/local/lib
    make
    ```

**Expected behavior (期望行为)**
编译通过；

**Versions (各种版本)**
OS: WIN11-WSLg-Ubuntu20.04
Compiler: g++ 9.3.0
brpc: 0.9.7
protobuf: 3.17.3

**Additional context/screenshots (更多上下文/截图)**

> 下面的日志是已经 make 过一次的情况下执行的；

```
➜  brpc sh config_brpc.sh --headers=/usr/include --libs=/usr/local/lib
➜  brpc
➜  brpc make
Linking protoc-gen-mcpack
/usr/bin/ld: libbrpc.a(iobuf.o): in function `butil::IOBuf::cut_multiple_into_SSL_channel(ssl_st*, butil::IOBuf* const*, unsigned long, int*)':
/home/jerry/Public/brpc/src/butil/iobuf.cpp:1022: undefined reference to `BIO_fd_non_fatal_error'
/usr/bin/ld: /home/jerry/Public/brpc/src/butil/iobuf.cpp:1002: undefined reference to `BIO_fd_non_fatal_error'
/usr/bin/ld: libbrpc.a(iobuf.o): in function `butil::IOPortal::append_from_SSL_channel(ssl_st*, int*, unsigned long)':
/home/jerry/Public/brpc/src/butil/iobuf.cpp:1695: undefined reference to `BIO_fd_non_fatal_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:241: protoc-gen-mcpack] Error 1
➜  brpc
➜  brpc grep -rn BIO_fd_non_fatal_error
Binary file src/butil/iobuf.o matches
src/butil/iobuf.cpp:1002:                        && BIO_fd_non_fatal_error(errno) == 1)) {
src/butil/iobuf.cpp:1022:        if (rc <= 0 && BIO_fd_non_fatal_error(errno) == 0) {
src/butil/iobuf.cpp:1695:                        && BIO_fd_non_fatal_error(errno) == 1)) {
Binary file libbrpc.a matches
➜  brpc
```

**Comment by serverglen** [comment]
可能是openssl版本不对，用1.1版本的openssl试试。

**Comment by TousakaRin** [comment]
确认下目录 /usr/local/lib 中是否包含libssl.so 以及 libcrypto.so，如果没有，确认下/usr/lib 是否包含这些so文件, 如果/usr/lib 下包含这些文件，可以通过软链接的方式将他们链接到 /usr/local/lib 下。

**Comment by jvfan** [comment]
> 确认下目录 /usr/local/lib 中是否包含libssl.so 以及 libcrypto.so，如果没有，确认下/usr/lib 是否包含这些so文件, 如果/usr/lib 下包含这些文件，可以通过软链接的方式将他们链接到 /usr/local/lib 下。

谢谢，把所有的依赖项都换成动态库后，编译正常了。
