### ISSUE TITLE
支持自定义Builtin Services访问规则

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1475]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
支持自定义Builtin Services访问规则

Builtin Services其实对查看服务运行状态很有帮助，特别是服务出问题的时候，但是如果线上所有服务都开启Builtin Services也是有风险的。

这种情况下：我们可以仅允许内网ip或者某几个ip有权限访问Builtin Services，当然也可以是其他任何的规则，用户按照自己的需求实现即可，框架需要提供这种能力。

**Comment by cdjingit** [comment]
具体需要做什么样的规则？
目前builtin service的启动可以通过ServerOptions.internal_port来指定一个对外访问受限的端口

**Comment by serverglen** [comment]
> 具体需要做什么样的规则？
> 目前builtin service的启动可以通过ServerOptions.internal_port来指定一个对外访问受限的端口

规则是用户自己实现的，框架只需要提供 "应用" 用户自定义规则 的能力即可。

**Comment by guodongxiaren** [comment]
给option的has_builtin_services设置成false就可以关闭，默认是true。
比如：
```cpp
    brpc::ServerOptions options;
    options.has_builtin_services = false;                                                                                             
    if (server.Start(FLAGS_port, &options) != 0) {
        LOG(ERROR) << "Fail to start EchoServer";
        return -1; 
    }  
```
你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
@serverglen

**Comment by guodongxiaren** [comment]
@cdjingit close了吧

**Comment by wasphin** [comment]
> 给option的has_builtin_services设置成false就可以关闭，默认是true。
> 
> 
> 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> 

这个能支持的场景还是比较有限的，比如无法在运行时配置。

**Comment by guodongxiaren** [comment]
> > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> > 
> > 
> > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> > 
> 
> 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> 

可以啊。你说的运行时不能设置是什么意思？

**Comment by wasphin** [comment]
> > > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> > > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> > 
> > 
> > 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> 
> 可以啊。你说的运行时不能设置是什么意思？

比如通过特定请求开启内置服务？使用完关闭内置服务。

**Comment by guodongxiaren** [comment]
> > > > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> 
> > > > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> 
> > > 
> 
> > > 
> 
> > > 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> 
> > 
> 
> > 可以啊。你说的运行时不能设置是什么意思？
> 
> 
> 
> 比如通过特定请求开启内置服务？使用完关闭内置服务。

那使用前面楼层提到的inner port吧。不过一般不需要针对特定请求开启，这么灵活…

**Comment by wasphin** [comment]
> > > > > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> > 
> > 
> > > > > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> > 
> > 
> > > 
> > 
> > 
> > > 可以啊。你说的运行时不能设置是什么意思？
> > 
> > 
> > 比如通过特定请求开启内置服务？使用完关闭内置服务。
> 
> 那使用前面楼层提到的inner port吧。不过一般不需要针对特定请求开启，这么灵活…

这边服务所在的主机或网络是不受信的，与其他互联网场景可能不同。

**Comment by cdjingit** [comment]
> > > > > > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> > > 
> > > 
> > > > > > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 可以啊。你说的运行时不能设置是什么意思？
> > > 
> > > 
> > > 比如通过特定请求开启内置服务？使用完关闭内置服务。
> > 
> > 
> > 那使用前面楼层提到的inner port吧。不过一般不需要针对特定请求开启，这么灵活…
> 
> 这边服务所在的主机或网络是不受信的，与其他互联网场景可能不同。
你是想禁止在线修改程序配置（gflag，在线profile等），还是想整个内置服务都不暴露？
https://github.com/apache/incubator-brpc/blob/60159fc3f3e13490fb9806ea0a0cb0dcdbda7f7d/src/brpc/builtin/flags_service.cpp#L37
设置这个gflag可以禁止通过内置服务在线修改程序配置，可以开发提供一个内置服务的接口控制这个gflag的设置。

**Comment by wasphin** [comment]
> > > > > > > 给option的has_builtin_services设置成false就可以关闭，默认是true。
> > > > 
> > > > 
> > > > > > > 你可以根据你的系统环境（开发环境、测试环境、生产环境）来指定启用或关闭内置服务。
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > >
> > > > 
> > > > 
> > > > > > 这个能支持的场景还是比较有限的，比如无法在运行时配置。
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > 可以啊。你说的运行时不能设置是什么意思？
> > > > 
> > > > 
> > > > 比如通过特定请求开启内置服务？使用完关闭内置服务。
> > > 
> > > 
> > > 那使用前面楼层提到的inner port吧。不过一般不需要针对特定请求开启，这么灵活…
> > 
> > 
> > 这边服务所在的主机或网络是不受信的，与其他互联网场景可能不同。
>
> 你是想禁止在线修改程序配置（gflag，在线profile等），还是想整个内置服务都不暴露？

整个内置服务都不暴露。

> https://github.com/apache/incubator-brpc/blob/60159fc3f3e13490fb9806ea0a0cb0dcdbda7f7d/src/brpc/builtin/flags_service.cpp#L37
> 
> 设置这个gflag可以禁止通过内置服务在线修改程序配置，可以开发提供一个内置服务的接口控制这个gflag的设置。

如果内置服务的开关也是个 gflag 就基本满足我这边的需求了，但这个和 OP @serverglen  的需求应该不一样。
