### ISSUE TITLE
brpc考虑支持流量染色全链路透传吗

### ISSUE THREAD

**Issue by zzkeln** [apache/incubator-brpc#1479]
brpc考虑支持一些协议例如std协议下的流量染色吗，主要目标是将染色在服务的全链路透传，染色可以是key-value形式的pair对

**Comment by guodongxiaren** [comment]
业务自己实现就可以了，给接口proto增加一个字段，传到每个下游。

**Comment by cdjingit** [comment]
借助brpc rpcz功能可以实现流量染色，每个服务节点可以把这些日志上传到日志分析平台，需要业务做一些适配的开发。

**Comment by wwbmmm** [comment]
如果业务自己实现，需要改所有的业务proto，成本高且不通用
rpcz功能只能传递trace_id/span_id等信息，无法携带更复杂如key-value形式的信息
