### ISSUE TITLE
brpc server 支持统计 error qps

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1482]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
当前 brpc 服务只能看到 error 的总数，没有统计平均 error qps 的 bvar 值。这个指标对服务性能指标观察非常有意义，可以直观的看出服务的健康程度，是否需要扩容。

**Comment by cdjingit** [comment]
eps就是

**Comment by serverglen** [comment]
> eps就是

目前应该只有method级别的eps，缺少server级别的eps
