### ISSUE TITLE
请问是否支持传递span上下文，支持跨越线程

### ISSUE THREAD

**Issue by liujianhua2016** [apache/incubator-brpc#1491]
你好， 我看到之前有对 span上下文，支持跨越线程 的功能支持的计划，但是我拉取最新的代码，似乎还是没有实现改功能，请问后续是否还有这个计划？

这个是之前的开发计划
https://github.com/apache/incubator-brpc/issues/505

**Comment by liujianhua2016** [comment]
太感谢了， 我这就去试试

**Comment by wwbmmm** [comment]
已支持，参考这里说明：
https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpcz.md#%E8%B7%A8bthread%E4%BC%A0%E9%80%92trace%E4%B8%8A%E4%B8%8B%E6%96%87
