### ISSUE TITLE
The relationship between qps and _explore_ratio

### ISSUE THREAD

**Issue by JockerWong** [apache/incubator-brpc#1496]
https://github.com/apache/incubator-brpc/blob/53f6436a63f4b4c23d22b9e07e5d6d9af8af7fe7/src/brpc/policy/auto_concurrency_limiter.cpp#L254

I think it should be "qps >= _ema_max_qps / (1.0 + min_explore_ratio)", that is, when the qps decrease is not obvious, you can continue to increase the explore speed. And when the qps decreases significantly, you need to reduce the explore speed.
I don't know whether my understanding is correct.

**Comment by TousakaRin** [comment]
When your max_concurrency is set too large, we think that latency will increase in most cases and qps will remain near max_qps, so when qps is smaller than the known max_qps(_ema_max_qps), we will try to increase max_concurrency.
