### ISSUE TITLE
butex_wait & remained相关问题

### ISSUE THREAD

**Issue by charyxiao** [apache/incubator-brpc#1497]
butex_wait 函数看代码有几点疑问
1. wait_for_butex 为什么不原地执行？为什么要放到remind里
2. wait_for_butex之后的sched如果切换的bthread上下文的代码断点在task_runner的thread_return = m->fn(m->arg)中，那就不会执行g->_last_context_remained的信息 相反会重新调用g->set_remained，将wait_for_butex冲掉
![image](https://user-images.githubusercontent.com/5407327/126870356-8dfec3bf-a3b2-4cf5-8881-2fb15381ea7c.png)

**Comment by jenrryyou** [comment]
有同样的疑惑。另外如果切换的后的bthread再次调用butex_wait，会不会覆盖task_group的remained回调？

**Comment by jenrryyou** [comment]
对第一点有同样的疑问；
第二点我的理解是：wait_for_butex里直接调用的是`TaskGroup::sched(&g)`，会调度新的`bthread`，一定会从头执行`task_runner`，把之前设置的回调执行；
![image](https://user-images.githubusercontent.com/4698734/127952379-1fc7d2b3-af2f-48ef-9e2a-d23075c77afd.png)

**Comment by charyxiao** [comment]
第二点 调用sched(&g) 不一定是调度新的bthread的 也可能是旧的bthread的 举个更极端的例子 如果没有新的bthread呢

**Comment by ZeroLiu2018** [comment]
> 第二点 调用sched(&g) 不一定是调度新的bthread的 也可能是旧的bthread的 举个更极端的例子 如果没有新的bthread呢

我说一下我的理解，先说第二点：除了 task_runner ,在 sche_to 里面，jump_stack 完成返回后，也会执行 _last_context_remained,也就是说在真正切到另一个 bthread 跑逻辑前，都会执行 _last_context_remained。
然后就是第一点，在第一点之前你可以看看切换 bthread 的逻辑，切换 bthread 之前有个 set_remained, 这个 remianed 的作用是将当前 bthread 放到队列。它也同样不是在原地执行，我想两者的原因是一样的(wait_for_butex 里面同样有将当前 bthread 入队的逻辑): 需要调度出新的 bthread 才能将旧 bthread 入列，否则，stack 切换可能很难处理。

**Comment by ZjuYTW** [comment]
对第一点的解释还有点模糊，楼上的大佬 @ZeroLiu2018 提到需要将本bthread先睡眠再进行入列, 否则会有stack切换的问题。我可以理解成——先将本bthread入列后如果被别的TaskGroup 直接Steal了可能会有奇怪的问题吗？

 然后其实这里我觉得如果这种情况是否可以避免——通过不设置remained而是直接执行butex_wait，因为走到wait_for_butex里面的TaskMeta有两种情况，一种是需要阻塞在butex下面，另一种是发现在同步点的时候实际已经可以拿到锁开始跑了，就可以避免把本bthread yield出去。
