### ISSUE TITLE
rpcz.md 中能否给一个可以真实跳转的地址，它可以直接让用户看到客户端或服务端中rpcz打印的信息

### ISSUE THREAD

**Issue by guzitajiu123** [apache/incubator-brpc#1510]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by TousakaRin** [comment]
通过源码编译example/echo_c++/ 中的例子就可以很快的在本地搭建一个demo
