### ISSUE TITLE
--bthread_concurrency设置的最小限制问题

### ISSUE THREAD

**Issue by HexToString** [apache/incubator-brpc#1513]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**![image](https://user-images.githubusercontent.com/35565423/128964704-980f1cc2-5169-4633-be87-186ce6a88587.png)某些情况下，需要Server端设置并发数量为2
![image](https://user-images.githubusercontent.com/35565423/128964687-1a4dfcee-8844-43a9-ab37-95e21b87b34a.png)

![Uploading image.png…]()**Describe the solution you'd like (描述你期望的解决方法)**
可以看到我们代码中要求--bthread_concurrency 必须设置大于等于types.h头文件中的BTHREAD_MIN_concurrency = 3+1 =4
那意味着用户--bthread_concurrency 传入的数字必须大于等于4.
可否把这个自由度开放给用户呢？允许用户最少设置为2.
因为当用户不设置的时候，并发度为8+1，当用户需要自己设定的时候，用户应该知道自己的需求。

**Describe alternatives you've considered (描述你想到的折衷方案)**
修改src/bthread/types.h文件中的相关地方3+BTHREAD_EPOLL_THREAD_NUM 改为1+BTHREAD_EPOLL_THREAD_NUM。
**Additional context/screenshots (更多上下文/截图)**

**Comment by gydong** [comment]
你遇到的业务场景是什么样子的？ 并发度过小会丧失框架的处理能力，也许有更合适的方案解决你遇到的问题

**Comment by wwbmmm** [comment]
设置为2可能会导致brpc无法正常工作（在开启SSL的情况下，存在两个会阻塞pthread的epoll线程）
