### ISSUE TITLE
brpc如何打开内置服务中的/brpc_metrics

### ISSUE THREAD

**Issue by dylanzhang** [apache/incubator-brpc#1514]
我在bvar的文档中看到，可以通过/brpc_metrics开把bvar采集的变量暴露给Prometheus。
但我在自己的测试中收到报错，“Fail to find method on `/brpc_metrics'”
我也阅读了server.cpp文件中对BuiltinService初始化的代码，发现并未默认启动Prometheus相关的service呀？请问一下大佬们，/brpc_metrics正确的开启办法是什么呢？

brpc version : v0.9.7
compiler : clang++

**Comment by cdjingit** [comment]
试试/metrics呢？ 你可能用的不是最新的版本

**Comment by dylanzhang** [comment]
> 试试/metrics呢？ 你可能用的不是最新的版本

/metrics也是不存在的，版本号是0.9.7，应该是最新的版本了

**Comment by cdjingit** [comment]
你测试的完整的地址是什么样的？

**Comment by dylanzhang** [comment]
> 你测试的完整的地址是什么样的？

curl 127.0.0.1:8067/brpc_metrics

**Comment by zyearn** [comment]
> 我也阅读了server.cpp文件中对BuiltinService初始化的代码，发现并未默认启动Prometheus相关的service呀？

初始化代码在这里：https://github.com/apache/incubator-brpc/blob/master/src/brpc/server.cpp#L494-L497。如果本地没有的话，就是版本问题了

**Comment by dylanzhang** [comment]
> > 我也阅读了server.cpp文件中对BuiltinService初始化的代码，发现并未默认启动Prometheus相关的service呀？
> 
> 初始化代码在这里：https://github.com/apache/incubator-brpc/blob/master/src/brpc/server.cpp#L494-L497 ，如果本地没有的话，就是版本问题了

果然是内部引入的版本和0.9.7有区别，多谢大佬
