### ISSUE TITLE
bthread 没有提供像 pthread_cancel 这样的功能么？

### ISSUE THREAD

**Issue by xdlove** [apache/incubator-brpc#1523]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
目前有 bthread_stop 函数，但是功能貌似无法对齐 pthread_cancel

**Describe the solution you'd like (描述你期望的解决方法)**
是否已经有支持了？

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
bthread_stop目前没有办法满足么

**Comment by serverglen** [comment]
closed，还有问题的话，reopen
