### ISSUE TITLE
[Client] 支持自动重建连接已实现无损发布

### ISSUE THREAD

**Issue by hiberabyss** [apache/incubator-brpc#1530]
在 k8s 场景里，会通过 brpc client 用 service 地址去连接下游的服务，如果使用的是长连接的话，在 service 对应的 pod 发布的时候，还会有请求持续不断地打到旧 pod 里，直到它被完全关闭。

能否提供一个机制让连接每隔几秒就自动重建一下 （类似 nginx 里的 keep_alive 的机制)，这样让 service 里的旧 pod 保存特定的时间就可以实现无损发布。

**Comment by gydong** [comment]
[优雅退出](https://github.com/apache/incubator-brpc/blob/master/docs/cn/server.md#%E5%81%9C%E6%AD%A2)不能满足你的需求？

**Comment by hiberabyss** [comment]
> [优雅退出](https://github.com/apache/incubator-brpc/blob/master/docs/cn/server.md#%E5%81%9C%E6%AD%A2)不能满足你的需求？

不能满足需求，我现在用的就是优雅退出。但因为 k8s 的 service 只能拿到一个 ip 地址，load balance 是由后面的 ipvs 来完成的，对 brpc client 来说只能看到一个 server，也就没法切换到别的 server 。

**Comment by gydong** [comment]
这个场景应该在LB层面加健康检查（比如通过HTTP协议访问/health路径）机制解决，brpc没法绕过LB去做这种支持，也不合理

**Comment by hiberabyss** [comment]
能有办法让 brpc 原生支持 k8s 的 service 么？例如支持 k8s://service-name 之类的形式

**Comment by zyearn** [comment]
目前还没有支持，欢迎内部实现以后给我们提PR
