### ISSUE TITLE
tensorflow中pthread线程池是否生效？

### ISSUE THREAD

**Issue by lfch** [apache/incubator-brpc#1532]
自己写了一个server，其中集成了tensorflow库。如果server的worker线程全都开启了bthread，不知道tensorflow中的pthread pool能否正常运行呢？ 是运行为bthread呢，还是pthread呢？ 谢谢 ！！

**Comment by cdjingit** [comment]
bthread只会被分发到worker线程执行。可以把你场景描述的更具体一点

**Comment by lfch** [comment]
server是一个异步IO的，会开启bthread功能，让接收到的请求直接在bthread中执行。执行过程中，会调用到tensorflow的Session::Run()函数。tensorflow内部有自己的pthread线程池，所以进入到Session::Run()函数之后，会进行并行的计算。我的疑问是server开启了bthread功能的场景下，此时tensorflow内部的并行用的pthread，还是bthread呢？ 
代码在https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/direct_session.cc  中 Status DirectSession::RunInternal()函数中。
<img width="852" alt="截屏2021-08-19 上午10 42 19" src="https://user-images.githubusercontent.com/5698293/129999069-89678794-32d4-4573-b35a-9b27dc30c436.png">

**Comment by chenzhangyi** [comment]
session->Run()会进入tensorflow自己的线程池(和Device有关)

**Comment by congxinbo** [comment]
那brpc的worker线程和tensorflow自己的线程肯定会产生资源竞争吧 怎么去平衡这个关系呢

**Comment by wwbmmm** [comment]
> 那brpc的worker线程和tensorflow自己的线程肯定会产生资源竞争吧 怎么去平衡这个关系呢

不同线程肯定会竞争cpu，确保分配足够多的cpu即可。

**Comment by congxinbo** [comment]
> > 那brpc的worker线程和tensorflow自己的线程肯定会产生资源竞争吧 怎么去平衡这个关系呢
> 
> 不同线程肯定会竞争cpu，确保分配足够多的cpu即可。

机器cpu固定的情况下 如果是高并发请求到server，而server内部又要调用tf去计算  worker对应的线程少了会导致服务阻塞耗时增加 worker对应的线程分配多了 会和tf的线程抢占资源 导致tf计算耗时增加从而导致服务本身的耗时增加
