### ISSUE TITLE
bRPC 在不同的PB版本，比如PB 2.5 和PB 3.8 性能表现

### ISSUE THREAD

**Issue by yujun411522** [apache/incubator-brpc#1540]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/8407293/130963130-0f2f4e18-d67f-4d85-8258-b39e2d09fc3c.png)
![image](https://user-images.githubusercontent.com/8407293/130963160-7c9e1966-397f-4648-88a2-40b99fd00169.png)
在PB 3.8 上为极限QPS在70W不到

而在PB2.5上，极限QPS在90W

想问下bRPC这里有测试过在不同的PB版本下的性能表现吗？

**Comment by yujun411522** [comment]
> 如果差异只有pb的版本，那性能主要的差异也是pb本身吧。可以分别画个火焰图，做个差分火焰图看看cpu diff在哪里

这个是PB 2.5 的火焰图
[bRPC_pb2.5_perf.svg.zip](https://github.com/apache/incubator-brpc/files/7076273/bRPC_pb2.5_perf.svg.zip)

这个是PB 3.8 的火焰图
[pb2.5_to_pb3.8.diff.svg.zip](https://github.com/apache/incubator-brpc/files/7076271/pb2.5_to_pb3.8.diff.svg.zip)

这个是PB 2.5 -> PB 3.8 的差分的火焰图
[bRPC_pb3.8_perf.svg.zip](https://github.com/apache/incubator-brpc/files/7076272/bRPC_pb3.8_perf.svg.zip)

**Comment by chenzhangyi** [comment]
用tcmalloc啥的看下吧，看起来多的就是和malloc相关的，就是pb3的实现里面多了一些内存分配。或者你看下更高版本的protobuf有没有解决这个问题
