### ISSUE TITLE
开启cpu profiler后导出的pdf文件异常简洁

### ISSUE THREAD

**Issue by zhangwenqin01** [apache/incubator-brpc#1543]
**Describe the bug (描述bug)**![image]
以echo_c++ server为例，使用方法：
tools/pprof host:ip/pprof/profile --pdf > output.pdf
获取到的pdf如图所示
[ech0.pdf](https://github.com/apache/incubator-brpc/files/7083462/ech0.pdf)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
 debian 9.13

Compiler: 
bazel 3.0.0

brpc: 
0.9.7

protobuf:
**Additional context/screenshots (更多上下文/截图)**

ps:为了排除是依赖的libtcmalloc_and_profiler.a和libunwind.a的问题，在demo程序上直接链接这两个静态库

按照如下使用方法
pprof ./demo(demo的二进制文件) 127.0.0.1:ip/pprof/profile --pdf > output.pdf 

获取到的pdf文件是正常的，如下图

[output.pdf](https://github.com/apache/incubator-brpc/files/7083464/output.pdf)

**Comment by cdjingit** [comment]
是指没有brpc框架函数的调用关系吗？确定是有流量的？另外bin里的符号都保留了吗？有没有stripped掉？

**Comment by 17336** [comment]
> **Describe the bug (描述bug)**![image] 以echo_c++ server为例，使用方法： tools/pprof host:ip/pprof/profile --pdf > output.pdf 获取到的pdf如图所示 [ech0.pdf](https://github.com/apache/incubator-brpc/files/7083462/ech0.pdf)
> 
> **To Reproduce (复现方法)**
> 
> **Expected behavior (期望行为)**
> 
> **Versions (各种版本)** OS: debian 9.13
> 
> Compiler: bazel 3.0.0
> 
> brpc: 0.9.7
> 
> protobuf: **Additional context/screenshots (更多上下文/截图)**
> 
> ps:为了排除是依赖的libtcmalloc_and_profiler.a和libunwind.a的问题，在demo程序上直接链接这两个静态库
> 
> 按照如下使用方法 pprof ./demo(demo的二进制文件) 127.0.0.1:ip/pprof/profile --pdf > output.pdf
> 
> 获取到的pdf文件是正常的，如下图
> 
> [output.pdf](https://github.com/apache/incubator-brpc/files/7083464/output.pdf)

请问你这个问题解决了吗

**Comment by 17336** [comment]
> 是指没有brpc框架函数的调用关系吗？确定是有流量的？另外bin里的符号都保留了吗？有没有stripped掉？

@cdjingit 我也遇到了这个问题，“bin里的符号都保留了吗”是什么意思，bin运行调用的符号应该会保留吧，不保留怎么找到符号定义呢
