### ISSUE TITLE
如果差异只有pb的版本，那性能主要的差异也是pb本身吧。可以分别画个火焰图，做个差分火焰图看看cpu diff在哪里

### ISSUE THREAD

**Issue by yujun411522** [apache/incubator-brpc#1544]
如果差异只有pb的版本，那性能主要的差异也是pb本身吧。可以分别画个火焰图，做个差分火焰图看看cpu diff在哪里

_Originally posted by @lorinlee in https://github.com/apache/incubator-brpc/issues/1540#issuecomment-906889000_

> 如果差异只有pb的版本，那性能主要的差异也是pb本身吧。可以分别画个火焰图，做个差分火焰图看看cpu diff在哪里

这个是PB 2.5 的火焰图
[bRPC_pb2.5_perf.svg.zip](https://github.com/apache/incubator-brpc/files/7076273/bRPC_pb2.5_perf.svg.zip)

这个是PB 3.8 的火焰图
[bRPC_pb3.8_perf.svg.zip](https://github.com/apache/incubator-brpc/files/7076272/bRPC_pb3.8_perf.svg.zip)

这个是PB 2.5 -> PB 3.8 的差分的火焰图
[pb2.5_to_pb3.8.diff.svg.zip](https://github.com/apache/incubator-brpc/files/7076271/pb2.5_to_pb3.8.diff.svg.zip)

**Comment by cdjingit** [comment]
Duplicate of #1540
