### ISSUE TITLE
brpc可以处理浏览器发过来的cookie吗

### ISSUE THREAD

**Issue by YvesZHI** [apache/incubator-brpc#1562]
有没有个例子能让我学习下？找了很久没能找到这样的例子。就是浏览器发过来的请求里携带了cookie，我应该怎么解析出这个cookie呢

**Comment by serverglen** [comment]
试试从HttpHeader中获取Cookie字段呢？

**Comment by serverglen** [comment]
closed, reopen if you have further ideas.
Thank you for your contributions!
