### ISSUE TITLE
brpc rdma IbvForkInit return not 0

### ISSUE THREAD

**Issue by zhangzhiming865** [apache/incubator-brpc#1568]
**Describe the bug (描述bug)** when tgtd already have iser connection, submodule call IbvForkInit will failed

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

E0927 20:52:10.379448 197900 rdma_helper.cpp:426] Fail to ibv_fork_init: No such file or directory [2]

**Comment by wwbmmm** [comment]
你好，原来的rdma分支不再维护了，计划将rdma功能合入master：https://github.com/apache/incubator-brpc/pull/1836
   可以看看新的rdma实现还有没有问题，如果有问题，可以提新的issue
   这个先close了
