### ISSUE TITLE
brpc 1.0 的 版本什么时候可以正式发布

### ISSUE THREAD

**Issue by yangzhg** [apache/incubator-brpc#1569]
请问brpc 1.0  什么时候可以正式发布，会有正式版本，现在rc 版本可以在线上使用吗？

**Comment by gydong** [comment]
rc 可以线上使用，很多公司的生产环境都在用 1.0 之前的版本。不是说只有1.0 正式版才可以在生产环境中使用

**Comment by yangzhg** [comment]
> rc 可以线上使用，很多公司的生产环境都在用 1.0 之前的版本。不是说只有1.0 正式版才可以在生产环境中使用

多谢 我只是不太清楚 brpc 的rc 是指还要经过测试版本还是受限于apache 的繁杂法办流程而不能发正式版

**Comment by cdjingit** [comment]
> > rc 可以线上使用，很多公司的生产环境都在用 1.0 之前的版本。不是说只有1.0 正式版才可以在生产环境中使用
> 
> 多谢 我只是不太清楚 brpc 的rc 是指还要经过测试版本还是受限于apache 的繁杂发版流程而不能发正式版， 现在哪个版本是最稳定的呢

rc是稳定的版本，目前是apache发版流程导致
