### ISSUE TITLE
DynamicPartitionChannel的客户端访问下游多分库服务时，当多分库中的一个分库服务异常后，客户端无法访问下游其他所有分库服务

### ISSUE THREAD

**Issue by y1825181** [apache/incubator-brpc#1572]
**Describe the bug (描述bug)**
配置如下：
客户端配置
reload_interval_ms: 3000
connect_timeout_ms: 15
timeout_ms: 100
max_retry: 0
load_balancer: rr
fail_limit: 3
serverlist配置
192.168.0.1:8001 0/3
192.168.0.2:8001 1/3
192.168.0.3:8001 2/3
**To Reproduce (复现方法)**
当3分库中的一个服务，例如192.168.0.1:8001服务不可用后，客户端也无法与下游的其他两个分库建立连接
附，当请求压力较大时，会出现该现象。请求压力小时，无该现象出现；
当192.168.0.1:8001服务可用后，客户端可与下游所有分库正常通信
**Expected behavior (期望行为)**
期望提供该问题定位方向，和修复办法
**Versions (各种版本)**
OS: openeuler 20.03
Compiler: gcc 4.8.5
brpc: 0.9.7
protobuf: 3.9.0

**Additional context/screenshots (更多上下文/截图)**
一些错误信息：
![E112]Fail to select channel, Host is down
incubator-brpc-0.9.7/src/brpc/selective_channel.cpp:53] Checking ParallelChannel[3] chan=0x0x557d9961cf30 FakeSocket{id=130 addr=0.0.0.0:0} (0x557d99603a30)
incubator-brpc-0.9.7/src/brpc/selective_channel.cpp:60] Revived ParallelChannel[3] chan=0x0x557d9961cf30 FakeSocket{id=130 addr=0.0.0.0:0} (0x557d99603a30) (Connectable)
并且，偶尔会打印一条这个日志信息（实际设置的fail_limit为3）
![E112]1/1 channels failed, fail_limit=1 [C0][E112]Fail to select server from list:// lb=rr

**Comment by wwbmmm** [comment]
DynamicPartitionChannel要求每个分库至少要有一个可用实例才能提供服务
