### ISSUE TITLE
CentOS 按照文档编译，不通

### ISSUE THREAD

**Issue by Gliushuai** [apache/incubator-brpc#1583]
想问下开发者，这个文档还能编译通过吗，能提供下最新的编译方法，或者依赖的库的版本，比如PB

**Comment by TousakaRin** [comment]
可以把更多上下文贴出来吗，正常按照文档是可以编译的

**Comment by Gliushuai** [comment]
> 可以把更多上下文贴出来吗，正常按照文档是可以编译的

在编译过程,pb少了一个port_def.inc 后缀的文件，发现是yum 安装的protobuf 版本过低，没有这个文件，所以想知道，你们配置的yum库是哪个地址。以及g++的版本是多少。我这边重新配置下环境

**Comment by wasphin** [comment]
应该是 epel 的源，具体依赖及编译参数可以参考下项目 package/rpm 下的 spec 文件。
