### ISSUE TITLE
请问下java客户端如何通过brpc调用c++端的服务，通过protobuf文件

### ISSUE THREAD

**Issue by TuJianwei** [apache/incubator-brpc#1584]
`syntax="proto3";
package example;

option cc_generic_services = true;

message EchoRequest {
      string message = 1;
};

message EchoResponse {
      string message = 1;
};

service EchoService {
      rpc Echo(EchoRequest) returns (EchoResponse);
};`
如果服务端通过C++实现，然后将服务注册到zookeeper上，如何通过java客户端进行调用

**Comment by wwbmmm** [comment]
可以尝试：https://github.com/baidu/brpc-java
