### ISSUE TITLE
controller->ErrorCode cannot set over 256?

### ISSUE THREAD

**Issue by zuoerfeng** [apache/incubator-brpc#1596]
**Describe the bug (描述bug)**
if controller->SetFailed(brpc::ERPCTIMEDOUT, "rpc call timeout");
but controller->ErrorCode() !=  brpc::ERPCTIMEDOUT?

check it , it maybe overflow? ErrorCode cannot > 256

**To Reproduce (复现方法)**
controller->SetFailed(brpc::ERPCTIMEDOUT, "rpc call timeout");
EXPECT_EQ(240, controller.ErrorCode());

**Expected behavior (期望行为)**
controller->SetFailed(brpc::ERPCTIMEDOUT, "rpc call timeout");
EXPECT_EQ(brpc::ERPCTIMEDOUT, controller.ErrorCode());

**Versions (各种版本)**
OS: centos6.5
Compiler:gcc482
brpc: 0.9.7
protobuf:2.5.0

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/22866359/140292547-be92e905-600b-4d37-8a00-e6c03de262e3.png)
![image](https://user-images.githubusercontent.com/22866359/140292596-0a478531-6a41-4f28-bed7-11a65b5b4389.png)

**Comment by wwbmmm** [comment]
测试了一下，master并没有这个问题
