### ISSUE TITLE
brpc有全面升级支持proto3的计划吗

### ISSUE THREAD

**Issue by zjhua68** [apache/incubator-brpc#1602]
用3.6版本的protobuf库生成proto2格式的pb，比生成的proto3格式的pb，在序列化和反序列化性能上大概差45%左右左右
目前市面上用grpc的用户或服务，基本都是proto3格式的pb了，如果考虑切换brpc，性能上基本没啥收益（因为上下游的架构不能统一切换，所以没法换成除pb之外的其他协议）。
brpc后续是否会全面支持proto3呢？

**Comment by guodongxiaren** [comment]
我们工作中用的就是proto3+brpc。一般不需要brpc升级吧。你用proto3编译brpc就行。

**Comment by GOGOYAO** [comment]
> 我们工作中用的就是proto3+brpc。一般不需要brpc升级吧。你用proto3编译brpc就行。

syntax 可以指定为proto3？

**Comment by guodongxiaren** [comment]
> > 我们工作中用的就是proto3+brpc。一般不需要brpc升级吧。你用proto3编译brpc就行。
> 
> 
> 
> syntax 可以指定为proto3？

可以

**Comment by guodongxiaren** [comment]
你不用修改，brpc里面已有的proto。只需要修改你系统中protobuf的版本

**Comment by zjhua68** [comment]
> 你不用修改，brpc里面已有的proto。只需要修改你系统中protobuf的版本

我自己的锅，从grpc切过来的时候service的pb里忘记加“option cc_generic_services = true;”这行参数了
