### ISSUE TITLE
brpc可以并行发多个请求吗

### ISSUE THREAD

**Issue by EngineerAzure** [apache/incubator-brpc#1607]
如题，brpc可以类似于 multi curl那样，同时发多个http请求外部吗？ 这些http请求直接互相独立，没有依赖关系

**Comment by EngineerAzure** [comment]
顶起

**Comment by cdjingit** [comment]
可以，建议先读下文档：https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%8F%91%E8%B5%B7%E8%AE%BF%E9%97%AE

**Comment by EngineerAzure** [comment]
> 可以，建议先读下文档：https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%8F%91%E8%B5%B7%E8%AE%BF%E9%97%AE

谢谢提醒，您指的是文档里写到的“半同步”方式吗？

**Comment by cdjingit** [comment]
> 谢谢提醒，您指的是文档里写到的“半同步”方式吗？

是的
