### ISSUE TITLE
urllib.urlopen().read() 访问http service卡住

### ISSUE THREAD

**Issue by liangwens** [apache/incubator-brpc#1615]
使用python 自带urllib.open("http://").read() 会卡住，拿不到结果，不知道其他人有没有遇到过这种情况

import urllib
urllib.urlopen('http://10.178.8.238:6000/ServerOpsService/ops?info').read()

**Comment by lorinlee** [comment]
可以抓包看看有没有什么线索，卡住的原因可能很多
