### ISSUE TITLE
请问replay采样的rpc_dump参数如何动态设置呢？

### ISSUE THREAD

**Issue by lixinkun** [apache/incubator-brpc#1618]
rpc_dump参数是在程序启动的时候附加的参数吗？
如果程序启动的时候开关是关闭的，请问之后需要如何操作可以在不重启程序的条件下将开关打开呢？
谢谢！~

**Comment by guodongxiaren** [comment]
可以在不停服务的情况下动态开启和关闭。

开启

curl 127.0.0.1:8888/flags/rpc_dump?setvalue=true

关闭
curl 127.0.0.1:8888/flags/rpc_dump?setvalue=false


IP和端口用你brpc服务的。

**Comment by lixinkun** [comment]
试了可以的，非常感谢~！
请问开启rpc_dump之后对服务的性能会有多大影响呢？官方有性能评估数据可以参考下吗？
