### ISSUE TITLE
请问下rpcz的z代表什么意思呢？

### ISSUE THREAD

**Issue by guzitajiu123** [apache/incubator-brpc#1619]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Huixxi** [comment]
这应该是一种用于监控工具，描述运行状态工具等的一种命名方式，rpcz代表的是描述一个rpc过程的运行状态的一个工具，类似的还有grpc的channelz。
