### ISSUE TITLE
按文档进行配置编译，但make之后

### ISSUE THREAD

**Issue by FakerShy** [apache/incubator-brpc#1627]
![0b1eb4db199df25d08040ce6433c114](https://user-images.githubusercontent.com/39550114/144800327-8d7361a2-8472-43e1-9d03-4ab2ec18e8ea.png)

**Comment by FakerShy** [comment]
protocolbuffer用的是3.19.1

**Comment by wwbmmm** [comment]
Hi @FakerShy you can try the latest master branch, #1679 may have resolved this problem

**Comment by sangli00** [comment]
but use protobuf-3.20,this problem is not fix。
