### ISSUE TITLE
cpu profile显示不出来

### ISSUE THREAD

**Issue by wengduo** [apache/incubator-brpc#1628]
将main.cpp里面对象池初始化的代码注释掉后cpu profile可以显示，不注释就显示不了，web页面也没有报任何错误，服务会重启。如果不跑cpu profile，服务处理可以正常处理请求。

**To Reproduce (复现方法)**
我们的对象池占内存比较大，是作为ctx用的，将其存在stack里面，每次请求从里面拿一个，是不是内存过大导致的？能帮解答下吗？谢谢～

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 7.2
Compiler: gcc 4.8.5
brpc: 0.9.7
protobuf: 8.0.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
重启的原因是什么？段错误？

**Comment by wengduo** [comment]
原因找到了，fork后，系统oom了，我这个服务内存占比比较高～

发自我的iPhone
