### ISSUE TITLE
V99 1207 18:47:09.863345  1326 /home/xiaoju/src/brpc/src/brpc/policy/thrift_protocol.cpp:379] version=795373312 doesn't match THRIFT_VERSION=2147549184

### ISSUE THREAD

**Issue by wengduo** [apache/incubator-brpc#1629]
V99 1207 18:47:09.863345  1326 /home/xiaoju/src/brpc/src/brpc/policy/thrift_protocol.cpp:379] version=795373312 doesn't match THRIFT_VERSION=2147549184

**To Reproduce (复现方法)**
thrift 版本是0.9.3和编译brpc是用的一个，为啥报版本不一致，这个是什么原因？

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 7.2
Compiler: gcc 4.8.5
brpc: 0.9.7
protobuf: 8.0.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
Would you please use thrift-0.9.2 for the moment? It works with thrift-0.9.2. 
@kenshinxf Could you help to check this problem? Why is the thrift version hard coded?

**Comment by wengduo** [comment]
我这边使用的是thrift0.9.3

发自我的iPhone

**Comment by kenshinxf** [comment]
@cdjingit it works well on thrift 0.9.2 and 0.9.3, as I remembered it also worked on 0.10.x
@wengduo 0.9.3 确定是没问题的，我在公司的时候线上用的就是这个版本，另外编译的时候请确保引用的头文件的位置不是系统lib下面的
