### ISSUE TITLE
关于各节点数据一致性问题

### ISSUE THREAD

**Issue by cqdjbb** [apache/incubator-brpc#1644]
有这么一个场景：
  有A，B两台服务器节点和一台服务器节点C。 C主要是rpc的消息分发。客户端上来的所有rpc调用通过C调用A或者B节点上的rpc服务(RR轮询模式)。但A，B节点需要数据一致性，如多个客户购买商品时，C负责扣款， 并把扣款成功的消息发送给A，B节点。A，B节点只负责处理发货。

问题：
  1.brpc框架提供file://./nodes.txt中配置节点的广播么。即启动时C把数据发送给A，B节点
  2.新增D节点时，C节应该在什么情况下通知D节点。初步想法是在C对D健康监测时，socket连接上D后发送数据。

期望结果：
   brpc是否有此类机制，或者其他设计思路

![无标题](https://user-images.githubusercontent.com/96334180/146637355-09f54c11-0aab-49a5-bc14-896b0a1f477b.png)

**Comment by chenzhangyi** [comment]
一个方案，C写MQ，AB分别独自订阅。 这个问题不是在RPC层面解决的。

**Comment by cqdjbb** [comment]
> 一个方案，C写MQ，AB分别独自订阅。这个问题不是在RPC层面解决的。

好的,了解
