### ISSUE TITLE
Brpc在protobuf3环境下编译报错问题

### ISSUE THREAD

**Issue by liujp** [apache/incubator-brpc#1673]
**Describe the bug (描述bug)**
环境： brpc release 1.0.0
依赖环境：其中一项是proptobuf3.18

在编译过程中会报错：
![image](https://user-images.githubusercontent.com/11934146/149703998-47f2b713-d587-4c1c-bcf4-a2002ee68f19.png)

查询后发现 protobuf2和protobuf3中， google::protobuf::io::CodedInputStreamAPI发生变化：
PB2中的定义：
![image](https://user-images.githubusercontent.com/11934146/149704165-5885ebd9-5bf9-4f1c-8ae9-a9fd405d681a.png)

PB3中的定义：
![image](https://user-images.githubusercontent.com/11934146/149704196-5181cf65-3ff9-4bbe-9b98-11ec95f26607.png)

请问，如果兼容PB3的话是否可以修改BRPC中的函数调用：
![image](https://user-images.githubusercontent.com/11934146/149704277-72488d1e-03d9-48dd-88ac-0e2a939ed919.png)

修改后是否有什么后续的问题？？

**Comment by lorinlee** [comment]
Hi @liujp , you can try the latest master branch,  #1679 may have resolved this problem
