### ISSUE TITLE
[Question] What if use ConditionVariable in pthread?

### ISSUE THREAD

**Issue by hiberabyss** [apache/incubator-brpc#1674]
当直接在 pthread 线程中使用 bthread 的 ConditionVariable 时， 能正常工作么？

**Comment by serverglen** [comment]
bthread所有接口可在pthread中被调用并有合理的行为，使用bthread的代码可以在pthread中正常执行。
参考：https://github.com/apache/incubator-brpc/blob/master/docs/cn/bthread.md
