### ISSUE TITLE
无法在Ubuntu 21.04 ARM64环境下编译通过

### ISSUE THREAD

**Issue by githubzilla** [apache/incubator-brpc#1675]
**Describe the bug (描述bug)**
无法在Ubuntu 21.04 ARM64环境下编译通过

**To Reproduce (复现方法)**
>sh config_brpc.sh --headers=/usr/include --libs=/usr/lib --cxx=clang++ --cc=clang
>make
./src/butil/time.h:223:11: error: invalid output constraint '=a' in asm
        : "=a" (lo), "=d" (hi)

**Expected behavior (期望行为)**
编译通过

**Versions (各种版本)**
OS: Ubuntu 21.04  5.10.76-linuxkit aarch64
Compiler: Ubuntu clang version 12.0.0-3ubuntu1~21.04.2
brpc: 0.9.7
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![2022-01-17_18-19-51](https://user-images.githubusercontent.com/10080336/149751624-5fa470a8-5ae2-4ecf-bcdd-5b3c644760f1.png)

**Comment by Overcautious** [comment]
请问解决了吗

**Comment by wwbmmm** [comment]
master已支持arm64
