### ISSUE TITLE
使用官方提供的方式访问redis，支持value是二进制数据吗?

### ISSUE THREAD

**Issue by moesakura** [apache/incubator-brpc#1683]
**Describe the bug (描述bug)**
redis中的数据
key是可读字符串
value是protobuf序列化后的数据

> brpc::Controller cntl;
  brpc::RedisRequest req;
  brpc::RedisResponse rsp;
  req.AddCommand("GET hello");
  channel_.CallMethod(NULL, &cntl, &req, &rsp, NULL /*done*/);

类似这种请求得到的结果A  和 使用redis-plus-plus 获取到的结果B
使用base64之后对比一下 发现不一致
结果B是符合预期的

请问一下是我用的方法不对吗?

**Comment by wwbmmm** [comment]
value的内容可以发下吗？比如base64后的内容

**Comment by moesakura** [comment]
brpc
1.is_nil
2.CAEQABoAIgAoADAAOgBCAEoAUABaAGIAaABwAHgAgAEAiAEAkAEAmgEAoAEAqAEAsgEAuAEAwAEAyAEA0AEA2AEA4AEA6AEA8AEA+AEAgAIAiAIAlQIAAAAAoAIAqAIAsAIAuAIA6gIGSGVhbHRo6gIJTGFyZ2VHYW1l+gIGMTAwNjM2+gIGMTAwNjM4ggMGMTAwNjM2ggMGMTAwNjM4igMGMTAwNjM2igMGMTAwNjM4yh8EbWFsZQ==
3.CAEYxhi6BggSBlF5cXB3WOISBgoEOTI2MYIZERgMKF8wgMKFkLsvSgQzMTQy
4.CAIYpjm6BggSBldLQk11cOISBgoEMzY2M4IZExj+DiikATDY9ffqyC9KBDczMzQ=


redis-plus-plus
1.EicKBmhYVXFkUBIGdGhFV0N2EgZpdk1CUE0YASCcqQQoxgMw8/+RjQY=
2.CAEaBUNoaW5hmgEHQ2hpbmVzZdABAeABGQ==
3.CAEYxTm6BggSBnZTYlVEZeISBgoEMTEwMYIZDBi51AMoCEoENzM2NQ==
4.CAIY/Dq6BggSBllBQldJSOISBgoEOTM3N4IZChhxKCVKBDc1NDg=

**Comment by moesakura** [comment]
> brpc 1.is_nil 2.CAEQABoAIgAoADAAOgBCAEoAUABaAGIAaABwAHgAgAEAiAEAkAEAmgEAoAEAqAEAsgEAuAEAwAEAyAEA0AEA2AEA4AEA6AEA8AEA+AEAgAIAiAIAlQIAAAAAoAIAqAIAsAIAuAIA6gIGSGVhbHRo6gIJTGFyZ2VHYW1l+gIGMTAwNjM2+gIGMTAwNjM4ggMGMTAwNjM2ggMGMTAwNjM4igMGMTAwNjM2igMGMTAwNjM4yh8EbWFsZQ== 3.CAEYxhi6BggSBlF5cXB3WOISBgoEOTI2MYIZERgMKF8wgMKFkLsvSgQzMTQy 4.CAIYpjm6BggSBldLQk11cOISBgoEMzY2M4IZExj+DiikATDY9ffqyC9KBDczMzQ=
> 
> redis-plus-plus 1.EicKBmhYVXFkUBIGdGhFV0N2EgZpdk1CUE0YASCcqQQoxgMw8/+RjQY= 2.CAEaBUNoaW5hmgEHQ2hpbmVzZdABAeABGQ== 3.CAEYxTm6BggSBnZTYlVEZeISBgoEMTEwMYIZDBi51AMoCEoENzM2NQ== 4.CAIY/Dq6BggSBllBQldJSOISBgoEOTM3N4IZChhxKCVKBDc1NDg=
> 
> redis 1.b"\x12'\n\x06hXUqdP\x12\x06thEWCv\x12\x06ivMBPM\x18\x01 \x9c\xa9\x04(\xc6\x030\xf3\xff\x91\x8d\x06" 2.b'\x08\x01\x1a\x05China\x9a\x01\x07Chinese\xd0\x01\x01\xe0\x01\x19' 3.b'\x08\x01\x18\xc59\xba\x06\x08\x12\x06vSbUDe\xe2\x12\x06\n\x041101\x82\x19\x0c\x18\xb9\xd4\x03(\x08J\x047365' 4.b'\x08\x02\x18\xfc:\xba\x06\x08\x12\x06YABWIH\xe2\x12\x06\n\x049377\x82\x19\n\x18q(%J\x047548'

**Comment by moesakura** [comment]
> value的内容可以发下吗？比如base64后的内容

brpc
1.is_nil
2.CAEQABoAIgAoADAAOgBCAEoAUABaAGIAaABwAHgAgAEAiAEAkAEAmgEAoAEAqAEAsgEAuAEAwAEAyAEA0AEA2AEA4AEA6AEA8AEA+AEAgAIAiAIAlQIAAAAAoAIAqAIAsAIAuAIA6gIGSGVhbHRo6gIJTGFyZ2VHYW1l+gIGMTAwNjM2+gIGMTAwNjM4ggMGMTAwNjM2ggMGMTAwNjM4igMGMTAwNjM2igMGMTAwNjM4yh8EbWFsZQ==
3.CAEYxhi6BggSBlF5cXB3WOISBgoEOTI2MYIZERgMKF8wgMKFkLsvSgQzMTQy
4.CAIYpjm6BggSBldLQk11cOISBgoEMzY2M4IZExj+DiikATDY9ffqyC9KBDczMzQ=

redis-plus-plus
1.EicKBmhYVXFkUBIGdGhFV0N2EgZpdk1CUE0YASCcqQQoxgMw8/+RjQY=
2.CAEaBUNoaW5hmgEHQ2hpbmVzZdABAeABGQ==
3.CAEYxTm6BggSBnZTYlVEZeISBgoEMTEwMYIZDBi51AMoCEoENzM2NQ==
4.CAIY/Dq6BggSBllBQldJSOISBgoEOTM3N4IZChhxKCVKBDc1NDg=

redis
1.b"\x12'\n\x06hXUqdP\x12\x06thEWCv\x12\x06ivMBPM\x18\x01 \x9c\xa9\x04(\xc6\x030\xf3\xff\x91\x8d\x06"
2.b'\x08\x01\x1a\x05China\x9a\x01\x07Chinese\xd0\x01\x01\xe0\x01\x19'
3.b'\x08\x01\x18\xc59\xba\x06\x08\x12\x06vSbUDe\xe2\x12\x06\n\x041101\x82\x19\x0c\x18\xb9\xd4\x03(\x08J\x047365'
4.b'\x08\x02\x18\xfc:\xba\x06\x08\x12\x06YABWIH\xe2\x12\x06\n\x049377\x82\x19\n\x18q(%J\x047548'

**Comment by cdjingit** [comment]
用的是那个method？贴下设置RedisRequest的代码？二进制字符串格式化造成了截断？
参考 https://github.com/apache/incubator-brpc/blob/master/src/brpc/redis.h#L61

**Comment by moesakura** [comment]
> 用的是那个method？贴下设置RedisRequest的代码？二进制字符串格式化造成了截断？ 参考 https://github.com/apache/incubator-brpc/blob/master/src/brpc/redis.h#L61

本来想提供单测的... 在验证的过程中发现了是我自己的问题
如果db不是0 每次请求都需要select一次
之前我只在初始化的时候select了一次

> req.AddCommand("select %s", db.c_str());
req.AddCommand("GET %s", key.c_str());


是否有更优雅的写法?

**Comment by wwbmmm** [comment]
> 

这个写法是没问题的

**Comment by moesakura** [comment]
> > 
> 
> 这个写法是没问题的

好的，谢谢
