### ISSUE TITLE
LoadBalancerWithNaming::Init LOG(FATAL) prevent return -1

### ISSUE THREAD

**Issue by hcoona** [apache/incubator-brpc#1684]
The `LOG(FATAL)` would cause abort which prevents returning an error to the user for error handling.

https://github.com/apache/incubator-brpc/blob/2c98d0a49312c02b6208e842cf23a164a1bba5ce/src/brpc/details/load_balancer_with_naming.cpp#L36-L43

**Comment by cdjingit** [comment]
naming service配置的不对，贴下channel.Init()的代码呢？

**Comment by wwbmmm** [comment]
Do you mean that "LOG(FATAL)" causes abort so "return -1" will not be executed?

**Comment by hcoona** [comment]
@cdjingit 我补充一下背景。这个问题是这样的，本地的 SD 配置有错误，或者别的什么原因，此时拿到的 server 列表是空的。我们希望能够感知到这一问题，做一些清理再退出。目前的实现有这样 2 种可能：

1. 直接 `LOG(FATAL)` core 掉，这个不太好，我们还想做点事情
2. 设置 `log_succeed_without_server` 忽略掉这个错误，这个也不好，我们的请求都会卡住，我们希望能够识别出这个问题并进行一些处理

**Comment by guodongxiaren** [comment]
glog的fatal日志，就是会导致core的。这里可以改成error级别。我之前也提过类似的PR #1415

**Comment by wwbmmm** [comment]
看了下百度内部版本这块已经改成ERROR级别了，而且是2017年8月改的，不知道为啥没有同步到社区

**Comment by hcoona** [comment]
哈哈，这个说法要让社区伤心了
