### ISSUE TITLE
Is there any particular reason for vendoring snappy?

### ISSUE THREAD

**Issue by hcoona** [apache/incubator-brpc#1688]
I notice that butil vendor snappy under https://github.com/apache/incubator-brpc/tree/1.0.0/src/butil/third_party/snappy

bRPC strongly depends on LevelDB, and LevelDB almost always compiles with snappy in production. Is there any particular reason using a vendor snappy instead of depending on a common snappy library?

The vender snappy is v1.1.3 which is pretty old. The newer versions contains many optimizations & bugfixes.

**Comment by wwbmmm** [comment]
I guess it's because snappy's codebase is small and doesn't require frequent upgrades.

**Comment by hcoona** [comment]
Many projects provide 2 ways for linking external dependencies:

1. link against user-provided dependencies
2. link against bundled dependencies

I think the vendors are good for would not cause conflict while bad for users controlling the dependencies.

It would be appreciate if there was any flag to control it.

**Comment by wwbmmm** [comment]
If you need that flag you can submit a PR, that's welcome. : )
