### ISSUE TITLE
[Bazel Build Error] Fail to build with new bazel version 4.2

### ISSUE THREAD

**Issue by hiberabyss** [apache/incubator-brpc#1689]
**Describe the bug (描述bug)**
使用 bazel 4.2 版本编译的时候会报错。

**To Reproduce (复现方法)**
直接编译的时候会有下面的 error：
![image](https://user-images.githubusercontent.com/2898670/151644590-4646a5cf-6da0-4467-b369-af4e9471e6ea.png)

在注释掉对应的 flag 之后，会有下面的 error：

![image](https://user-images.githubusercontent.com/2898670/151644669-85999a5f-8ca3-46bf-99f6-4a8436979aef.png)

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
看起来是bazel版本太高不兼容，可以试试这个PR：#1657
