### ISSUE TITLE
RDMA分支里面的block_pool.cc的thread_atexit会造成内存泄漏

### ISSUE THREAD

**Issue by zhangzhiming865** [apache/incubator-brpc#1699]
**Describe the bug (描述bug)**
RDMA分支里面的block_pool.cc的thread_atexit可能与其他的thread_atexit先后对tls_idle_list链表操作造成内存泄漏，如果block_pool.cc的thread_atexit先执行，而其他的thread_atexit后执行，并且其他的thread_atexit调用内存释放的函数，则会造成内存泄漏。
**To Reproduce (复现方法)**
创建pthread，申请block_pool里面的内存，并注册atexit释放内存，然后退出pthread，反复执行多次。
**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by zhangzhiming865** [comment]
rdma_memory_pool_tls_cache_num 设置成0也会触发内存泄漏。

**Comment by wwbmmm** [comment]
你好，原来的rdma分支不再维护了，计划将rdma功能合入master：https://github.com/apache/incubator-brpc/pull/1836
可以看看新的rdma实现还有没有问题，如果有问题，可以提新的issue
这个先close了
