### ISSUE TITLE
RDMA分支socket.cpp _read_buf.copy_to(tmp, rdma::HELLO_LENGTH)会越界，buf长度不够

### ISSUE THREAD

**Issue by zhangzhiming865** [apache/incubator-brpc#1700]
**Describe the bug (描述bug)**

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by serverglen** [comment]
> **Describe the bug (描述bug)**
> 
> **To Reproduce (复现方法)**
> 
> **Expected behavior (期望行为)**
> 
> **Versions (各种版本)** OS: Compiler: brpc: protobuf:
> 
> **Additional context/screenshots (更多上下文/截图)**

多谢反馈，应该改成
`
  char tmp[rdma::MAGIC_LENGTH];
  _read_buf.copy_to(tmp, rdma::MAGIC_LENGTH);
`
有兴趣的话可以提个PR，修下这个问题。

**Comment by serverglen** [comment]
多谢反馈，应该改成这样：
```c++
  char tmp[rdma::MAGIC_LENGTH];
  _read_buf.copy_to(tmp, rdma::MAGIC_LENGTH);
```
有兴趣的话可以提个PR修下这个问题。

**Comment by zhangzhiming865** [comment]
> 

https://github.com/apache/incubator-brpc/issues/1699 这个issue看一下？

**Comment by serverglen** [comment]
> > 
> 
> #1699 这个issue看一下？

这个我研究下。

**Comment by wwbmmm** [comment]
你好，原来的rdma分支不再维护了，计划将rdma功能合入master：https://github.com/apache/incubator-brpc/pull/1836
可以看看新的rdma实现还有没有问题，如果有问题，可以提新的issue
这个先close了
