### ISSUE TITLE
https://brpc.apache.org 主页文档内跳转连接故障

### ISSUE THREAD

**Issue by litao3rd** [apache/incubator-brpc#1701]
**Describe the bug (描述bug)**
https://brpc.apache.org 这个主页中的文档，文档内的跳转链接基地址错误，导致所有文档内以及文档间的跳转都有故障无法直接跳转。

**To Reproduce (复现方法)**
https://brpc.apache.org/docs/overview/ 直接访问这个页面中的 URL 链接即可复现

**Expected behavior (期望行为)**
恢复跳转

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by serverglen** [comment]
@Huixxi

**Comment by Huixxi** [comment]
好的，感谢反馈，这个我近期修复一下。

**Comment by litao3rd** [comment]
赞 响应很快～ 我没有找到文档代码库 所以在这里提了 issue 方便的话麻烦给个文档代码库的地址，我 star 一下

PS：
我看文档里说基于 brpc 的 hadoop-rpc 即将开源 不知道这个是否有时间表之类的信息 或者已经开源了但是我没找到地址

**Comment by Huixxi** [comment]
> 赞 响应很快～ 我没有找到文档代码库 所以在这里提了 issue 方便的话麻烦给个文档代码库的地址，我 star 一下
> 
> PS： 我看文档里说基于 brpc 的 hadoop-rpc 即将开源 不知道这个是否有时间表之类的信息 或者已经开源了但是我没找到地址

https://github.com/apache/incubator-brpc-website

**Comment by Huixxi** [comment]
现已修复Overview中英文页面，及部分文档页面中的文档连接跳转问题，预计下周会合入上线。由于文档迁移导致的链接跳转问题还在许多页面存在。。工作量比较大，后续会随发现随修复，也希望社区同学可以在这个问题上做贡献~

**Comment by Huixxi** [comment]
现在可以直接在文档的repo中提issue了 https://github.com/apache/incubator-brpc-website/issues

**Comment by litao3rd** [comment]
确认问题已经解决，这个 issue 我 close 了。
