### ISSUE TITLE
brpc访问grpc server

### ISSUE THREAD

**Issue by wyz997** [apache/incubator-brpc#1702]
有个小问题，在example中的例子中，如果grpc的服务不是直接监听在端口，而是类似于 0.0.0.0:50051/sayhello
Brpc client有办法设置并访问这个服务吗

**Comment by ehds** [comment]
client直接使用http协议？

**Comment by wyz997** [comment]
> client直接使用http协议？

我看文档，访问grpc的话，protocol应该设置为“h2:grpc”吧。那如何再设置http？

**Comment by wwbmmm** [comment]
cntl.http_request().uri().set_path("/sayhello")
这样？
