### ISSUE TITLE
请问：Bthread 可以独立出来用么？  可以单独编译成一个库 或者 源码是很独立的部分?

### ISSUE THREAD

**Issue by triump2020** [apache/incubator-brpc#1707]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
目前没有单独拆分的计划哈
