### ISSUE TITLE
DoublyBufferedData 死锁问题

### ISSUE THREAD

**Issue by zwkno1** [apache/incubator-brpc#1713]
代码如下：

```
class A{
DoublyBufferedData<std::unique_ptr<brpc::Channel>> channel;

void do_request() {
    butil::DoublyBufferedData<std::unique_ptr<brpc::Channel>>::ScopedPtr c;
    channel.Read(&c);
    c->CallMethod(nullptr, &cntl, &req, &resp, nullptr);
}
};
```
调用do_request函数的时候会导致死锁，我猜是CallMethod会导致携程切换，导致同一个线程锁了多次double buffer的thread local 锁。

**Comment by TousakaRin** [comment]
DoublyBufferedData的[基本工作原理](https://github.com/apache/incubator-brpc/blob/master/docs/cn/lalb.md#doublybuffereddata)是为每个线程都设置一把锁，ScopedPtr用RAII的方式管理了这个per thread的锁，你的例子里，在临界区中发起了rpc。brpc中，锁内rpc属于未定义行为（大概率会造成死锁）。

建议把std::unique_ptr<brpc::Channel> 换成 std::shared_ptr<brpc::Channel>：
```
std::shared_ptr<brpc::Channel> chan;
{
     butil::DoublyBufferedData<std::unique_ptr<brpc::Channel>>::ScopedPtr c;
     channel.Read(&c);
     chan = c;
}
chan->CallMethod(...);
```

**Comment by wwbmmm** [comment]
DoublyBufferedData<std::unique_ptr<brpc::Channel>> 也改成 DoublyBufferedData<std::shared_ptr<brpc::Channel>> 吧
否则无法统一引用计数，可能会出现重复释放

**Comment by cdjingit** [comment]
closed掉了，还有疑问，reopen。
