### ISSUE TITLE
Why is the public function 'bvar::Variable::count_exposed' not designed to be thread-safe

### ISSUE THREAD

**Issue by stefanlin1993** [apache/incubator-brpc#1715]
**Describe the solution you'd like (描述你期望的解决方法)**
maybe lock 

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/97238184/157231781-d2fa6577-0afc-445c-89f2-6303b4d4c404.png)

**Comment by wwbmmm** [comment]
get_var_maps() returns an array with multiple VarMapWithLock, each has a lock, there's no global lock. 
Maybe it was designed for performance, the count result is not accurate, it is used in Variable::list_exposed() to reserve a vector.

**Comment by serverglen** [comment]
closed, if have any other problems, reopen
