### ISSUE TITLE
rdma 中iobuf转sglist 过程出现bug导致进入死循环，线程busy

### ISSUE THREAD

**Issue by mengmayang** [apache/incubator-brpc#1720]
**Describe the bug (描述bug)**
在实践过程中发现，某个iobuf中有一个ref的offset指向一个block的结尾8160，长度为0，这个时候调用cutn将出现问题：rdma_endpoint.cpp line 733-739

进程通过gcore保留，如果需要，可以提供

**To Reproduce (复现方法)**
偶现

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/16302568/158173615-5696c9ae-07b9-4dae-97b1-f0d4d42f6c30.png)

**Comment by wwbmmm** [comment]
你好，原来的rdma分支不再维护了，计划将rdma功能合入master：https://github.com/apache/incubator-brpc/pull/1836
可以看看新的rdma实现还有没有问题，如果有问题，可以提新的issue
这个先close了
