### ISSUE TITLE
请问brpc client是否能够察觉服务端的快速重启？

### ISSUE THREAD

**Issue by hujianxin** [apache/incubator-brpc#1722]
我的需求是，客户端察觉到server端重启过的时候，做一些清理工作。多谢。

**Comment by hujianxin** [comment]
@cdjingit 好主意，这是一个利用非rpc的机制来实现的，请问rpc有办法做到吗？多谢多谢

**Comment by serverglen** [comment]
> 

可以实现一个内置服务，返回server的启动后到现在的运行时间，client端定时轮询调用内置服务。

**Comment by wwbmmm** [comment]
在response pb里加个字段，返回server启动时间？

**Comment by hujianxin** [comment]
@cdjingit @serverglen @wwbmmm 多谢建议，我感觉在response pb里面加入server启动时间是一个非常棒的主意，谢谢。
