### ISSUE TITLE
编译报错-google::FlagRegisterer::FlagRegisterer

### ISSUE THREAD

**Issue by sangli00** [apache/incubator-brpc#1732]
**Describe the bug (描述bug)**
Centos7.8  把GCC升级到7.5版本 
编译brpc，gflags,leveldb,protobuffer都是编译的动态库。

> Linking protoc-gen-mcpack
g++ -o protoc-gen-mcpack -I./src -I/usr/include/ -I/usr/local/include/ -L/usr/lib64 -L/usr/local/lib -L/usr/local/lib64 -std=c++0x -Xlinker "-(" src/idl_options.pb.cc src/mcpack2pb/generator.o libbrpc.a -Wl,-Bstatic -lprotobuf -lprotoc -Wl,-Bdynamic -Xlinker "-)" -lpthread -lssl -lcrypto -ldl -lz -lrt -lgflags -lleveldb
> Copying to output/lib
libbrpc.a(logging.o)：在函数‘__static_initialization_and_destruction_0’中：
/data/build_mysql_8.0/brpc/src/butil/logging.cc:126：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/butil/logging.cc:1471：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
libbrpc.a(variable.o)：在函数‘bvar::dumping_thread(void*)’中：
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:705：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:709：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:714：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:719：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:723：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
libbrpc.a(variable.o)：在函数‘__static_initialization_and_destruction_0’中：
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:674：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:675：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:677：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:679：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:680：对‘google::FlagRegisterer::FlagRegisterer<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:825：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:827：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:829：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:831：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
/data/build_mysql_8.0/brpc/src/bvar/variable.cpp:833：对‘google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))’未定义的引用
libbrpc.a(gflag.o)：在函数‘bvar::GFlag::get_value[abi:cxx11]() const’中：
/data/build_mysql_8.0/brpc/src/bvar/gflag.cpp:81：对‘google::GetCommandLineOption(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*)’未定义的引用
libbrpc.a(gflag.o)：在函数‘bvar::GFlag::set_value(char const*)’中：
/data/build_mysql_8.0/brpc/src/bvar/gflag.cpp:88：对‘google::SetCommandLineOption[abi:cxx11](char const*, char const*)’未定义的引用
collect2: 错误：ld 返回 1
make: *** [protoc-gen-mcpack] 错误 1

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
成功

**Versions (各种版本)**
OS:Centos7.8
Compiler:GCC 7.5
brpc:最新release
protobuf:3.13.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
gflags改成静态链接的试试？

**Comment by sangli00** [comment]
> gflags改成静态链接的试试？

是不是brpc不支持动态库

**Comment by sangli00** [comment]
> Linking protoc-gen-mcpack
g++ -o protoc-gen-mcpack -I./src -I/usr/include/ -I/usr/local/include/ -L/usr/local/lib -L/usr/local/lib64 -std=c++0x -Xlinker "-(" src/idl_options.pb.cc src/mcpack2pb/generator.o libbrpc.a -Wl,-Bstatic -lgflags -lprotobuf -lprotoc -Wl,-Bdynamic -Xlinker "-)" -lpthread -lssl -lcrypto -ldl -lz -lrt -lleveldb -D_GLIBCXX_USE_CXX11_ABI=0
src/mcpack2pb/generator.o：在函数‘google::protobuf::internal::StringTypeTraits::Get(int, google::protobuf::internal::ExtensionSet const&, std::string const&)’中：
/usr/local/include/google/protobuf/extension_set.h:1077：对‘google::protobuf::internal::ExtensionSet::GetString(int, std::string const&) const’未定义的引用
src/mcpack2pb/generator.o：在函数‘google::protobuf::io::Printer::PrintInternal(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >*, char const*)’中：
/usr/local/include/google/protobuf/io/printer.h:304：对‘google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)’未定义的引用
/usr/local/include/google/protobuf/io/printer.h:304：对‘google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)’未定义的引用
/usr/local/include/google/protobuf/io/printer.h:304：对‘google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)’未定义的引用
/usr/local/include/google/protobuf/io/printer.h:304：对‘google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)’未定义的引用
/usr/local/include/google/protobuf/io/printer.h:304：对‘google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)’未定义的引用
src/mcpack2pb/generator.o:/usr/local/include/google/protobuf/io/printer.h:304: 跟着更多未定义的参考到 google::protobuf::io::Printer::Print(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, char const*)
src/mcpack2pb/generator.o:(.data.rel.ro._ZTVN9mcpack2pb16McpackToProtobufE[_ZTVN9mcpack2pb16McpackToProtobufE]+0x28)：对‘google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::string const&, google::protobuf::compiler::GeneratorContext*, std::string*) const’未定义的引用
collect2: 错误：ld 返回 1
make: *** [protoc-gen-mcpack] 错误 1
[root@vm10-0-0-152 incubator-brpc-1.0.0]#

gflags改成静态库protobuf这块就过不去了

**Comment by sangli00** [comment]
**gflags**
[root@vm10-0-0-152 build]# nm -CA lib/libgflags.a |grep "RegisterFlagValidator"
lib/libgflags.a:gflags.cc.o:0000000000004930 T google::RegisterFlagValidator(bool const*, bool (*)(char const*, bool))
lib/libgflags.a:gflags.cc.o:0000000000004980 T google::RegisterFlagValidator(double const*, bool (*)(char const*, double))
lib/libgflags.a:gflags.cc.o:0000000000004940 T google::RegisterFlagValidator(int const*, bool (*)(char const*, int))
lib/libgflags.a:gflags.cc.o:0000000000004950 T google::RegisterFlagValidator(unsigned int const*, bool (*)(char const*, unsigned int))
lib/libgflags.a:gflags.cc.o:0000000000004960 T google::RegisterFlagValidator(long const*, bool (*)(char const*, long))
lib/libgflags.a:gflags.cc.o:0000000000004970 T google::RegisterFlagValidator(unsigned long const*, bool (*)(char const*, unsigned long))
lib/libgflags.a:gflags.cc.o:0000000000004990 T google::RegisterFlagValidator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*, bool (*)(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))

静态库中，也有cxx11的函数

**protobuf**
[root@vm10-0-0-152 protobuf-3.13.0]# nm -AC ./src/.libs/libprotobuf.a |grep "GetString"
./src/.libs/libprotobuf.a:extension_set.o:00000000000085d4 T google::protobuf::internal::ExtensionSet::GetString(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const
静态库中也有GetString函数的定义啊


**Makefile**
CPPFLAGS+=-DBTHREAD_USE_FAST_PTHREAD_MUTEX -D_GLIBCXX_USE_CXX11_ABI=0 -D__const__= -D_GNU_SOURCE -DUSE_SYMBOLIZE -DNO_TCMALLOC -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -D__STDC_CONSTANT_MACROS -DNDEBUG -DBRPC_REVISION=\"$(shell ./tools/get_brpc_revision.sh .)\"

还是编译不过去。。

**Comment by wwbmmm** [comment]
> ABI问题 已经fix。

怎么解决的？分享一下？

**Comment by wasphin** [comment]
C++ 11 string 相关的 ABI 问题出现好多次了。典型的常见问题。

**Comment by willamhou** [comment]
> ABI问题 已经fix。

怎么解决的？我也遇到了。 ABI的设置都设置成零了，还是报错

**Comment by wasphin** [comment]
是否设置为 0 取决于是否所有依赖的模块是否也都设置为 0 了，关键在于统一，都设置为 1 或 0 都是可以正常编译链接的。
