### ISSUE TITLE
网络断开自动重连问题

### ISSUE THREAD

**Issue by yz-cyz** [apache/incubator-brpc#1733]
channel的两端网络突然中断后，client发送的request，持续报E1008，而没有重新连接

我们遇到的问题是网络中断后， 健康检查好像并没有生效，比如A -> B , 断网后很长一段时间内， A发给B的请求，还是会写入到socket的发送缓冲区（最少持续写入了10s以上）， 导致断网恢复时B突然收到大量请求。

看log， 10分钟后， 所有的请求还是会报E1008 超时错误， 而不是 E112 (Not connected to xxx)，

配置：health_check_interval = 3, health_check_timeout_ms = 500。

版本：0.9.7

**Comment by wwbmmm** [comment]
健康检查是基于连接的，这种情况应该是连接没有断开，brpc没有收到内核的通知，认为连接还是可用的，所以继续写数据，表现为超时。

**Comment by yz-cyz** [comment]
@wwbmmm 那健康检查什么情况下才会重新连接呢，，我们这种情况，只要关闭连接重新创建连接就能避免， 但是业务侧没法重连。
怎么能够配置健康检查10s未收到答复就重连吗？

**Comment by wwbmmm** [comment]
可以尝试启动这里说的可选的熔断策略：
https://github.com/apache/incubator-brpc/blob/master/docs/cn/circuit_breaker.md
