### ISSUE TITLE
parallel_channel 的优化

### ISSUE THREAD

**Issue by 0x007004** [apache/incubator-brpc#1738]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

否

**Describe the solution you'd like (描述你期望的解决方法)**

这里的controller接受了使用方设置一些rpc相关的参数：
https://github.com/apache/incubator-brpc/blob/4b0b239111f1afdfd8e1bd5cf4c87bc95666751d/src/brpc/parallel_channel.cpp#L144

在使用parallel_channel时，如果没有设置call_mapper，表示request是完全相同的，在调用CallMethod时，先进行request的序列化，后面在构造SubDone时（在ApplyClientSettings的同时），使用已经序列化好的request直接给Controller的_request_buf赋值（这里如果改造成一个shared_ptr)可以减少很多次重复的工作， 在request比较复杂的时候可以节约一些cpu，降低一些耗时，这么做是可以的吗？ 

**Describe alternatives you've considered (描述你想到的折衷方案)**

无

**Additional context/screenshots (更多上下文/截图)**

controller：
https://github.com/apache/incubator-brpc/blob/4b0b239111f1afdfd8e1bd5cf4c87bc95666751d/src/brpc/controller.h#L774

**Comment by wwbmmm** [comment]
有没有可能存在这种场景，ParallelChannel的不同子Channel的协议不同，导致序列化的结果不能复用？

**Comment by 0x007004** [comment]
不同协议看代码应该还好， 数据主要就是_request_buf
- 唯一被读取的地方是“pack_request“，直接附加到发送到iobuf后面,和协议无关。
![image](https://user-images.githubusercontent.com/13299372/163514937-06b10355-5384-44a7-beba-70493e8a2be3.png)

- 唯一被写入的地方是"serialize_request"，这里和压缩算法相关，但是在parallel_channel的使用中，只有一个controller，不同子channel会ApplyClientSettings，压缩算法在这里是可以被统一的。

不过这样逻辑就复杂了， 主要现在有个多分片的场景，分片数太多了，才想扣这一点点的性能

**Comment by 0x007004** [comment]
close
