### ISSUE TITLE
设置超时没有生效为啥？

### ISSUE THREAD

**Issue by xianshangyouling** [apache/incubator-brpc#1746]
Master_Stub stub(_master_client.get());
brpc::Controller cntl;
cntl.set_timeout_ms(200);
int64_t start = butil::gettimeofday_ms();
stub.sync_meta(&cntl, &sync_request, &sync_response, NULL);
int64_t end = butil::gettimeofday_ms();
std::cout << "cost:" << end - start << std::endl;

这样设置超时时间，但有时会卡住几分钟，请问为啥没有生效呢？

**Comment by serverglen** [comment]
是不是其他地方有pthread锁？把bthread底层的worker给hang住了

**Comment by xianshangyouling** [comment]
看了前后代码，没有锁

**Comment by xianshangyouling** [comment]
> 是不是其他地方有pthread锁？把bthread底层的worker给hang住了

看了前后代码，没有锁

**Comment by jamesge** [comment]
看看服务的负载是不是太高了，以至于rpc阻塞结束后bthread重新运行要等待

**Comment by xianshangyouling** [comment]
> 看看服务的负载是不是太高了，以至于rpc阻塞结束后bthread重新运行要等待

看了一下，好像就是这个原因导致的，非常感谢

**Comment by xianshangyouling** [comment]
> 是不是其他地方有pthread锁？把bthread底层的worker给hang住了

感谢大佬
