### ISSUE TITLE
用ubuntu22.04 gcc11.2 cmake3.21编译，报以下错误

### ISSUE THREAD

**Issue by zhoucheng2021** [apache/incubator-brpc#1748]
/usr/include/x86_64-linux-gnu/sys/cdefs.h:314:60: error: macro "__has_attribute" requires an identifier
  314 | #if __GNUC_PREREQ (2,5) || __glibc_has_attribute (__const__)

**Comment by ehds** [comment]
https://github.com/apache/incubator-brpc/issues/1693

**Comment by wwbmmm** [comment]
https://github.com/apache/incubator-brpc/pull/1783 已合入master
