### ISSUE TITLE
对端重启后，客户端报错Reached timeout

### ISSUE THREAD

**Issue by vinllen** [apache/incubator-brpc#1756]
**Describe the bug (描述bug)**
对端服务端重启后，某些情况情况下客户端会报错Reached timeout，有时候又是报错EOF（符合预期）。毕竟tcp断开了，服务端会发一个RST包，从而客户端直接EOF。
因为我们配置的超时时间比较久，所以导致了对端进程退出后，等到超时才感知到（Reached timeout），我们希望业务能够立刻感知到。
不知道是否因为我们参数配置的问题？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
某些情况是什么情况，网络有丢包情况吗？

**Comment by vinllen** [comment]
如果brpc本身没有bug的话，看起来只有可能是最后回复的RST包丢包了。
但看起来，我们有3个客户端，位于3台主机上，服务端重启后，3个客户端报错都有Reached timeout，这就比较奇怪，理论上不应该同时都有问题。
