### ISSUE TITLE
integer division issue in CircuitBreaker

### ISSUE THREAD

**Issue by sunhs** [apache/incubator-brpc#1758]
https://github.com/apache/incubator-brpc/blob/c75d53a62c181db0aec300f41787c0c0786c69d0/src/brpc/circuit_breaker.cpp#L95

With  `_max_error_percent` as an integer and less or equal to 100, it seems that the right hand side will always be either `_window_size` or `0`, which may causes a bug.

**Comment by wwbmmm** [comment]
The execution order is first `_window_size * _max_error_percent`
then  `/ 100`

**Comment by sunhs** [comment]
@wwbmmm I got it. Thanks
