### ISSUE TITLE
What's the behavior of SendRpcResponse in memory constrained env?

### ISSUE THREAD

**Issue by amosbird** [apache/incubator-brpc#1761]
It seems `SendRpcResponse` contains heap allocations (`butil::IOBuf::append`) which returns `-1` if malloc fails. This error code is silently dropped when building response. Do we have defined behavior when response is partially built and sent back to client?

ref:

https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/baidu_rpc_protocol.cpp#L222-L229

btw, can we mark `SendRpcResponse` as **noexcept** ?

**Comment by wwbmmm** [comment]
The append function is void, it will not return -1: 
`void append(const Movable& other);`
https://github.com/apache/incubator-brpc/blob/master/src/butil/iobuf.h#L206

**Comment by amosbird** [comment]
@wwbmmm Thank you for the quick response. I was referring to this `append` https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/baidu_rpc_protocol.cpp#L83 .

**Comment by wwbmmm** [comment]
> @wwbmmm Thank you for the quick response. I was referring to these two `append` calls. https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/baidu_rpc_protocol.cpp#L83-L87

It is better to check return code for these two `append` calls. But in practice, we rarely encounter `append` failures.

**Comment by amosbird** [comment]
> It is better to check return code for these two append calls.

I guess the answer is UB then :)

> But in practice, we rarely encounter append failures.

Memory allocation failures are always rare. However, well-defined applications are required to handle it properly. This is especially true since brpc identifies itself as an industrial-grade RPC framework.
