### ISSUE TITLE
brpc作为客户端与go-grpc服务端通信经过Nginx负载均衡后，brpc无法解析数据了

### ISSUE THREAD

**Issue by xihaishibei** [apache/incubator-brpc#1769]
**Describe the bug (描述bug)**
1.协议类型是 h2:grpc
2.没有Nginx的时候是正常的，加了Nginx后，就不行了
incubator-brpc-1.1.0/src/brpc/policy/http2_rpc_protocol.cpp:450] Too large frame length=4740180 max=16384
3.改brpc源码里面default frame大小为：MAX_OF_MAX_FRAME_SIZE 后，又出现如下错误：
![image](https://user-images.githubusercontent.com/13553842/170823788-38c7f8b9-d621-4c3c-b2b4-50a10d81c512.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos 7.9
Compiler: gcc 4.8.5
brpc:1.1.0
protobuf:3.17.3

**Additional context/screenshots (更多上下文/截图)**

**Comment by xihaishibei** [comment]
用了ssl证书

**Comment by runrunrun-go** [comment]
请问下这个怎么解决的呢，遇到了同样的问题

**Comment by xihaishibei** [comment]
我们把Nginx的负载均衡由7层配置成了4层，就解决了

**Comment by xihaishibei** [comment]
> 请问下这个怎么解决的呢，遇到了同样的问题

我们把Nginx的负载均衡由7层配置成了4层，就解决了
