### ISSUE TITLE
server端的 health check path 支持 restful mapping

### ISSUE THREAD

**Issue by zengkui** [apache/incubator-brpc#1780]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
client针对http server做健康检查，有时是依赖下游结点的一个标志文件，比如nginx里就经常会touch
 status.html 作为心跳标志文件。 当用brpc来替换这个http服务的时候，好像健康检查只能是/health 
为了迁移不影响上下游模块，这个访问路径希望能支持restful mapping

**Describe the solution you'd like (描述你期望的解决方法)**
1.   在server.cpp里添加一个gflag变量，获取restful mapping
2.  重载AddBuiltinService方法，支持传入option。 demo如下:
```cpp
    if (!FLAGS_restful_mapping_health_check_path.empty()) {
      LOG(INFO) << "health check path " << FLAGS_restful_mapping_health_check_path;
      ServiceOptions options;
      options.restful_mappings = FLAGS_restful_mapping_health_check_path;
      // override AddBulitinService, add restfull mappings to options
      if (AddBuiltinService(new (std::nothrow) HealthService, &options)) {
        LOG(ERROR) << "Fail to add HealthService";
        return -1;
      }
    } else if (AddBuiltinService(new (std::nothrow) HealthService)) {
        LOG(ERROR) << "Fail to add HealthService";
        return -1;
    }
```

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
不用AddBuiltinService，自己用AddService添加一个服务来输出健康检查信息也可以吧，而且可以自定义输出的内容。

**Comment by zengkui** [comment]
> 不用AddBuiltinService，自己用AddService添加一个服务来输出健康检查信息也可以吧，而且可以自定义输出的内容。

似乎确实是这样，是我想复杂了。 谢谢。
