### ISSUE TITLE
[Protobuf 解析 IOBuf] Protobuf 解析IOBuf 数据错误

### ISSUE THREAD

**Issue by LionelDong** [apache/incubator-brpc#1792]
**Describe the bug (描述bug)**
测试代码为/example/http_c++
Protobuf 文件为：
![image](https://user-images.githubusercontent.com/7533395/173015012-cad94b2c-1eb6-4c89-9a90-711a095a537c.png)

想解析通过post请求发送到server端的json数据，于是在示例代码中新增如下行
![image](https://user-images.githubusercontent.com/7533395/173015196-e8fa76a0-90f7-4e59-a187-a2edc4b3342c.png)
输出信息如下：
![image](https://user-images.githubusercontent.com/7533395/173015309-fda34986-5b3b-4096-976b-5ba4a1cc24e4.png)
第一个箭头部分是直接输出的request_attachment();
第二个箭头是通过protobuf 解析数据后又序列化输出的内容；

请求命令如下：
`curl -H "Content-Type:application/json" -X POST -d '{"domains": ["admin", "passwd"]}' http://127.0.0.1:8010/HttpService/Echo`

**Expected behavior (期望行为)**
正确解析request_attachment()中的domains 列表数据；

**Versions** 
OS: ubuntu20.04
Compiler: Ubuntu clang version 15.0.0-++20220606091511+5018a5dcbe70-1~exp1~20220606091601.535
brpc: 1.1.0
protobuf: 3.0.0

**Comment by jamesge** [comment]
protobuf自带的方法是解析不了json的，[json2pb/json_to_pb.h](https://github.com/apache/incubator-brpc/blob/master/src/json2pb/json_to_pb.h)下有提供转化的接口

**Comment by LionelDong** [comment]
tks
