### ISSUE TITLE
brpc server启动get_value core了

### ISSUE THREAD

**Issue by helloqingbing** [apache/incubator-brpc#1793]
**Describe the bug (描述bug)**
(gdb) bt
#0  0x0000000000000001 in ?? ()
#1  0x00007f2c5876b338 in get_value (this=<optimized out>, this=<optimized out>) at ./src/bvar/passive_status.h:140
#2  bvar::detail::ReducerSampler<bvar::PassiveStatus<double>, double, bvar::detail::AddTo<double>, bvar::detail::MinusFrom<double> >::take_sample (
    this=0x7f2c504355a8) at ./src/bvar/detail/sampler.h:137
#3  0x00007f2c5876dda3 in bvar::detail::SamplerCollector::run (this=0x7f2c5042b080) at src/bvar/detail/sampler.cpp:169
#4  0x00007f2c5876eb29 in bvar::detail::SamplerCollector::sampling_thread (arg=<optimized out>) at src/bvar/detail/sampler.cpp:110
#5  0x00007f2c59c76ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007f2c53e788dd in clone () from /lib64/libc.so.6

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
brpc server启动的时候直接core了

**Versions (各种版本)**
OS:5.4.42-200.el7.x86_64
Compiler:gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
brpc: 1.1-release
protobuf: 0.12.0

**Additional context/screenshots (更多上下文/截图)**
	linux-vdso.so.1 =>  (0x00007fffb25f9000)
	libjemalloc.so.2 => /data/redkv/kv-0/replicator/libs/libjemalloc.so.2 (0x00007f3f81aa5000)
	libgflags.so.2.1 => /data/redkv/kv-0/replicator/libs/libgflags.so.2.1 (0x00007f3f81884000)
	libglog.so.0 => /data/redkv/kv-0/replicator/libs/libglog.so.0 (0x00007f3f81655000)
	libevent-2.0.so.5 => /lib64/libevent-2.0.so.5 (0x00007f3f8140d000)
	libthrift-0.12.0.so => /data/redkv/kv-0/replicator/libs/libthrift-0.12.0.so (0x00007f3f8113b000)
	libthriftnb-0.12.0.so => /data/redkv/kv-0/replicator/libs/libthriftnb-0.12.0.so (0x00007f3f80f20000)
	librocksdb.so.6.11 => /data/redkv/kv-0/replicator/libs/librocksdb.so.6.11 (0x00007f3f80678000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3f8045c000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f3f801ea000)
	libboost_system.so.1.76.0 => /data/redkv/kv-0/replicator/libs/libboost_system.so.1.76.0 (0x00007f3f7ffe8000)
	libbrpc.so => /data/redkv/kv-0/replicator/libs/libbrpc.so (0x00007f3f7ed75000)
	libprotobuf.so.8 => /data/redkv/kv-0/replicator/libs/libprotobuf.so.8 (0x00007f3f7ea63000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f3f7e84d000)
	libPocoNetSSL.so.64 => /data/redkv/kv-0/replicator/libs/libPocoNetSSL.so.64 (0x00007f3f7e609000)
	libPocoNet.so.64 => /data/redkv/kv-0/replicator/libs/libPocoNet.so.64 (0x00007f3f7e2d5000)
	libPocoCrypto.so.64 => /data/redkv/kv-0/replicator/libs/libPocoCrypto.so.64 (0x00007f3f7e09c000)
	libPocoUtil.so.64 => /data/redkv/kv-0/replicator/libs/libPocoUtil.so.64 (0x00007f3f7de26000)
	libPocoJSON.so.64 => /data/redkv/kv-0/replicator/libs/libPocoJSON.so.64 (0x00007f3f7dbd3000)
	libPocoFoundation.so.64 => /data/redkv/kv-0/replicator/libs/libPocoFoundation.so.64 (0x00007f3f7d7be000)
	libPocoXML.so.64 => /data/redkv/kv-0/replicator/libs/libPocoXML.so.64 (0x00007f3f7d505000)
	libarrow.so.700 => /data/redkv/kv-0/replicator/libs/libarrow.so.700 (0x00007f3f7b8d8000)
	libparquet.so.700 => /data/redkv/kv-0/replicator/libs/libparquet.so.700 (0x00007f3f7b3a4000)
	libzstd.so.1 => /data/redkv/kv-0/replicator/libs/libzstd.so.1 (0x00007f3f7b154000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f3f7ae4d000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f3f7ab4b000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3f7a935000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f3f7a567000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f3f81d26000)
	libcrypto.so.1.1 => /data/redkv/kv-0/replicator/libs/libcrypto.so.1.1 (0x00007f3f7a085000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f3f79e7d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f3f79c79000)
	libsnappy.so.1 => /lib64/libsnappy.so.1 (0x00007f3f79a73000)
	liblz4.so.1 => /data/redkv/kv-0/replicator/libs/liblz4.so.1 (0x00007f3f79851000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f3f79604000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f3f7931b000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f3f79117000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f3f78ee4000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f3f78a81000)
	libleveldb.so.1 => /data/redkv/kv-0/replicator/libs/libleveldb.so.1 (0x00007f3f7882d000)
	libprotoc.so.8 => /data/redkv/kv-0/replicator/libs/libprotoc.so.8 (0x00007f3f78553000)
	libbrotlienc.so.1 => /data/redkv/kv-0/replicator/libs/libbrotlienc.so.1 (0x00007f3f782c6000)
	libbrotlidec.so.1 => /data/redkv/kv-0/replicator/libs/libbrotlidec.so.1 (0x00007f3f780b9000)
	libbrotlicommon.so.1 => /data/redkv/kv-0/replicator/libs/libbrotlicommon.so.1 (0x00007f3f77e99000)
	libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3f77c89000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f3f77a79000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f3f77875000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f3f7765b000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3f77434000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f3f771d2000)

**Comment by jamesge** [comment]
这是偶发还是必现？那个PassiveStatus是你们用到的还是brpc自带的？

**Comment by helloqingbing** [comment]
偶发的，PassiveStatus是brpc自带的

**Comment by wwbmmm** [comment]
可能是因为sampler线程启动过快，有些全局变量还没初始化导致的。
百度内部版本在sampler线程启动时加上了10ms的延迟时间，来避免这个问题

**Comment by Huixxi** [comment]
#1863

**Comment by Huixxi** [comment]
现在相关修复已经合入master了，可以再试下
