### ISSUE TITLE
Go-grpc client get EOF error

### ISSUE THREAD

**Issue by EAHITechnology** [apache/incubator-brpc#1811]
# BUG report 
I'm using the go-grpc client, it returns when the return body is too large. 
I used the following configuration：
```
InitialConnWindowSize = 1GB
MaxRecvMsgSize = 32MB
MaxSendMsgSize =32 MB
```

But I got the result as below:
```
rpc error: code = Internal desc = unexpected EOF
```

# Reproduce
When response is bigger. 1MB in my act.

# Expected behavior
Normal request according to my setup.

**Comment by EAHITechnology** [comment]
When we set WithInitialWindowSize and WithInitialConnWindowSize,it won't be wrong.This is so weird, it doesn't seem to fit the logic of grpc at the moment

solution:

grpc.WithInitialConnWindowSize(...)
grpc.WithInitialWindowSize(...)

**Comment by zyearn** [comment]
Currently you need to pass a big value to WithInitialConnWindowSize and WithInitialWindowSize as a workaround. This is because before brpc sends back response, it will check it the client's remaining window is enough. In your case, response was too big so the check failed.

**Comment by EAHITechnology** [comment]
> Currently you need to pass a big value to WithInitialConnWindowSize and WithInitialWindowSize as a workaround. This is because before brpc sends back response, it will check it the client's remaining window is enough. In your case, response was too big so the check failed.

probably not.I have some new information such as:
- brpc received RST.
- grpc client executes closeStream Function. (As if the http/2 flow control implementations of brpc and grpc are different?) The data obtained by grpc is larger than its flow control size.The error just happened.
