### ISSUE TITLE
考虑引入一个 clang format 文件 格式化代码？

### ISSUE THREAD

**Issue by ZeroLiu2018** [apache/incubator-brpc#1815]
现在看起来没有固定的格式化风格(还是我没看到？)，这样本地开发的时候不敢 format，有考虑引入一个 clang format 吗，用工具来做统一的格式化，方便点。

**Comment by serverglen** [comment]
遵守 [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) 即可

**Comment by serverglen** [comment]
closed
