### ISSUE TITLE
Fail to build in Ubuntu 20.04 + GCC 11.2.0

### ISSUE THREAD

**Issue by Sigma711** [apache/incubator-brpc#1816]
**Describe the bug (描述bug)**
CMake output the error:
```
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.22/Modules/FindThreads.cmake:238 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:148 (find_package)


-- Configuring incomplete, errors occurred!
```

**To Reproduce (复现方法)**
Maybe we should insert something into CMakeLists.txt:30 like this:
```
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
set(CMAKE_HAVE_THREADS_LIBRARY 1)
set(CMAKE_USE_WIN32_THREADS_INIT 0)
set(CMAKE_USE_PTHREADS_INIT 1)
set(THREADS_PREFER_PTHREAD_FLAG ON)
```
Or we can delete CMakeLists.txt:148:
```
find_package(Threads REQUIRED)
```

**Expected behavior (期望行为)**
I hope it will never fail in this environment when building.

**Versions (各种版本)**
OS: Ubuntu 20.04 X86_64
Compiler: GCC 11.2.0
brpc: master && rdma && release-1.1
protobuf: 3.12.4

**Comment by skyitachi** [comment]
I have meet with same problem

**Comment by wasphin** [comment]
This is duplicate to #1693, cmake fail to find pthread as the simple compile test failed, which is caused by the nil defined `__const__`.
