### ISSUE TITLE
【编译报错】

### ISSUE THREAD

**Issue by willamhou** [apache/incubator-brpc#1833]
**Describe the bug (描述bug)**
   
![image](https://user-images.githubusercontent.com/8574759/178475662-c8b15859-43ac-42ba-bff2-a63f46ff13cd.png)

**To Reproduce (复现方法)**
 git clone https://github.com/apache/incubator-brpc.git
 git checkout -b release-1.1 origin/release-1.1

**Expected behavior (期望行为)**
make success

**Versions (各种版本)**
OS: WSL Ubuntu18.04
Compiler: gcc 7.5 g++7.5 
![image](https://user-images.githubusercontent.com/8574759/178475930-09ba5ab9-5242-4471-b8af-caef411fafd0.png)

brpc: release1.1
protobuf: 3.8.0
![image](https://user-images.githubusercontent.com/8574759/178476006-a690552d-df36-4a59-bf1b-f1d73fb85199.png)

**Additional context/screenshots (更多上下文/截图)**
Makefile 的CXXFlags中增加了-D_GLIBCXX_USE_CXX11_ABI=0参数.
![image](https://user-images.githubusercontent.com/8574759/178476222-1704d725-46e6-479a-8aae-07dc5a95033b.png)

gflgas 手工编译

**Comment by wwbmmm** [comment]
编译gflags的时候也加上-D_GLIBCXX_USE_CXX11_ABI=0了吗？

**Comment by willamhou** [comment]
> 编译gflags的时候也加上-D_GLIBCXX_USE_CXX11_ABI=0了吗？
刚刚不记得加没加了。重新加了一下，又编译了下brpc。报错和前面一样。
![image](https://user-images.githubusercontent.com/8574759/178488044-e468403a-5574-4e1c-a334-493bd0e2b7d7.png)

**Comment by wasphin** [comment]
印象中 ubuntu 18.04 中 7.5 编译器，系统安装的库都禁用了c++11abi，但编译器默认编译选项是打开的。

**Comment by willamhou** [comment]
> gflags 编译完有没有安装？
都是make install得，日志是显示装上了。现在报protobuf得事情了

**Comment by willamhou** [comment]
gflags 
![image](https://user-images.githubusercontent.com/8574759/178636017-65198b52-b3da-4e40-b84e-fba870717aff.png)

![Uploading image.png…]()

**Comment by wasphin** [comment]
`protoc-gen-mcpack` master 上最近刚改了一个 Makefile 中编译参数未生效的问题，release-1.1 应该没这个修正，可以换 master 试试。

**Comment by willamhou** [comment]
> `protoc-gen-mcpack` master 上最近刚改了一个 Makefile 中编译参数未生效的问题，release-1.1 应该没这个修正，可以换 master 试试。
> 
> #1824

我试一下。BTW 我找了大概是3年的版本编译了下，重新编译了下leveldb, 整个就正常compile 了。

**Comment by willamhou** [comment]
> `protoc-gen-mcpack` master 上最近刚改了一个 Makefile 中编译参数未生效的问题，release-1.1 应该没这个修正，可以换 master 试试。
> 
> #1824
master，从日志里看是带上-D_GLIBCXX_USE_CXX11_ABI=0.  结果仍旧是报错的
![image](https://user-images.githubusercontent.com/8574759/178647154-2fbb9771-d9b5-4d38-af83-aa108c48078d.png)

**Comment by willamhou** [comment]
发现了新问题
1. master分支下，直接执行cmake -B build && cmake --build build -j6，会报错。
![image](https://user-images.githubusercontent.com/8574759/178706772-0efb4b5f-d836-463a-9b5b-f0d702815bb2.png)

2. 当新建build目录，并将CMakeList.txt及config.h.in拷贝进build目录下，会报GFLAGS_NAMESPACE错.
![image](https://user-images.githubusercontent.com/8574759/178707102-d5ab7045-0153-4b56-873c-660084fd6db3.png)

3. 不使用"cmake -B build && cmake --build build -j6", 使用mkdir bld && cd bld && cmake .. && make是可以编译的

**Comment by willamhou** [comment]
update  config_brpc.sh的方式可以正常编译了.

**Comment by wasphin** [comment]
> 发现了新问题
> 
> 1. master分支下，直接执行cmake -B build && cmake --build build -j6，会报错。
> 2. 当新建build目录，并将CMakeList.txt及config.h.in拷贝进build目录下，会报GFLAGS_NAMESPACE错.

cmake 就不是这么用的，没必要拿一个错误的尝试说有问题...

> 3. 不使用"cmake -B build && cmake --build build -j6", 使用mkdir bld && cd bld && cmake .. && make是可以编译的

**Comment by willamhou** [comment]
> > 发现了新问题
> > 
> > 1. master分支下，直接执行cmake -B build && cmake --build build -j6，会报错。
> > 2. 当新建build目录，并将CMakeList.txt及config.h.in拷贝进build目录下，会报GFLAGS_NAMESPACE错.
> 
> cmake 就不是这么用的，没必要拿一个错误的尝试说有问题...
> 
> > 3. 不使用"cmake -B build && cmake --build build -j6", 使用mkdir bld && cd bld && cmake .. && make是可以编译的
文档上是这么写的。
![image](https://user-images.githubusercontent.com/8574759/178741733-bdf530b7-5a2e-4c1a-a6e0-fd756c5b33a5.png)

**Comment by willamhou** [comment]
> > 发现了新问题
> > 
> > 1. master分支下，直接执行cmake -B build && cmake --build build -j6，会报错。
> > 2. 当新建build目录，并将CMakeList.txt及config.h.in拷贝进build目录下，会报GFLAGS_NAMESPACE错.
> 
> cmake 就不是这么用的，没必要拿一个错误的尝试说有问题...
> 
> 稍后更新 cmake 相关编译文档。
> 
> > 3. 不使用"cmake -B build && cmake --build build -j6", 使用mkdir bld && cd bld && cmake .. && make是可以编译的

我可以正确的使用cmake来编译。只不过顺手尝试文档的方式发现他是不work的

**Comment by willamhou** [comment]
> `-B` 选项是在 3.13+ 的版本引入的, Ubuntu 18.04 中还是 3.10, 不支持该选项, 文档已更新.

Get. Thx, 感谢解答。另外是否需要一个官方编译镜像？我可以提供centos 和 ubuntu的

**Comment by wasphin** [comment]
使用的场景通常应该不是标准化的场景，如果和运行环境不符的话，编译镜像适用性就没那么大了，毕竟是要集成在用户应用中编译的。只是测试用的话也可以考虑提供几个常用发行版的安装包，开发用还是建议自己编一遍，即便趟一遍坑我觉得也是有益的。
