### ISSUE TITLE
实现自动化检查发布结果

### ISSUE THREAD

**Issue by serverglen** [apache/incubator-brpc#1839]
用脚本实现自动化[检查发布结果](https://github.com/apache/incubator-brpc/blob/master/community/release_cn.md#%E6%A3%80%E6%9F%A5%E5%8F%91%E5%B8%83%E7%BB%93%E6%9E%9C)

**Comment by wasphin** [comment]
Skywalking 只检查了授权部分，还需要支持类似自动下载发布包，校验 sha512，验证签名以及必要的其他文件内容的检查。
