### ISSUE TITLE
protobuf 3.21.2  编译失败

### ISSUE THREAD

**Issue by bailongxian** [apache/incubator-brpc#1841]
**Describe the bug (描述bug)**
protobuf 3.21.2  编译失败，该版本的protobuf在Message中加了一个纯虚函数Message* New(Arena* arena) const override = 0;
NsheadMessage继承自该类，当前brpc版本为实现该函数

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
编译成功

**Versions (各种版本)**
OS:
ubuntu 20.04
Compiler:
gcc 10
brpc:
protobuf:
3.21.2 

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
你好，请问brpc用的是哪个版本呢？ #1679 应该已经修复了这个问题，可以更新到1.1.0版本或者master分支试试
