### ISSUE TITLE
butil::IOBuf中block占用的内存没有被释放

### ISSUE THREAD

**Issue by JackyChen-Kuang** [apache/incubator-brpc#1845]
我用Postman对服务端进行http请求时在Body中带了一个文件，通过butil::Controller::request_attchment()获取到Body中的文件数据并使用butil::IOBuf变量储存，后来文件读写完成后respond了消息回去，发现request_attchment()中内存没有被释放掉，有什么方法可以释放这些block占用的内存。
![image](https://user-images.githubusercontent.com/82799271/179709784-7fc7ff78-b14b-4afc-8b6f-8f41e57e46a5.png)

**Comment by JackyChen-Kuang** [comment]
![image](https://user-images.githubusercontent.com/82799271/179710523-f3c3e195-3402-4c4a-8531-11393e9ccdd6.png)

**Comment by JackyChen-Kuang** [comment]
传输了一个120MB的文件，下载完后就一直占用这部分内存了，除非再次请求一个小一点的文件空间才能不占用这么多
![image](https://user-images.githubusercontent.com/82799271/179710738-f94fa734-6daa-404f-84bd-b82dc5df31ed.png)

**Comment by wwbmmm** [comment]
> ![image](https://user-images.githubusercontent.com/82799271/179710523-f3c3e195-3402-4c4a-8531-11393e9ccdd6.png)

这个new出来的IOBuf用完有delete吗？

**Comment by JackyChen-Kuang** [comment]
> > ![image](https://user-images.githubusercontent.com/82799271/179710523-f3c3e195-3402-4c4a-8531-11393e9ccdd6.png)
> 
> 这个new出来的IOBuf用完有delete吗？

这个buf是个引用类型，全文是
``` c
butil::IOBuf &buf = new butil::IOBuf(contrikker->request_attachment)
```
试过delete buf还有一些释放内存的函数都没办法释放它

**Comment by wwbmmm** [comment]
IOBuf底层的block在释放时是不会归还给系统的，而是放在一个池子里，后续新建block的时候可以复用。所以delete buf是无法释放这部分内存的。
