### ISSUE TITLE
自定义内置bvar的名称，如qps、latency

### ISSUE THREAD

**Issue by MonstarCoder** [apache/incubator-brpc#1849]
当前brpc内置的qps、latency监控名称是由"rpc_server"和service、port拼接起来，看了下代码，应该没有暴露接口给用户自定义该名称，有其他方法修改这些监控项的名称吗？

**Comment by serverglen** [comment]
内部版本有这个功能，@KaneVV1 可以提个PR

**Comment by MonstarCoder** [comment]
> 内部版本有这个功能，@KaneVV1 可以提个PR

太棒了，急需该功能，期待PR！

**Comment by serverglen** [comment]
已合入 #1854
