### ISSUE TITLE
使用 brpc-java 的 client 访问 bprc-cpp 的server 可行么？

### ISSUE THREAD

**Issue by gtarcoder** [apache/incubator-brpc#1850]
如题。

需要一个brpc的java client，但是目前brpc 这个项目没有 java client。
而 brpc-java (https://github.com/baidu/brpc-java) 这个项目有client，所以想问能否使用 bprc-java 的java client 访问 brpc 的cpp server?
@jamesge

**Comment by serverglen** [comment]
我理解是可以的，只要协议格式一样应该没问题
