### ISSUE TITLE
熔断无法恢复，错误码为112

### ISSUE THREAD

**Issue by Heihuang** [apache/incubator-brpc#1874]
**Describe the bug (描述bug)**
服务的一个Channel熔断之后，一直无法恢复，返回错误码为112，[E112]Fail to select server from file:
下游服务以及网络正常
options.enable_circuit_breaker=true
options.protocol=h2:grpc
**To Reproduce (复现方法)**
集群中个别机器出现

**Expected behavior (期望行为)**
熔断之后能够正常恢复

**Versions (各种版本)**
OS:CentOS Linux release 7.4.1708
Compiler:g++ (GCC) 4.8.5
brpc:1.1.6-2
protobuf: 2

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
这里有相似的issue 可以参考 https://github.com/apache/incubator-brpc/issues/1773
