### ISSUE TITLE
编译失败,protobuf 3.21.5

### ISSUE THREAD

**Issue by FakeCore** [apache/incubator-brpc#1880]
**Describe the bug (描述bug)**
编译时报错:fatal error: 'google/protobuf/generated_message_table_driven.h' file not found

**To Reproduce (复现方法)**
recompile

**Expected behavior (期望行为)**

编译成功
**Versions (各种版本)**
OS:macos 12.4 m1
Compiler:clang 13
brpc:master commit 6495704589d2ed21df22d0b296dddff738024551
protobuf:3.21.5(使用brew安装的3.20.*,也有相关问题),随后手动安装了最新版

**Additional context/screenshots (更多上下文/截图)**

**Comment by guodongxiaren** [comment]
一般是系统里装了多个protobuf，然后protoc的版本和protobuf库版本不一致导致的。

`protoc --version`看一下protoc版本。保证protoc的版本和链接的protobuf库的版本是同一个版本。

**Comment by zyearn** [comment]
刚刚试了下3.21.5的Mac编译，没遇到什么问题

**Comment by FakeCore** [comment]
> 刚刚试了下3.21.5的Mac编译，没遇到什么问题

感谢.那应该是我之前的操作有问题.目前手动安装了3.1x.x的版本,能够正常使用.
