### ISSUE TITLE
如何关闭 sampler 线程？

### ISSUE THREAD

**Issue by zengshicai2015** [apache/incubator-brpc#1891]
当前在我们线上场景发现bvar 线程始终是100%在运转的。所以我们在思考，
1，能否彻底关闭bvar 的sampler 线程？从代码来看，当前貌似没有关闭的gflag。
2，关闭了sampler 线程对brpc实际的影响是啥？仅仅是一些统计值看不了吗？如果我们不关心这些统计值的话，是不是就没有影响？
3，能否在后续的迭代版本中增加一个gflag，用来控制是否开启sampler线程？
辛苦帮忙解答一下，谢谢，Thanks♪(･ω･)ﾉ

**Comment by serverglen** [comment]
1. 目前确实没有关闭 sampler的 gflag
2. 关闭 sampler 线程 会导致 所有的bvar统计值失效，我理解应该不影响brpc和用户的业务逻辑
3. 可以增加一个gflag控制是否开启sampler线程。

**Comment by leaf-potato** [comment]
PR: #1990

**Comment by serverglen** [comment]
已合入，closed
