### ISSUE TITLE
test_bvar failed in macbook

### ISSUE THREAD

**Issue by guodongxiaren** [apache/incubator-brpc#1897]
**Describe the bug (描述bug)**
```
[  FAILED  ] 1 test, listed below:
[  FAILED  ] RecorderTest.latency_recorder_qps_accuracy
```

**To Reproduce (复现方法)**
```
cd test
make
./test_bvar
```

**Expected behavior (期望行为)**

All unittests should be passed.

**Versions (各种版本)**
OS: macos 12.4 within Apple M1 and macos 12.3 within Intel i7
Compiler: clang
brpc: master or release-1.2
protobuf: 3.21

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
Here is the error message:

```
[ RUN      ] RecorderTest.latency_recorder_qps_accuracy
/Users/zhujiashun/gitrepo/brpc/test/bvar_recorder_unittest.cpp:240: Failure
Expected: (0.1) > (read(lr1, 100/2.0)), actual: 0.1 vs 0.205
[  FAILED  ] RecorderTest.latency_recorder_qps_accuracy (4009 ms)
```
