### ISSUE TITLE
定期回收tcmalloc内存crash风险

### ISSUE THREAD

**Issue by chenBright** [apache/incubator-brpc#1903]
**Describe the bug (描述bug)**
最近想打开定期回收tcmalloc内存的功能。但是看到这个[issue](https://github.com/apache/incubator-brpc/issues/313#issuecomment-386503394)提到设置free_memory_to_system_interval定期调用过tcmalloc的ReleaseFreeMemory有crash风险。请问，线上使用这个功能风险大吗？还有就是crash的条件是什么？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
https://github.com/apache/incubator-brpc/blob/master/src/brpc/global.cpp#L273
这里有一些注释，不过也没解释很具体

**Comment by chenBright** [comment]
> https://github.com/apache/incubator-brpc/blob/master/src/brpc/global.cpp#L273 这里有一些注释，不过也没解释很具体

百度内部有开这个功能吗？

**Comment by chenBright** [comment]
部署在k8s上的brpc服务，如果pod内存超过阈值，就会触发告警。目前来看，如果是因为tcmalloc内存导致的，默认设置的brpc服务是不可恢复的，只能重启pod来解决问题了。

**Comment by wwbmmm** [comment]
> > https://github.com/apache/incubator-brpc/blob/master/src/brpc/global.cpp#L273 这里有一些注释，不过也没解释很具体
> 
> 百度内部有开这个功能吗？

有开启的，但我没有遇到crash的情况
我们大部分用的是tcmalloc 2.7

**Comment by chenBright** [comment]
> > > https://github.com/apache/incubator-brpc/blob/master/src/brpc/global.cpp#L273 这里有一些注释，不过也没解释很具体
> > 
> > 
> > 百度内部有开这个功能吗？
> 
> 有开启的，但我没有遇到crash的情况 我们大部分用的是tcmalloc 2.7

了解，感谢
