### ISSUE TITLE
调整brpc worker线程数的接口

### ISSUE THREAD

**Issue by zhoukangsheng** [apache/incubator-brpc#1906]
问题背景：目前，使用brpc框架的服务，在cpu和内存资源富余的情况下，服务的最大吞吐能力与brpc的线程数和并发度设置有关。如果线程数和并发度设置不合理，会出现机器的CPU资源仍有冗余，但是服务的处理能力达到瓶颈的现象。目前brpc提供了调整服务并发度的接口，在某些场景下可以通过提高并发度来提高服务的吞吐；但是，当服务的吞吐能力受限于线程数时，只能通过调整静态配置里的线程数，服务重新上线的方式来调整线程数。因此，想对brpc进行升级，提供可以调整brpc worker线程数的接口，不知这个想法是否可行。

**Comment by wwbmmm** [comment]
通过访问内置服务的接口：
/flags/bthread_concurrency?setvalue&withform
可以动态调整worker数量（只能调大不能调小）

**Comment by zhoukangsheng** [comment]
> 通过访问内置服务的接口： /flags/bthread_concurrency?setvalue&withform 可以动态调整worker数量（只能调大不能调小）

ok，感谢回复～还有一个疑惑，worker数量不能调小的主要考虑是啥，如果某次调整线程数设置不合理，需要调小，这种场景怎么处理

**Comment by wwbmmm** [comment]
动态回收pthread worker在实践中会有一些困难，比如无法把待回收的pthread上正在执行的bthread强制调度走（bthread是主动让出），比如如何回收pthread上面的tls变量（有些是业务创建的，没有释放机制），所以没有支持worker动态调小，要调小只能重启

**Comment by zhoukangsheng** [comment]
> 动态回收pthread worker在实践中会有一些困难，比如无法把待回收的pthread上正在执行的bthread强制调度走（bthread是主动让出），比如如何回收pthread上面的tls变量（有些是业务创建的，没有释放机制），所以没有支持worker动态调小，要调小只能重启

嗯嗯，这些确实是要考虑的问题；能否在收到worker调小的通知后，随机选取几个线程进行标记，之后不再往标记的线程分配bthread任务就可以达到worker调小的目的，不知道这个思路是否可行？另外我们在使用brpc框架时，我们不建议业务代码使用tls变量，当一个bthread被多个线程调度到后，访问tls变量会存在一些未定义的行为；对于一些需要使用tls变量的场景，比如trace，我们参考brpc中的tls在bthread中做了一些二次开发，在bthread切换调度线程时，将tls变量保存在了bthread的context中，当它被其它线程调度到时，再从context中恢复到tls。

**Comment by wwbmmm** [comment]
> 能否在收到worker调小的通知后，随机选取几个线程进行标记，之后不再往标记的线程分配bthread任务就可以达到worker调小的目的

虽然不再分配新的bthread任务，但当前执行的bthread任务的退出时间是无法预期的

**Comment by zhoukangsheng** [comment]
> 

有道理，当某个bthread是个while循环，且没有调用bthread阻塞函数，是有可能独占一个pthread的，这样的pthread无法退出。但是对线上服务来说，总归是有一些pthread在不断执行新的bthread的，否则系统就无法work了。那么是否在pthread执行完一个bthread之后，在执行下一个bthread之前判断一下是否需要减小worker数就可以了。

**Comment by zhoukangsheng** [comment]
> > 能否在收到worker调小的通知后，随机选取几个线程进行标记，之后不再往标记的线程分配bthread任务就可以达到worker调小的目的
> 
> 虽然不再分配新的bthread任务，但当前执行的bthread任务的退出时间是无法预期的

有道理，当某个bthread是个while循环，且没有调用bthread阻塞函数，是有可能独占一个pthread的，这样的pthread无法退出。但是对线上服务来说，总归是有一些pthread在不断执行新的bthread的，否则系统就无法work了。那么是否在pthread执行完一个bthread之后，在执行下一个bthread之前判断一下是否需要减小worker数就可以了。
