### ISSUE TITLE
关于append_user_data中数据的生命周期问题

### ISSUE THREAD

**Issue by luliyucoordinate** [apache/incubator-brpc#1907]
我有一段内存想要自己管理或者上层系统管理，例如

```c++
static void NoOpDeleter(void *) {}

class EchoServiceImpl : public EchoService {
public:
  EchoServiceImpl() {};
  virtual ~EchoServiceImpl() {};
  virtual void Echo(google::protobuf::RpcController* cntl_base,
                    const EchoRequest* request,
                    EchoResponse* response,
                    google::protobuf::Closure* done) {
    std::vector<int> a;
    {
      brpc::ClosureGuard done_guard(done);
      brpc::Controller* cntl =
                static_cast<brpc::Controller*>(cntl_base);
      a.resize(dim);
      //... a do some calc
      butil::IOBuf &buf = cntl.response_attachment();
      buf.append_user_data(a.data(), a.size() * sizeof(int), NoOpDeleter);
    }
  }
}
```

我的理解是done->Run()过程中，done->Run()是阻塞的，数据`a`会发送结束再出括号再析构a，但是我实际操作发现结果是不正确的。

所以我想问一下如果采用NoOpDeleter这样方式手动管理内存的生命周期，这块内存的生命周期需要存活多久才能保证发送的数据安全。

另外，如果我的数据通过[bthread local](https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md#bthread-local)创建，采用NoOpDeleter这种方式管理安全吗？

**Comment by lorinlee** [comment]
done->Run()不保证io结束才返回，这里数据的生命周期是和request_attachment的IOBuf生命周期绑在一起的，不太好确定结束的边界，bthread_local 也不可以。
这里自己/上层管理具体是想怎么管理呢？

**Comment by luliyucoordinate** [comment]
> done->Run()不保证io结束才返回，这里数据的生命周期是和request_attachment的IOBuf生命周期绑在一起的，不太好确定结束的边界，bthread_local 也不可以。 这里自己/上层管理具体是想怎么管理呢？

我大概能理解你的意思。我是这样理解的，deleter负责在io结束后真正的释放动作。 我有一个需求，如果我的value是一个shared_ptr，那么此时现在的deleter应该是一个ref-1的动作，但是现在的api好像没法实现？

另外我还有一个问题关于fetch和cutn的。对于一个iobuf（这个iobuf实际的意义是一个std::vector<float[]>），我现在需要将每个float[]的片段拿出来，可以通过多次fetch吗，还是说fetch对一个iobuf只能发生一次。fetch得到的内存可以交给shared_ptr管理吗？比如说我的request是一个table的keys和values（table是一个<int64_t, std::shared_ptr<float[]>>类型），当我收到request的时候实际上iobuf已经分配好内存了，此时我能否将iobuf管理的内存交给我的table的shared_ptr管理。

**Comment by lorinlee** [comment]
1. 这个可以考虑先把这块内存append_user_data到一个IOBuf里，然后不同query共享这个IOBuf，之后每次都把这个IOBuf append到cntl.response_attachment()上，IOBuf对指向的内存块本身是有refcount的，每次append()都只会操作refcount

2. fetch会一次性返回所有的数据，且可能会发生拷贝（需要用户传一块内存进来）。如果分段取的话可以用cutn，当然也会发生拷贝。
3. 内存复用的话，这里一个背景是IOBuf内部的内存不保证连续，可能是分段的。如果要复用内存，可以直接持有IOBuf，但这里复用内存有利有弊，复用减少拷贝，但是内存不连续可能导致读数据变慢。也可以选择第一次的时候拷贝一份，后面复用这一份，得结合业务场景来看

**Comment by luliyucoordinate** [comment]
对于1我有些疑问，多个query如果不是共享一个static的IOBuf会有问题吧？我看IOBuf的引用计数不是线程安全的

**Comment by lorinlee** [comment]
@luliyucoordinate append的时候需要加个锁

**Comment by luliyucoordinate** [comment]
了解了，感谢

**Comment by 372046933** [comment]
> done->Run()不保证io结束才返回，这里数据的生命周期是和request_attachment的IOBuf生命周期绑在一起的，不太好确定结束的边界，bthread_local 也不可以。 这里自己/上层管理具体是想怎么管理呢？

closure->Run()不保证io结束吗？ 我发现把append_user_data的析构函数，放到 closure的 Run逻辑里面，好像数据不对了？

**Comment by 372046933** [comment]
> 我有一段内存想要自己管理或者上层系统管理，例如
> 
> static void NoOpDeleter(void *) {}
> 
> class EchoServiceImpl : public EchoService {
> public:
>   EchoServiceImpl() {};
>   virtual ~EchoServiceImpl() {};
>   virtual void Echo(google::protobuf::RpcController* cntl_base,
>                     const EchoRequest* request,
>                     EchoResponse* response,
>                     google::protobuf::Closure* done) {
>     std::vector<int> a;
>     {
>       brpc::ClosureGuard done_guard(done);
>       brpc::Controller* cntl =
>                 static_cast<brpc::Controller*>(cntl_base);
>       a.resize(dim);
>       //... a do some calc
>       butil::IOBuf &buf = cntl.response_attachment();
>       buf.append_user_data(a.data(), a.size() * sizeof(int), NoOpDeleter);
>     }
>   }
> }
> 我的理解是done->Run()过程中，done->Run()是阻塞的，数据`a`会发送结束再出括号再析构a，但是我实际操作发现结果是不正确的。
> 
> 所以我想问一下如果采用NoOpDeleter这样方式手动管理内存的生命周期，这块内存的生命周期需要存活多久才能保证发送的数据安全。
> 
> 另外，如果我的数据通过[bthread local](https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md#bthread-local)创建，采用NoOpDeleter这种方式管理安全吗？

我在client端做了类似的逻辑，发现也是有问题的

**Comment by chenBright** [comment]
> > done->Run()不保证io结束才返回，这里数据的生命周期是和request_attachment的IOBuf生命周期绑在一起的，不太好确定结束的边界，bthread_local 也不可以。 这里自己/上层管理具体是想怎么管理呢？
> 
> closure->Run()不保证io结束吗？ 我发现把append_user_data的析构函数，放到 closure的 Run逻辑里面，好像数据不对了？

不保证。

将析构逻辑放到append_user_data的deleter就行，现在deleter类型是std::function，可以用lambda捕获析构相关的变量。
