### ISSUE TITLE
grpc迁移brpc遇到问题.

### ISSUE THREAD

**Issue by jiangdongzi** [apache/incubator-brpc#1912]
grpc client请求brpc server直连一切正常, 但是通过nginx转发会有一半出错, 请教下原因, 报错如下

upstream sent invalid http2 table index: 63 while reading response header from upstream
upstream sent invalid header while reading response header from upstream
错误码502 bad gate way

使用工具: rpc_press
如果brpc server换回grpc server 就正常

**Comment by jiangdongzi** [comment]
抓包分析, 与 https://github.com/openMF/android-client/issues/1005 这个有些类似, brpc无法理解, "dynamic table update"
![image](https://user-images.githubusercontent.com/17529657/187820164-b31d399d-e939-437a-8456-189cd08378fa.png)
这是nginx发给brpc server的第一个magic包, 如图 
![image](https://user-images.githubusercontent.com/17529657/187820266-76424317-35e4-4043-94aa-afa6290ef4a7.png)

@jbonofre @wwbmmm 麻烦看下 感觉是brpc对http2支持不全

**Comment by dream110fly** [comment]
@jiangdongzi  请问这个问题最终是怎么解决的？
