### ISSUE TITLE
关于connections页面统计的in和out问题

### ISSUE THREAD

**Issue by FancyJan** [apache/incubator-brpc#1914]
大佬求问下在什么情况下connections中的server_connection中的out会明显大于in（即response的数量大于request）？

背景：
brpc内置服务connections页面统计的in和out指标可以体现入口和出口的qps。
我们这边从生产实际看，大部分情况下in和out的值是十分接近的（一个request对应一个response）。
我们想通过in和out的关系去判断某些场景的调用情况，例如对于一个server，如果in远大于out可能可以说明server处理不过来了，不知道是否可行。

附：生产实际中的一个例子（真实ip已被隐去）
java的grpc client通过h2协议调用一个c++的brpc server（版本0.9.7）
connections信息：
![image](https://user-images.githubusercontent.com/37871611/187901518-280fec2e-678c-4bb3-a963-71fd2d2339e2.png)
socket信息：
version=2
shared_part={
  ref_count=1
  socket_pool=null
  creator_socket=8589935746
  in_size=1513761153547
  in_num_messages=9785242
  out_size=3616210108
  out_num_messages=16883270
}
nref=1
nevent=0
fd=283
tos=0
reset_fd_to_now=281166610682us
remote_side=java ip
local_side=cpp ip
on_et_events=0x5d2d000
user=(brpc::Acceptor*)0x7f10e4b13c80
this_id=8589935746
preferred_index=26 (h2)
hc_count=0
avg_input_msg_size=151976
read_buf=0
last_read_to_now=79055us
last_write_to_now=71395us
overcrowded=0
id_wait_list={}
parsing_context=brpc::policy::H2Context{
  conn_state=READY
  last_received_stream_id=19570485
  last_sent_stream_id=1
  deferred_window_update=0
  remote_conn_window_left=58910338
  remote_settings={header_table_size=4096 enable_push=0 max_concurrent_streams=0 stream_window_size=67108864 conn_window_size=1048576 max_frame_size=16384 max_header_list_size=8192}
  remote_settings_received=1
  local_settings={header_table_size=4096 enable_push=0 max_concurrent_streams=4294967295 stream_window_size=262144 conn_window_size=1048576 max_frame_size=16384 max_header_list_size=4294967295}
  hpacker={
    encode_table={start_index=62 need_indexes=1 add_times=210 max_size=4096 size=4029 header_queue.size=17 header_index.size=17 name_index.size=3}
    decode_table={start_index=62 need_indexes=0 add_times=10264696 max_size=4096 size=4049 header_queue.size=76 header_index.size=0 name_index.size=0}
  }
  abandoned_streams=0
  pending_streams=0
}
pipeline_q=0
hc_interval_s=-1
ninprocess=1
auth_flag_error=4294967296
auth_id=47566762867641
auth_context=0
logoff_flag=0
recycle_flag=0
ninflight_app_health_check=0
agent_socket_id=(none)
cid=0
write_head=0
ssl_state=SSL_OFF
tcpi={
  state=1
  ca_state=0
  retransmits=0
  probes=0
  backoff=0
  options=7
  snd_wscale=9
  rcv_wscale=9
  rto=214000
  ato=40000
  snd_mss=1448
  rcv_mss=1448
  unacked=0
  sacked=0
  lost=0
  retrans=0
  fackets=0
  last_data_sent=71
  last_ack_sent=0
  last_data_recv=79
  last_ack_recv=29
  pmtu=1500
  rcv_ssthresh=3367592
  rtt=13871
  rttvar=13845
  snd_ssthresh=4
  snd_cwnd=6
  advmss=1448
  reordering=3
}

**Comment by lorinlee** [comment]
业务需求是想做服务端限流吗，可以参考下这个文档 https://github.com/apache/incubator-brpc/blob/master/docs/cn/auto_concurrency_limiter.md，如果这个限流不能满足需求，可以参考这个限流的实现做自定义的策略开发，在ConcurrentLimiter里是可以做到统计qps信息的，而且可以比较及时地拒绝新请求。

**Comment by FancyJan** [comment]
> 业务需求是想做服务端限流吗，可以参考下这个文档 https://github.com/apache/incubator-brpc/blob/master/docs/cn/auto_concurrency_limiter.md
> 
> 如果这个限流不能满足需求，可以参考这个限流的实现做自定义的策略开发，在ConcurrentLimiter里是可以做到统计qps信息的，而且可以比较及时地拒绝新请求。

感谢大佬回答。

大佬，我们这边想了解的是connections的server_connection中的out明显大于in是否说明这两个节点间的交互有问题？
现在服务是正常跑的没有异常，in的统计值和服务入口qps是一致的，out明显比服务出口qps大。
我们想知道是不是我们业务代码实现有bug，导致额外的输出开销。

然后是关于降级和限流：
我们这边有实现自定义限流，不过我们这边有的场景除了限流之外，还需要上游做降级。
服务端自定义限流没有办法实现这样一种情况：感知到下游扛不住之后，让上游降低每个请求的算力，尽量让每个请求成功。

**Comment by wwbmmm** [comment]
> 我们这边想了解的是connections的server_connection中的out明显大于in是否说明这两个节点间的交互有问题？
> 现在服务是正常跑的没有异常，in的统计值和服务入口qps是一致的，但是out明显比服务出口qps大。
> 我们想知道是不是我们业务代码实现有bug，导致额外的输出开销。

如果是h2协议的话，会有些Ack包被统计到out messages里了，导致out明显大于in。这个应该不是业务代码的问题。

**Comment by FancyJan** [comment]
> 

好的，谢谢大佬解答，我这边确认下
