### ISSUE TITLE
stream protocol 多streams用同一个socket

### ISSUE THREAD

**Issue by chenbay** [apache/incubator-brpc#1929]
多streams公用一个socket，只有单个stream的comsume queue大小限制max_buf_size，没有socket级别的stream comsume queue大小限制，而且stream不同情况下不好直接设置统一的stream限制。
有必要加一个socket级别的限制？ https://github.com/apache/incubator-brpc/pull/1928

**Comment by wwbmmm** [comment]
Fixed by https://github.com/apache/incubator-brpc/pull/1958
