### ISSUE TITLE
Should add a pull_request_template.md?

### ISSUE THREAD

**Issue by fansehep** [apache/incubator-brpc#1951]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

项目并没有 pull_request_template.md. 这可能不利于贡献者对问题的详细描述.

This project don't have a pull_request_template.md, this can be detrimental to the contributor's detailed description of the problem.

**Describe the solution you'd like (描述你期望的解决方法)**
我想增加一个 pull_request_template.md.

can i add a pull_request_template.md for this?

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by Huixxi** [comment]
Good idea.
