### ISSUE TITLE
butil::WriteFile()出错，如何返回具体的错误信息，目前所有异常情况都只会返回一个-1的错误码。

### ISSUE THREAD

**Issue by wang-jiechen** [apache/incubator-brpc#1957]
butil::WriteFile()出错，如何返回具体的错误信息，目前所有异常情况都只会返回一个-1的错误码。

**Comment by lorinlee** [comment]
错误信息可以看下errno，不过这里看起来如果write出错的话，还是会调用close，write的errno可能看不到了，那只能自己实现这块的逻辑了，针对每个调用都做一下判断
