### ISSUE TITLE
编译链接错误

### ISSUE THREAD

**Issue by HehuaTang** [apache/incubator-brpc#1966]
**Describe the bug (描述bug)**
# git pull
Already up-to-date.
# git branch
* master
  rdma-old
# pwd
/root/rdma/incubator-brpc/example/rdma_performance/bu
make client
[ 25%] Linking CXX executable client
CMakeFiles/client.dir/client.cpp.o: In function `main':
client.cpp:(.text.startup+0x181): undefined reference to `brpc::rdma::GlobalRdmaInitializeOrDie()'
collect2: error: ld returned 1 exit status
make[3]: *** [client] Error 1
make[2]: *** [CMakeFiles/client.dir/all] Error 2
make[1]: *** [CMakeFiles/client.dir/rule] Error 2
make: *** [client] Error 2

**To Reproduce (复现方法)**

master 分支编译错误
**Expected behavior (期望行为)**
版本能够编译通过，测试rdma功能

**Versions (各种版本)**
OS:centos7.7
Compiler:gcc
brpc: master
protobuf:none

**Additional context/screenshots (更多上下文/截图)**

**Comment by HehuaTang** [comment]
cmake -DWITH_RDMA=on .  # in brpc  project's directory can fixed this issue.

**Comment by Tuvie** [comment]
This is because brpc is not compile with rdma. Let me add a warning for this kind of mistake.
