### ISSUE TITLE
请问在使用single这种连接方式时，如何限制服务端的最大连接数

### ISSUE THREAD

**Issue by kof02guy** [apache/incubator-brpc#1976]
对于连接池来说，有max_connection_pool_size。而对于baidu_std默认的single这种方式，是否有方法去限制服务端创建的最大连接数呢？

**Comment by wwbmmm** [comment]
max_connection_pool_size是限制客户端连接数的。
single模式，每个后端server（ip+port）只会建立一个连接。所以只要限制server个数，就可以限制客户端的连接数。
服务端的连接数目前无法限制

**Comment by kof02guy** [comment]
多谢回复。请问对于服务端的连接数，是否有一个推荐的值的范围。如果连接数过多，除了linux本身的limit限制之外，还会有别的影响么？

**Comment by cdjingit** [comment]
max_connection_pool_size 的话只是限制一个连接池常驻链接的数量，实际建立的连接数取决于并发数量，brpc作为客户端底层建立的tcp连接会尽量共享的。

**Comment by wwbmmm** [comment]
> 多谢回复。请问对于服务端的连接数，是否有一个推荐的值的范围。如果连接数过多，除了linux本身的limit限制之外，还会有别的影响么？

连接数一般来说没什么影响，只要不超过linux本身limit限制即可。
对服务可用性影响更大的是并发请求数，这个一般通过ServerOptions的max_concurrency来限制

**Comment by kof02guy** [comment]
> > 多谢回复。请问对于服务端的连接数，是否有一个推荐的值的范围。如果连接数过多，除了linux本身的limit限制之外，还会有别的影响么？
> 
> 连接数一般来说没什么影响，只要不超过linux本身limit限制即可。 对服务可用性影响更大的是并发请求数，这个一般通过ServerOptions的max_concurrency来限制

请问下，这里的max_concurrency可以理解成是对连接数的一个限制吗？因为如果有大于max_concurrency的请求到来，会被立刻拒绝。这里实际的连接数应该总是<= max_concurrency的

**Comment by wwbmmm** [comment]
> 
> 请问下，这里的max_concurrency可以理解成是对连接数的一个限制吗？因为如果有大于max_concurrency的请求到来，会被立刻拒绝。这里实际的连接数应该总是<= max_concurrency的

max_concurrency跟连接没关系，它限制的是并发处理的请求数。
