### ISSUE TITLE
brpc如何在service mesh环境下实现一致性哈希的负载均衡策略

### ISSUE THREAD

**Issue by yyhclimacool** [apache/incubator-brpc#1978]
我们的生产环境是基于istio的service mesh，我需要实现一致性hash的负载均衡策略，传输协议我们使用http，这样service mesh可以基于http里的header做一致性hash（比如http的header requestid，每次请求让requestid赋值为本次请求的logid）；
这样我的client端protocol需要为http，我如何能定制这样的requestid的header呢？

我试过了调用cntl.SetHeader("requestid", logid)，从服务端日志看一致性hash的负载均衡策略没有生效。

**Comment by serverglen** [comment]
确认下service mesh http请求header中是包含requestid

**Comment by yyhclimacool** [comment]
测试通过了，SetHeader是起作用的，需要mesh下发配置生效才行！
