### ISSUE TITLE
warning信息标点错误

### ISSUE THREAD

**Issue by leaf-potato** [apache/incubator-brpc#1988]
**Describe the bug (描述bug)**

在`src/butil/iobuf.cpp:144`的警告信息中英文标点错误：

```cpp
#else   // ARCH_CPU_X86_64

#warning "We don't check if the kernel supports SYS_preadv or SYS_pwritev on non-X86_64, use impl. on pread/pwrite directly"
```

**To Reproduce (复现方法)**

查看代码文件的对应位置

**Expected behavior (期望行为)**

应该是`use impl on pread/pwrite directly.` 而不是`use impl. on pread/pwrite directly`

**Comment by jamesge** [comment]
"impl."中的.指这是一个缩写
![image](https://user-images.githubusercontent.com/6566535/202227535-bf6049df-e19e-4377-81d7-10fa0365ce77.png)
