### ISSUE TITLE
Rewrite the brpc bazel build rules

### ISSUE THREAD

**Issue by fansehep** [apache/incubator-brpc#1992]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
Now brpc as an bazel external dependency is not easy. 

**Describe the solution you'd like (描述你期望的解决方法)**
rewrite it.
as a third_party like
```c++
git_repository(
    name = "apache_brpc",
    branch = "release-1.3",
    remote = "https://github.com/apache/incubator-brpc",
)
```
before this. we can easy make build deps ```deps = "@apache_brpc//:bthread``` or other deps.

**Describe alternatives you've considered (描述你想到的折衷方案)**

rewrite it or minor modifications.

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
Fan, do you want to work on it?

The ideal state would be the [examples](https://github.com/apache/incubator-brpc/tree/master/example) can link brpc using bazel as a third_party

**Comment by fansehep** [comment]
I'll try, but it may take some time.

**Comment by zyearn** [comment]
> I'll try, but it may take some time.

Sounds good.

**Comment by 372046933** [comment]
```BUILD
http_archive(
    name = "apache_brpc",
    urls = [
        "https://github.com/apache/incubator-brpc/archive/3d90221107000133c2d7f3ccc6372680fb6af27d.tar.gz",
    ],
    sha256 = "b4f4517bad125e8b57a1af54cfe6d31691362c9e02db6f8c434fdd693e27c71a",
    strip_prefix = "incubator-brpc-3d90221107000133c2d7f3ccc6372680fb6af27d",
)
```

**Comment by fansehep** [comment]
> ```
> http_archive(
>     name = "apache_brpc",
>     urls = [
>         "https://github.com/apache/incubator-brpc/archive/3d90221107000133c2d7f3ccc6372680fb6af27d.tar.gz",
>     ],
>     sha256 = "b4f4517bad125e8b57a1af54cfe6d31691362c9e02db6f8c434fdd693e27c71a",
>     strip_prefix = "incubator-brpc-3d90221107000133c2d7f3ccc6372680fb6af27d",
> )
> ```

it seems useless in my server. bazel can not found some deps like openssl.

**Comment by 372046933** [comment]
@fansehep 
```BUILD
http_archive(
    name = "rules_perl",  # 2021-09-23T03:21:58Z
    sha256 = "55fbe071971772758ad669615fc9aac9b126db6ae45909f0f36de499f6201dd3",
    strip_prefix = "rules_perl-2f4f36f454375e678e81e5ca465d4d497c5c02da",
    urls = [
        "https://github.com/bazelbuild/rules_perl/archive/2f4f36f454375e678e81e5ca465d4d497c5c02da.tar.gz",
    ],
)
# Use rules_foreign_cc as fewer as possible.
#
# 1. Build very basic libraries without any further dependencies.
# 2. Build too complex to bazelize library.
http_archive(
    name = "rules_foreign_cc",
    sha256 = "2a4d07cd64b0719b39a7c12218a3e507672b82a97b98c6a89d38565894cf7c51",
    strip_prefix = "rules_foreign_cc-0.9.0",
    url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.9.0.tar.gz",
)
#
# Starlark rules
#
load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies()
#
# Perl Dependencies
# (Required by building openssl)
#
load("@rules_perl//perl:deps.bzl", "perl_register_toolchains", "perl_rules_dependencies")
perl_rules_dependencies()
perl_register_toolchains()

# bRPC cannot use boringssl. Build openssl.
http_archive(
   name = "openssl",  # 2022-11-1
   build_file = "//third_party/openssl:openssl.foreign_rules.BUILD",
   sha256 = "c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa",
   strip_prefix = "openssl-1.1.1s",
   urls = [
       "https://www.openssl.org/source/openssl-1.1.1s.tar.gz",
   ],
)
```
`openssl.foreign_rules.BUILD`
```BUILD
"""An openssl build file based on a snippet found in the github issue:
https://github.com/bazelbuild/rules_foreign_cc/issues/337

Note that the $(PERL) "make variable" (https://docs.bazel.build/versions/main/be/make-variables.html)
is populated by the perl toolchain provided by rules_perl.
"""

load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make", "configure_make_variant")

# Read https://wiki.openssl.org/index.php/Compilation_and_Installation

filegroup(
    name = "all_srcs",
    srcs = glob(
        include = ["**"],
        exclude = ["*.bazel"],
    ),
)

CONFIGURE_OPTIONS = [
    "no-comp",
    "no-idea",
    "no-weak-ssl-ciphers",
    "no-shared",
]

LIB_NAME = "openssl"

MAKE_TARGETS = [
    "build_libs",
    "install_dev",
]

config_setting(
    name = "msvc_compiler",
    flag_values = {
        "@bazel_tools//tools/cpp:compiler": "msvc-cl",
    },
    visibility = ["//visibility:public"],
)

alias(
    name = "openssl",
    actual = "openssl_default",
    visibility = ["//visibility:public"],
)

alias(
    name = "ssl",
    actual = "openssl_default",
    visibility = ["//visibility:public"],
)

alias(
    name = "crypto",
    actual = "openssl_default",
    visibility = ["//visibility:public"],
)

configure_make(
    name = "openssl_default",
    configure_command = "config",
    configure_in_place = True,
    configure_options = CONFIGURE_OPTIONS,
    args = ["-j `nproc`"],
    env = select({
        "@platforms//os:macos": {
            "AR": "",
            "PERL": "$$EXT_BUILD_ROOT$$/$(PERL)",
        },
        "//conditions:default": {
            "PERL": "$$EXT_BUILD_ROOT$$/$(PERL)",
        },
    }),
    lib_name = LIB_NAME,
    lib_source = ":all_srcs",
    copts = ["-fPIC"],
    # Note that for Linux builds, libssl must come before libcrypto on the linker command-line.
    # As such, libssl must be listed before libcrypto
    out_static_libs = [
        "libssl.a",
        "libcrypto.a",
    ],
    targets = MAKE_TARGETS,
    toolchains = ["@rules_perl//:current_toolchain"],
)

filegroup(
    name = "gen_dir",
    srcs = [":openssl"],
    output_group = "gen_dir",
    visibility = ["//visibility:public"],
)
```

**Comment by fansehep** [comment]
> @fansehep
> 
> ```
> http_archive(
>     name = "rules_perl",  # 2021-09-23T03:21:58Z
>     sha256 = "55fbe071971772758ad669615fc9aac9b126db6ae45909f0f36de499f6201dd3",
>     strip_prefix = "rules_perl-2f4f36f454375e678e81e5ca465d4d497c5c02da",
>     urls = [
>         "https://github.com/bazelbuild/rules_perl/archive/2f4f36f454375e678e81e5ca465d4d497c5c02da.tar.gz",
>     ],
> )
> # Use rules_foreign_cc as fewer as possible.
> #
> # 1. Build very basic libraries without any further dependencies.
> # 2. Build too complex to bazelize library.
> http_archive(
>     name = "rules_foreign_cc",
>     sha256 = "2a4d07cd64b0719b39a7c12218a3e507672b82a97b98c6a89d38565894cf7c51",
>     strip_prefix = "rules_foreign_cc-0.9.0",
>     url = "https://github.com/bazelbuild/rules_foreign_cc/archive/0.9.0.tar.gz",
> )
> #
> # Starlark rules
> #
> load("@rules_foreign_cc//foreign_cc:repositories.bzl", "rules_foreign_cc_dependencies")
> rules_foreign_cc_dependencies()
> #
> # Perl Dependencies
> # (Required by building openssl)
> #
> load("@rules_perl//perl:deps.bzl", "perl_register_toolchains", "perl_rules_dependencies")
> perl_rules_dependencies()
> perl_register_toolchains()
> 
> # bRPC cannot use boringssl. Build openssl.
> http_archive(
>    name = "openssl",  # 2022-11-1
>    build_file = "//third_party/openssl:openssl.foreign_rules.BUILD",
>    sha256 = "c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa",
>    strip_prefix = "openssl-1.1.1s",
>    urls = [
>        "https://www.openssl.org/source/openssl-1.1.1s.tar.gz",
>    ],
> )
> ```
> 
> `openssl.foreign_rules.BUILD`
> 
> ```
> """An openssl build file based on a snippet found in the github issue:
> https://github.com/bazelbuild/rules_foreign_cc/issues/337
> 
> Note that the $(PERL) "make variable" (https://docs.bazel.build/versions/main/be/make-variables.html)
> is populated by the perl toolchain provided by rules_perl.
> """
> 
> load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make", "configure_make_variant")
> 
> # Read https://wiki.openssl.org/index.php/Compilation_and_Installation
> 
> filegroup(
>     name = "all_srcs",
>     srcs = glob(
>         include = ["**"],
>         exclude = ["*.bazel"],
>     ),
> )
> 
> CONFIGURE_OPTIONS = [
>     "no-comp",
>     "no-idea",
>     "no-weak-ssl-ciphers",
>     "no-shared",
> ]
> 
> LIB_NAME = "openssl"
> 
> MAKE_TARGETS = [
>     "build_libs",
>     "install_dev",
> ]
> 
> config_setting(
>     name = "msvc_compiler",
>     flag_values = {
>         "@bazel_tools//tools/cpp:compiler": "msvc-cl",
>     },
>     visibility = ["//visibility:public"],
> )
> 
> alias(
>     name = "openssl",
>     actual = "openssl_default",
>     visibility = ["//visibility:public"],
> )
> 
> alias(
>     name = "ssl",
>     actual = "openssl_default",
>     visibility = ["//visibility:public"],
> )
> 
> alias(
>     name = "crypto",
>     actual = "openssl_default",
>     visibility = ["//visibility:public"],
> )
> 
> configure_make(
>     name = "openssl_default",
>     configure_command = "config",
>     configure_in_place = True,
>     configure_options = CONFIGURE_OPTIONS,
>     args = ["-j `nproc`"],
>     env = select({
>         "@platforms//os:macos": {
>             "AR": "",
>             "PERL": "$$EXT_BUILD_ROOT$$/$(PERL)",
>         },
>         "//conditions:default": {
>             "PERL": "$$EXT_BUILD_ROOT$$/$(PERL)",
>         },
>     }),
>     lib_name = LIB_NAME,
>     lib_source = ":all_srcs",
>     copts = ["-fPIC"],
>     # Note that for Linux builds, libssl must come before libcrypto on the linker command-line.
>     # As such, libssl must be listed before libcrypto
>     out_static_libs = [
>         "libssl.a",
>         "libcrypto.a",
>     ],
>     targets = MAKE_TARGETS,
>     toolchains = ["@rules_perl//:current_toolchain"],
> )
> 
> filegroup(
>     name = "gen_dir",
>     srcs = [":openssl"],
>     output_group = "gen_dir",
>     visibility = ["//visibility:public"],
> )
> ```

Thank you. but it seems not only openssl. and leveldb or other deps. I know how to solve it. you can see my new pr.

**Comment by 372046933** [comment]
`bind` is not recommended. See https://bazel.build/reference/be/workspace#bind
IMHO, you can write a bazel function that expose all external dependency in BRPC, and call that function in BRPC `WORKSPACE` or in project that depends on BRPC. For example, TF WORKSPACE
https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE#L9-L23

**Comment by fansehep** [comment]
> `bind` is not recommended. See https://bazel.build/reference/be/workspace#bind IMHO, you can write a bazel function that expose all external dependency in BRPC, and call that function in BRPC `WORKSPACE` or in project that depends on BRPC. For example, TF WORKSPACE https://github.com/tensorflow/tensorflow/blob/49959d2f7d5e497edf90d6cdebc9afa3247234b7/WORKSPACE#L9-L23

wow, thank you!. looks elegance. i will try it.

**Comment by kevincai** [comment]
it would be good to have a bazel script to get all these deps defined in a bazel function (e.g. `brpc_deps()`, so other projects who want to introduce brpc as thirdparty, can just call the `brpc_deps()` to get all the deps ready for build.

**Comment by fansehep** [comment]
> it would be good to have a bazel script to get all these deps defined in a bazel function (e.g. `brpc_deps()`, so other projects who want to introduce brpc as thirdparty, can just call the `brpc_deps()` to get all the deps ready for build.最好有一个 bazel 脚本来获取在 bazel 函数中定义的所有这些 deps（例如 `brpc_deps()` ，因此其他想要将 brpc 作为第三方引入的项目，只需调用 `brpc_deps()` 即可让所有 deps 准备好建造。

Maybe this https://github.com/apache/brpc/blob/master/example/build_with_bazel/brpc_workspace.bzl is your want.

**Comment by kevincai** [comment]
> Maybe this https://github.com/apache/brpc/blob/master/example/build_with_bazel/brpc_workspace.bzl is your want.

refer to prometheus-cpp repository, the following example is a common way to allow other projects to reference to.

https://github.com/jupp0r/prometheus-cpp

```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")
http_archive(
    name = "com_github_jupp0r_prometheus_cpp",
    strip_prefix = "prometheus-cpp-master",
    urls = ["https://github.com/jupp0r/prometheus-cpp/archive/master.zip"],
)

load("@com_github_jupp0r_prometheus_cpp//bazel:repositories.bzl", "prometheus_cpp_repositories")

prometheus_cpp_repositories()
```

**Comment by fansehep** [comment]
maybe this doc can help you. https://github.com/apache/brpc/blob/master/docs/cn/bazel_support.md

**Comment by kevincai** [comment]
thx
