### ISSUE TITLE
使用master分支中的rdma测试代码进行测试，发现是否使用rdma，延迟基本没有区别

### ISSUE THREAD

**Issue by zoulei** [apache/incubator-brpc#2010]
![6b0b37ede60da86a9e89a6ead894ee5](https://user-images.githubusercontent.com/11936655/203461582-792c135e-8b74-4295-baa3-de9dbee82a2a.jpg)
![4549b49aa631b27228d2731832966a8](https://user-images.githubusercontent.com/11936655/203461618-ae29a2df-3cd2-49d7-a04c-3f6824486207.jpg)
我使用example/rdma_performance下的代码进行测试，客户端和服务端分别在不同的机器上，两台机器都支持RDMA，使用RDMA之后，机器的CPU使用率明显下降，但是延迟没有影响，有哪位大佬知道这是什么原因吗？

**Comment by Tuvie** [comment]
这个测试case里面，带宽是瓶颈，都达到25G满带宽了。时延不会有啥差距的。

**Comment by zoulei** [comment]
> 这个测试case里面，带宽是瓶颈，都达到25G满带宽了。时延不会有啥差距的。

但是我看RDMA的理论介绍中，RMDA能减少一次内存的拷贝，减少这一次拷贝却没有降低延迟是因为和网络传输相比，内存的拷贝速度太快了吗？

**Comment by zoulei** [comment]
> 这个测试case里面，带宽是瓶颈，都达到25G满带宽了。时延不会有啥差距的。

我大概有点明白了，在一次请求的数据传输过程中，内存的拷贝和数据通过网络传输，并不是串行的，而是并行的，拷贝了一部分之后，就会开始并行的拷贝与传输，而内存的拷贝速度要远快于网络传输的速度，从而导致出现延迟并没有下降的结果。请问大佬们，是这样的吗？
如果是这样的话，那么对于IO密集型服务，cpu利用率本身就不高，使用RDMA也基本无法带来收益。我这么理解对吗？
