### ISSUE TITLE
 ExecutionQueue是严格有序的么, A B依次提交, 是否可以保证B任务必然在A任务完成后开始执行

### ISSUE THREAD

**Issue by jiangdongzi** [apache/incubator-brpc#2032]
还是A B可能会并发执行

**Comment by yanglimingcn** [comment]
严格有序

**Comment by jiangdongzi** [comment]
> 严格有序

我们现在有一种需求,  同一userId的请求需要串行执行, 我们又想得到尽可能高的并发, 所以目前的想法是创建大量的ExecutionQueue, 比如1000, 同一userId的请求就哈希到对应的 ExecutionQueue,  这样是合理可行的吧

**Comment by jiangdongzi** [comment]
> 我觉得合理，但是你可以根据userid做个hash，这样execution_queue的数量就是可调整的了，不用和userid一一对应。

thx
