### ISSUE TITLE
brpc的multi-label的bvar，是否可以支持，label的动态释放？

### ISSUE THREAD

**Issue by ldak4747** [apache/incubator-brpc#2040]
实际场景如：
metric都是同一个metric(multi-label的MVariable)
1、根据索引的上线，增加metric的对应label
2、当索引下线，删除metric的对应label

原因：有脚本根据metrics做对应处理，对于下线的索引，如果label对应的统计还存在，则会导致脚步误判

**Comment by serverglen** [comment]
本周我提交下，内部版本已经支持了

**Comment by ldak4747** [comment]
非常的感谢，我怎么能及时知道更新呢？

**Comment by serverglen** [comment]
我提交完后，在这里at你，你也可以[订阅brpc邮件](https://brpc.apache.org/zh/docs/community/mailing_list/)。
另外：欢迎提交 [贵公司的使用案例](https://github.com/apache/incubator-brpc/issues/1640)，帮助bRPC越来越好。
十分感谢。

**Comment by serverglen** [comment]
> 非常的感谢，我怎么能及时知道更新呢？

@ldak4747 可以试试 #2041

**Comment by ldak4747** [comment]
好的我试试～

**Comment by serverglen** [comment]
> 好的我试试～

先close了，有问题可以reopen。
