### ISSUE TITLE
服务端主动发送数据给客户端，并能感知客户端处理结果

### ISSUE THREAD

**Issue by yongxiangzheng** [apache/incubator-brpc#2043]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

我们对brpc的应用，使用uds用于进程间通讯。场景存在中心服务发指令给客户端执行，并要求得到客户端执行结果。
看了 这个https://github.com/apache/incubator-brpc/blob/master/docs/cn/server_push.md推送方式，只能做到订阅通知，没法感知客户端执行后的结果，请问目前brpc有其他方式可以支持吗
**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by wwbmmm** [comment]
可以使用[streaming rpc](https://github.com/apache/incubator-brpc/blob/master/docs/cn/streaming_rpc.md) 进行双向流通信

**Comment by yongxiangzheng** [comment]
感谢回答，我验证了下[streaming rpc](https://github.com/apache/incubator-brpc/blob/master/docs/cn/streaming_rpc.md)，确实可以达到需求，但是代码量增多不少，不利为维护。
    多进程通讯，是否可以按照即是服务端也是客户端进行设计，这样也是可以达到我们的业务需求。弊端是要多维护一条链路。或者您是否有更好的建议？

**Comment by wwbmmm** [comment]
> 服务端也是客户端进行设计

你是指服务端反向连接客户端是吗？这样当然也是可以的，不过客户端需要多监听一个端口，并且服务端需要知晓这个端口。

**Comment by yongxiangzheng** [comment]
是的，就是一个进程可以充当服务端也可以当客户端，应该是挺多业务场景，需要这样设计的。
