### ISSUE TITLE
example中logoff_ms参数的作用

### ISSUE THREAD

**Issue by leaf-potato** [apache/incubator-brpc#2060]
在example目录下大多数例子的`server.cpp`中都定义了`logoff_ms`这个gflag， 但似乎没有地方使用了这个参数。想问下这个参数在什么地方发挥作用呢？
![image](https://user-images.githubusercontent.com/49188857/209420157-72e08237-80b7-49e2-8ace-9c6e8335758f.png)

**Comment by wwbmmm** [comment]
这个是用来传递给Server::Stop方法的参数，不过按照注释，这个参数已不再使用

```cpp
    // Stop accepting new connections and requests from existing connections.
    // Returns 0 on success, -1 otherwise.
    int Stop(int closewait_ms/*not used anymore*/);
```

**Comment by leaf-potato** [comment]
这样的话是否可以提个PR删掉example中的这个gflag呢

**Comment by wwbmmm** [comment]
可以的
