### ISSUE TITLE
有支持.NET Core的计划么?

### ISSUE THREAD

**Issue by egmkang** [apache/incubator-brpc#4]
RT
谢谢

**Comment by IronsDu** [comment]
@jamesge 好像没看到通信协议相关文档，类似 https://github.com/baidu/sofa-pbrpc/wiki/RPC%E5%8D%8F%E8%AE%AE 。

**Comment by mazong1123** [comment]
多语言的支持其实可以考虑用社区推动，只要有好的文档和开发规范就可以。

另外brpc多语言的实现计划是考虑在C++实现外面加个wrapper还是使用各种语言重新实现？
PS: .NET Core的实现我可以参与:)

**Comment by taadis** [comment]
同问需求 +1

**Comment by geffzhang** [comment]
同问需求 +1

**Comment by wwbmmm** [comment]
没有计划
