### ISSUE TITLE
连接断开重连后的问题

### ISSUE THREAD

**Issue by ufosky** [apache/incubator-brpc#493]
这算是 https://github.com/brpc/brpc/issues/476 问题的延续吧，还是选择逻辑数据库，底层连接断开了重连就丢失了之前选择的逻辑数据库，我需要重连之后选择之前连接的逻辑数据库，有没有合适的方式实现？

**Comment by gydong** [comment]
要临时应对这个问题的话，想到一种非常hack的方案：实现一个Authenticator，在GenerateCredential 函数中去 select DB 。

**Comment by jamesge** [comment]
@gydong auth的方法我觉得也是可以，只是现在auth的接口不够通用，不太符合直觉。

**Comment by zwkno1** [comment]
这个功能有实现了没？

**Comment by zwkno1** [comment]
#1768
