### ISSUE TITLE
DoublyBufferedData扩展性受限于_SC_THREAD_KEYS_MAX只能到1024

### ISSUE THREAD

**Issue by ipconfigme** [apache/incubator-brpc#502]
如题，DoublyBufferedData每个实例会使用一个pthread_key创建一块TLS的内存，用于保存Wrapper结构。LoadBalancer实现中使用DoublyBufferedData实现写少读多场景的优化，当Client并发很大的时候，会出现pthread_key_create失败。
DoublyBufferedData的实现可以使用一个全局的TLS结构，为每个实例分配一个Id，从而避免为每个实例分配一个pthread_key，提升扩展性。

**Comment by x-x-p** [comment]
什么时候能合并到主分支呢？#708

**Comment by x-x-p** [comment]
????????????????????????????

**Comment by x-x-p** [comment]
@jamesge @wanglun @jbonofre

**Comment by eyun221** [comment]
@wanglun 大佬，问下这个fix有在生产环境使用吗？

**Comment by wwbmmm** [comment]
> @wanglun @wuw92 大佬，问下这个fix有在生产环境使用吗？

有的，百度内部一直在用

**Comment by eyun221** [comment]
> 

好的，感谢大佬，这个fix为啥不合并到master呢？

**Comment by wwbmmm** [comment]
> > 
> 
> 好的，感谢大佬，这个fix为啥不合并到master呢？

之前漏了，近期合入一下
@KaneVV1

**Comment by wwbmmm** [comment]
> > 
> 
> 好的，感谢大佬，这个fix为啥不合并到master呢？

已合入master，可以试试

**Comment by eyun221** [comment]
> 

好的，感谢
