### ISSUE TITLE
请教: time profile 工具是否有可能

### ISSUE THREAD

**Issue by yitian134** [apache/incubator-brpc#514]
看了下，brpc目前提供cpu profile和contention_profile，但是貌似还定位不到 io bound 的耗时？(并不确定)

不知道是否有time profile的工具，或者现有的开源工具没有没建议的？ 搜了一圈没找到，只找到了一个qt的问答。。 https://stackoverflow.com/questions/4394606/beyond-stack-sampling-c-profilers

**Comment by jamesge** [comment]
你说的io是指什么？磁盘一般是看ioutil，网络一般是tracing。

**Comment by yitian134** [comment]
对，是类似函数级tracing这样的。
其实期望的工具就是能分析【函数调用时间】的占比，类似cpu profile的那种图，这样可以直接判断出瓶颈函数在哪，就不用多个工具切换来排查了。加上tracing可能比较影响性能，感觉现有的cpp世界并不支持这种工具。。

**Comment by jamesge** [comment]
支持的可能性是完全ok的，具体做法以前都考虑过，我称之为Path profiler。实现方法有两个极端:
* 一个极端是修改gcc，在主要的函数的开头(prolog)和末尾(epilog)加上收集代码。缺点是所有函数都要加，overhead太大。
* 另一个极端是提供一个RAII对象（类似unique_lock那种），让用户手动选择一些函数插入进去。构造和析构时会调用收集代码。缺点是很繁琐。

一个折衷是提供RAII对象，然后写一个预处理脚本，在每次编译前预处理下所有的函数，对于比较长的且还没有插入那个RAII对象的函数，插入那个对象。预处理过的源代码可以拷贝到独立的目录，且尽量做到没修改的就不更新，以加快编译速度。

至于怎么以超低overhead收集信息，以及怎么做profiler，怎么展示结果，就是另外一回事了。

**Comment by kenshinxf** [comment]
可以考虑用systemtap, on cpu/ off cpu, 我理解off cpu的火焰图这个可以分析你说的这类问题
https://openresty.org/posts/dynamic-tracing/

**Comment by yitian134** [comment]
@kenshinxf 对，是类似的功能。但是这个安装步骤略显繁琐，还在研究中。。

**Comment by jamesge** [comment]
@kenshinxf off-cpu能工作的前提是阻塞都来自syscall吧，这个对目前的brpc似乎不成立。
