### ISSUE TITLE
lalb负载均衡的疑问

### ISSUE THREAD

**Issue by marvv** [apache/incubator-brpc#641]
改了example下echo server的例子，起3个server去计算100以内素数，客户端使用SelectiveChannel并添加3个server为sub channel，以lalb负载均衡算法。统计每秒的调用情况，发现流量并不是均匀分布的，甚至相差一倍，延时差不多，但cpu使用率也流量一样相差较大。

另外如果按项目文档里面的例子 server逻辑设定为sleep若干ms 实际测试和文档的一致。

这样的结果是符合预期的吗 还是我的测试有问题？看文档lalb是默认的负载均衡算法，线上有出现类似的情况吗

**Comment by jamesge** [comment]
符合预期，lalb追求的就是最小化平均延时，所以每个节点的负载可能相差很大。lalb不是默认的负载均衡算法，rr才是。

**Comment by marvv** [comment]
谢谢解答

**Comment by marvv** [comment]
请问生产环境lalb用得多吗，与wrr的大致比例是如何的呢？
假设后端节点服务性能一致的情况下，lalb比wrr性能会差一些？

**Comment by jamesge** [comment]
lalb可类比为wrr+一种weight调节机制，没法横向比较。
