### ISSUE TITLE
bthread::Mutex 静默初始化失败的疑问

### ISSUE THREAD

**Issue by choleraehyq** [apache/incubator-brpc#645]
使用 brpc 的程序出 core，发现是一个 bthread::Mutex 内部的 butex 为空指针，追溯发现在 bthread::Mutex 的构造函数中，如果 bthread_mutex_init 返回空指针，只会打日志，不会向外报出错误。为何要这样设计呢？

另外，在何状态下会导致 bthread_mutex_init 返回空指针呢？

**Comment by jamesge** [comment]
这里可以考虑抛出std::system_error和std::mutex行为对齐。另外也可以先检查下为什么butex分配失败，是不是某些对象的数量不符合预期了，另外也可以考虑打开[-crash_on_fatal_log](https://github.com/brpc/brpc/blob/19f3e87409af789cb17b8ef004b5a5aff7540263/src/butil/logging.cc#L115)
