### ISSUE TITLE
支持热点情况下的一致性hash？

### ISSUE THREAD

**Issue by THCloud** [apache/incubator-brpc#649]
https://github.com/brpc/brpc/blob/master/docs/cn/consistent_hashing.md

这个文档里介绍了一致性hash，其中介绍的缓存问题几乎与线上的生产环境是完全一致的。散列hash的缺点和一致性hash的优点也基本介绍的很完全。

不过我会感觉，一致性hash有可能存在的问题，就是流量热点：大部分流量如果爆发到一个range，请求有可能会打到集中的几个server上，从而形成负载不均衡问题。所以是否有可能，实现一个基于权重的一致性hash？

我的一些想法：
1. client如何探测到热点？
结合这个https://github.com/brpc/brpc/blob/master/docs/cn/lalb.md  lalb。基于lalb中的这个weight计算，统计到server端当前的负载情况
2. 假设1能够做到探测热点，接下来怎么做？
想法是让热点区间尽可能摊到能多的server去承担压力。根据weight探测到热点的server，在实际hash的时候，分配到的range区间会缩短。相应的，其他的server会增大各自的区间。
3. 如何避免cache颠簸？
这个没想好。能想到的方法就是减少range变动的周期，实现一个定时的range重计算。

戈神看看对于这个问题有没有什么意见或者想法。目前希望能对这个有一些方案，着手搞一下。

**Comment by jamesge** [comment]
一致性哈希的虚拟节点不能防止“打到集中的几个server上”这个情况么？

**Comment by THCloud** [comment]
是希望热点区间能够分配到足够多的虚拟节点

**Comment by THCloud** [comment]
因为没有看到类似相关的资料。所以在想能不能把权重的元素带到一致性hash中。核心的诉求是当有热点range的时候能有更多的server去分摊流量压力。

**Comment by jamesge** [comment]
正文中“我们为每个server计算m个hash值”中的m就是虚拟节点的个数。

**Comment by THCloud** [comment]
我试试重新描述一下这个问题：
比如我的range是 0~1000的整数。  现在发现流量爆发在50~60这个小range内了。
n个server，每个server有m个hash值。总共有n*m个虚拟节点，去划分0~1000这个range。
诉求是50~60这个小range内能分配到尽可能多的server（就是server不同的虚拟节点。）

**Comment by THCloud** [comment]
emm还有个点就是，可能考虑到在hash的背景下，50到60这个range应该被hash到整个ring。然后结合hash，热点被均摊到所有server。但是这样可能带来另一个问题是：后端存储如果50到60这个区间挂掉了，会影响整个集群所有server。

**Comment by zyearn** [comment]
当你用cryptographic hash functions的时候，比如SHA1、md5，结果本来就是均匀分布的，不会出现热点在50到60这个区间的现象。另外，如果是防攻击者，加个salt似乎就可以了

**Comment by account-login** [comment]
楼主的意思应该是带权重的一致性哈希。

**Comment by GardianT** [comment]
我来回捞这个问题了。。。我在想这个是不是在说 Rendezvous hashing ？

**Comment by GardianT** [comment]
一致性hash的话，每个server处理的range是不确定的。对于有cache的系统，这样很可能有严重的cache颠簸问题；所以我理解这个问题是在说一致性hash有没有解决cache颠簸问题的比较好的方案

**Comment by tiankonguse** [comment]
1. 增大虚拟节点的个数， 可以降低热点集中在一个节点的概率

2. 如果某一个单Key是热点，那不断如何增加虚拟节点数，单key的热点都不可能被均摊

此时有两个方法
1. 多个一致性hash环
2. 只有一个一致性hash环，但是环后面的节点不是对应一个实例，而是多个实例

**Comment by jamesge** [comment]
@tiankonguse 说的对。如果对值的一致性要求放低，其实承载流量的server也可以在内存中缓存最热的N个Key。如果要在server间贡献热Key的缓存，可以对热Key加上后缀做进一步的散列。

**Comment by GardianT** [comment]
（流量本身的）key为url，后端存储按照这个url全局有序。流量的（写入）存储过程中牵扯若干的词典，词典可能以domain，或者site为单位。所以server如果以这样的url为range做sharding条件，可以比较有效的提升词典cache的命中率。比如一个server a，处理的range是 [a.test.com, b.test.com) ，那server只需要cache住一条词典（test.com）就足够了。但是这样的话，test.com下如果有流量爆发的场景，明显server a就负载极高，需要一些负载均衡措施。

如果我们使用了一致性hash，由于使用了hash等，[a.test.com, b.test.com) 可能就扩散到很多很多个（甚至所有的）server都有可能处理到。那这样的话，很多很多个server都需要cache test.com这条词典。同理，由于hash打破了这种domain，site的规律，所有的server都需要cache多条词典；而cache不可能无限增长。所以这样就有可能出现cache颠簸的问题（cache频繁的更新）

感觉这种场景下，产生了cache颠簸的主要原因应该是hash函数；而没有hash函数，又不知道如何将热点打散到全局。所以这种场景的负载均衡有什么好办法解决么？

**Comment by jamesge** [comment]
@GardianT 你说的这种情况不是一致性哈希能解决的。用到一致性哈希的场景的前提之一就是server加载什么数据由client决定，但这里机器加载什么是由机器自己决定的，类型场景还有机器学习model serving。这种场景中一个记录什么数据在哪里的高可用模块是无法绕开的，经常叫Meta Server或Placement Driver，实现可以用zk/etcd/consul之类的。有了这个模块，针对热点也就比较直接了，在多个server上多加载几份数据就行了。

**Comment by GardianT** [comment]
> @GardianT 你说的这种情况不是一致性哈希能解决的。用到一致性哈希的场景的前提之一就是server加载什么数据由client决定，但这里server加载什么是由自己决定的，类型场景还有机器学习model serving。这种场景中一个记录什么数据在哪里的高可用模块是无法绕开的，经常叫Meta Server或Placement Driver，实现可以用zk/etcd/consul之类的。有了这个模块，针对热点也就比较直接了，在多个server上多加载几份数据就行了。

需要一个meta server去监控热点，然后调度更多的server去均摊热点，是这样的意思么？
其实我也感觉一致性hash可能不解决问题。。。主要的关注点是这种场景下的负载均衡。

**Comment by GardianT** [comment]
@jamesge 
顺便多问下：这种场景下有机会或者比较成熟的方案 让server实现自适应的负载均衡么？
比如redis有slot的概念，server节点之间会通信每个server负责的slot信息。有节点失效的时候也重分配对应的slot，这样的。

**Comment by tiankonguse** [comment]
> （流量本身的）key为url，后端存储按照这个url全局有序。流量的（写入）存储过程中牵扯若干的词典，词典可能以domain，或者site为单位。所以server如果以这样的url为range做sharding条件，可以比较有效的提升词典cache的命中率。比如一个server a，处理的range是 [a.test.com, b.test.com) ，那server只需要cache住一条词典（test.com）就足够了。但是这样的话，test.com下如果有流量爆发的场景，明显server a就负载极高，需要一些负载均衡措施。
> 
> 如果我们使用了一致性hash，由于使用了hash等，[a.test.com, b.test.com) 可能就扩散到很多很多个（甚至所有的）server都有可能处理到。那这样的话，很多很多个server都需要cache test.com这条词典。同理，由于hash打破了这种domain，site的规律，所有的server都需要cache多条词典；而cache不可能无限增长。所以这样就有可能出现cache颠簸的问题（cache频繁的更新）
> 
> 感觉这种场景下，产生了cache颠簸的主要原因应该是hash函数；而没有hash函数，又不知道如何将热点打散到全局。所以这种场景的负载均衡有什么好办法解决么？
> 
> 不要太care这个是否sharding。我们这里sharding是因为主要希望cache命中率足够。主要是希望有这样的一个负载均衡方案，可以：
> 
> 1. 热点下的负载均衡
> 2. cache命中率足够，不会颠簸。

这个例子其实有几个关键的地方没有说清楚。
1. 你是使用域名(a.b.vom) 还是 url(a.b.com/xx/xx/xx) 作为一致性HASH的KEY的？
2. 如果是使用域名的话，那KEY量其实很少的，使用一致性HASH没意义了吧，你应该使用URL来当做KEY。  
3. 如果URL当做KEY依旧存在热点，那说明是固定的一个或几个页面非常热，这个时候，按照上面我提到的方法就可以解决：一致性HASH下是路由节点，每个路由节点下根据实际的访问量扩容即可。

当然也可以手动降低这个路由节点的权重（虚拟节点个数），从而将其他无关的流量导走（概率问题，不一定有效）。
至于你说的监控热点，自动化调整权重什么的，只是上面的手动操作改成自动操作，依旧是概率问题，不一定解决问题。  

扩容才是根本的解决方法。

**Comment by GardianT** [comment]
@tiankonguse  已经说的很清楚了。

1. 流量本身的key为url。
2. 流量爆发，热点不会固定的，数量也不会固定的。今天可能是test.com下爆发了大量的url，明天可能就是github.com下爆发了大量url。一致性hash下是路由节点，每个路由节点按实际访问量扩容。其实这个就是关键了，如何扩容可以让全局代价最小，热点消失如何缩容等等。

PS两点
1. 即使使用site or domain，key量也不少。。
2. 你的文章里没有具体说小set的设计。当然其实这种做法，和有一个master去调控全局所有server的range我理解没有本质差别。这里的负载均衡设计主要关键点就是这个range怎么调整才可以解决热点且代价最小。（映射到你的文章里应该就是小set包括谁吧？）

**Comment by tiankonguse** [comment]
@GardianT 了解你的意思了。

重新描述你的问题：会有某一个key突然特别热（新闻热点），这个量可能足够大到 一致性HASH对应的节点支撑不住。  

这种使用小SET不好，比较浪费资源，扩容难度也较大。
可以按照第二种设计：一致性HASH下面的节点是路由表，路由表下有若干机器来均摊流量。  
至于扩容，只需要在负载高的节点上加即可，缩容也一样。
