### ISSUE TITLE
redis protocol bug导致内存占用不停增加，耗尽内存

### ISSUE THREAD

**Issue by cdjingit** [apache/incubator-brpc#653]
**Describe the bug (描述bug)**
当first character错误时，redis protocol当做数据包不完整处理，导致socket read buf积压。
出现如下日志后，进程占用内存不停增长。
E0205 11:57:56.218215 70793 redis_reply.cpp:202] Invalid first character=1
E0205 11:57:56.218761 70793 redis_reply.cpp:202] Invalid first character=1
E0205 11:57:56.218951 70706 redis_reply.cpp:202] Invalid first character=1

**To Reproduce (复现方法)**
线上触发原因未知。目前这个问题出现过两次。可以通过hack代码复现，修改iobuf里的值，使得first character失效。方法如下,在如下函数中插入红框内的代码，修改response的iobuf里的数据，使得brpc redis protocol当做数据不完整处理。然后再恢复FLAGS_debug_redis为false。去除侵入的代码。
![20190214170752](https://user-images.githubusercontent.com/31362185/52836062-0a208d80-3124-11e9-8b29-569cb3cd935b.png)

**Expected behavior (期望行为)**
redis protocl的ParseRedisMessage()在消费iobuf里的数据错误时，应该返回MakeParseError(PARSE_ERROR_ABSOLUTELY_WRONG)，触发SetFailed()当前socket，然后重新建立tcp连接，现在是返回MakeParseError(PARSE_ERROR_NOT_ENOUGH_DATA)。最终导致iobuf里的数据在不停的累积，最终耗尽内存。
![20190214170537](https://user-images.githubusercontent.com/31362185/52836158-8d41e380-3124-11e9-8bcf-ce667a01f81d.png)

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
相关的parse函数确实可以考虑返回ParseError

**Comment by lorinlee** [comment]
#654 尝试修复这个问题，辛苦review @jamesge @cdjingit
