### ISSUE TITLE
Compile brpc with cmake  error

### ISSUE THREAD

**Issue by xyjiao** [apache/incubator-brpc#659]
[ 71%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/brpc/esp_message.cpp.o
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp:50:29: error: expected constructor, destructor, or type conversion before ‘(’ token
 GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
                             ^
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp: In function ‘void brpc::{anonymous}::protobuf_AssignDescriptorsOnce()’:
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp:52:5: error: ‘GoogleOnceInit’ is not a member of ‘google::protobuf’
     ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
     ^
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp:52:41: error: ‘protobuf_AssignDescriptors_once_’ was not declared in this scope
     ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                                         ^
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp: In function ‘void brpc::protobuf_AddDesc_esp_5fmessage_2eproto()’:
/unit-uskit/third_party/brpc/src/brpc/esp_message.cpp:81:57: error: invalid conversion from ‘void (*)(const string&) {aka void (*)(const std::basic_string<char>&)}’ to ‘void*’ [-fpermissive]
             "esp_message.proto", &protobuf_RegisterTypes);
                                                         ^
In file included from /usr/local/include/google/protobuf/generated_message_reflection.h:48:0,
                 from /unit-uskit/third_party/brpc/src/brpc/esp_message.h:24,
                 from /unit-uskit/third_party/brpc/src/brpc/esp_message.cpp:18:
/usr/local/include/google/protobuf/message.h:1115:15: error:   initializing argument 2 of ‘static void google::protobuf::MessageFactory::InternalRegisterGeneratedFile(const char*, void*)’ [-fpermissive]
   static void InternalRegisterGeneratedFile(const char* filename,
               ^
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/brpc/esp_message.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
make: *** [all] Error 2

**Comment by CalvinNeo** [comment]
请参考 https://github.com/brpc/brpc/issues/656
