### ISSUE TITLE
可以支持多进程模型吗

### ISSUE THREAD

**Issue by leihuxi** [apache/incubator-brpc#668]
多进程模型业务代码实现起来更简单, 
稳定性也更高.

**Comment by jamesge** [comment]
起多个进程就行了。多进程共享数据是很麻烦的。

**Comment by leihuxi** [comment]
多进程可以大大降低业务的开发成本, 多线程对业务开发人员还是有些要求的, 比如不小心使用了全局变量,
而且调用库很多都不是线程安全的, 多进程更不容易崩溃掉整个服务.
如果能支持可选是最好的.
