### ISSUE TITLE
在ConsistentHashingLoadBalancer中某些服务节点可能不会加在HASH环中

### ISSUE THREAD

**Issue by MR-workaholic** [apache/incubator-brpc#673]
**Describe the bug (描述bug)**
在`brpc/src/brpc/policy/consistent_hashing_load_balancer.cpp`的`size_t ConsistentHashingLoadBalancer::AddServersInBatch`函数中，在操作双buffer之前，对服务列表中的socket作一个`Socket::AddressFailedAsWell(servers[i].id, &ptr)`判断。但是在其他LB的`AddServersInBatch()`中却没有作这个对socket的判断，这是出于什么样的设计考虑呢？

是否存在一种情况，对于某个socket的AddressFailedAsWell返回-1,因此没有加进hash环中，但是稍后又恢复了。而在NamingServiceThread中，虽然周期性会执行NamingServiceThread::Actions::ResetServers，但是是会判断与上一次的服务列表出现偏差才会选择性执行OnRemovedServers或者OnAddedServers。因此是否会出现上述的恢复的服务节点没有被加进hash环中的问题？

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
可否去掉`size_t ConsistentHashingLoadBalancer::AddServersInBatch`中的`Socket::AddressFailedAsWell(servers[i].id, &ptr)`判断，毕竟在SelectServer函数中会对被选中的socket作Socket::Address(choice->server_sock.id, out->ptr)检查。

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
brpc/src/brpc/policy/consistent_hashing_load_balancer.cpp：
![image](https://user-images.githubusercontent.com/12267045/53464654-f7904780-3a85-11e9-931d-090c43b43609.png)

brpc/src/brpc/details/naming_service_thread.cpp：
![image](https://user-images.githubusercontent.com/12267045/53464718-548bfd80-3a86-11e9-8c59-098a558c5a2f.png)

**Comment by chenzhangyi** [comment]
这个是为了拿到server的endpoint

**Comment by MR-workaholic** [comment]
@chenzhangyi 那会出现我说的那种特殊情况吗？

**Comment by chenzhangyi** [comment]
addressfailedaswell只要这个server还在ns中，就会一直成功
