### ISSUE TITLE
对于cluster类型的channel， 在发送某个rpc请求时是否可以指定其中某台服务器

### ISSUE THREAD

**Issue by yujun777** [apache/incubator-brpc#676]
我们有一个场景是需要业务进行ack的，客户端向服务器发送一个请求并处理完服务器的响应后， 客户端会给该服务器发一条确认消息。 

问题：对于通过naming_service_url来初始化的channel，在发送某个brpc请求（上面的业务确认消息）时，是否可以指定endpoint ？ 还是只能再创建一个新的指定endpoint的channel ?

先谢谢各位大佬了 ~~

**Comment by jamesge** [comment]
通过controller.remote_side()取到endpoint，然后新建一个channel做rpc，发完rpc那个channel就可以析构，只要连接方式是单链接或连接池，背后的连接是复用的。

**Comment by reachfish** [comment]
好的， 谢谢戈大！
