### ISSUE TITLE
关于一致性hash只支持32位key问题

### ISSUE THREAD

**Issue by hairet** [apache/incubator-brpc#678]
**Describe the bug (描述bug)**

现在https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/consistent_hashing_load_balancer.cpp里面会有32位hash key限制
![image](https://user-images.githubusercontent.com/7167017/53726205-7c28fe80-3ea8-11e9-9742-7814879b9951.png)

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

想问下只支持32位是处于什么考虑，因为现在我们这边想自行改成64位，初看就是把相关变量以及Node.hash以及ConsistentHashingLoadBalancer::_hash函数改成64位即可
想问下还有没有别的坑
**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by hairet** [comment]
看了下，是不是因为murmurhash3没有64位版本的问题？

**Comment by hairet** [comment]
已经自行基于google cityhash,做了一次Hash128to64来封装解决

**Comment by dapengbusi** [comment]
一致性hash，你提到的这个原因，这也是一方面原因。但我理解，一致性hash之所以选32位最大值，是因为虚拟节点个数，一般最大值也就这个。当然你也可以设置成16位的，任何你想设置的数字，但需要保证，虚拟节点对应的实体ip，分布较为均匀即可。
