### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by walterzhaoJR** [apache/incubator-brpc#682]
**Describe the bug (描述bug)**
![image](https://user-images.githubusercontent.com/22393698/54082492-9b64d780-4351-11e9-88b4-c6b53dafce6f.png)
<img width="1440" alt="屏幕快照 2019-03-10 下午4 28 13" src="https://user-images.githubusercontent.com/22393698/54082530-ff879b80-4351-11e9-9b30-fdf4be88607b.png">

**To Reproduce (复现方法)**
compile

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:  4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Compiler:gcc version 6.1.0 (GCC)
brpc: master branhc
protobuf:master branch

**Additional context/screenshots (更多上下文/截图)**

**Comment by chenzhangyi** [comment]
先使用protobuf3.6或者更低的版本

**Comment by walterzhaoJR** [comment]
ok let me have a try

**Comment by wwbmmm** [comment]
master已支持新版protobuf
