### ISSUE TITLE
Thrift protocol中序列化的请求时，writeStructBegin 和 writeFieldBegin中的服务名和请求的名是固定的。无法定制

### ISSUE THREAD

**Issue by cdjingit** [apache/incubator-brpc#685]
**Describe the bug (描述bug)**
[如题：]

thrift_protocol.cpp的SerializeThriftRequest函数中
```
        char struct_begin_str[32 + method_name.size()];
        char* p = struct_begin_str;
        memcpy(p, "ThriftService_", 14);  // 这里的service name写死了 ThriftService
        p += 14;
        memcpy(p, method_name.data(), method_name.size());
        p += method_name.size();
        memcpy(p, "_pargs", 6);
        p += 6;
        *p = '\0';
        xfer += oprot.writeStructBegin(struct_begin_str);
        xfer += oprot.writeFieldBegin("request", ::apache::thrift::protocol::T_STRUCT, 
                                                        THRIFT_REQUEST_FID);  // 这里的请求名称写死了 “request”
````
**Expected behavior (期望行为)**
由用户定制。

**Comment by cdjingit** [comment]
@kenshinxf

**Comment by kenshinxf** [comment]
> **Describe the bug (描述bug)**
> [如题：]
> 
> thrift_protocol.cpp的SerializeThriftRequest函数中
> 
> ```
>         char struct_begin_str[32 + method_name.size()];
>         char* p = struct_begin_str;
>         memcpy(p, "ThriftService_", 14);  // 这里的service name写死了 ThriftService
>         p += 14;
>         memcpy(p, method_name.data(), method_name.size());
>         p += method_name.size();
>         memcpy(p, "_pargs", 6);
>         p += 6;
>         *p = '\0';
>         xfer += oprot.writeStructBegin(struct_begin_str);
>         xfer += oprot.writeFieldBegin("request", ::apache::thrift::protocol::T_STRUCT, 
>                                                         THRIFT_REQUEST_FID);  // 这里的请求名称写死了 “request”
> ```
> **Expected behavior (期望行为)**
> 由用户定制。

想问一下， 这里用户定制的场景和目的是？ 现在不能定制的影响是？如有有影响能提供个bad case例子吗？

**Comment by cdjingit** [comment]
因为有些服务server端的实现不是基于brpc的。比如，我们现在开发brpc支持cassandra thrift，
就有很多不同的方法和请求名称。
这里似乎应该直接调用req->raw_instance()->Write(oport) 。直接写入整个请求的struct，就可以。比如
/example/thrift_extension_c++/gen-cpp的例子

```
179 void EchoServiceClient::send_Echo(const EchoRequest& request)
180 {
181   int32_t cseqid = 0;
182   oprot_->writeMessageBegin("Echo", ::apache::thrift::protocol::T_CALL, cseqid);
183 
184   EchoService_Echo_pargs args;  
185   args.request = &request;  
186   args.write(oprot_);  // args作为raw_instance()传入 直接调用thrift生成的代码写入就可以
187 
188   oprot_->writeMessageEnd();
189   oprot_->getTransport()->writeEnd();
190   oprot_->getTransport()->flush();
191 }

```

**Comment by jamesge** [comment]
这个struct叫什么无所谓的，你说的是不是多args情况下如何传入的问题

**Comment by cdjingit** [comment]
不是多参数的问题，是指序列化到buf的struct名称 和field名称无所谓？不影响server解析？不会吧

**Comment by cdjingit** [comment]
ok 了解了 所谓半描述的 只要field顺序不变就可以。那就没问题了。多参数的情况，是当作一个struct里的多个fields处理的，没有问题。
