### ISSUE TITLE
bthread_cond_signal中的一点疑问

### ISSUE THREAD

**Issue by sige5566** [apache/incubator-brpc#688]
bthread::CondInternal* ic = reinterpret_cast<bthread::CondInternal*>(c);
如何理解 ic is probably dereferenced after fetch_add,

**Comment by hairet** [comment]
bthread_cond_wait里面会判断ic->seq,即如果ic->seq被fetch_add了，则存在一个可能性是wait的bthread在butex_wait里面还未进入代码阻塞（pthread的butex_wait_from_pthread或者bthread的sched），已经因为expected_value被改变而直接退出bthread_cond_wait。
