### ISSUE TITLE
cpu profile 问题

### ISSUE THREAD

**Issue by cxxcunow** [apache/incubator-brpc#690]
直接下载代码，默认参数编译brpc和echo c++的test例子，运行echo_server，报错：
Check failed: !internal_init_start_has_run: Heap-check constructor called twice.  Perhaps you both linked in the heap checker, and also used LD_PRELOAD to load it?

请问这个怎么弄？

**Comment by tonyboxes** [comment]
clone master，编译brpc和example/multi_threaded_echo_server，直接运行我也出现这个

**Comment by xiaohuifirst** [comment]
同问，编译所有使用DBRPC_ENABLE_CPU_PROFILER的程序，运行都会报Check failed: !internal_init_start_has_run: Heap-check constructor called twice.  Perhaps you both linked in the heap checker, and also used LD_PRELOAD to load it?
只能关掉这个然后取消连接GPERFTOOLS_LIBRARIES才可以正常运行。

**Comment by xiaohuifirst** [comment]
找到原因了，因为libtcmalloc.so与libtcmalloc_and_profiler.so同时连接到同一个程序中时，启动会报那个Check failed错误。
    我的情况是，直接拉取leveldb的master分支代码，然后编译，默认情况下leveldb会把tcmalloc动态库连接到libleveldb.so，而libbrpc.so又连接了leveldb的so，导致libbrpc.so链接了libtcmalloc.so。
    而在echo例子开启DBRPC_ENABLE_CPU_PROFILER时，又会链接上libtcmalloc_and_profiler.so，最终echo例子同时链接了libtcmalloc.so与libtcmalloc_and_profiler.so，启动报错。
    解决方法：把leveldb的CMakeList.txt中开启tcmalloc的配置注释掉，重新编译安装leveldb库，然后再重新编译安装brpc动态库，最后重新生成echo例子，可以跑起来了。
