### ISSUE TITLE
nameservice can't select server

### ISSUE THREAD

**Issue by xuxiping** [apache/incubator-brpc#696]
**Describe the bug (描述bug)**
         nameservice can't select server after modify system time.

**To Reproduce (复现方法)**
         modify system time.

**Expected behavior (期望行为)**
         

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
什么nameservice?
