### ISSUE TITLE
Fail to find protoc

### ISSUE THREAD

**Issue by darrenwang00** [apache/incubator-brpc#698]
**Describe the bug (描述bug)**
centos7   安装安装完所有依赖，

sh config_brpc.sh --headers=/usr/include --libs=/usr/lib64

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: 
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
![屏幕快照 2019-03-23 下午1 12 21](https://user-images.githubusercontent.com/7533358/54861924-50918980-4d6d-11e9-8897-458f18ac7662.png)

PROTOC=$(find_bin_or_die protoc)

protoc bin not  install  in /usr/lib64 ?

**Comment by darrenwang00** [comment]
in centos , the protoc install in   /usr/bin/protoc

**Comment by zyearn** [comment]
try this: sh config_brpc.sh --headers=/usr/include --libs="/usr/lib64 /usr/bin/"

**Comment by darrenwang00** [comment]
> try this: sh config_brpc.sh --headers=/usr/include --libs="/usr/lib64 /usr/bin/"

ok ,  make success
