### ISSUE TITLE
grpc迁移brpc问题

### ISSUE THREAD

**Issue by koujian** [apache/incubator-brpc#700]
grpc中根据pb文件转化的函数调用例子如下，第一个参数的类型是ClientContext*。但是brpc示例中SayHello的第一个参数是RpcController*类型，是因为protoc.exe版本的原因吗？？
ClientContext context;
  // The actual RPC.
 Status status = stub_->SayHello(&context, request, &reply);

**Comment by zyearn** [comment]
ClientContext在brpc里面对应是Controller，把本来要赋给ClientContext值在Controller里面找到对应项。
```
ClientContext context;
Status status = stub_->SayHello(&context, request, &reply); 
```
替换成：
```
brpc::Controller cntl;
cntl.set_timeout_ms(...);
...
stub_->SayHello(&cntl, &request, &reply, NULL); 
if (cntl.Failed()) {
...
}
```

**Comment by koujian** [comment]
这样做编不过的，类型都不一致。现在用proto.exe生成了helloworld.grpc.pb.h,helloworld.grpc.pb.cc;helloworld.pb.h、helloworld.pb.cc；helloworld.grpc.pb.h中service类派生自grpc::service而不是google::protobuf::service，是不是我生成时用的插件不对？

**Comment by zyearn** [comment]
需要把grpc自带的插件删掉

**Comment by koujian** [comment]
不使用grpc自带的插件无法支持service语义，请问是要下载哪个插件来支持service语义

**Comment by koujian** [comment]
请问你们使用的是proto3吗?

**Comment by zyearn** [comment]
不需要用任何插件，具体怎么生成service，参考一下example吧，然后把你的实现类改成继承生成的service

**Comment by koujian** [comment]
谢谢，忘记加option cc_generic_services = true;了。
