### ISSUE TITLE
[grpc-java-client] grpc java client call brpc server get INTERNAL: HTTP/2 error code: FLOW_CONTROL_ERROR 

### ISSUE THREAD

**Issue by Xavier1994** [apache/incubator-brpc#704]
**Describe the bug (描述bug)**
I use a grpc-java-client to call brpc server, And I just use one grpc's managed channel, but i have multi threads to use this managed channel to init grpc's blocking stub.  and call the brpc server. But i get a FLOW_CONTROL_ERROR. my request and response is small enough. 
I am curious about if my behavior is correct 

**To Reproduce (复现方法)**
just above

**Expected behavior (期望行为)**
I expect the call can return successfully

**Versions (各种版本)**
OS: CentOS 7.4
Compiler: gcc 8.3
brpc:0.9.5
protobuf: 3.6.1

**Additional context/screenshots (更多上下文/截图)**
io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: FLOW_CONTROL_ERROR
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:233)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:214)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:139)

**Comment by jamesge** [comment]
Did the RPC succeed when there's only one thread?
