### ISSUE TITLE
Received request 慢问题

### ISSUE THREAD

**Issue by phye** [apache/incubator-brpc#705]
Hi,
根据server_debug 文档，峰值 bthread_worker_usage (12)远小于 bthread_worker_count(24)，process_cpu_usage 11.7左右，也远小于system_core_count(48)，但是此时却发现server端QPS无法进一步提升，查看rpcz发现请求收的很慢。想问一下这样现象的可能原因是什么呢？

PS：服务这里有比较重的计算逻辑，单个请求处理完成，需要耗时50ms左右，但是现在发现QPS到了200就上不去了，理论上应该有 1/0.05 * 24 ~= 480 才对。

Thanks!
```log
[root@9 /data/home/phye/ws/]# curl http://127.0.0.1:50053/rpcz?trace=faad30c0c260147d
2019/03/27-17:38:03.188328 Received request(25035) from 9.43.176.143:47599 baidu_std log_id=0 trace=faad30c0c260147d span=a3885e8717f01393 parent_span=6a1eef85f6e13cf2
17:38:03.307673    .119345 Processing the request in a new bthread
17:38:03.309096    .  1423 Enter phye.RPCCall
17:38:03.367399    . 58303 Leave phye.RPCCall
17:38:03.367599    .   200 Responded(2664)
```

**Comment by jamesge** [comment]
你这服务已经严重拥塞了，先寻找一下拥塞原因吧，如锁，资源限制etc

**Comment by phye** [comment]
我不是很明白，为什么拥塞严重了bthread_worker_usage只有50%呢？既然worker充足，应该不至于收包慢？

**Comment by phye** [comment]
进一步排查了一下服务，QPS高的时候几乎每个worker线程都被阻塞的系统调用阻塞了，导致EDISP无法快速获得新请求。
又看了一下 FAQ，才发现这个问题早已列出来了：
https://github.com/apache/incubator-brpc/blob/master/docs/cn/bthread.md#q%E8%8B%A5%E6%9C%89%E5%A4%A7%E9%87%8F%E7%9A%84bthread%E8%B0%83%E7%94%A8%E4%BA%86%E9%98%BB%E5%A1%9E%E7%9A%84pthread%E6%88%96%E7%B3%BB%E7%BB%9F%E5%87%BD%E6%95%B0%E4%BC%9A%E5%BD%B1%E5%93%8Drpc%E8%BF%90%E8%A1%8C%E4%B9%88

**Comment by ryankeke** [comment]
@phye , 请问这个问题是怎么解决的，我也遇到了同样的问题
