### ISSUE TITLE
NamingService 初始化过多导致LOG(FATAL)

### ISSUE THREAD

**Issue by ghost** [apache/incubator-brpc#708]
**Describe the bug (描述bug)**
Channel 使用NamingService 初始化， 当Channel过多时导致LOG(FATAL)  进程崩溃。
pthread_key_create 超过系统限制 1024。
https://github.com/apache/incubator-brpc/blob/19f3e87409af789cb17b8ef004b5a5aff7540263/src/butil/containers/doubly_buffered_data.h#L273-L284

**To Reproduce (复现方法)**
新建超过1024个 NamingService 的Channel。

**Expected behavior (期望行为)**
不崩溃。

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

![图片](https://user-images.githubusercontent.com/38487648/55148350-02242680-5183-11e9-8616-0dec88c75e8d.png)

**Comment by x-x-p** [comment]
#708

**Comment by wwbmmm** [comment]
最新master已修复
