### ISSUE TITLE
How to implement interceptor(or middleware)-like functionality before or after each rpc call?

### ISSUE THREAD

**Issue by altkatz** [apache/incubator-brpc#711]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

 I'm implementing a service which contains 8 rpc calls, and i want to do something (auth, logging, tracing, etc) before / after each of these rpc calls, how should i do that ? A similar issue already existed in grpc https://github.com/grpc/grpc/issues/9035 

**Describe the solution you'd like (描述你期望的解决方法)**
How to do it in a clean and safe way?

**Describe alternatives you've considered (描述你想到的折衷方案)**
Currently I'm considering sub-classing brpc::ClosureGuard and add logging/tracing logic there, but is that even possible ?, if so, is it safe?

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
[client-side auth](https://github.com/apache/incubator-brpc/blob/master/docs/en/client.md#authentication), [server-side auth](https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md#verify-identities-of-clients), [tracing](https://github.com/apache/incubator-brpc/blob/master/docs/cn/rpcz.md) (no english doc yet). As for logging, it's more likely to be temporarily added for debugging, with the source code in hand, I think you can add logging anywhere you like.

**Comment by altkatz** [comment]
Thanks, i'll look into it.
