### ISSUE TITLE
如何使用channel？

### ISSUE THREAD

**Issue by haolujun** [apache/incubator-brpc#714]
HI ：
     当我并发请求同一个IP和端口后，结果经常会混乱。我每次请求都是用不同的channel。请问一下大神，我如何才能保证两次请求的结果不混乱呢？需要用connection_group? 那么connection_group需要做一个全局唯一哈希么？现在我侧测试结果是，只要connection_group相同，那么结果就会混乱。求大神给一个解决方案。多谢！！！

**Comment by jamesge** [comment]
举个例子具体描述一下你提到的"混乱"吧，包括协议、连接方式、版本等重要信息。

**Comment by haolujun** [comment]
HI：
     大神，我刚刚看了一下以往的issue，发现了这个，https://github.com/apache/incubator-brpc/issues/454，我应该是和这里面一样的问题。已经知道怎么解决了，多谢！！！

**Comment by haolujun** [comment]
问题已解决
