### ISSUE TITLE
brpc的rpcz是否支持客户端传递trace id

### ISSUE THREAD

**Issue by Xavier1994** [apache/incubator-brpc#718]
在rpcz中, trace id是rpc内部生成的. 
比如 
2019/04/07-17:56:54.780385    .   110 S trace=cc425628f80284ae span=cc425628f802ff59 log_id=0 bpn.BPNRpcService.Search(194)=889 [OK]

但是在一个请求的生命周期中, 在自己的应用层可能也有一个跟踪请求生命周期执行的trace id, 比如可以在客户端生成, 然后在应用层打日志的时候将trace id打出来. 

所以想问rpcz中的trace id是否支持设置, 这样的话就可以将两边统一, 更完整地观察到请求的生命周期

**Comment by jamesge** [comment]
如果是在程序的运行日志增加自己的trace-id，看上去也并不依赖rpcz；如果是在rpcz中的日志中增加自定义日志，可以调用TRACEPRINTF，但如果还要求能按自己的trace-id进行高效率的搜索和展示，那目前还不行。

**Comment by Xavier1994** [comment]
@jamesge rpcz中会显示一个log id, 这个log id是否在在server端接收到请求的时候创建的controller中调用set_log_id方法设置的呢

**Comment by jamesge** [comment]
这个功能一直没有文档说明，以至于都忘记了。这个log-id确实是可以的，并且支持按其做过滤。其余支持过滤的字段可以参考[这里](https://github.com/apache/incubator-brpc/blob/master/src/brpc/builtin/rpcz_service.cpp#L408)
