### ISSUE TITLE
关于volatile关键字

### ISSUE THREAD

**Issue by yuinm** [apache/incubator-brpc#720]
关于volatile能否给科普一下，查资料怎么说的都有，代码里有好多地方用到volatile看起来很晕。
只是知道volatile能避免编译器优化。
https://www.zhihu.com/topic/20034193/top-answers 这个说法是否正确(KE meng 这个人的回答)。

这个宏我理解成强制某个变量是volatile的。
#define ACCESS_ONCE(x) (*(volatile typeof(x) *)&(x))

@jamesge 
希望可以了解到什么时候应该用volatile 
非常感激。

**Comment by jamesge** [comment]
除非写硬件驱动碰到程序不可控的内存修改，一般用不到。当然权威答案可能得去问写编译器的，但一般例子中以两个线程共享一个变量云云举例，我觉得过度低估编译器了，这一点上和带gc的语言中的逃逸分析是有相似性的，编译器完全可以保守处理，或留至链接时优化。

**Comment by skilxnTL** [comment]
基本可以归纳为：只在硬件编程中有用。
一个地址的值可能被程序以外的环境修改的场景下，这个关键词才有用处。

**Comment by zyearn** [comment]
一些补充：如果想知道为什么会被硬件修改RAM，看一下 https://en.wikipedia.org/wiki/Memory-mapped_I/O。

**Comment by yuinm** [comment]
谢谢.这样就放心了.
