### ISSUE TITLE
mac 10.13.6 编译出错

### ISSUE THREAD

**Issue by xuexiangjys** [apache/incubator-brpc#726]
**Describe the bug (描述bug)**

ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbrpc.dylib] Error 1

**To Reproduce (复现方法)**
$ sh config_brpc.sh --headers=/usr/local/include --libs=/usr/local/lib --cc=clang --cxx=clang++
$ make

**Expected behavior (期望行为)**
编译通过

**Versions (各种版本)**
OS: mac 10.13.6
Compiler:
brpc:
protobuf:3.6.1

**Additional context/screenshots (更多上下文/截图)**
Packing libbrpc.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(atomicops_internals_x86_gcc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(asan_invalid_access.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(thread_restrictions.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(mesalink_ssl_helper.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(baidu_naming_service.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libbrpc.a(giano_authenticator.o) has no symbols
Linking protoc-gen-mcpack
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreGraphics.framework/CoreGraphics.tbd and library file /System/Library/Frameworks//CoreGraphics.framework/CoreGraphics are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreText.framework/CoreText.tbd and library file /System/Library/Frameworks//CoreText.framework/CoreText are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Foundation are out of sync. Falling back to library file for linking.
Linking libbrpc.dylib
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreGraphics.framework/CoreGraphics.tbd and library file /System/Library/Frameworks//CoreGraphics.framework/CoreGraphics are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreText.framework/CoreText.tbd and library file /System/Library/Frameworks//CoreText.framework/CoreText are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Security.framework/Security.tbd and library file /System/Library/Frameworks//Security.framework/Security are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//Foundation.framework/Foundation.tbd and library file /System/Library/Frameworks//Foundation.framework/Foundation are out of sync. Falling back to library file for linking.
Undefined symbols for architecture x86_64:
  "_BN_get_rfc2409_prime_1024", referenced from:
      brpc::SSLDHInit() in ssl_helper.o
      brpc::policy::DHWrapper::do_initialize() in dh.o
  "_BN_get_rfc3526_prime_2048", referenced from:
      brpc::SSLDHInit() in ssl_helper.o
  "_BN_get_rfc3526_prime_4096", referenced from:
      brpc::SSLDHInit() in ssl_helper.o
  "_BN_get_rfc3526_prime_8192", referenced from:
      brpc::SSLDHInit() in ssl_helper.o
  "_DH_get0_key", referenced from:
      brpc::policy::DHWrapper::initialize(bool) in dh.o
      brpc::policy::DHWrapper::copy_public_key(char*, int*) const in dh.o
  "_DH_set0_pqg", referenced from:
      brpc::SSLDHInit() in ssl_helper.o
      brpc::policy::DHWrapper::do_initialize() in dh.o
  "_OPENSSL_init_ssl", referenced from:
      brpc::GlobalInitializeOrDieImpl() in global.o
  "_OPENSSL_sk_num", referenced from:
      brpc::ExtractHostnames(x509_st*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in ssl_helper.o
  "_OPENSSL_sk_pop_free", referenced from:
      brpc::ExtractHostnames(x509_st*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in ssl_helper.o
  "_OPENSSL_sk_value", referenced from:
      brpc::ExtractHostnames(x509_st*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*) in ssl_helper.o
  "_SSL_CTX_set_options", referenced from:
      brpc::SetSSLOptions(ssl_ctx_st*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, brpc::VerifyOptions const&) in ssl_helper.o
  "_X509_getm_notAfter", referenced from:
      brpc::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, x509_st*, char const*) in ssl_helper.o
  "_X509_getm_notBefore", referenced from:
      brpc::Print(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, x509_st*, char const*) in ssl_helper.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libbrpc.dylib] Error 1

**Comment by xuexiangjys** [comment]
openssl的问题，修改了config.mk就解决了
```
HDRS=/usr/local/Cellar/openssl/1.0.2r/include /usr/local/include/ /usr/local/include/node/
LIBS=/usr/local/Cellar/openssl/1.0.2r/lib /usr/local/lib
```

**Comment by wenweihu86** [comment]
#723
