### ISSUE TITLE
何时支持java client？

### ISSUE THREAD

**Issue by darrenwang00** [apache/incubator-brpc#735]

**Comment by jasonszang** [comment]
You can use HTTP protocol to access protobuf-based rpc services. From virtually anything that supports HTTP.
See https://github.com/apache/incubator-brpc/blob/master/docs/en/server.md#accessed-by-httph2

**Comment by wenweihu86** [comment]
@darrenwang00 you can try brpc-java, may be useful for you. 
https://github.com/baidu/brpc-java
