### ISSUE TITLE
树莓派上的编译问题

### ISSUE THREAD

**Issue by cg82616424** [apache/incubator-brpc#742]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
我想再树莓派上编译一下brpc

**Describe the solution you'd like (描述你期望的解决方法)**
我去掉了msse等x86平台的优化参数
但是由于是32位的系统，导致编译不过去。。。。

**Comment by cg82616424** [comment]
![image](https://user-images.githubusercontent.com/6222464/56458795-b3526100-63bd-11e9-9521-0c304b4f2b31.png)

**Comment by zyearn** [comment]
size_t is 32 bit in 32-bit machine. Try to replace 32UL with (size_t)32 and recompile your code. When all errors are resolved and code can be compiled successfully, pull request is welcomed to solve this issue.

**Comment by cg82616424** [comment]
[ 10%] Built target PROTO_LIB
[ 45%] Built target BUTIL_LIB
[ 45%] Building CXX object src/CMakeFiles/OBJ_LIB.dir/bthread/butex.cpp.o
{standard input}: Assembler messages:
{standard input}:7556: 错误：bad instruction `pause'
{standard input}:7620: 错误：bad instruction `pause'
{standard input}:7995: 错误：bad instruction `pause'
src/CMakeFiles/OBJ_LIB.dir/build.make:254: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/bthread/butex.cpp.o' failed
make[2]: *** [src/CMakeFiles/OBJ_LIB.dir/bthread/butex.cpp.o] Error 1
CMakeFiles/Makefile2:208: recipe for target 'src/CMakeFiles/OBJ_LIB.dir/all' failed
make[1]: *** [src/CMakeFiles/OBJ_LIB.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
i can not figure out how to solve this problem ....

**Comment by jamesge** [comment]
不支持32位系统。

**Comment by wasphin** [comment]
@jamesge 不支持 32 位系统是因为使用了什么 32 位系统中不支持的特性还是只是因为使用场景少而没考虑该问题? 有这方面的什么考虑吗?
