### ISSUE TITLE
BuiltinService不支持安全认证，可能导致一些支持热加载的gflag配置项被无端篡改

### ISSUE THREAD

**Issue by cdjingit** [apache/incubator-brpc#747]
**Describe the bug (描述bug)**
通过访问内置http服务，gflag配置项有可能被修改，导致服务非预期的行为。
```
if (mp != NULL &&
        mp->is_builtin_service &&
        mp->service->GetDescriptor() != BadMethodService::descriptor()) {
        // BuiltinService doesn't need authentication
        // TODO: Fix backdoor that sends BuiltinService at first
        // and then sends other requests without authentication
        return true;
}
```
[https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/http_rpc_protocol.cpp#L1173](url)

**Expected behavior (期望行为)**
支持http认证

**Comment by cdjingit** [comment]
请问一下，这个不支持认证的具体原因是什么呢？修复方案困难吗？

**Comment by jasonszang** [comment]
BuiltinService本来就不是开放给外网用户用的，如果需要对非可信方（比如外网）提供brpc服务，应该把内置服务分离到另一个端口，而且不要对外开放内置服务端口。

**Comment by cdjingit** [comment]
内网也不是绝对安全，安全团队的安全扫描也会导致所说的问题，目前已经发生过这个现象。主要是想知道加上认证会有什么问题？代码的comments中说是有bug，想了解这个背景

**Comment by jasonszang** [comment]
你说的这段comment里的TODO的背景我很久以前遭遇过这个，如果我没记错的话，这个问题是这样的，brpc的一个长连接只有第一个rpc需要鉴权，通过了后续的就不需要鉴权了，于是如果开放builtin service端口给客户端，那么客户端可以先发一个内部服务，然后再发未鉴权的业务服务，来绕过鉴权。
这个应该不是builtin service不支持鉴权的理由，我个人觉得builtin加鉴权应该是没问题的，只是之前认为builtin不应该对外开放所以没做。你可以问问项目维护的同学看看有没有别的坑在里面。

**Comment by cdjingit** [comment]
如果如你所说，可以使builtin service从另外的port上start。也可以配置builtin service自己的鉴权（和业务服务区分开来）。
