### ISSUE TITLE
brpc的错误码，对于HTTP client来说ERPCTIMEDOUT和EHTTP中的HTTP_STATUS_REQUEST_TIMEOUT 两种超时错误的区别是什么呢？

### ISSUE THREAD

**Issue by crazyjiang** [apache/incubator-brpc#750]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
一个是rpc的错误码，一个是http的status，两者会尽量一致，因为一些用户可能会习惯性地只看http的status而不判定cntl->Failed()与否，丛直觉上来说，这种代码应该仍能够正确运行。

**Comment by walterzhaoJR** [comment]
@jamesge 想请教下 对于client来说ERPCTIMEDOUT 这个超时主要意味着什么。是说明从client发起这次rpc请求的request到等待response的整个过程超时吗

**Comment by jamesge** [comment]
对，就是遇到了rpc的deadline，故超时后不会重试，对用户更可控。若需要等待一段时间后无返回便重试，对应的是backup request功能，可以搜索下文档。字面上类似的ETIMEDOUT是系统的错误码，代表连接超时。
