### ISSUE TITLE
There is a useless check in variable.cpp

### ISSUE THREAD

**Issue by lingbin** [apache/incubator-brpc#751]
https://github.com/apache/incubator-brpc/blob/cc6642bde45a804dc9fec95fa0c8b23432a12e15/src/bvar/variable.cpp#L203-L206

The check `if (names->size() < 32) ` is useless, because after a `std::vector.clear()`, its size is 0, so this is a useless check

I think the idea here should be to `resolve` the memory in advance, but the check here is really redundant, for it is always true

**Comment by jasonszang** [comment]
Guess they wanted `capacity`

**Comment by jamesge** [comment]
@jasonszang yes, this is a typo

**Comment by jasonszang** [comment]
Fixed in #757
