### ISSUE TITLE
请问下开源版本和公司内部版本的同步机制是怎样的？

### ISSUE THREAD

**Issue by skilxnTL** [apache/incubator-brpc#753]
目前是两者各自独立发展吗？后续是否会定期同步？这个同步应该 工作量巨大吧。。。。

**Comment by jamesge** [comment]
内外版本目录结构、命名空间、包含代码差异还是比较多的，所以很难自动化地patch。之前的方案是：开源版本中有一个[patch_from_baidu](https://github.com/apache/incubator-brpc/blob/master/tools/patch_from_baidu)，内部版本中有一个patch_from_github，然后定期手动同步，大部分diff都是可以自动patch的，所以工作量还好。但这个工作并没有明确的文档，所以我就不清楚目前的状况了。

**Comment by skilxnTL** [comment]
嗯嗯，我看github的版本已经增加了不少feature，确实不太好同步，谢谢。
