### ISSUE TITLE
对arm64平台支持吗

### ISSUE THREAD

**Issue by chenlei5662** [apache/incubator-brpc#756]
目前看context的实现里面，是用的x86的指令，是否有支持arm64指令的计划

**Comment by zyearn** [comment]
The [context lib](https://github.com/twlostow/libcontext) that brpc uses has already supported linux on arm64. But the version adopted by brpc maybe too old that new features are not added. If you have the demand to run your application on arm64, you can try to replace the context with the newest version and check whether it can be compiled as expected

**Comment by chenlei5662** [comment]
ok，thanks！
