### ISSUE TITLE
Centos 7.3运行example的echo_server报错

### ISSUE THREAD

**Issue by crise1990** [apache/incubator-brpc#761]
版本信息：
brpc-0.9.5
protobuf-3.6.1
gflags-2.2.1
glog-0.4.0

编译brpc和example/echo_c++ 没有异常，运行./echo_server时报错：
E0510 06:10:36.911083  2562 server.cpp:664] previous call to MaxConcurrencyOf() was failed, fix it before starting server
E0510 06:10:36.911213  2562 server.cpp:98] Fail to start EchoServer
E0510 06:10:36.911227  2562 server.cpp:1453] Can't clear services from Server[] which is UNKNOWN_STATUS

**Comment by crise1990** [comment]
plus, while making example/http_c++ ：

Compiling http_client.o
Linking http_client
Compiling benchmark_http.o
Linking benchmark_http
Generating http.pb.cc
Compiling http.pb.o
Compiling http_server.o
Linking http_server
http_server.o: In function `main':
/workspace/tools/brpc-0.9.5/example/http_c++/http_server.cpp:187: undefined reference to `brpc::ServerOptions::mutable_ssl_options()'
/workspace/tools/brpc-0.9.5/example/http_c++/http_server.cpp:188: undefined reference to `brpc::ServerOptions::mutable_ssl_options()'
/workspace/tools/brpc-0.9.5/example/http_c++/http_server.cpp:189: undefined reference to `brpc::ServerOptions::mutable_ssl_options()'
collect2: error: ld returned 1 exit status
make: *** [http_server] Error 1
rm http.pb.cc

**Comment by serverglen** [comment]
应该是用法问题，MaxConcurrencyOf() 应该发生在AddService后，server启动前。

closed, reopen if you have further ideas.
Thank you for your contributions!
