### ISSUE TITLE
支持Redis Sentinel

### ISSUE THREAD

**Issue by brianjcj** [apache/incubator-brpc#762]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by brianjcj** [comment]
有没有计划支持这个？好像比较难集成到brpc的ns＋lb的框架中？有思路吗？

**Comment by jamesge** [comment]
目前没有相关的计划，redis sentinel在redis生态里整体已经属于边缘化的状态了。
