### ISSUE TITLE
rpc 请求卡住了，不超时

### ISSUE THREAD

**Issue by lwmonster** [apache/incubator-brpc#763]
**Describe the bug (描述bug)**
rpc 请求卡住了，不超时

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**
超时报错

**Versions (各种版本)**
OS: Centos
Compiler: gcc 4.8.5
brpc: 
protobuf: 3.5.1

**Additional context/screenshots (更多上下文/截图)**
我加了些日志，发现卡在 channel.cpp  的 CallMethod 函数的 Join(correlation_id); 这里。

我的服务既作为brpc 的server ，也作为brpc 的client；作为server是用的thrift协议通信；作为client 是用的baidu_std+protobuf 协议通信的， 是否这样使用有问题？

**Comment by lwmonster** [comment]
大概知道原因了， 自己的 pthread 和 brpc 的 pthread 互相等待，造成死锁。

**Comment by yockie** [comment]
> pthread 和 brpc 的 pthrea

老哥，brpc的pthread为啥会等你自己的pthread？
