### ISSUE TITLE
brpc支持Prometheus收集，没有label维度的信息，类型限定是gauge

### ISSUE THREAD

**Issue by yineima** [apache/incubator-brpc#765]
这是brpc输出
![image](https://user-images.githubusercontent.com/7900766/57679653-7432cb00-765e-11e9-8604-4eb5078dea4e.png)

这是一般的promethus client的输出
![image](https://user-images.githubusercontent.com/7900766/57679718-9e848880-765e-11e9-850c-cf45d194ab91.png)

brpc的输出缺少label维度的信息，不便于promQL快速查询
并且产出都是gauge类型，缺少counter，summary这些类型
请问：
1.后续会支持label维度的产出吗
2.后续会支持除了gauge类型以外的产出吗？

@zyearn @jamesge @wanglun

**Comment by skilxnTL** [comment]
我理解 brpc 的 prometheus 是用来传输自己的 metric 信息的，而不是一套公开的机制，因此是不是对 counter summary 这些东西并没有什么需求，其实就是一堆统计信息

**Comment by peiyuanzheng** [comment]
我们也遇到同样的问题，解决方法是在自己的应用代码中，把metrics name 和 label 拼接成bvar，然后提供一个给Prometheus查询的服务，解析bvar回metrics name 和label。

**Comment by zyearn** [comment]
目前brpc内部统计的metric用gauge和summary就足够了，所以只输出了gauge和summary。如果需要用label来输出业务的统计数据，建议用Prometheus官方提供的cpp client

**Comment by wanglun** [comment]
> 目前brpc内部统计的metric用gauge和summary就足够了，所以只输出了gauge和summary。如果需要用label来输出业务的统计数据，建议用Prometheus官方提供的cpp client

能否将用户自定义的LatencyRecorder，也用summary导出？

**Comment by xu-tao777** [comment]
> 我们也遇到同样的问题，解决方法是在自己的应用代码中，把metrics name 和 label 拼接成bvar，然后提供一个给Prometheus查询的服务，解析bvar回metrics name 和label。

能麻烦您贴了一下，您这边的拼接示例吗？非常感谢！

**Comment by wwbmmm** [comment]
master已支持多维度bvar，支持输出多维度prometheus信息：https://github.com/apache/incubator-brpc/blob/master/docs/cn/mbvar_c%2B%2B.md
