### ISSUE TITLE
使用redis客户端时奇怪的200ms问题

### ISSUE THREAD

**Issue by haolujun** [apache/incubator-brpc#767]
HI 大神：
       在使用brpc的redis客户端访问redis时，发现很奇怪的长尾现象。redis的耗时在200ms处有一个特别明显的断层。如下图所示，下图时间单位是us。长尾处的时间基本都是200的倍数加上一小点零头，例如200+ms，400+ms，600+ms。我使用redis客户端，connection_type = pooled， max_retry = 3。查了一下brpc，发现只有一个connect_timeout默认值是200ms，于是乎我把connect_timeout设置成50ms，发现现象依旧200+ms，400+ms，600+ms，貌似并不是connect_timeout的问题。最后没办法，把backup_request_ms设置成50ms，这才没有了200+ms，400+ms，600+ms的现象。过程中也观察过redis-server端，server端并没有200ms的定时或者轮询参数设置，并且server端没有观察到超过200ms的请求。请大神帮忙参谋一下，会是哪里的问题呢。下面是我的redis耗时图，单位us。

![image](https://user-images.githubusercontent.com/10751631/57819376-c983ef00-77ba-11e9-819c-1cb02728ba9f.png)

**Comment by jamesge** [comment]
1. 之前设置backup_request_ms了么
2. 有不同延时请求的比例么？（cdf）

**Comment by haolujun** [comment]
之前没有设置过backup_request_ms，只设置了timeout_ms和connection_type两个参数。我自己根据日志统计过耗时比例，大概0.5%的请求会超过200ms，99.5%的请求在50ms以内，也就是说超过50ms的请求基本上全都是200+ms，400+ms，600+ms这种。

**Comment by account-login** [comment]
200ms 可能是 tcp 重发的时间。

**Comment by verydota** [comment]
看一下机器的 tcp 重传监控，是否tcp重传很高 。 200ms看起来是触发了 tcp重传 导致部分请求+200ms

**Comment by haolujun** [comment]
> 看一下机器的 tcp 重传监控，是否tcp重传很高 。 200ms看起来是触发了 tcp重传 导致部分请求+200ms

是的，应该是网络流量大，有偶尔的丢包现象，导致触发tcp重传，重传是的ttl最小值一般为200ms。
