### ISSUE TITLE
channel连接失败

### ISSUE THREAD

**Issue by GTHubT** [apache/incubator-brpc#768]
**client端初始化一个channel后保留指针，后续的rpc复用这个channel。server端不定期stop start，在某次server start后，client端channel连接不上了，Not connected to xxx yet。这个会是什么原因呢？
server是正常start的，应该可以排除time_wait。**

**Comment by jamesge** [comment]
在做健康检查，默认最多3秒后会连上。

**Comment by GTHubT** [comment]
thanks！
