### ISSUE TITLE
brpc 是否支持 访问tcp server的tcp client，如何实现兼容到框架中去

### ISSUE THREAD

**Issue by kevinmgyu** [apache/incubator-brpc#779]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
是

**Describe the solution you'd like (描述你期望的解决方法)**

我需要在brpc服务器中访问一个tcp server
**Describe alternatives you've considered (描述你想到的折衷方案)**
是否有兼容框架的tcp client，如果我自己写一个普通client的话，一般是阻塞的，没有用到框架的异步机制，怎么办？
**Additional context/screenshots (更多上下文/截图)**

实现思路

**Comment by kevinmgyu** [comment]
up

**Comment by yanglimingcn** [comment]
我理解tcp的client和server通讯，总归需要定义一种通信的协议，所以如果现有的比较通用的协议都不是你想要的，你可以实现你的私有协议。另外用protobuf定义协议很方便啊

**Comment by ipconfigme** [comment]
可以尝试定制protocol，也可以考虑用bthread/unstable.h中的bthread_xxx的类socket接口
