### ISSUE TITLE
啥时候开源关于PROTOCOL_HADOOP_SERVER_RPC这个的实现

### ISSUE THREAD

**Issue by xmm1989218** [apache/incubator-brpc#780]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by hubble-insight** [comment]
现在开源了吗？
