### ISSUE TITLE
brpc single模式下无法摘掉故障机器

### ISSUE THREAD

**Issue by scottzzq** [apache/incubator-brpc#787]
**Describe the bug (描述bug)**

使用brpc client访问下游服务，如果下游服务某台机器故障(模拟故障可以用iptables命令直接将目标ip数据包过滤掉)，这个时候brpc client仍然向故障机器发送请求，根本原因是brpc针对某个socket上出现的超时请求没有做额外的探测工作。如果是临时的出现的几次超时不做额外的检查一般不会有问题，但是极端情况下如果是机房级别的网线断开，这个时候不能及时做故障转移就会造成比较大的问题。

**To Reproduce (复现方法)**
模拟故障可以用iptables命令直接将目标ip数据包过滤掉

**Expected behavior (期望行为)**
期望能够及时屏蔽下游不可用的机器列表

**Versions (各种版本)**
OS:linux
Compiler:5.2
brpc:master
protobuf:2.5

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
可以试验下[熔断](https://github.com/apache/incubator-brpc/blob/master/docs/cn/circuit_breaker.md)

**Comment by scottzzq** [comment]
https://github.com/apache/incubator-brpc/blob/master/src/brpc/socket.cpp#L878 这一行直接调用了SetFailed，内部重新设置fd=-1, 理论上会执行到这一行https://github.com/apache/incubator-brpc/blob/master/src/brpc/socket.cpp#L1933，我们的系统遇到FATAL直接coredump了。 @jamesge

**Comment by scottzzq** [comment]
我自己实现的一种简单粗暴的屏蔽策略，测试的时候会走到：https://github.com/apache/incubator-brpc/blob/master/src/brpc/socket.cpp#L1933 我的代码大概的逻辑就是保存连续超时的次数，达到阈值直接调用SetFailed这个函数,最终走到L1933行，程序挂掉了，我取了两台机器当时socket的状态数据如下：
第一个
$4 = {static STREAM_FAKE_FD = 2147483647, static PROGRESS_INIT = 1, _versioned_ref = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {
        static _S_alignment = 8, _M_i = 3}, <No data fields>}, <No data fields>}, _shared_part = {<std::atomic<brpc::Socket::SharedPart*>> = {_M_b = {
        _M_p = 0x7f2e3387fd00}}, <No data fields>}, _nevent = {<std::atomic<int>> = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
        _M_i = 0}, <No data fields>}, <No data fields>}, _keytable_pool = 0x0, _fd = {<std::atomic<int>> = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
        _M_i = -1}, <No data fields>}, <No data fields>}, _tos = 0, _reset_fd_real_us = 1558802556182021, _remote_side = {ip = {s_addr = XXXX}, port = 8090}, 
  _local_side = {ip = {s_addr = 0}, port = 0}, _on_edge_triggered_events = 0x1353780 <brpc::InputMessenger::OnNewMessages(brpc::Socket*)>, _user = 0x7f314923ef90, 
  _conn = 0x0, _app_connect = {<std::__shared_ptr<brpc::AppConnect, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x0, _M_refcount = {_M_pi = 0x0}}, <No data fields>}, 
  _this_id = 8601, _preferred_index = 1, _hc_count = 0, _last_msg_size = 0, _avg_msg_size = 12083, _read_buf = {<butil::IOBuf> = {static DEFAULT_BLOCK_SIZE = 8192, 
      static INITIAL_CAP = 32, static INVALID_AREA = 0, {_bv = {magic = 0, start = 0, refs = 0x0, nref = 0, cap_mask = 0, nbytes = 0}, _sv = {refs = {{offset = 0, 
              length = 0, block = 0x0}, {offset = 0, length = 0, block = 0x0}}}}}, _block = 0x0}, 
  _last_readtime_us = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 716836113636}, <No data fields>}, <No data fields>}, 
  _parsing_context = {<std::atomic<brpc::Destroyable*>> = {_M_b = {_M_p = 0x0}}, <No data fields>}, _correlation_id = 0, _health_check_interval_s = 3, 
  _ninprocess = {<std::atomic<unsigned int>> = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, <No data fields>}, 
  _auth_flag_error = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, <No data fields>}, 
  _auth_id = {value = 35923106471208}, _auth_context = 0x0, _ssl_state = brpc::SSL_OFF, _ssl_session = 0x0, 
  _ssl_ctx = {<std::__shared_ptr<brpc::SocketSSLContext, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x0, _M_refcount = {_M_pi = 0x0}}, <No data fields>}, 
  _connection_type_for_progressive_read = brpc::CONNECTION_TYPE_UNKNOWN, _controller_released_socket = {<std::atomic<bool>> = {_M_base = {static _S_alignment = 1, 
        _M_i = false}}, <No data fields>}, _overcrowded = false, _fail_me_at_server_stop = false, _logoff_flag = {<std::atomic<bool>> = {_M_base = {
        static _S_alignment = 1, _M_i = false}}, <No data fields>}, _recycle_flag = {<std::atomic<bool>> = {_M_base = {static _S_alignment = 1, 
        _M_i = false}}, <No data fields>}, _error_code = 1009, _error_text = {static npos = 18446744073709551615, 
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7f2986450ba0 ""}, _M_string_length = 0, {
      _M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}, _agent_socket_id = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {
        static _S_alignment = 8, _M_i = 18446744073709551615}, <No data fields>}, <No data fields>}, _pipeline_mutex = {_native_handle = {__data = {__lock = 0, 
        __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, 
  _pipeline_q = 0x0, _id_wait_list_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
    __size = '\000' <repeats 39 times>, __align = 0}, _id_wait_list = {impl = 0x0, head = 0, size = 0, conflict_head = 0, conflict_size = 0}, 
  _last_writetime_us = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 716836113636}, <No data fields>}, <No data fields>}, 
  _unwritten_bytes = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, <No data fields>}, 
  _epollout_butex = 0x7f298586b780, _write_head = {<std::atomic<brpc::Socket::WriteRequest*>> = {_M_b = {_M_p = 0x0}}, <No data fields>}, _stream_mutex = {
    _native_handle = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 39 times>, __align = 0}}, _stream_set = 0x0, _message_count = {<std::__atomic_base<long>> = {static _S_alignment = 8, 
      _M_i = 0}, <No data fields>}, _timeout_count = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, 
  _last_failed_timestamp = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 9223372036854775807}, <No data fields>}}

第二个：
$5 = {static STREAM_FAKE_FD = 2147483647, static PROGRESS_INIT = 1, _versioned_ref = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {
        static _S_alignment = 8, _M_i = 4294967299}, <No data fields>}, <No data fields>}, _shared_part = {<std::atomic<brpc::Socket::SharedPart*>> = {_M_b = {
        _M_p = 0x7f6d02e89040}}, <No data fields>}, _nevent = {<std::atomic<int>> = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
        _M_i = 0}, <No data fields>}, <No data fields>}, _keytable_pool = 0x0, _fd = {<std::atomic<int>> = {<std::__atomic_base<int>> = {static _S_alignment = 4, 
        _M_i = -1}, <No data fields>}, <No data fields>}, _tos = 0, _reset_fd_real_us = 1558802940407031, _remote_side = {ip = {s_addr = XXXXX}, port = 8090}, 
  _local_side = {ip = {s_addr = 0}, port = 0}, _on_edge_triggered_events = 0x1353780 <brpc::InputMessenger::OnNewMessages(brpc::Socket*)>, _user = 0x7f6da944b080, 
  _conn = 0x0, _app_connect = {<std::__shared_ptr<brpc::AppConnect, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x0, _M_refcount = {_M_pi = 0x0}}, <No data fields>}, 
  _this_id = 1397, _preferred_index = 1, _hc_count = 0, _last_msg_size = 0, _avg_msg_size = 13654, _read_buf = {<butil::IOBuf> = {static DEFAULT_BLOCK_SIZE = 8192, 
      static INITIAL_CAP = 32, static INVALID_AREA = 0, {_bv = {magic = 0, start = 0, refs = 0x0, nref = 0, cap_mask = 0, nbytes = 0}, _sv = {refs = {{offset = 0, 
              length = 0, block = 0x0}, {offset = 0, length = 0, block = 0x0}}}}}, _block = 0x0}, 
  _last_readtime_us = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 716566117540}, <No data fields>}, <No data fields>}, 
  _parsing_context = {<std::atomic<brpc::Destroyable*>> = {_M_b = {_M_p = 0x0}}, <No data fields>}, _correlation_id = 0, _health_check_interval_s = 3, 
  _ninprocess = {<std::atomic<unsigned int>> = {<std::__atomic_base<unsigned int>> = {static _S_alignment = 4, _M_i = 1}, <No data fields>}, <No data fields>}, 
  _auth_flag_error = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, <No data fields>}, 
  _auth_id = {value = 71902047506782}, _auth_context = 0x0, _ssl_state = brpc::SSL_OFF, _ssl_session = 0x0, 
  _ssl_ctx = {<std::__shared_ptr<brpc::SocketSSLContext, (__gnu_cxx::_Lock_policy)2>> = {_M_ptr = 0x0, _M_refcount = {_M_pi = 0x0}}, <No data fields>}, 
  _connection_type_for_progressive_read = brpc::CONNECTION_TYPE_UNKNOWN, _controller_released_socket = {<std::atomic<bool>> = {_M_base = {static _S_alignment = 1, 
        _M_i = false}}, <No data fields>}, _overcrowded = false, _fail_me_at_server_stop = false, _logoff_flag = {<std::atomic<bool>> = {_M_base = {
        static _S_alignment = 1, _M_i = false}}, <No data fields>}, _recycle_flag = {<std::atomic<bool>> = {_M_base = {static _S_alignment = 1, 
        _M_i = true}}, <No data fields>}, _error_code = 110, _error_text = {static npos = 18446744073709551615, 
    _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, 
      _M_p = 0x7f6d26c5a000 "Fail to connect Socket{id=1397 addr=XXXXX:8090} (0x0x7f6d03367780): Connection timed out"}, _M_string_length = 95, {
      _M_local_buf = "\244", '\000' <repeats 14 times>, _M_allocated_capacity = 164}}, 
  _agent_socket_id = {<std::atomic<unsigned long>> = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, 
        _M_i = 18446744073709551615}, <No data fields>}, <No data fields>}, _pipeline_mutex = {_native_handle = {__data = {__lock = 0, __count = 0, __owner = 0, 
        __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}}, _pipeline_q = 0x0, 
  _id_wait_list_mutex = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
    __size = '\000' <repeats 39 times>, __align = 0}, _id_wait_list = {impl = 0x0, head = 0, size = 0, conflict_head = 0, conflict_size = 0}, 
  _last_writetime_us = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 716566117540}, <No data fields>}, <No data fields>}, 
  _unwritten_bytes = {<std::atomic<long>> = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, <No data fields>}, 
  _epollout_butex = 0x7f6d03231f00, _write_head = {<std::atomic<brpc::Socket::WriteRequest*>> = {_M_b = {_M_p = 0x0}}, <No data fields>}, _stream_mutex = {
    _native_handle = {__data = {__lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __list = {__prev = 0x0, __next = 0x0}}, 
      __size = '\000' <repeats 39 times>, __align = 0}}, _stream_set = 0x0, _message_count = {<std::__atomic_base<long>> = {static _S_alignment = 8, 
      _M_i = 0}, <No data fields>}, _timeout_count = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 0}, <No data fields>}, 
  _last_failed_timestamp = {<std::__atomic_base<long>> = {static _S_alignment = 8, _M_i = 9223372036854775807}, <No data fields>}}
  

@jamesge  麻烦帮忙看下，出现这个case的原因是啥，谢谢了！

**Comment by jamesge** [comment]
我并不知道你提到的”简单粗暴的屏蔽策略“是怎么写的，C++有太多理由coredump，所以还是建议你自己先review下代码，看看是否有内存相关的bug。

**Comment by scottzzq** [comment]
coredump的原因是这个是比较明确的，就是执行到L1933,最终调用了glog打印了FATAL日志导致的，现在看起来原因就是调用了socket的SetFailed方法，之后还能收到这个socket的可读事件，但是在StartInputEvent的时候其实发现fd被设置成-1了，我仔细看过SetFailed的代码，中间其实是有个WaitAndReset的，理论上执行完这个函数之后，fd已经从EventDispatch中删除掉了，不会再触发到可读事件了，但是现在的确出现这样的问题了。

**Comment by scottzzq** [comment]
我的关闭的策略和master中的熔断功能基本是一样的，都是调用SetFailed方法来做的，理论上如果启用了熔断功能也会有类似的问题的 @jamesge

**Comment by scottzzq** [comment]
https://github.com/apache/incubator-brpc/blob/master/src/brpc/socket.cpp#L693 能不能把这行挪到https://github.com/apache/incubator-brpc/blob/master/src/brpc/socket.cpp#L839这一行的位置，这样可以在健康检查开始之前就把socket注册的可读事件删除掉，这样可能就能避免上面提到的问题，你看这样可行吗 @jamesge

**Comment by scottzzq** [comment]
通过上面我发的Socket的信息，发现_versioned_ref 分别是3、4294967299，这个数字和0xFFFFFFFFul这个做&运算，结果都是3，说明外部对Socket句柄的引用计数是3，这也就是说在WaitAndReset(2)之后，的确有其他线程对Socket做了一次新的引用。@jamesge

**Comment by jamesge** [comment]
StartInputEvent里会先address一次，failed之后是address不到的，直接就退了，走不到L1933那里

**Comment by jamesge** [comment]
做健康检查也会address的，所以WaitAndReset之后引用超过2也是可能的（不过得通过AddressFailedAsWell）

**Comment by scottzzq** [comment]
是的，看代码逻辑的确是这样的，我看注释WaitAndReset(2)的时候不是已经把健康检查持有的句柄算进去了吗？看_hc_count=0，从现象上来看，多出来的引用计数的确是被StartInputEvent里面的Address给占用了。

**Comment by scottzzq** [comment]
@jamesge  这几天仔细看代码，线下做了多次尝试，今天终于复现出来了。原因如下：EventDispatch线程在某一次epoll_wait返回之后得到可读fd列表，之后依次调用fd的StartInputEvent函数，在执行比较慢的情况下(cpu非常繁忙)，假设某一个Socket还没有进入到StartInputEvent函数，此时别的线程调用了这个Socket的SetFailed函数，之后启动健康检查，之后新建连接成功，健康检查结果正常，调用了Socket的Revive函数，但是还没有调用ResetFileDescriptor，这个时候通过SocketId调用Address已经可以成功了，这个时候刚好又进入Socket的StartInputEvent，此时就会遇到fd=-1

**Comment by jamesge** [comment]
多谢详细的解释，看起来只要去掉EventDispatcher中的CHECK就解决问题了？

**Comment by scottzzq** [comment]
去掉的确不会core掉了，我还在确认下有没有其他副作用，比如能预料到的一个case就是，如果EventDistapch执行有延迟，如果刚好调用了ResetFileDescriptor之后，再调用StartInputEvent，这个时候时候fd就是合法的了，但是如果此时fd上并没有可读事件，仍然会触发一次InputMessenger::OnNewMessages，只要这个函数可以兼容这种情况，应该就没啥问题了 @jamesge

**Comment by jamesge** [comment]
这个不要紧，消息通知出现"假阳性"的后果只是白读了而已。

**Comment by scottzzq** [comment]
@jamesge  又出现一个新问题，在遇到EFAILEDSOCKET错误的时候，brpc默认会做重试，按照时间序一次发生下列事件：
IssueRPC: _current_call.nretry:0, _correlation_id:57144539873281, cid:57144539873282, _current_call.nretry:0, remote_side:10.207.149.57:22690
IssueRPC:  _current_call.nretry:1, _correlation_id:57144539873281, cid:57144539873283, _current_call.nretry:1, remote_side:11.20.124.17:22690
IssueRPC: _current_call.nretry:2, _correlation_id:57144539873281, cid:57144539873284, _current_call.nretry:2, remote_side:10.172.29.164:22690

EndRPC: error_code:0,info.id:57144539873283, current_id:57144539873284, _correlation_id:57144539873281, _current_call.nretry:2

这种情况下brpc仍然会打印FATAL并且coredump，原因就是 https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L798 这一行判断失败，问下这块能否改成  info.id <= current_id() && info.id >= _correlation_id？ 多谢了！
