### ISSUE TITLE
/proc/self/io report :Permission denied

### ISSUE THREAD

**Issue by loadrunit** [apache/incubator-brpc#788]
**Describe the bug (描述bug)**
brpc 警告
/brpc-0.9.5/src/bvar/default_variables.cpp:431] Fail to open /proc/self/io: Permission denied
但是cat /proc/self/io是可以访问的
**To Reproduce (复现方法)**
正常使用场景

**Expected behavior (期望行为)**
解决该警告， 因为该警告会打印到控制台， 引起用户反感

**Versions (各种版本)**
OS: CentOS7
Compiler:
gcc-7.3.0
brpc: 0.9.5
protobuf:2.6.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
这个看起来可能和你启动程序的方法有关，使得程序的权限不够

**Comment by loadrunit** [comment]
我直接将输出警告的那一行注释掉了：）

**Comment by verydota** [comment]
我遇到了类似的问题。直接注释掉会影响监控。 

问题来源是， 因为我们需要对裸盘操作， 所以给 二进制加了部分权限
setcap cap_sys_rawio,cap_sys_admin=eip  ./datanode】

加权限之后， 程序运行时无法 打开   /proc/self/io 。导致缺少bvar 监控值。

为二进制继续添加  cap_dac_read_search 权限后得以 可以解决权限问题。
