### ISSUE TITLE
bvar 中Adder是否存在上限

### ISSUE THREAD

**Issue by chyxyjh** [apache/incubator-brpc#796]
想请教一下，如果用bvar中的Adder类型来监控请求量，我对外输出的是用PerSecond类型封装的每秒请求，但是这个每秒请求也是基于Adder类型的请求累计统计出来的，那么随着请求总量的不断累计，会不会造成Adder存储达到其上限呢？如果存在，我应如何解决，定时清理Adder中的存储值？
感谢支持

**Comment by jamesge** [comment]
上限有两种：一种是内存放不下了，这是不存在的，因为adder只会存累加后结果；另一种是overflow了，如果类型宽度太小，确实有这个可能，那就换一个更宽的类型。

**Comment by chyxyjh** [comment]
上限的第二种，overflow，我个人理解是，如定义了Adder<int> request_adder，那么其最大存储便只有2*10^9左右，随着程序的运行，request_adder不断累加，便可能发生overflow，请问理解是否正确？
如果正确的话，overflow的结果只会导致累加结果错误是吗，比如当前request_adder累加到了2147483647，之后`request_adder << 1;`，request_adder中存储的值便因overflow被计算为-2147483648。
感谢支持

**Comment by chenzhangyi** [comment]
会，如果没有特殊的考虑， 建议定义Adder<int64_t>, 基本上不会有overflow的问题.
如果需要看一段时间的累加值，可以套上Window, 这个即使Adder本身溢出了，只要时间跨度不太夸张，结果也是准确的

**Comment by hanyunchang** [comment]
看代码，加入window绑定的变量是Adder<int64>, 那么window的get_value方法的返回值类型就是int64，也就是说在window_size内累加值也是可能溢出的。  "只要时间跨度不太夸张，结果也是准确的"  应该是这个意思吧？
