### ISSUE TITLE
bvar::Status是否能记录历史值

### ISSUE THREAD

**Issue by ShinanWu** [apache/incubator-brpc#798]
hi，请教一下，
使用bvar::Status做状态记录，在标签页“vars”中查询到的只是当前的值，没有历史记录和图表。  
看到自有的一些有历史记录和图表的var都是用PassiveStatus定义，这是问题的关键吗，是否需要使用PassiveStatus，这个应该是需要执行回调函数的时候才需要定义这个类型吧？bvar::Status能否用图表显示历史记录呢？  
先谢过了~

**Comment by jamesge** [comment]
bvar的作用就是记录当前值供监控系统搜集，不会向用户暴露历史值。"自有的一些有历史记录和图表的var"只是为了方面用户调试问题，且并不限定于PassiveStatus。

**Comment by ShinanWu** [comment]
bvar的作用就是记录当前值供监控系统搜集，不会向用户暴露历史值。"自有的一些有历史记录和图表的var"只是为了方面用户调试问题，且并不限定于PassiveStatus。
>>>那如果希望Status也可以方便的调试问题（图表显示变化），需要怎么做呢，有参考的demo吗?

**Comment by jamesge** [comment]
master head中数字型Status会出现历史曲线。不过一般来说服务中关注的都是累加值，会用其他带reduce语意的bvar，bvar::Status几乎用不到，所以这里你可能也要看下是否其他bvar能更好地满足需求。
