### ISSUE TITLE
brpc重试相关代码疑似有bug

### ISSUE THREAD

**Issue by scottzzq** [apache/incubator-brpc#799]
**Describe the bug (描述bug)**
brpc重试的相关代码有两处，分别如下
https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L596
https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L617

第一处重试之前创建_unfinished_call，第二处重试的地方没有创建_unfinished_call，这个疑似bug？
我们现在的确遇到这个问题,遇到EFAILEDSOCKET错误，经常走到https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L826 打印FATAL日志，进而引起coredump.

按照时间顺序依次发生的事件如下：
IssueRPC: _current_call.nretry:0, _correlation_id:57144539873281, cid:57144539873282, _current_call.nretry:0, remote_side:A:port
IssueRPC: _current_call.nretry:1, _correlation_id:57144539873281, cid:57144539873283, _current_call.nretry:1, remote_side:B:port
IssueRPC: _current_call.nretry:2, _correlation_id:57144539873281, cid:57144539873284, _current_call.nretry:2, remote_side:C:port

EndRPC: error_code:0,info.id:57144539873283, current_id:57144539873284, _correlation_id:57144539873281, _current_call.nretry:2

就会执行到https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L826 

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
这个不是bug，L596处是backup request的逻辑，对应的_current_call移入了_unfinished_call，而L617处直接结束_current_call了。

**Comment by scottzzq** [comment]
https://github.com/apache/incubator-brpc/blob/master/src/brpc/controller.cpp#L826 但是执行了这一行会挂掉，这个怎么解决呢？ @jamesge
