### ISSUE TITLE
bthread_id_t是否可以用一个指针取代

### ISSUE THREAD

**Issue by zhuchong0329** [apache/incubator-brpc#801]
bthread_id_t其实是一个64位ID，作用是作为一个correlation_id，在O(1)时间内找到对应的Controller。这种模式下是不是用一个指针就能到达目的了，而且应该会更快，至于lock和join这些操作，只要在对应的Controller里面加入mutex等类型就可以了吧？望brpc的大神解答一下疑惑。
补充：是为了避免频繁申请和释放内存么？

**Comment by skilxnTL** [comment]
这块儿确实有点复杂，但是一个简单的指针没法满足需求。
考虑 RPC 超时的场景下，这个指针在用户回调执行后就被销毁了。
所以至少得有一个 Global 的东西来记录目前已经创建的指针，并且引入类似 weak_ptr 的机制。
同时还要解决 ABA 的问题，请求超时->用户销毁 controller -> 用户创建新的 controller 发起新的请求
这个过程中后创建的 controller 的address 很可能和已经销毁的是相同的，那么就会错误的处理已经超时的请求的 response。

这么最后搞吧搞吧，搞出来跟现在估计也差不多了。

**Comment by zhuchong0329** [comment]
有道理，还要解决ABA的问题，感谢解答。
