### ISSUE TITLE
当 server.stop 时，NamingServiceThread导致core。

### ISSUE THREAD

**Issue by Tsrign** [apache/incubator-brpc#809]
**Describe the bug (描述bug)**
当使用server.Stop() 和 server.Join() 正常停止服务时，发现NamingServiceThread经常大概率产生SIGSEGV core， 特别是服务注册的service多，而且ns_access_interval默认为5秒时。 目前通过调大ns_access_interval至60或120测试能够很大程度降低这个core概率。 

猜测server.Stop() && server.Join()时，NamingServiceThread仍在周期性执行，并有访问将被析构内存的风险。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

在 server.stop()&&server.join()时，需要事先通知NamingServiceThread停止period run。

**Versions (各种版本)**
OS: CentOS release 4.3
Compiler: 4.8.2
brpc: 2014年的老版本，不确定新版本 brpc 是否有该问题。
protobuf:

**Additional context/screenshots (更多上下文/截图)**
![image](https://user-images.githubusercontent.com/10807479/59592001-bea5dc80-9121-11e9-918d-88aa6de2920f.png)

**Comment by jamesge** [comment]
这个看上去是BNS SDK的问题。

**Comment by Tsrign** [comment]
查看BNS SDK，发现其通过单例模式在.bss 段注册了一个 lrucache 实例， 想了解下， brpc当 server.stop && server.join 结束时，主线程退出，全局变量析构的过程中， NamingServiceThread是否未停止，还可能在 period run， 是否可能存在线程安全问题。

**Comment by skilxnTL** [comment]
server.join 也不会停掉主线程吧？。。。

**Comment by jamesge** [comment]
这个大概是因为bns中使用了一些会在程序退出时析构的static变量，作为一个lib，一般来说是要能正确地处理在main函数之前或之后运行的问题的。

**Comment by Tsrign** [comment]
> server.join 也不会停掉主线程吧？。。。

嗯，我的意思是问题出现在server.join返回之后，main函数便是正常return弹栈，开始析构整个进程的static和全局变量，怀疑是在这个析构过程中，子线程NamingServiceThread使用的BNS SDK仍在访问它注册的全局变量。

**Comment by Tsrign** [comment]
最终的trick方案：主线程退出main函数之前无线等待，等待外部的kill信号。
