### ISSUE TITLE
多client对单server发压在h2:grpc协议下无法压满qps

### ISSUE THREAD

**Issue by lorinlee** [apache/incubator-brpc#813]
**Describe the bug (描述bug)**
测试机64核，网卡3万兆
包大小约200Byte，简单的echo回包，网卡带宽不高

protocol使用baidu_std能压到qps 400w
切换到h2:grpc后到100w就不涨了，使用大概20个核，增加client(client在多台机器)会增大cpu使用，但是qps不变或降低，cpu压到满的火焰图如下
![image](https://user-images.githubusercontent.com/16054841/59711422-b04ce300-923d-11e9-863e-6584490ab3cd.png)
contention图如下：
![image](https://user-images.githubusercontent.com/16054841/59712440-d5daec00-923f-11e9-9554-b70263d2b19b.png)
调整event_dispatcher没什么效果，根据baidu_std的测试情况设置为了1

最开始用了jemalloc库，contention profile看je_tcache_bin_flush_small占比比较高，猜测是内存分配的问题
换ptmalloc在相同压力下qps 80w，使用20个核，一直加client能到85w就涨不动了
换tcmalloc在相同压力下qps 100w+，使用20个核，一直加client会降低一些qps，不过也在100w qps左右

在h2:grpc qps不能上涨的时候，增加baidu_std的client数量，qps会上涨，按目前client实现，单独加一个baidu_std client会加30w qps，再加一个还会涨30w

内存分配导致的并发上不去的猜测是否正确呢？有没有什么办法可以实锤

或者可能是什么原因呢

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: Linux 4.4.0
Compiler: GCC 4.9.2
brpc: 63e0c80821b1ecb892f746f8562e4808d6f047c7
protobuf: 3.5.1

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
h2:grpc能达到什么样的qps

**Comment by lorinlee** [comment]
> h2:grpc能达到什么样的qps

100w+ qps，用了30个核，issue表述有误，刚确认了下加client会增加server端cpu使用，但是qps不涨

**Comment by lorinlee** [comment]
更新了一些描述，以及压满cpu下的火焰图

**Comment by lorinlee** [comment]
contention的图也补了一下，有点长只截了je_tcache_bin_flush_small在的那块

**Comment by jamesge** [comment]
1. 看一下使用h2:proto是否有区别，上图中占比较大的PercentEncode是grpc特有的
2. 你上面的图是指server端的情况吧？client端是否可能成为瓶颈？

**Comment by lorinlee** [comment]
> 1. 看一下使用h2:proto是否有区别，上图中占比较大的PercentEncode是grpc特有的
> 2. 你上面的图是指server端的情况吧？client端是否可能成为瓶颈？

1. 压了一下h2:proto，表现是占用23核时能达到120w qps，客户端再加压直到压满服务端CPU(64核)，最终是140w qps，比h2:grpc高了一些
![image](https://user-images.githubusercontent.com/16054841/59791496-d38e9580-9304-11e9-817e-1575ee45274e.png)
![image](https://user-images.githubusercontent.com/16054841/59791513-e0ab8480-9304-11e9-936b-dfc7355f4719.png)

2. 是server情况，client应该不是瓶颈，server端CPU已经被打满了，h2:grpc是可以打满cpu的，但是20核就已经到100w qps了，再加客户端压满cpu(64核)，qps基本不变

**Comment by lorinlee** [comment]
h2:proto画了一个contention图，看着还是同样的地方
![image](https://user-images.githubusercontent.com/16054841/59791929-b8705580-9305-11e9-8509-f1a81897ded0.png)

**Comment by jamesge** [comment]
确认一下："增加client"指的是增加client进程的数量，而不是增加线程或是channel数量吧

**Comment by jamesge** [comment]
1. 看一下server端的bthread_worker_count和bthread_worker_usage是多少？排除线程数是瓶颈。
2. contention那个框虽然大，但上面的数字0.566(秒)占profiling的总时间(默认10秒)比例也不是很高。可以看看有无其他框，以及可以贴一下文字版的。
3. 一般来说，64核cpu肯定是numa架构。可以通过numactl --hardware看看有几个nodes，并尝试起对应个数的server，并把client平分加压看看差异是否较大。也许对不同协议的影响量不太一样。

**Comment by lorinlee** [comment]
> 确认一下："增加client"指的是增加client进程的数量，而不是增加线程或是channel数量吧

是进程数量

**Comment by lorinlee** [comment]
> 1. 看一下server端的bthread_worker_count和bthread_worker_usage是多少？排除线程数是瓶颈。
> 2. contention那个框虽然大，但上面的数字0.566(秒)占profiling的总时间(默认10秒)比例也不是很高。可以看看有无其他框，以及可以贴一下文字版的。
> 3. 一般来说，64核cpu肯定是numa架构。可以通过numactl --hardware看看有几个nodes，并尝试起对应个数的server，并把client平分加压看看差异是否较大。也许对不同协议的影响量不太一样。

下面的数据是h2:proto下cpu使用率接近跑满的数据
![image](https://user-images.githubusercontent.com/16054841/59819504-b8e70b80-935a-11e9-9470-295875945d47.png)
1. bthread_worker_count是65，bthread_worker_usage大概在40
![image](https://user-images.githubusercontent.com/16054841/59819337-f9925500-9359-11e9-9b3f-086c785291a2.png)
2. total看只有0.187s，那可能是有符号没有打出来嘛。butil:Mutex这个是bvar的，测baidu_std协议这个占比也挺高
![image](https://user-images.githubusercontent.com/16054841/59819383-2f373e00-935a-11e9-8f0b-eddc44554a72.png)
![image](https://user-images.githubusercontent.com/16054841/59819452-80dfc880-935a-11e9-9b9d-71ff7a1397aa.png)
3. 我测一下再给一些数据

**Comment by lorinlee** [comment]
再补下process_cpu_usage的信息
![image](https://user-images.githubusercontent.com/16054841/59820017-e7fe7c80-935c-11e9-83e9-b0558ad5ff91.png)
