### ISSUE TITLE
LALB 策略可能落入死循环

### ISSUE THREAD

**Issue by gtarcoder** [apache/incubator-brpc#820]
**Describe the bug (描述bug)**
LALB 策略在下游服务一段时间内超时频繁后，陷入不可用状态。 即使下游服务恢复，也无法逃出。

**To Reproduce (复现方法)**
1. 启动几个（1-3个）下游服务节点，设置服务节点处理请求时候随机sleep 比较大的数值（频繁超过客户端的timeout时间）
2. 客户端使用 LA 负载均衡 + list Naming service
3. 客户端发请求给服务端
4. 等待一段 **不短** 的时间
5. 服务端恢复正常服务（不再在处理请求中sleep）

6. 会发现客户端一直无法恢复正常访问服务端，日志中始终报错：[E112]Fail to select server from list://xxxx

**Expected behavior (期望行为)**
客户端能够快速恢复正常访问服务端，而不是一直报错 [E112]Fail to select server from list://

**Versions (各种版本)**
OS: ubuntu 16.04
Compiler: gcc-5.4
brpc: master 分支，commit id：  1eeee3d07c5b1bfcf368003627da0682505e9ad2
protobuf: 3.2

**Additional context/screenshots (更多上下文/截图)**

**Comment by gtarcoder** [comment]
发现程序的运行路线是这样的：

1. 下游服务端频繁超时
2. 客户端每次RPC 后会 FeedBack ( src/brpc/policy/locality_aware_load_balancer.cpp/Feedback) 更新节点的weight
3.  节点不断被降权 
4. 最终节点的 _base_weight 变成了0 ，从而节点被disable
5. 在 SelectServer 中，始终走到如下分支逻辑，
在 AddInflight 中，会直接返回 {false, 0}. （由于节点被disable）

![image](https://user-images.githubusercontent.com/11898942/59926685-68ac9e00-946d-11e9-9218-5db5ea6e2f9c.png)
所以，每次都无法select 出来节点。

6 . 无法select节点，就无法IssueRPC，节点的weight 就无法通过 Feedback 来进行更新, 节点就一直无法被选择，从而一直报 [E112]Fail to select server from list:// （即使下游服务已经恢复）

**Comment by gtarcoder** [comment]
看起来如果naming service 一直不更新下游服务节点（比如测试中使用list 这种naming service方式），那么这种状态就无法跳出。 @jamesge   这种情况是因为使用不当吗？ 还是框架本身就有可能出现这种情况？ 以及，能否通过 定期check 下游节点的方式 去避免？

**Comment by gtarcoder** [comment]
之前我们的服务使用LALB 出现过两种现象：
1. 客户端连接后端server，如果一个节点连续 timeout 之后， 日志里面后面会紧跟着 can not select server from list://xxxx 这种错误
2. 连续几分钟后端服务不可用之后， brpc 就彻底不会再尝试链接后端服务了 

于是，看了 LALB 的实现代码，感觉原因如下：
现象1： 因为LALB 的实现中，是概率性的选择下游节点，权重越大（一般是latency越小会导致权重越大），则被选中的概率越大 （通过产生随机数实现）。 如果一个节点出问题后，这个节点可能短时间内无法被成功选中（这是符合预期的，代码里面也是这么实现的），但是随机数产生的时候，仍然会可能产生到这个节点的区间，导致不断的去尝试选这个节点，当耗尽 ntry 次数之后，选择过程结束，最终没有选中 这个坏节点之外的其他好节点。 （因为是概率选择，所以这是可能发生的，尤其是一个本来权重很高的节点，突然出问题之后，短时间内，它的选中概率仍然最大）

所以，就会出现 连续的  can not select server from list 这种错误

现象2： 如果LALB 后面的server 节点，都连续超时，导致他们不断被降权，最终 _base_weight = 0, 此时会被 disable 掉。 然后之后的所有 SelectServer 都不会返回节点了， 一直出现  can not select server from list:// 错误


感觉LALB 的实现中， SelectServer中的 ntry 有些问题，它对于两次产生随机数去选择节点过程中，没有去除重复节点，最终直接和 总节点数n 比较。如果一个坏节点不断被选中，会浪费选择次数，最终导致没有选择出可用节点。 虽然 Selectserver 循环有 nloop最大次数 10000 的限制，如果按现在这种实现的话，那么nloop 是永远不会被触发。因为循环（统计产生随机数的次数）最多被执行n次（节点数）， ntry >= n 就会退出

感觉可以有两点改进：
1. 在 SelectServer 中，ntry 不单纯统计尝试的次数，而是统计 尝试的unique的节点的个数，这样避免了 can not select server from 这种错误的误发生几率 （因为后端是有可用节点的，但是没有选出来）
2. 节点被disable之后，尝试一定时间间隔去重新复活一次，防止节点落入永久不可恢复状态。

@jamesge  你觉得合理吗？

**Comment by zyearn** [comment]
这个问题是在 https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/locality_aware_load_balancer.cpp#L460 这里对_base_weight赋值的时候赋成0了，导致在SelectServer时判断disable()为true就永远选不了了，最简单的解决办法是把 Disable() 和 Disabled()的实现改成 _base_weight = -1, 以及 _base_weight == -1就好了。

如果一个节点出问题了，那么在feedback的时候会减小它的权重，就算在随机值落在这个server上，在发rpc之前也会把InFlight rpc的惩罚加到权重上，如果随机值不落在这个新权重里，还是会重新选一次的，这里的逻辑看起来没问题，问题节点的流量会越来越小

**Comment by gtarcoder** [comment]
> 这个问题是在 https://github.com/apache/incubator-brpc/blob/master/src/brpc/policy/locality_aware_load_balancer.cpp#L460 这里对_base_weight赋值的时候赋成0了，导致在SelectServer时判断disable()为true就永远选不了了，最简单的解决办法是把 Disable() 和 Disabled()的实现改成 _base_weight = -1, 以及 _base_weight == -1就好了。
> 
> 如果一个节点出问题了，那么在feedback的时候会减小它的权重，就算在随机值落在这个server上，在发rpc之前也会把InFlight rpc的惩罚加到权重上，如果随机值不落在这个新权重里，还是会重新选一次的，这里的逻辑看起来没问题，问题节点的流量会越来越小

因为是随机性的选取，如果每次选择都是 一个坏节点被选中； 那么n次之后，就返回 can not select server， 而有其他节点没有被选中。 这种情况需要避免吗？

**Comment by zyearn** [comment]
这个问题需要避免，这里的逻辑和weight round robin lb在选到Failed节点时的处理逻辑是差不多的，可以在pr里参考下那里的实现。

**Comment by gtarcoder** [comment]
ok 我看下

**Comment by beyond-wyc** [comment]
这个问题很常见，确实是个大问题。

**Comment by beyond-wyc** [comment]
> 最简单的解决办法是把 Disable() 和 Disabled()的实现改成 _base_weight = -1, 以及 _base_weight == -1就好了。

这个为啥没有改到主干代码中去呢？

**Comment by jamesge** [comment]
@beyond-wyc https://github.com/apache/incubator-brpc/commit/6e39f0398dc7a308c08330ecf4348aa5c8614f46

**Comment by beyond-wyc** [comment]
> @beyond-wyc [6e39f03](https://github.com/apache/incubator-brpc/commit/6e39f0398dc7a308c08330ecf4348aa5c8614f46)

我已经用了这个版本，但是问题依旧~

**Comment by flowold** [comment]
这个问题后来怎么解决的？是否解决了？

**Comment by flowold** [comment]
@beyond-wyc @gtarcoder

**Comment by gtarcoder** [comment]
> 6e39f03

我这边没问题了。按照  6e39f03
