### ISSUE TITLE
关于client端controller设置超时的一些问题

### ISSUE THREAD

**Issue by Xavier1994** [apache/incubator-brpc#822]
假设我先对controller设置了一个初始超时时间100ms, controller->set_timeout_ms(100), 然后发出rpc请求,  然后过了10ms, 我又调用同样的controller, controller->set_timeout_ms(50), 那么我想问后面这个设置50ms超时有效吗, 如果有效, 那50ms是相对现在设置的时间还是发出rpc请求的时间

**Comment by jamesge** [comment]
如果是同步访问，再能设置controller时rpc已经结束了，设了也没有意义。如果是异步访问，这个操作的行为是undefined，controller可能出于还没用、正在被用、重试中、已经删除等状态，各有各的情况
