### ISSUE TITLE
服务侧（server-side）负载均衡新增服务实例没有连接的问题

### ISSUE THREAD

**Issue by chengweiv5** [apache/incubator-brpc#823]
**Describe the bug (描述bug)**

使用服务侧负载均衡的时候，例如，使用 LVS，或者 https://github.com/iqiyi/dpvs ，当连接稳定后，也就是 client 建立完所有的长连接之后。假设现在服务实例需要扩容，那么新增的服务实例是不会有 client 过来连接的。

所以，在使用者来看，服务实例就无法做到灵活扩容，不知道有没有什么好办法解决？

**Comment by chengweiv5** [comment]
例如是否可以给长连接设置一个老化时间？到时自动断开重新建立连接？不知道是否合理。

**Comment by wwbmmm** [comment]
因为rpc已经自带naming和LB功能，所以其实没必要再加一层LVS，可以直接把服务实例注册到某种naming系统（如consul/etcd）然后通过rpc访问

**Comment by chengweiv5** [comment]
好的，多谢，我们考虑下。

**Comment by jamesge** [comment]
四层负载均衡一般是用在直接接受用户流量的服务上，内部服务尽量别用。你说的问题(连接vip)，用pooled连接模式就行了，默认情况下一个连接只要10秒没有使用，就会关闭，由于流量总是有高有低，连接其实会持续（但不高频）地关闭和打开的。

**Comment by chengweiv5** [comment]
@jamesge 好的，多谢，我们试试效果

**Comment by hiberabyss** [comment]
> 因为rpc已经自带naming和LB功能，所以其实没必要再加一层LVS，可以直接把服务实例注册到某种naming系统（如consul/etcd）然后通过rpc访问

但在 K8S 的场景下是会存在这个问题的，在使用内部 service 的情况下
