### ISSUE TITLE
长尾问题

### ISSUE THREAD

**Issue by wzw921026** [apache/incubator-brpc#827]
**Describe the bug (描述bug)**
一个无锁的函数，本该在1-2ms内完成，耗时却会达到几十毫秒或几百毫秒。我打印了各个部分的耗时，耗时所在的地方不稳定（这次在A这块耗时多，下次在B这块耗时多）。

**To Reproduce (复现方法)**
服务创建了 几百万～一千万个对象，该服务内存消耗10G，机器总内存消耗70%-80%。函数的操作就是 对象的读，和对象的智能指针的操作。如果一直不发请求然后忽然发一次，超时率非常高。如果服务一直有流量，超时率比较低。

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: centos6.7
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**
我分析有如下原因：
1. 内存换入换出，导致读对象耗时变长
2. bthread切换，导致本该1ms内完成的bthread，耗时变成了几十毫秒

**Comment by jamesge** [comment]
建议跑下cpu profiler或perf，根据量化的热点进行优化
