### ISSUE TITLE
关于SelectiveChannel的一些疑问

### ISSUE THREAD

**Issue by Xavier1994** [apache/incubator-brpc#831]
SelectiveChannel支持lb, 但是看了下代码, 如果我想用lalb, 那貌似只能全局共享一个, 所以如果我有多个SelectiveChannel, 这些Channel后端对应的服务不一样, 是不是lalb也是共享的, 这样是不是会有问题

**Comment by wwbmmm** [comment]
不是共享的，每个channel会有一个lb实例
