### ISSUE TITLE
brpc 作为服务端，客户端通过http post访问，只支持json格式嘛? 是否支持urlencode?

### ISSUE THREAD

**Issue by hongbshi** [apache/incubator-brpc#836]
如题

**Comment by jamesge** [comment]
1. body可以是任意格式（包括二进制），由content-type区分，这是http本身就支持的。比如当content-type是application/proto时，brpc会认为body是pb（的序列化结果）
2. 不直接支持，需要用户自己做

**Comment by hongbshi** [comment]
客户端通过http post 访问服务, content-type为urlencode时, brpc框架会如何处理? 如何让brpc框架不进行处理，交由service实现方处理? 非常感谢

**Comment by wwbmmm** [comment]
> 客户端通过http post 访问服务, content-type为urlencode时, brpc框架会如何处理? 如何让brpc框架不进行处理，交由service实现方处理? 非常感谢

把request的proto定义成一个空的message就可以
