### ISSUE TITLE
thrift头部的sequence number能当作correlation_id用吗

### ISSUE THREAD

**Issue by lorinlee** [apache/incubator-brpc#837]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by cdjingit** [comment]
是用来支持single连接吗？

**Comment by lorinlee** [comment]
> 是用来支持single连接吗？

是的想搞单连接，不过correlation_id是64位的，seq num是32位的，重新生成一个call_id可行不

**Comment by cdjingit** [comment]
这个需要你自己记录seq num和correlation_id的映射。可以参考其他协议类似的问题是如何处理的，比如h2。

**Comment by lorinlee** [comment]
感谢！我看下
