### ISSUE TITLE
aarch64 编译错误

### ISSUE THREAD

**Issue by x-x-p** [apache/incubator-brpc#838]
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L117
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L118
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L123
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L144
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L145
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-stubs-internal.h#L158
https://github.com/apache/incubator-brpc/blob/e09b620d8f10316c9ae8ac69599beb264eb6d3c5/src/butil/third_party/snappy/snappy-internal.h#L135

**Comment by jamesge** [comment]
没有适配过这个架构，手头也没有相应的机器，你可以帮我们看看相关的编译错误是否很多，以及易于适配，合适的话可以发pr

**Comment by x-x-p** [comment]
在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g->current_tid() << " sched_to itself!";
请问下哪种情况下会有这个情况？
https://github.com/apache/incubator-brpc/blob/f43bdcec3a73ecc93859c372f2650334d412f065/src/bthread/task_group.cpp#L566-L630
