### ISSUE TITLE
是否有计划支持  __aarch64__

### ISSUE THREAD

**Issue by x-x-p** [apache/incubator-brpc#839]
如题，是否计划支持 __aarch64__ 架构？

**Comment by x-x-p** [comment]
bthread/context.h  中bthread切换问题

**Comment by zyearn** [comment]
please refer to this issue https://github.com/apache/incubator-brpc/issues/756. The latest code of libcontext has already supported aarch64, you can have a try.

**Comment by x-x-p** [comment]
thanks
