### ISSUE TITLE
client请求包太大（90M）时server core

### ISSUE THREAD

**Issue by zhangqiang4002** [apache/incubator-brpc#844]
**Describe the bug (描述bug)**
#0  0x00007f6623f571d7 in raise () from /lib64/libc.so.6
#1  0x00007f6623f588c8 in abort () from /lib64/libc.so.6
#2  0x00007f662488b8ad in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f6624889906 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007f66248889b9 in __cxa_call_terminate (ue_header=ue_header@entry=0x7f65d265e060) at ../../../../libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007f66248892a5 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=<optimized out>, exception_class=5138137972254386944, ue_header=<optimized out>, 
    context=0x7f6606ffeb00) at ../../../../libstdc++-v3/libsupc++/eh_personality.cc:676
#6  0x00007f66242f3eb3 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x7f65d265e060, context=context@entry=0x7f6606ffeb00) at ../../../libgcc/unwind.inc:62
#7  0x00007f66242f43d7 in _Unwind_Resume (exc=exc@entry=0x7f65d265e060) at ../../../libgcc/unwind.inc:230
#8  0x00000000009ef9f9 in operator() (this=<optimized out>, obj=<optimized out>) at ./src/brpc/destroyable.h:36
#9  ~unique_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /usr/include/c++/5.4.0/bits/unique_ptr.h:236
#10 ~DestroyingPtr (this=<optimized out>, __in_chrg=<optimized out>) at ./src/brpc/destroyable.h:42
#11 brpc::policy::ProcessRpcRequest (msg_base=<optimized out>) at src/brpc/policy/baidu_rpc_protocol.cpp:306
#12 0x0000000000b09927 in brpc::ProcessInputMessage (void_arg=void_arg@entry=0x7f65d2675400) at src/brpc/input_messenger.cpp:136
#13 0x0000000000b0a887 in operator() (this=<optimized out>, last_msg=0x7f65d2675400) at src/brpc/input_messenger.cpp:142
#14 brpc::InputMessenger::OnNewMessages (m=0x7f65d5e64b40) at /usr/include/c++/5.4.0/bits/unique_ptr.h:236
#15 0x0000000000972c1d in brpc::Socket::ProcessEvent (arg=0x7f65d5e64b40) at src/brpc/socket.cpp:1020
#16 0x0000000000a83594 in bthread::TaskGroup::task_runner (skip_remained=<optimized out>) at src/bthread/task_group.cpp:297
#17 0x0000000000a860e1 in bthread_make_fcontext ()
#18 0x0000000000000000 in ?? ()

**To Reproduce (复现方法)**
构造大请求包，例如90M

**Expected behavior (期望行为)**
正常或者报错， 而不是coredump

**Versions (各种版本)**
OS: Linux
Compiler: gcc 5.4
brpc: 2019/7/16 master
protobuf: 3.6.0

**Additional context/screenshots (更多上下文/截图)**

**Comment by zgb40302** [comment]
请问这个问题是如何解决的？
