### ISSUE TITLE
在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g->current_tid() << " sched_to itself!"; 请问下哪种情况下会有这个情况？

### ISSUE THREAD

**Issue by x-x-p** [apache/incubator-brpc#845]
在 aarch64下编译， 单纯编译 example中echo++ server端程序， 启动服务，不停访问web内置服务，即手动点击页面选项卡 /vars, /flag, /connect等， 过段时间就会在bthread线程切换时崩溃。

https://github.com/apache/incubator-brpc/blob/f43bdcec3a73ecc93859c372f2650334d412f065/src/bthread/task_group.cpp#L619

**Comment by zyearn** [comment]
用了最新的 libcontext 么？

**Comment by x-x-p** [comment]
是的

**Comment by altman08** [comment]
我也遇到了这个问题，bthread好多单元测试过不去。

**Comment by x-x-p** [comment]
编译不过去只是有些地方变量类型与变量之间没空格，修改一下，对于context.cpp中两个线程上下文切换的可以参考github里面libcontext库相应的修改为arch64


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: altman08 <notifications@github.com&gt;
发送时间: 2019年9月1日 13:33
收件人: apache/incubator-brpc <incubator-brpc@noreply.github.com&gt;
抄送: x-x-p <x_x_p@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[apache/incubator-brpc] 在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g-&gt;current_tid() << " sched_to itself!"; 请问下哪种情况下会有这个情况？ (#845)




我也遇到了这个问题，bthread好多单元测试过不去。

**Comment by altman08** [comment]
> 编译不过去只是有些地方变量类型与变量之间没空格，修改一下，对于context.cpp中两个线程上下文切换的可以参考github里面libcontext库相应的修改为arch64 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: altman08 <notifications@github.com&gt; 发送时间: 2019年9月1日 13:33 收件人: apache/incubator-brpc <incubator-brpc@noreply.github.com&gt; 抄送: x-x-p <x_x_p@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[apache/incubator-brpc] 在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g-&gt;current_tid() << " sched_to itself!"; 请问下哪种情况下会有这个情况？ (#845) 我也遇到了这个问题，bthread好多单元测试过不去。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

不是编译不过，是编过了单元测试过不了，bthead切换会间歇性core

**Comment by x-x-p** [comment]
😂去掉编译器优化 debug模式能正常使用


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: altman08 <notifications@github.com&gt;
发送时间: 2019年9月2日 17:49
收件人: apache/incubator-brpc <incubator-brpc@noreply.github.com&gt;
抄送: x-x-p <x_x_p@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[apache/incubator-brpc] 在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g-&gt;current_tid() << " sched_to itself!"; 请问下哪种情况下会有这个情况？ (#845)



 
编译不过去只是有些地方变量类型与变量之间没空格，修改一下，对于context.cpp中两个线程上下文切换的可以参考github里面libcontext库相应的修改为arch64 发自我的iPhone
 …
 ------------------ 原始邮件 ------------------ 发件人: altman08 <notifications@github.com&gt; 发送时间: 2019年9月1日 13:33 收件人: apache/incubator-brpc <incubator-brpc@noreply.github.com&gt; 抄送: x-x-p <x_x_p@qq.com&gt;, Author <author@noreply.github.com&gt; 主题: 回复：[apache/incubator-brpc] 在aarch64下编译之后，运行会触发 LOG(FATAL) << "bthread=" << g-&gt;current_tid() << " sched_to itself!"; 请问下哪种情况下会有这个情况？ (#845) 我也遇到了这个问题，bthread好多单元测试过不去。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
不是编译不过，是编过了单元测试过不了，bthead切换会间歇性core

**Comment by Tuvie** [comment]
禁用gcse优化就可以了：-fno-gcse

**Comment by altman08** [comment]
禁用gcse优化，bthread的单测可以通过了，切换也没有遇到core问题了

**Comment by wwbmmm** [comment]
master 已修复

**Comment by adonis0147** [comment]
> master 已修复

Hi @wwbmmm ，我看了下master的提交记录，好像是给g++添加了`-fno-gcse`的编译选项来修复这个问题，请问，如果用clang编译器编译brpc的话，得怎么处理呢？

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by jamesge** [comment]
> > master 已修复
> 
> Hi @wwbmmm ，我看了下master的提交记录，好像是给g++添加了`-fno-gcse`的编译选项来修复这个问题，请问，如果用clang编译器编译brpc的话，得怎么处理呢？

目前还不太清楚clang中有没有对应选项

**Comment by adonis0147** [comment]
感谢大神 @jamesge 的回复！

经过我的尝试，在Ubuntu 22.04 aarch64平台上，禁止Clang对`TaskGroup::task_runner`和`TaskGroup::sched_to`这两个函数进行优化，好像在我们的项目中就可以正常通过UT测试了。

这个是[修改](https://github.com/apache/incubator-brpc/pull/1950)，有空的时候麻烦查看下。

**Comment by ysj1173886760** [comment]
在Mac M1上也遇到了相同的问题。在并发数偏高的时候会出现`sched_to itself`的错误。

尝试去除掉这次修改中的`if #define(_linux_)`后问题仍然存在。

 奇怪的是在我把我自己的项目设置成Release模式构建之后，就不会出现`sched_to itself`的错误了。

**Comment by wwbmmm** [comment]
> 在Mac M1上也遇到了相同的问题。在并发数偏高的时候会出现`sched_to itself`的错误。
> 
> 尝试去除掉这次修改中的`if #define(_linux_)`后问题仍然存在。
> 
> 奇怪的是在我把我自己的项目设置成Release模式构建之后，就不会出现`sched_to itself`的错误了。

使用的是master的最新代码吗？

**Comment by ysj1173886760** [comment]
> > 在Mac M1上也遇到了相同的问题。在并发数偏高的时候会出现`sched_to itself`的错误。
> > 尝试去除掉这次修改中的`if #define(_linux_)`后问题仍然存在。
> > 奇怪的是在我把我自己的项目设置成Release模式构建之后，就不会出现`sched_to itself`的错误了。
> 
> 使用的是master的最新代码吗？

是的。尝试使用了这个PR中的修改--在Mac下禁用了那两个函数的优化，仍然会出现问题。后来试了几次发现-O2 -O1优化下可以正常运行，-O0就会出现`sched_to itself`以及`task_group.cpp:298`出现空指针的问题。目前还不清楚原因，就在我自己的项目中用-O2先缓解这个问题了。
我是在自己的项目中将brpc作为subdirectory引入的，不清楚我的Cmake中的编译选项会不会影响到brpc的编译。

**Comment by ehds** [comment]
> > > master 已修复
> > 
> > 
> > Hi @wwbmmm ，我看了下master的提交记录，好像是给g++添加了`-fno-gcse`的编译选项来修复这个问题，请问，如果用clang编译器编译brpc的话，得怎么处理呢？
> 
> 目前还不太清楚clang中有没有对应选项

Mac M1 下确实还会遇到这个问题，目前似乎没有找到对应的选项来解决这个问题。
stackoverflow 上问了下类似的情况：https://stackoverflow.com/questions/75592038/how-to-disable-clang-expression-elimination-for-thread-local-variable/75622732#75622732。

建议是说给获取 tls 的变量加上 noinline 的函数防止优化，但是可能存在函数调用开销。
参考 qemu 的做法：https://github.com/qemu/qemu/blob/d7e2fe4aac8b74bbfe82b2309536528b4dbe0d34/include/qemu/coroutine-tls.h#L141-L163

**Comment by x-x-p** [comment]
您好，邮件已收到...

**Comment by dingxiaoshuai123** [comment]
> > > > master 已修复
> > > 
> > > 
> > > Hi @wwbmmm ，我看了下master的提交记录，好像是给g++添加了`-fno-gcse`的编译选项来修复这个问题，请问，如果用clang编译器编译brpc的话，得怎么处理呢？
> > 
> > 
> > 目前还不太清楚clang中有没有对应选项
> 
> Mac M1 下确实还会遇到这个问题，目前似乎没有找到对应的选项来解决这个问题。 stackoverflow 上问了下类似的情况：[https://stackoverflow.com/questions/75592038/how-to-disable-clang-expression-elimination-for-thread-local-variable/75622732#75622732。](https://stackoverflow.com/questions/75592038/how-to-disable-clang-expression-elimination-for-thread-local-variable/75622732#75622732%E3%80%82)
> 
> 建议是说给获取 tls 的变量加上 noinline 的函数防止优化，但是可能存在函数调用开销。 参考 qemu 的做法：https://github.com/qemu/qemu/blob/d7e2fe4aac8b74bbfe82b2309536528b4dbe0d34/include/qemu/coroutine-tls.h#L141-L163
> 
> 是否可以在 clang && mac 的情况下走这个解决方法，避免错误的产生？

您好，请问在 clang && mac 的情况下解决了吗？

**Comment by x-x-p** [comment]
您好，邮件已收到...
