### ISSUE TITLE
Builtin Services如何关闭

### ISSUE THREAD

**Issue by aericpp** [apache/incubator-brpc#848]
出于在使用场景上的安全性考虑，并不希望用户可以接触到内置服务，例如服务私有化的部署场景。是否能够直接禁用Builtin Services功能？

**Comment by zyearn** [comment]
把服务端口和内置服务的端口分开，详见 https://github.com/apache/incubator-brpc/blob/master/docs/cn/server.md#%E5%AE%89%E5%85%A8%E6%A8%A1%E5%BC%8F

**Comment by aericpp** [comment]
> 把服务端口和内置服务的端口分开，详见 https://github.com/apache/incubator-brpc/blob/master/docs/cn/server.md#%E5%AE%89%E5%85%A8%E6%A8%A1%E5%BC%8F

场景比较特殊，服务本身部署的环境就是不信任的，对127.0.0.1也仍不希望暴露Builtin Service。

**Comment by aericpp** [comment]
已解决
ServerOptions.options.has_builtin_services = false
