### ISSUE TITLE
CMakeLists.txt:9 Syntax error in cmake code , when parsing string "\"

### ISSUE THREAD

**Issue by southfly** [apache/incubator-brpc#853]
![uskit](https://user-images.githubusercontent.com/28092819/61761327-ff6bd200-ae00-11e9-8bdc-1b20a509338e.png)

option(DOWNLOAD_GTEST "Download and build a fresh copy of \
                            googletest. Requires Internet access." ON)

modified: 

option(DOWNLOAD_GTEST "Download and build a fresh copy of  googletest. Requires Internet access." ON)

**Comment by zyearn** [comment]
Line continuation is possible with \ after cmake 3.0. However we will fix the issue in cmake 2.x.

**Comment by zyearn** [comment]
Fixed in https://github.com/apache/incubator-brpc/pull/876
