### ISSUE TITLE
Options to disable "useless" protocols

### ISSUE THREAD

**Issue by tjxduck** [apache/incubator-brpc#854]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
我们新加了私有protocol，作为服务端时，有些包到不了我们的parser。
gdb追查是到了nshead这个protocol里面，它似乎需要比较长的数据（30 bytes?）才能获取magic number。
对于我们协议中一些比较短的包（例如连接后的第一个ping包），就一直卡在那里。
而且这种"nshead"似乎百度内部的协议？我们也不需要。

**Describe the solution you'd like (描述你期望的解决方法)**
提供全局选项/宏，disable掉指定协议

**Describe alternatives you've considered (描述你想到的折衷方案)**
修改源码，注释掉我们认为无用的协议的注册

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
试下这个 https://github.com/apache/incubator-brpc/blob/fc07b7bf45c4b2aa90ae5c832f3b48a8da124640/src/brpc/server.h#L230
