### ISSUE TITLE
read_cpu_frequency 函数可能读到非预期的HZ

### ISSUE THREAD

**Issue by simpx** [apache/incubator-brpc#861]
**Describe the bug (描述bug)**

cpuinfo里的值不一定是预期的hz数，一旦brpc使用了一个错误值，后续没有机会fix

**To Reproduce (复现方法)**
不停cat /proc/cpuinfo，在比较大的机器数样本下可以看到值特别不一样的cpu mHz值

**Expected behavior (期望行为)**
是否应该换一个实现方式，采用类似dpdk里：https://github.com/DPDK/dpdk/commit/ad3516bb4ae199cb4e7b668da34192d40caf6121

**Versions (各种版本)**
OS: linux 2.6
Compiler: gcc 4.1.2
brpc: master
protobuf: master

**Additional context/screenshots (更多上下文/截图)**

线上机器cat /proc/cpuinfo后能看到CPU MHz不同，其中有一个cpu上是2399hz
已经开启constant_tsc和nonstop_tsc

cpu MHz    : 1001.269
cpu MHz    : 999.902
cpu MHz    : 999.902
cpu MHz    : 999.902
cpu MHz    : 999.902
cpu MHz    : 999.902
cpu MHz    : 2399.902

**Comment by jamesge** [comment]
目前开源的版本在默认编译条件下不会使用read_cpu_frequency。tsc频率要正确读取比较麻烦，dpdk这个版本（也仅针对x86)是否能工作需要在很多不同类型的机器上验证后才行。

**Comment by simpx** [comment]
@jamesge 多谢解答，看起来我们只能先保守用clock，再看dpdk的测试结果了
