### ISSUE TITLE
如何更改baidu_rpc_protocol.cpp，支持objectpool（）

### ISSUE THREAD

**Issue by gxkevin** [apache/incubator-brpc#865]
源码如下，想Message req、Message res设置为object pool，减少parse的时候，内存拷贝、delete的时间开销：
     void ProcessRpcRequest(InputMessageBase* msg_base) {
         std::unique_ptr<google::protobuf::Message> req;
         std::unique_ptr<google::protobuf::Message> res;

        ret.reset(svc->GetRequestPrototype(method).New());
        res.reset(svc->GetResponsePrototype(method).New());

但是直接通过下面的设置有问题
    google::protobuf::Message *req = butil::get_object<google::protobuf::Message>();
    google::protobuf::Message *res = butil::get_object<google::protobuf::Message>();

**Comment by gxkevin** [comment]
@jamesge

**Comment by gxkevin** [comment]
@zyearn

**Comment by jamesge** [comment]
这用法完全错的

**Comment by gxkevin** [comment]
具体的pb的编码规则有什么可参考的么
