### ISSUE TITLE
安装brpc报这个错误：invalid use of incomplete type ‘class google::protobuf::Message’

### ISSUE THREAD

**Issue by gxkevin** [apache/incubator-brpc#872]
编译brpc报这个问题，protoc version 3.9.0， 系统Ubuntu 16.04， gcc 5.4

    Compiling src/brpc/esp_message.o
    In file included from src/brpc/esp_message.cpp:18:0:
    src/brpc/esp_message.h:37:47: error: invalid use of incomplete type ‘class     google::protobuf::Message’
     class EspMessage : public ::google::protobuf::Message {
                                               ^
    In file included from /usr/include/google/protobuf/implicit_weak_message.h:37:0,
                     from /usr/include/google/protobuf/generated_message_util.h:49,
                     from src/brpc/esp_message.h:21,
                     from src/brpc/esp_message.cpp:18:
    /usr/include/google/protobuf/arena.h:76:7: note: forward declaration of ‘class   google::protobuf::Message’
    class Message;  // defined in message.h
           ^
    In file included from src/brpc/esp_message.cpp:24:0:
    /usr/include/google/protobuf/wire_format_lite_inl.h:59:13: error: redefinition of ‘static bool   google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)5u]’
     inline bool WireFormatLite::ReadPrimitive<int32, WireFormatLite::TYPE_INT32>(
                 ^
    In file included from /usr/include/google/protobuf/generated_message_util.h:53:0,
                     from src/brpc/esp_message.h:21,
                     from src/brpc/esp_message.cpp:18:
    /usr/include/google/protobuf/wire_format_lite.h:918:13: note: ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)5u]’ previously declared here
     inline bool WireFormatLite::ReadPrimitive<int32, WireFormatLite::TYPE_INT32>(
                 ^
    In file included from src/brpc/esp_message.cpp:24:0:
    /usr/include/google/protobuf/wire_format_lite_inl.h:68:13: error: redefinition of ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = long int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)3u]’
     inline bool WireFormatLite::ReadPrimitive<int64, WireFormatLite::TYPE_INT64>(
             ^
    In file included from /usr/include/google/protobuf/generated_message_util.h:53:0,
                     from src/brpc/esp_message.h:21,
                     from src/brpc/esp_message.cpp:18:
    /usr/include/google/protobuf/wire_format_lite.h:926:13: note: ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = long int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)3u]’ previously declared here
     inline bool WireFormatLite::ReadPrimitive<int64, WireFormatLite::TYPE_INT64>(
                 ^
    In file included from src/brpc/esp_message.cpp:24:0:
    /usr/include/google/protobuf/wire_format_lite_inl.h:77:13: error: redefinition of ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = unsigned int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)13u]’
     inline bool WireFormatLite::ReadPrimitive<uint32, WireFormatLite::TYPE_UINT32>(
                 ^
    In file included from /usr/include/google/protobuf/generated_message_util.h:53:0,
                     from src/brpc/esp_message.h:21,
                     from src/brpc/esp_message.cpp:18:
    /usr/include/google/protobuf/wire_format_lite.h:934:13: note: ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = unsigned int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = (google::protobuf::internal::WireFormatLite::FieldType)13u]’ previously declared here
     inline bool WireFormatLite::ReadPrimitive<uint32, WireFormatLite::TYPE_UINT32>(

**Comment by zyearn** [comment]
我本地用pb3.9编了下没有问题。另外，最新master的EspMessage定义在33行，而你的错误日志是在37行，是不是自己改过了增加/删除什么文件了

**Comment by gxkevin** [comment]
我用的brpc版本是1.6，是不是这个版本对pb的版本有要求
https://github.com/bigo-sg/brpc/releases/tag/v1.6

**Comment by gxkevin** [comment]
@zyearn

**Comment by zyearn** [comment]
为什么要用这个版本，这个不是brpc官方版本

**Comment by a0soft** [comment]
@gxkevin  我遇到类似的问题，只是我在WSL ubuntu18.04下，您这边最终怎么解决的呢？

**Comment by gxkevin** [comment]
你用的什么版本的brpc

**Comment by a0soft** [comment]
谢谢你的快速回复。
具体版本号没查到，我是在编译DMKit的依赖时出现编译错误的。
git checkout master
git pull
git checkout 2ae7f04ce513c6aee27545df49d5439a98ae3a3f

**Comment by a0soft** [comment]
2ae7f04ce513c6aee27545df49d5439a98ae3a3f

**Comment by a0soft** [comment]
2AE7F04CE513C6AEE27545DF49D5439A98AE3A3F

**Comment by gxkevin** [comment]
建议pb的版本低于3.7
或者升级到最新的brpc

**Comment by a0soft** [comment]
我试试，谢谢。

**Comment by a0soft** [comment]
升级到最新的brpc，经测试可以正常编译。
非常感谢！@gxkevin
