### ISSUE TITLE
connect_timeout_ms 默认值与文档不一致

### ISSUE THREAD

**Issue by phye** [apache/incubator-brpc#882]
**Describe the bug (描述bug)**
文档描述connect_timeout_ms为1s，代码中实际值为200ms。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
感谢指出。默认值应以代码中的为准，文档中的已删除
