### ISSUE TITLE
brpc log performance

### ISSUE THREAD

**Issue by gxkevin** [apache/incubator-brpc#886]
我有个问题，关于log的：
1：目前我看到brpc的log中，使用了localtime_s/localtime_r，这两个函数应该调用了__tz_convert， __tz_convert，有tzset_lock全局锁，每次获取时间都会使用到kernel级别的futex锁，不知道我分析的对不对，这块getimeofday会不会好点

    #if _MSC_VER >= 1400
        localtime_s(&local_tm, &t);
    #else
        localtime_r(&t, &local_tm);
    #endif

2：关于log打印的问题，目前多线程下，log打印是有锁的，当打印的内容比较多的时候，这个锁就会有一定的问题，是否有种无锁的设计方式？

**Comment by jamesge** [comment]
这个log主要是提供接口，实现作为参考，性能是没有任何优化的，在生产环境中建议适配使用公司内或第三方日志库

**Comment by gxkevin** [comment]
@jamesge 好的，谢谢戈神，目前我实现的方法是继承了LogSink，但没看到类似于glog那种AddLogSink()，如何调用我这个logsink呢，还是得改brpc源码

**Comment by gxkevin** [comment]
找到了
