### ISSUE TITLE
随着运行时间的增长出现很多未释放的close wait的连接和bthread

### ISSUE THREAD

**Issue by wxj1992** [apache/incubator-brpc#894]
用了两年brpc了，以前一直没出现这个问题，进开始出现这个问题，去线上机器看发现很多close wait的连接，在达到并发上限之前业务不会有什么问题，但是一旦到上限上游的连接就有问题了，gdb看了下那些hang住的bthread应该都阻塞了，worker线程里面找不到相关信息，有什么办法能得到这些bthread的信息么？contention也没什么异常。

**Comment by zyearn** [comment]
worker全部都阻塞住了么（可以通过curl 'ip:port/health'判断，如果没有返回就是阻塞了）？如果阻塞住的话，EventDispatcher就不工作了，fd可能不会被close

**Comment by wxj1992** [comment]
@zyearn 多谢解答，发现问题了，有个地方关于缓存的更新代码会死锁，但因为过期时间很长，再加上相关功能是代码上线之后很久才开启的，一直没有排查到那里去 = =。
