### ISSUE TITLE
NamingServiceThread::Actions::ResetServers 在设置SSL后失败的问题

### ISSUE THREAD

**Issue by feifeiiong** [apache/incubator-brpc#897]
**Describe the bug (描述bug)**
代码位置：src\brpc\details\naming_service_thread.cpp
NamingServiceThread::Actions::ResetServers 
在SocketMapInsert操作中插入了一个key，这个key包含了owner的ssl，而ssl被用于计算SocketMapKeyChecksum的哈希值，然而SocketMapFind重新构建的key不包含ssl，从而导致简单的五元组匹配不能够产生相同哈希值，匹配失败。包含SSL的server无法被删除。
SocketMapFind 返回-1，未找到key。

**To Reproduce (复现方法)**
我们验证的过程是发起HTTP请求，并设置channel的ssl_options（必现）。
**Expected behavior (期望行为)**
希望知道这里将SSL加入哈希的原因，以及对该问题的具体解决方案。

**Comment by feifeiiong** [comment]
新版已经解决

**Comment by hanxuan123** [comment]
请问是怎么解决的额
