### ISSUE TITLE
链接 libbrpc.so 的时候出现错误, 依赖的静态库需要使用 -fPIC 方式编译

### ISSUE THREAD

**Issue by NetWilliam** [apache/incubator-brpc#901]
**Describe the bug (描述bug)**
静态库编译成功, 动态库链接的时候出现
`/usr/bin/ld: /usr/local/lib64/libprotobuf.a(wire_format.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(implicit_weak_message.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(strtod.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(stringprintf.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(structurally_valid.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(strutil.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(any.cc.o): relocation R_X86_64_32 against symbol `__pthread_key_create@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/lib64/libprotobuf.a(zero_copy_stream_impl.cc.o): relocation R_X86_64_32S against symbol `_ZTVN6google8protobuf2io15FileInputStreamE' can not be used when making a shared object; recompile with -fPIC`
这样的错误

**To Reproduce (复现方法)**
安装各类依赖之后, 使用cmake 编译, 静态库可以成功编译  动态库无法正常编译.
即使在修改 gflags, leveldb 和 protobuf 加上 -fPIC 选项之后编译出静态库安装到系统环境, 再来编译brpc 仍然会报错
我试图让brpc 依赖动态库版本的gflags, leveldb 和protobuf, 但是失败了,一是 gflags 本身没有动态库, 第二是 试图修改cmake 找动态库版本的libprotobuf , 但是失败了.

**Expected behavior (期望行为)**
编译动态库成功

**Versions (各种版本)**
OS: CentOS Linux release 7.6.1810 (Core) 
Compiler: g++ 4.8.5 

brpc master, protobuf v3.7.0,  leveldb master, gflags master

**Additional context/screenshots (更多上下文/截图)**

![image](https://user-images.githubusercontent.com/3966971/63633349-e3668500-c679-11e9-8ca5-f3f9c2f27be3.png)

**Comment by NetWilliam** [comment]
既然cmake 已经没有更新支持了, 为什么不删掉呢? 我在这个地方搞了一天...  还有bazel 什么的, 我是不敢用的.

如果只支持类似autogen 的方式的编译, 建议就把命名改一下, 免得别人走歧路

**Comment by zyearn** [comment]
libbrpc.so依赖libgflags.so，libleveldb.so，libprotobuf.so，你看看自己系统里有没有

**Comment by NetWilliam** [comment]
> libbrpc.so依赖libgflags.so，libleveldb.so，libprotobuf.so，你看看自己系统里有没有

有的, 我调试cmake的时候发现 寻找那个package的时候总是找到的是静态库, 不知道为什么.
cmake 这种编译方式好像有问题走不通, 用那个 config_brpc.sh 才可以跑通

**Comment by NetWilliam** [comment]
我cmake 的版本还挺新的
cmake version 3.15.2

不晓得是不是cmake 的脚本在不同系统上有细微区别导致的. 这边是centos

**Comment by zyearn** [comment]
config_brpc.sh会搜索指定路径下的所有文件，而cmake只会搜索特定前缀，比如/usr/local/lib，要把so放在这下面，再检查下软链接对不对。cmake一般是向后兼容的，如果不是，也会有对应的warning

**Comment by NetWilliam** [comment]
找到原因了, 因为我的系统上装了几个版本的protobuf 这个链接链接到了老的版本, 删掉就好了
