### ISSUE TITLE
目前RPC重试策略只能支持跨机器重试，希望支持跨机器组重转

### ISSUE THREAD

**Issue by 8urdennn** [apache/incubator-brpc#908]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**

**Describe the solution you'd like (描述你期望的解决方法)**
之前的rpc重试策略只是跨机器之间的重试，希望增加一个tag维度，这个tag里面有一组机器，这样重试可以跨组重传。

**Describe alternatives you've considered (描述你想到的折衷方案)**
修改src/baidu/rpc/excluded_servers.h中ExcludedServers的部分属性，让用户可以自己创建、拓展。

**Additional context/screenshots (更多上下文/截图)**

**Comment by zyearn** [comment]
[SelectiveChannel](https://github.com/apache/incubator-brpc/blob/master/docs/cn/combo_channel.md#selectivechannel) 能满足你的场景么

**Comment by wwbmmm** [comment]
> [SelectiveChannel](https://github.com/apache/incubator-brpc/blob/master/docs/cn/combo_channel.md#selectivechannel) 能满足你的场景么

和SelectiveChannel不完全一样，这里负载均衡还是希望在所有实例间做负载均衡（可能是RR、WRR、LA等），但是SelectiveChannel把负载均衡变成了两层，效果就不一样了，特别是不同组的实例数量不同的情况。而且这个会拆出很多NS，这个组的数量可能会动态变化，这些情况处理起来比较复杂。

**Comment by jamesge** [comment]
SelectiveChannel是考虑了实例数不同这个问题的，不同的组有不同“weight"。
