### ISSUE TITLE
listen port supports customized listener

### ISSUE THREAD

**Issue by yuhao600** [apache/incubator-brpc#918]
The current implementation uses a const listen sockfd.
Sometimes the listener needs a customized one.
The currently used one could be used as default, so that the users who don't need customized listener don't need to modify code.

**Comment by wwbmmm** [comment]
默认的tcp_listen函数实现目前变得更复杂了，尤其在合入了ipv6和uds功能之后。用户自定义listen函数想要正确地处理各种情况并不容易，也不推荐。
建议如果有更明确的需求，可以通过修改tcp_listen，添加一些gflag或者参数来实现。
