### ISSUE TITLE
如何将多台机器的监控指标汇总显示？

### ISSUE THREAD

**Issue by fliage** [apache/incubator-brpc#921]
需求为：一个集群多台机器部署同样的服务，需要将多机器的业务指标汇总，在一个监控页面显示，如总qps, 失败率等，
请问各位大神如何实现？

**Comment by jamesge** [comment]
看下 https://github.com/apache/incubator-brpc/blob/master/docs/cn/bvar.md#%E7%9B%91%E6%8E%A7bvar

**Comment by fliage** [comment]
就是说需要额外的监控程序去定期汇总每台机器导出的文件，brpc本身的监控页面只能显示单机的指标，对吧？多谢指教
