### ISSUE TITLE
ObjectPool是否会分配不出对象

### ISSUE THREAD

**Issue by wzw921026** [apache/incubator-brpc#925]
**Describe the bug (描述bug)**
butil::ObjectPool<T>::singleton()->get_object() 是否会分配对象失败，返回NULL。
如果会失败，一般在什么情况下会出现。

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by lorinlee** [comment]
看起来分配不出内存、placement new返回了NULL、或者ObjectPoolValidator::validate检测结果是false都有可能会返回NULL
