### ISSUE TITLE
为什么只有连接池模式才能关闭空闲连接

### ISSUE THREAD

**Issue by ufosky** [apache/incubator-brpc#926]
看文档只支持连接池模式关闭空闲连接，但我们现在用的单连接的模式，怎么关闭空闲连接 https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%85%B3%E9%97%AD%E8%BF%9E%E6%8E%A5%E6%B1%A0%E4%B8%AD%E7%9A%84%E9%97%B2%E7%BD%AE%E8%BF%9E%E6%8E%A5

**Comment by cdjingit** [comment]
单连接为啥还有空闲连接？ 单连接只有节点被naming service移除后自然会被关闭。

**Comment by ufosky** [comment]
因为策略上的原因，需要在流量上升时用到某些节点，但是大部分时间应该是用不到的

**Comment by cdjingit** [comment]
流量低的时候摘除这些backup节点就可以了。你们现在怎么管理？

**Comment by ufosky** [comment]
backup节点也有另外的服务在用，就是说流量高的时候会分一部分流量到别的服务的节点，但平时都走正常节点，关闭不必要的连接

**Comment by ufosky** [comment]
如果要让单连接模式可以关闭空闲连接，可以怎么实现？

**Comment by cdjingit** [comment]
> 如果要让单连接模式可以关闭空闲连接，可以怎么实现？

如果节点没有被ns移除，你们如何让他空闲下来的？（如何让lb不选择这些backup节点？）

**Comment by ufosky** [comment]
使用SelectiveChannel将正常节点和备用节点放到不同的subchannel里面，然后通过策略让一般情况选择正常节点的subchannel，但是现在的问题是一旦备用节点的channel建立了连接，就一直不断开了
