### ISSUE TITLE
咨询一下，brpc 客户端能支持绑定一个特定的IP吗？

### ISSUE THREAD

**Issue by GuShuhengSimon** [apache/incubator-brpc#935]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
No

**Describe the solution you'd like (描述你期望的解决方法)**
brpc 客户端可以 支持绑定特定IP.  

**Describe alternatives you've considered (描述你想到的折衷方案)**

N.A
**Additional context/screenshots (更多上下文/截图)**

N.A

**Comment by hnwyllmm** [comment]
TCP可以支持吗？

**Comment by jamesge** [comment]
Channel创建时可以指定ip。如果你需要获得某次访问选择的机器的话，调用Controller::remote_side()
