### ISSUE TITLE
网络上线了之后持续几十秒的[E112] 问题

### ISSUE THREAD

**Issue by m200972391** [apache/incubator-brpc#943]
在rpc消息通信过程中（比如braft的PreVote），断网一点时间之后，将网络上线（ifconfig up），还在持续返回E112错误，一段时间（几秒到几十秒）之后才恢复，这个现象可以有什么排查方法么？

**Comment by zyearn** [comment]
对端在断网后，健康检查每隔一段时间会去检测是否正常 https://github.com/apache/incubator-brpc/blob/master/docs/cn/client.md#%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5。

**Comment by m200972391** [comment]
谢谢回复。health_check_interval 健康检查的时间是3秒钟，网络恢复之后，有时候会持续四五十秒还在返回E112的错误，还有其他的什么机制可能让客户端返回E112错误么？

**Comment by jamesge** [comment]
@m200972391 你看看日志中是否有Checking开头(及对应ip)的日志，看看断网，第一次返回E112错误，Checking日志，恢复等时间点的关系。

**Comment by m200972391** [comment]
我调试了一下，应该是版本比较老，我的版本中CheckHealth函数中的connect函数没有加超时，谢谢两位回复。@jamesge @zyearn
