### ISSUE TITLE
疑问：ConditionVariable 相关操作

### ISSUE THREAD

**Issue by lijianSE** [apache/incubator-brpc#949]
如果在bthread中使用 ConditionVariable wait mutex
在另一个pthread（另一个工作线程池的pthread，该线程池与bthread无关） 使用同一个ConditionVariable Notify 操作
该使用方式，会存在什么问题么？（bug 或 性能问题）

**Comment by jamesge** [comment]
目前没有已知问题，包括wait处醒来立刻析构CV应该也没有问题

**Comment by lijianSE** [comment]
好的，谢谢
