### ISSUE TITLE
brpc-thrift TBufferedTransport支持

### ISSUE THREAD

**Issue by feifeiiong** [apache/incubator-brpc#951]
请问官方是否有对TBufferedTransport的支持计划？或者如何在brpc中使用thrift的tbuffered传输方式？

**Comment by jamesge** [comment]
没有支持计划，在brpc中使用thrift协议不需要使用这个

**Comment by feifeiiong** [comment]
对，这里是想要实现brpc-thrift和原生thrift-server的tbuffered方式通信
