### ISSUE TITLE
支持腾讯开源rpc框架tars使用的tars协议

### ISSUE THREAD

**Issue by fireboyvt** [apache/incubator-brpc#954]
目前很多公司使用腾讯的tars框架，希望brpc能支持tars协议

**Comment by jamesge** [comment]
如果只是简单二进制传输协议+protobuf序列化的payload，支持难度会很低。但看起来是自有idl的，会很麻烦。brpc的百度内部版是通过protobuf插件+pb options支持了百度内部的idl语言，但工作量很大，开源部分不会考虑做此种支持。

**Comment by mistyliu** [comment]
仅验证使用的话，可以参考目前brpc中支持thrift的模式，通过变通的方式引入tars协议。

**Comment by fireboyvt** [comment]
> 仅验证使用的话，可以参考目前brpc中支持thrift的模式，通过变通的方式引入tars协议。
能更详细说下如何实现吗，没用过thrift

**Comment by huntinux** [comment]
可以参考redis协议，实现非pb编码的协议。

**Comment by serverglen** [comment]
如戈神描述，不考虑支持。
