### ISSUE TITLE
建议线程退出时，把LocalPool中未使用item的id也加入到全局空闲队列

### ISSUE THREAD

**Issue by tesla1995** [apache/incubator-brpc#956]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
在文件 `src/butil/resource_pool_inl.h` 中，线程退出时，析构LocalPool对象，在LocalPool的析构函数，只将_cur_free的item的id加入到全局空闲队列，是不是考虑把_cur_block中未使用的item的id也加入到全局队列，以减少内存浪费呢？
![localpool](https://user-images.githubusercontent.com/11598872/68085854-5d886680-fe80-11e9-8d46-f2288450b545.png)

**Describe the solution you'd like (描述你期望的解决方法)**
析构LocalPool对象时，判断_cur_block->nitem是否小于BLOCK_NITEM。如果是，说明_cur_block中有未使用的item，把这部分item的id也要加入到全局的_free_chunks中。

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
确实是可以的，不过目前brpc的场景中几乎不会退出pthread（才会导致LocalPool析构），这个修改很难验证实际效果。

**Comment by tesla1995** [comment]
> 确实是可以的，不过目前brpc的场景中几乎不会退出pthread（才会导致LocalPool析构），这个修改很难验证实际效果。

如果不是pthread频繁创建、退出的场景，确实没修改的必要。另外，brpc中很多地方使用了原子编程技术，我想请教下原子编程的学习方法和怎么验证原子编程的正确性。

**Comment by jamesge** [comment]
学习资料很多建议搜索，验证可以用Thread Sanitizer(tsan)

**Comment by tesla1995** [comment]
> 学习资料很多建议搜索，验证可以用Thread Sanitizer(tsan)

多谢
