### ISSUE TITLE
bthread支持类似omp的并行计算的方法

### ISSUE THREAD

**Issue by YoungAndSure** [apache/incubator-brpc#965]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
现在的bthread接口使用时，在需要并行计算的时候，要设置好回调函数、初始化一系列参数、等待回调结束、收集计算结果等，比较繁琐。而在业务代码中使用omp会默认调用pthread，无法继承父bthread的相关属性。

**Describe the solution you'd like (描述你期望的解决方法)**
想问下，bthread是否有考虑对omp的支持，或者实现类似omp、tbb的抽象接口，以更好的支持并行计算？或者是否有已知与bthread兼容的库？或者是否有值得研究方向的建议？

**Comment by jamesge** [comment]
这个视角不错，不过bthread的主要设计目的简化网络和IO中的多线程交互，而omp的主要使用场景是cpu-intensive的，如科学运算，这个场景中使用bthread也没什么优势。所以应该不会支持。

**Comment by guodongxiaren** [comment]
> 这个视角不错，不过bthread的主要设计目的简化网络和IO中的多线程交互，而omp的主要使用场景是cpu-intensive的，如科学运算，这个场景中使用bthread也没什么优势。所以应该不会支持。

请问在brpc的服务中，使用tbb等并行计算库是不是会冲突？
