### ISSUE TITLE
从release的源代码编译时无法获取BRPC_VERSION

### ISSUE THREAD

**Issue by straywarrior** [apache/incubator-brpc#969]
**Describe the bug (描述bug)**
编译时git操作报错
`fatal: Not a git repository (or any parent up to mount point /)`
可以继续编译，但会有大量上述错误信息

**To Reproduce (复现方法)**
下载release的代码包，例如 `https://github.com/apache/incubator-brpc/archive/0.9.6.tar.gz`，执行`config_brpc.sh; make`

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS: CentOS 6
Compiler: gcc 4.9.2
brpc: 0.9.6
protobuf: 3.5.2

**Additional context/screenshots (更多上下文/截图)**
错误来自于Makefile中的git命令（已省略其它不相关内容）：
```
CPPFLAGS+=-DBRPC_REVISION=\"$(shell git rev-parse --short HEAD)\"
```
使用release的代码包时，没有git目录导致报错

**Comment by zyearn** [comment]
Fixed in https://github.com/apache/incubator-brpc/pull/984
