### ISSUE TITLE
关于BRPC设计的一些疑问（定时器，网络模型等）

### ISSUE THREAD

**Issue by MR-workaholic** [apache/incubator-brpc#971]
**关于BRPC定时器设计的疑问**
BRPC的定时线程是独立的线程，而执行定时回调函数是在定时线程就地马上执行的，请问可以将回调函数放在bthread上执行吗？若这么实现，有什么不妥麽？

**起因**
我们在修改BRPC的代码时，在以为所有网络收发都是基于bthread的认知上，在socket层面加了阻塞协程的动作。但是实验发现，定时线程被堵塞了！原因是，出现连接超时时，定时器会直接在定时线程中直接执行重发任务，导致定时线程被堵塞了。

**思考**
BRPC中有bthread的概念，但发现这种概念的引用似乎仅仅是存在于channel层面之上；在channel层面之下，如socket网络层面，还是运用异步+非阻塞的实现方法，没有采取bthread的思想去编码（代码中大量运用pthread mutex而非bthread mutex似乎就是一个印证，当然bthread也不像其他协程库那样hook了网络相关的阻塞函数）。

是不是意味着，在修改channel层面下的代码时，我们不能采用bthread的思想编码了吗？

对于最开始的疑问，可否将定时器的回调函数扔到bthread中执行？若这么做之后，我们是否就可以用bthread的思想修改channel层面之下的代码了？

**Comment by jamesge** [comment]
定时线程就是这么设计的，因为一些特别小的回调还启动一个线程运行是没有意义的，复杂的回调，特别是有用户代码的，应该启动一个bthread运行。

**Comment by MR-workaholic** [comment]
> 定时线程就是这么设计的，因为一些运行时间短or确定的回调还启动一个线程运行是没有意义的，复杂的回调，特别是有用户代码的，应该启动一个bthread运行。

那因为定时器线程有可能执行重发任务，那channel层面之下，就不能采取bthread的思路写代码了？

**Comment by jamesge** [comment]
在框架层面做成全异步而不依赖任何的阻塞操作，是很正常的。正因为阻塞很少，所以用pthread mutex也影响不大，这是pthread mutex用的多的主要原因。未必不能用bthread，要看频率和场景，比如框架中写入socket不就是可能会创建bthread运行KeepWrite么？
