### ISSUE TITLE
brpc能否做到完全不依赖于protocol buffer

### ISSUE THREAD

**Issue by mistyliu** [apache/incubator-brpc#976]
初略看了下文档和示例demo，似乎每一个rpc都是依赖于protocol buffer里面的service流程，不管通信协议用的是不是pb。做为一个rpc框架，能否做到完全与协议格式解耦？

**Comment by jamesge** [comment]
确实在一些场景中可能需要适配已有的协议，但从设计成熟度来说，pb是最好的（此处没有之一），且pb本身是个框架，是可以支持其他序列化格式的（比较繁琐，百度内有应用），所以brpc不太可能和pb脱钩。
