### ISSUE TITLE
where is Benchmark test code?

### ISSUE THREAD

**Issue by lichuang** [apache/incubator-brpc#988]
**Is your feature request related to a problem? (你需要的功能是否与某个问题有关?)**
In the benchmark doc:https://github.com/apache/incubator-brpc/blob/master/docs/cn/benchmark.md, it mentions that the benchmark perf test code is https://svn.baidu.com/com-test/trunk/public/rpc-perf/, what cannot be accessed by others outside Baidu.

Can upload the benchmark code to github?

**Describe the solution you'd like (描述你期望的解决方法)**

**Describe alternatives you've considered (描述你想到的折衷方案)**

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
sorry, the benchmark involves heavily with internal machines' setup, and we don't have any plan to opensource it. You can do your own benchmark to verify the claims inside.
