### ISSUE TITLE
Link to contributing page is invalid

### ISSUE THREAD

**Issue by ten2ton** [apache/incubator-brpc#994]
**Describe the bug (描述bug)**
In project home site community page, link to contributing page is invalid. 

**To Reproduce (复现方法)**

**Expected behavior (期望行为)**

**Versions (各种版本)**
OS:
Compiler:
brpc:
protobuf:

**Additional context/screenshots (更多上下文/截图)**

**Comment by jamesge** [comment]
Do you have a screenshot? I don't know which link you're referring

**Comment by ten2ton** [comment]
---Original---

**Comment by wwbmmm** [comment]
Fixed by https://github.com/apache/incubator-brpc-website/pull/93
